### PR TITLE
Bump Avro version to 1.10.1

### LINKED ISSUE #8943: Upgrade Avro version to 1.10.1
A [bug](https://github.com/apache/avro/pull/969/files#diff-2812ad83e127ca916e60f60beff26c675cb92eaa7159fb7bc100971d5a1c69f8R61) in the current avro version fails some iceberg queries because it fails to read an avro file. https://github.com/apache/iceberg/issues/1654

We need to bump the avro version to `1.10.1` for the fix. However, we should see if we should only do that when we upgrade Iceberg version to `0.12.0`, since some additional Iceberg side changes may be required. https://github.com/apache/iceberg/pull/1648

cc @electrum @findepi @jackye1995

### PR DESCRIPTION
**Pull request by jirassimok**
This should resolve #8943 and similar problems.

### CODE REVIEW

**Comment by findepi** [comment]
@jirassimok see build outcome.

**Comment by hashhar** [comment]
I consider https://github.com/apache/iceberg/pull/1648 to be important (so version should be bumped with Iceberg version) since it looks like it can lead to silent loss of precision for decimal columns judging by:

> The validation of downcasting decimals was made more strict. Therefore with the Parquet to Avro Decimal conversion, there was an implicit downcast from 34 to 10. The current conversion only takes scale into account, so it could be that precision would be lost.

**Comment by findepi** [comment]
> I consider [apache/iceberg#1648](https://github.com/apache/iceberg/pull/1648) to be important (so version should be bumped with Iceberg version)

so we should be able to bump Avro version for Hive connector, but not for Iceberg just yet

**Comment by electrum** [comment]
The Avro dependency in Trino is not used for Hive or Iceberg. You can see the modules like Kafka, BigQuery, Pinot, that use the dependency. For Hive and Iceberg, Avro comes from the [shaded Hive depencency](https://github.com/trinodb/trino-hive-apache/blob/50f62e05bcc4d33df97c7d5ede83800237340f92/pom.xml#L48).

A potential issue with updating Avro for Hive is that Hive has code like `org.apache.hadoop.hive.serde2.avro.AvroSerDe` that might not be compatible with newer versions. If that turns out to be the case, we can solve this for Iceberg by moving Avro out of the shaded Hive dependency, and then the Hive connector can use the older version and the Iceberg connector can use the new version.

**Comment by electrum** [comment]
I put up a PR, let's see if the tests pass: https://github.com/trinodb/trino/pull/9114

**Comment by jirassimok** [comment]
Closed in favor of #8946.

**Pull request closed without merging**
