### PR TITLE
Fix kafka protoc compile error

### PR DESCRIPTION
**Pull request by chenjian2664**
## Description
I am not able to compile the trino-kafka module on Mac M2 
Meet the error https://trinodb.slack.com/archives/CP1MUNEUX/p1698747502481569

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Comment by hashhar** [comment]
@wendigo @nineinchnick Can you help with how to resolve offline artifacts issue here?

Thanks @chenjian2664 for the solution. Lot of people hit this so thank you for providing a solution which should work out of the box.

**Comment by wendigo** [comment]
@hashhar https://github.com/trinodb/trino/pull/19595

**Comment by wendigo** [comment]
Adding:
```
 <DynamicDependency>
                                <groupId>com.google.protobuf</groupId>
                                <artifactId>protoc</artifactId>
                                <type>exe</type>
                                <classifier>linux-x86_64</classifier>
                                <version>${dep.protobuf.version}</version>
                                <repositoryType>MAIN</repositoryType>
                            </DynamicDependency>
                            <DynamicDependency>
                                <groupId>com.google.protobuf</groupId>
                                <artifactId>protoc</artifactId>
                                <type>exe</type>
                                <classifier>linux-aarch_64</classifier>
                                <version>${dep.protobuf.version}</version>
                                <repositoryType>MAIN</repositoryType>
                            </DynamicDependency>
```

Will fix this PR.. @chenjian2664 can you add it here?

**Comment by chenjian2664** [comment]
https://github.com/trinodb/trino/actions/runs/6714201704/job/18247503304?pr=19592#step:7:28715 @wendigo I think it's not related to the change

**Review by hashhar — APPROVED** [review]
Thanks, failures are unrelated.

**Pull request merged**
