### PR TITLE
Add cache for OAuth userInfo

### LINKED ISSUE #21937: OAuth userinfo should be cached
OAuth userinfo get from Idp should be cached. (userinfo from `http-server.authentication.oauth2.userinfo-url`)
Otherwise every time a user access WEB_UI API will trigger a HTTP call from coordinator to Idp to fetch userinfo.

Trino WebUI consistently fetch from `/ui/api/stats`, `/ui/api/cluster`, and `/ui/api/query`. Each API call will trigger a HTTP call to Idp in coordinator. 

Benefits of adding a cache:
* improve the performance for WebUI
* lower the workload for coordinator

https://github.com/trinodb/trino/blob/6d20ac2d41c7696b0e6cf83e700235ede3ff4d37/core/trino-main/src/main/java/io/trino/server/security/oauth2/NimbusOAuth2Client.java#L397-L400

Call stack:
```
queryUserInfo:400, NimbusOAuth2Client (io.trino.server.security.oauth2)
getJWTClaimsSet:392, NimbusOAuth2Client (io.trino.server.security.oauth2)
getClaims:184, NimbusOAuth2Client (io.trino.server.security.oauth2)
getAccessTokenClaims:142, OAuth2WebUiAuthenticationFilter (io.trino.server.ui)
2 hidden frames
filter:98, OAuth2WebUiAuthenticationFilter (io.trino.server.ui)
57 hidden frames
```

A naive cache implementation on queryUserInfo() shows significant improvement on latency.
Before:
image

After:
image

### PR DESCRIPTION
**Pull request by oneonestar**
## Description
Fix #21937
Cache userinfo get from OAuth Idp.

## Additional context and related issues
OAuth userinfo get from Idp should be cached. (userinfo from `http-server.authentication.oauth2.userinfo-url`)
Otherwise every time a user access WEB_UI API will trigger a HTTP call from coordinator to Idp to fetch userinfo.

Trino WebUI constantly fetch from `/ui/api/stats, /ui/api/cluster, and /ui/api/query`. Each API call will trigger a HTTP call to Idp in coordinator.

Benefits of adding a cache:
* improve the performance for WebUI
* lower the workload for coordinator

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# Section
* Improve responsiveness of Web UI when OAuth is used.
```

### CODE REVIEW

**Comment by oneonestar** [comment]
@wendigo 
Each accessToken maps to one user info. Currently we store accessToken in cookie.
I don't think storing user info in cookies will make much of a difference in terms of performance.
The addition signing/verification/encryption needed to store the user info in cookies is also a concern.

**Comment by wendigo** [comment]
@oneonestar you can issue encrypted cookie and decrypt it server side

**Comment by oneonestar** [comment]
@wendigo Yea, we can do that. But is it better than this PR?
The implementation will be more complicated. Encryption and decryption also consume CPU resource.

**Comment by wendigo** [comment]
@oneonestar we are decrypting small amouny of data so cpu is negligible

**Comment by mosabua** [comment]
Do we want to reopen and pursue this more @wendigo and @oneonestar ?

**Pull request closed without merging**
