### PR TITLE
Update JDK 22 to 22.0.2+9

### PR DESCRIPTION
**Pull request by wendigo**
## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by wendigo** [comment]
Currently blocked on PPC64LE linux build

**Comment by wendigo** [comment]
@martint PTAL

**Review by martint — APPROVED** [review]

**Comment by mosabua** [comment]
I assume this is not required for users...

**Comment by wendigo** [comment]
@mosabua No. 22.0.1 still supported

**Pull request merged**
