### PR TITLE
Change Alluxio config to use proper type

### PR DESCRIPTION
**Pull request by rongrong**
## Description

Later versions of Alluxio will enforce config property types. Update the config to use proper types.

## Documentation

No documentation is needed.

## Release notes

No release notes entries required.

### CODE REVIEW

**Comment by raunaqmorarka** [comment]
Is is possible to write a test which showcases the problem ?

**Comment by findepi** [comment]
Please make sure the CLA is signed. 
Also, shall we bump the Alluxio version? Until the bump, this change is not necessary, AFAIU.

**Comment by bitsondatadev** [comment]
:wave: @rongrong - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by colebow** [comment]
Closing this one out due to inactivity, but please reopen if you would like to pick this back up.

**Pull request closed without merging**
