### PR TITLE
Fail on interval with exceeded precision

### LINKED ISSUE #6754: INTERVAL `x` SECOND values with `x<0.001` are silently truncated to zero
minimal example:
```
presto:default> SELECT val + INTERVAL '.0001' second FROM (VALUES TIMESTAMP '2021-01-01 00:00:00.123456789 UTC') AS t (val);
               _col0
-----------------------------------
 2021-01-01 00:00:00.123456789 UTC
(1 row)
```

This is a really unfortunate bug as it results in silently incorrect data. Ideally the `INTERVAL` function could be patched to do the right thing here, but we'd also be ok if it would at least throw an error rather than return incorrect data.

### PR DESCRIPTION
**Pull request by mwesolowski**
## Description

Fix in the core query engine. It prevents silent truncation of interval value to milliseconds precision.

## Related issues, pull requests, and links

* Fixes #6754

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by mwesolowski** [comment]
Seems like all failed tests are flaky as indicated in https://github.com/trinodb/trino/issues/13362

**Comment by findepi** [comment]
This should be done directly by the library, so the implicit validation should be part of `parsePeriodMillis`.
for example, this
```
private static final PeriodFormatter INTERVAL_HOUR_SECOND_FORMATTER = cretePeriodFormatter(IntervalField.HOUR, IntervalField.SECOND);
```

should allow parsing "00:00:01.1234", because it truncates the millisecond information.

To achieve that, we can do `builder.maximumParsedDigits(3);` within the `io.trino.util.DateTimeUtils#cretePeriodFormatter`. method.

**Comment by mwesolowski** [comment]
@findepi Thanks for taking the time to review. I agree that it should be done directly by the library and that my first attempt was a shortcut.

I have 2 follow up questions:

1) maximumParsedDigits makes sure that the remaining part of the value contains no more digits than specified. As long as we continue to use appendSecondsWithOptionalMillis it's rather useless because we have to apply this check only the decimal part. Other than that it just checks number of occurring digits, including trailing zeros. I'm not sure if "INTERVAL '1:1.1110'  MINUTE TO SECOND" should be rejected.
Anyway my plan is to replace .appendSecondsWithOptionalMillis()I with .appendSeconds() and a call to custom implementation of PeriodParser that will parse optional millis and make sure precision is not exceeded. What do you think about it?

2) What did you mean with "INTERVAL_HOUR_SECOND_FORMATTER should allow parsing "00:00:01.1234", because it truncates the millisecond information" ? 
I've made a quick test and milliseconds in this interval are retained. It's microseconds part that is silently truncated.
```
trino> SELECT val + INTERVAL '00:00:01.1234' HOUR TO SECOND 
    -> FROM (VALUES TIMESTAMP '2021-01-01 00:00:00.0 UTC') 
    -> AS t (val);
            _col0            
-----------------------------
 2021-01-01 00:00:01.123 UTC 
(1 row)
```

**Comment by mwesolowski** [comment]
Some comments to the changes I've made:
 - I used custom OptionalSecondsParser instead of appendSeconds() which doesn't allow empty seconds. So far "INTERVAL '.1' SECOND" was accepted so using appendSeconds() would break backward compatibility.
 - So far '"INTERVAL '1.' SECOND"' and "INTERVAL '.1' SECOND" were accepted but '"INTERVAL '.' SECOND"' were not. After my changes '"INTERVAL '.' SECOND"' is also accepted. It that's a problem I can fix it by merging OptionalSecondsParser and OptionalFractionOfSecondParser into one parser.
 - both '.' and ',' are accepted as a decimal separator for backward compatibility. 
 - I didn't provide custom printers respective to my custom parsers because built formaters are private and used only for parsing.

**Comment by martint** [comment]
@cla-bot check

**Comment by mosabua** [comment]
:wave: @mwesolowski @martint  - this PR has become inactive. We hope you are still interested in working on it. Please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by mosabua** [comment]
@martint can you validate if this is still a desired change please. If so the test would have to be adapted to use Junit

**Pull request closed without merging**
