### PR TITLE
Skip docs steps if there is change in other directory

### LINKED ISSUE #10242: Skip docs.yml workflow when PR contains both code + docs change
Also, we may want to run `docs-checks` job only in `java-version=11`.

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #10242

Tested in https://github.com/ebyhr/gha
I couldn't find the way to skip in workflow level, so introduced https://github.com/dorny/paths-filter.

### CODE REVIEW

**Review by hashhar — COMMENTED** [review]
You can both include and ignore paths - see https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths

So for docs we can add `paths:` and for ci we can add `paths-ignore`?

**Comment by ebyhr** [comment]
If you mean below paths (or reversed order) for docs job, it doesn't work. I already confirmed that in other repository. 
```
    paths:
      - 'docs/**'
      - '!docs/**'
```

**Comment by hashhar** [comment]
Ah, nevermind. I notice that with my idea we'd still run some tests twice (unless we remove the ones already present in docs.yml from ci.yml).

I'll re-review this again. 🙂

**Review by nineinchnick — APPROVED** [review]

**Review by hashhar — APPROVED** [review]
Works.

**Pull request merged**
