### PR TITLE
Move auto-commit flag from ConnectorSession to Connector

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Review by losipiuk — APPROVED** [review]
Thanks.

cc: @aczajkowski

**Comment by losipiuk** [comment]
CI failed - related

**Comment by electrum** [comment]
Thanks @losipiuk, I fixed that and added another commit to migrate all the implementations to the new version

**Comment by losipiuk** [comment]
> Thanks @losipiuk, I fixed that and added another commit to migrate all the implementations to the new version

LGTM

**Review by aczajkowski — APPROVED** [review]
LGTM

**Pull request merged**
