### PR TITLE
Prevent delta lake transaction log entry creation on empty insert

### PR DESCRIPTION
**Pull request by pajaks**
## Release notes

(x ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by ebyhr** [comment]
What's the motivation of this change? OSS Delta Lake creates transaction files even for empty INSERT.

**Comment by pajaks** [comment]
> What's the motivation of this change? OSS Delta Lake creates transaction files even for empty INSERT.

Idea taken from PR review comment: https://github.com/trinodb/trino/pull/16026#discussion_r1104352125

**Comment by ebyhr** [comment]
We can't see the executed operations with `$history` system table. I don't think this change is a good idea from audit perspective.

**Comment by pajaks** [comment]
Databricks also creates transaction log for empty insert. Closing PR as current behaviour is expected then.

**Comment by findinpath** [comment]
> We can't see the executed operations with history system table after this change. 
> Do you know Databricks behavior?

image


@ebyhr good catch. Indeed Databricks records empty inserts in the history and the the fact that the query didn't have any output can be seen in the `operationMetrics` column:

```
{"numFiles": "0", "numOutputRows": "0", "numOutputBytes": "0"}
```

**Pull request closed without merging**
