### PR TITLE
Add support for loading configuration from toml files

### PR DESCRIPTION
**Pull request by wendigo**
## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by Praveen2112** [comment]
Can we have some example/Environment which uses this toml file as a part of configuration ?

**Comment by wendigo** [comment]
@Praveen2112 sure :)

**Comment by wendigo** [comment]
@electrum question whether directionally this is a way to go?

**Comment by wendigo** [comment]
@Praveen2112 here you go :)

**Comment by Praveen2112** [comment]
Are we planning to replace `properties` file with `toml` in general or do we have have plans on replacing multiple files with a single toml file ? i.e instead of iterating over a catalog directory for the list catalogs to be created - We could iterate over a single TOML file for the same ? 

Similarly multiple access connector can be configued via a single TOML file instead of multiple files configured as a part of `config.properties` i.e configured via `access-control.config-files` property

**Comment by electrum** [comment]
I don't think we want to simply replace each properties file with TOML. Rather, we'd like to have a single TOML file for everything, so that server config, catalogs, access control, etc., can all be in the same file. Maybe catalogs would be separate, since that is pluggable.

**Pull request closed without merging**
