### PR TITLE
Delay Some AvroTypeErrors to read time to allow union data to conform…

### PR DESCRIPTION
**Pull request by jklamer**
… to smaller union

## Description

HIVE/AVRO: It is possible for data that is written using a 3 element union to be read with a 2 element union provided that either all data types can be coerced (already possible) or the offending data type(s) isn't present. This change delays all type errors to read time to allow more type leniency.

Examples of new successful reads:
- Any two field types are compatible provided there is no data in the file 
- written [null, int] -> read [null, record]: will read successful if all the data in the field is null
- written [null, int, string] -> read [null, int]: will read successfully if all the data in the field is either null or an int

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(X ) Release notes are required, with the following suggested text:
HIVE/AVRO: It is possible for data that is written using a 3 element union to be read with a 2 element union provided that either all data types can be coerced (already possible) or the offending data type(s) isn't present. This change delays all type errors to read time to allow more type leniency.

Examples of new successful reads:
- Any two field types are compatible provided there is no data in the file 
- written [null, int] -> read [null, record]: will read successful if all the data in the field is null
- written [null, int, string] -> read [null, int]: will read successfully if all the data in the field is either null or an int

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by jklamer** [comment]
Test believed to be flaky. Will push empty or changes to retry after review.

**Comment by electrum** [comment]
Please shorten the commit title:

> Allow union data to conform to smaller union

**Review by electrum — APPROVED** [review]

**Comment by jklamer** [comment]
@electrum done

**Comment by hashhar** [comment]
the information from PR description is very very useful to have in commit body too.

**Comment by jklamer** [comment]
@hashhar done

**Review by hashhar — APPROVED** [review]

**Pull request merged**
