### PR TITLE
Improve printing of join criteria in PlanPrinter

### PR DESCRIPTION
**Pull request by raunaqmorarka**
## Description
Print join criteria and filter separately for clarity

## Additional context and related issues
e.g.
```
LeftJoin[criteria = ("custkey" = "custkey_2"), filter = ("orderdate_5" BETWEEN date_add('day', BIGINT '-30', "orderdate") AND "orderdate"), hash = [$hashvalue_11, $hashvalue_13], distribution = PARTITIONED]
```

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by lukasz-stec — APPROVED** [review]
lgtm

**Review by sopel39 — APPROVED** [review]
nit: you could add explain tests. make sure automation passes (there might be test already)

**Comment by raunaqmorarka** [comment]
unrelated failure https://github.com/trinodb/trino/issues/19045

**Comment by wendigo** [comment]
@raunaqmorarka unrelated failure is resolved now

**Review by wendigo — APPROVED** [review]

**Pull request merged**
