### PR TITLE
Do not consider stages which are still executing as completed

### PR DESCRIPTION
**Pull request by sopel39**
Previously phased scheduler scheduled next stage (e.g. probe source stage)
while splits for previous stage (e.g. build source stage) were stil queued
on worker nodes. In certain, non-deterministic scenarios this lead
to very pool split assignments that caused remaining build spits
to be competing for drivers slots with blocked probe splits.
This can significnalty increase query wall time.

### CODE REVIEW

**Comment by sopel39** [comment]
It prevents this (unlucky split allocation of blocked probe and build splits on same node)
Zrzut ekranu 2022-01-21 o 10 51 32



  | label | TPCH wall time | TPC-DS wall time | TPCH CPU time | TPC-DS CPU time | TPCH peak mem | TPC-DS peak mem
-- | -- | -- | -- | -- | -- | -- | --
baseline part | 845.091667 | 1136.074000 | 112368.2 | 134326.411667 | 2.146326e+09 | 1.254622e+09
baseline part | 880.779000 | 1156.097000 | 111335.0 | 132362.951667 | 2.146513e+09 | 1.251436e+09
baseline part | 820.132500 | 1509.949167 | 109727.5 | 133456.768333 | 2.143980e+09 | 1.253911e+09
flushing | 823.152667 | 1147.416167 | 110490.6 | 133393.498333 | 2.139559e+09 | 1.218028e+09

label | TPCH wall time | TPC-DS wall time | TPCH CPU time | TPC-DS CPU time | TPCH peak mem | TPC-DS peak mem
-- | -- | -- | -- | -- | -- | --
baseline unpart | 744.836167 | 1797.205167 | 98262.0 | 240302.869500 | 2.077188e+09 | 1.125668e+09
flushing | 748.735333 | 1830.377000 | 98381.7 | 239354.763333 | 2.061210e+09 | 1.089139e+09

**Comment by sopel39** [comment]
fyi @martint @pettyjamesm

**Review by losipiuk — APPROVED** [review]
This looks reasonable to me. 
@arhimondr PTAL too.

**Comment by arhimondr** [comment]
I pretty much have the same concerns as @losipiuk. Delaying scheduling util stage completion may introduce additional latency. It would be nice to check how it behaves on smaller data sets (sub second queries)

**Comment by sopel39** [comment]
Actually we are trying to address `SplitConcurrencyController` concurrency issue here.
The problem is as follows:
* build splits schedule
* FAST probe splits schedule
* probe split block
* build finishes
* probe splits unblock and probe splits finish. This happens withing first 100ms of query
* probe splits rapidly finish and `SplitConcurrencyController#splitFinished` brings down concurrency in cascade

I will try another approach where `SplitConcurrencyController` won't use "quick splits" path right from the beginning to prevent cascade concurrency drop

**Comment by sopel39** [comment]
no noticable gain, closing

**Pull request closed without merging**
