### PR TITLE
Snowflake connector

### PR DESCRIPTION
**Pull request by taher-cldcvr**
## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by ebyhr** [comment]
This is a duplicate of #10387

**Comment by taher-cldcvr** [comment]
@ebyhr This commit implements JdbcJoinPushDownModule and also is collecting stats from snowflake to make query plans better. We do not see that happening this [pr](https://github.com/trinodb/trino/pull/10387)

**Comment by ebyhr** [comment]
@taher-cldcvr Some features are excluded intentionally.

**Comment by taher-cldcvr** [comment]
@ebyhr may i ask why this PR is not being considered even though it has those features tested and implemented already ?

**Pull request closed without merging**
