### PR TITLE
[DEFUNCT] Reword Oracle pushdown support to clarify which types are unsupported

### PR DESCRIPTION
**Pull request by jhlodin**
The wording of this link confuses which column types don't support predicate pushdown. Reword slightly to make it clear that "these" doesn't mean "all the Trino data types in the linked table"

### CODE REVIEW

**Review by hashhar — APPROVED** [review]

**Comment by hashhar** [comment]
CI hit https://github.com/trinodb/trino/issues/10674

**Comment by jhlodin** [comment]
> CI hit #10674

@hashhar Is there something I need to do on this PR to address that?

**Comment by hashhar** [comment]
@jhlodin Can you rebase your branch on updated `master` to get CI to run once more? The failure was fixed in `master` since then.

**Comment by jhlodin** [comment]
Well I screwed up the rebase on this PR so I just recreated it here. Sorry!  https://github.com/trinodb/trino/pull/10713

**Pull request closed without merging**
