### PR TITLE
Change catalog not found error messages to match error code name

### PR DESCRIPTION
**Pull request by charlesjmorgan**
## Description
The error code name when a catalog is not found is `CATALOG_NOT_FOUND` but the message is always `Catalog 'X' does not exist` which doesn't match the error name. This PR changes all the error messages to `Catalog 'X' not found`

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Review by mosabua — APPROVED** [review]
I agree with this change since it is also semantically more correct. The catalog might in fact exist, but just not be available for a user due to access control restrictions. The "not found" message does not imply anything about the catalog existing or not.

**Review by ebyhr — APPROVED** [review]

**Comment by mosabua** [comment]
Also since this is kind of a semantic change I am adding the syntax needs review label although its maybe a stretch. cc @martint 

Build failures still need to be fixed. And it might also be worth following up with simmilar changes about schemas, tables and other objects. But that can be done in another PR imho.

**Comment by martint** [comment]
This PR contains two separate changes:
* returning CATALOG_NOT_FOUND error code
* changing the error message text

Split them into two separate commits, as they are logically independent changes.

As an aside, regarding the motivation described above, there’s no requirement that the error code name be equal to the content of the error message.

**Comment by mosabua** [comment]
> As an aside, regarding the motivation described above, there’s no requirement that the error > code name be equal to the content of the error message.

Fair enough. I was not trying to imply that. In this case however the error message code is more correct than the message and changing it is the correct thing to do in my opinion.

**Comment by charlesjmorgan** [comment]
I split the commits as requested

> This PR contains two separate changes:
>
> - returning CATALOG_NOT_FOUND error code
> - changing the error message text
>
> Split them into two separate commits, as they are logically independent changes.

**Comment by mosabua** [comment]
I think we should be good to merge this. Any objections @martint ?

**Pull request merged**
