### PR TITLE
Use upper bounded wildcard to read and delete cookie

### PR DESCRIPTION
**Pull request by krvikash**
## Description
Use upper bounded wildcard to read and delete cookie. It will help to use same api to read and delete `NewCookie`.

### CODE REVIEW

**Review by ksobolew — APPROVED** [review]
There's also `OAuthIdTokenCookie`, AFAICT

**Comment by krvikash** [comment]
Thanks @ksobolew for the review. Added `OAuthIdTokenCookie` as well.

**Review by wendigo — APPROVED** [review]

**Comment by mosabua** [comment]
I assume no release note entry needed @wendigo and @krvikash  .. note please use template or label to indicate on each PR.

**Comment by wendigo** [comment]
@mosabua no, this is helper util :)

**Pull request merged**
