### PR TITLE
Support insert overwrite partition for iceberg

### PR DESCRIPTION
**Pull request by ans76**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

> How would you describe this change to a non-technical end user or system administrator?

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Support insert overwrite partition for iceberg
```

### CODE REVIEW

**Comment by findepi** [comment]
cc @electrum @dain @martint

**Comment by Chaho12** [comment]
Would there be any plans to add this feature?

**Comment by amir-upstream** [comment]
We really want this feature also, we highly depend on partition write overwrite mode in hive and this makes the switch to iceberg harder

**Review by dimasm1 — APPROVED** [review]

**Comment by nooberfsh** [comment]
We want this too.

**Comment by mosabua** [comment]
:wave: @ans76 @findepi  - this PR has become inactive. We hope you are still interested in working on it. Please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Review by amir-upstream — APPROVED** [review]

**Comment by mosabua** [comment]
@amir-upstream and @ans76 .. this PR needs to be rebased so we can review and work towards merge.

**Comment by mosabua** [comment]
@cwsteinbach and @alex can you chime in here

**Pull request closed without merging**
