### PR TITLE
Update joda-time to 2.10.14

### PR DESCRIPTION
**Pull request by wendigo**
https://www.joda.org/joda-time/changes-report.html#a2.10.14

### CODE REVIEW

**Review by findepi — CHANGES_REQUESTED** [review]
This requires a discussion.

Joda releases notes mention a fork TZ database and https://github.com/JodaOrg/joda-time/issues/566 states that explicitly too.
I see why Joda chose to use a fork to maintain compatibility, but we have a problem. We use both: Joda Time and Java Time and we need them to agree. Better compatibility is not beneficial to use, if we can get weird, incorrect or inconsistent results.

A possible way forward could be to use same TZ in both libraries. I remember we tried that and there were problems with it, but i don't remember the details.

cc @electrum @martint @losipiuk @dain

**Comment by wendigo** [comment]
@findepi And what about removing Joda usage instead?

**Comment by findepi** [comment]
> @findepi And what about removing Joda usage instead?

That would be nice to have one library.

I think someone experimented with that in the past, but i don't have any numbers.

OTOH, "don't upgrade" is not a solution either. We will need to upgrade sooner or later -- as soon as when Java's tz database gains a new time zone. cc @trinodb/maintainers @ilfrin 

Does Joda allow to switch over to a standard tz database instead of a fork?
(i am assuming Java Time won't switch over)

**Comment by findepi** [comment]
Do you want to start a conversation with the Joda Time community about this?

**Comment by findepi** [comment]
@wendigo can you please add a test that would expose the problem we're concerned here about?

**Pull request closed without merging**
