### PR TITLE
Convert selected Oracle tests to use SqlDataTypeTest

### PR DESCRIPTION
**Pull request by brandboat**
relates to #6394

### CODE REVIEW

**Review by hashhar — CHANGES_REQUESTED** [review]
Thanks a lot for doing this via small contained commits - was much easier to review than the full diff (even though we might want to squash before merge anyway).

Let's also execute all tests that are using `trinoCreateAsSelect` to also use `trinoCreateAndInsert`.
In Trino CREATE TABLE AS SELECT follows a different code path compared to INSERT.

**Comment by brandboat** [comment]
@hashhar Thanks for your review ! I've addressed your comments in b8cbbbb

**Review by hashhar — APPROVED** [review]
Looks good to me.

Please update the linked issue (or create a new one) mentioning the remaining tests (for temporal types) that need to be migrated.

**Comment by brandboat** [comment]
> Please update the linked issue (or create a new one) mentioning the remaining tests (for temporal types) that need to be migrated.

Copy that, update in https://github.com/trinodb/trino/issues/6394#issuecomment-799991289

**Comment by findepi** [comment]
Merged, thanks!

**Pull request merged**
