### PR TITLE
Support propagation of custom split info when using custom input format

### PR DESCRIPTION
**Pull request by akshayrai**
## Description
This PR adds support for extracting and propagating custom split related info when using a custom input format.

When using a custom input format in the hive connector, we would like to extract and propagate some additional custom split related info along with the split metadata. The metadata will be used later during data streaming to recreate a custom split from file split and pass it to the custom input format's getRecordReader interface for processing the records.

If anyone wants to leverage this, they can implement the CustomSplitConverter interface and plug that into the HiveModule. We need to note that Trino Hive connector isn't designed to support custom formats out of the box. You may get things to working by adding additional jars to its classpath, but this may break in a future release without warning.

## Additional context and related issues
At LinkedIn, we use a CDC system called [Opal](https://engineering.linkedin.com/blog/2022/opal--building-a-mutable-dataset-in-data-lake) and we are using a custom input format on Trino to read those datasets. This is slightly analogous to Hudi but the implementations are different. Though Hudi has taken a separate connector route for reasons of evolution, we don't think a separate connector is suitable for our use-case. We have it working internally by just implementing the RecordCursor interface within the Hive Connector and leveraging the custom input format hooks available in the hive connector. Though the custom input format is a pluggable implementation, the above custom split related info propagation is something we feel can be utilized by other custom input formats. We also want to avoid maintaining the patch internally as it touches multiple files and interfaces and see if the community is welcome to these changes.

This PR leverages some a lot of capabilities (like the CustomSplitConverter) proposed in this Hudi [PR](https://github.com/trinodb/trino/pull/9641).

## Release notes
(x) This is not user-visible or docs only and no release notes are required.
() Release notes are required, please propose a release note for me.
() Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by findepi** [comment]
What is a custom input format?

**Comment by akshayrai** [comment]
> What is a custom input format?

Custom input format is any implementation of Hadoop's InputFormat interface. Trino's Hive connector has a hook for reading such formats by annotation the Impl class with _UseFileSplitsFromInputFormat_. Just linking the relevant part of the code [here](https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java#L512).

**Comment by akshayrai** [comment]
> Trino Hive connector isn't designed to support "custom formats". It's a "sealed box product". You may get things to working by adding additional jars to its classpath, but this may break in a future release without warning.
> 
> I think it's good to state the above explicitly. Not that I expect it will have impact on what you're trying to do.

Ack! Sure, I can put a quote in the description of the PR. But why do you say so? Are there any known limitations or issues with this form of integration? And have there been any discussions around it on what is recommended or how to plug such formats to Trino?

**Comment by findepi** [comment]
i believe this was always trino philosophy, but @electrum would know better

**Comment by akshayrai** [comment]
@electrum could you help review this PR?

**Comment by akshayrai** [comment]
@findepi, I updated the description highlighting the implications as you stated. Would you be able to review the PR or should we relay this to electrum to take a look?

**Comment by mosabua** [comment]
:wave: @akshayrai  - this PR has become inactive. We hope you are still interested in working on it. Please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by hashhar** [comment]
Custom input formats are now something that don't align with the de-hadoop direction we're going.

See Dain's detailed comment about why and the options here: https://github.com/trinodb/trino/issues/19018#issuecomment-1795742792

Closing this because of that, feel free to re-open if this can be reworked keeping in mind Dain's comments.

**Pull request closed without merging**
