### PR TITLE
Presto router

### PR DESCRIPTION
**Pull request by luohao**
Add a router module that does rule-based redirecting. It's a stateless service that can be deployed in multiple instances behind a load balancer. It includes a UI similar to what Presto includes.

cc: @dain @electrum

### CODE REVIEW

**Comment by sopel39** [comment]
Thanks for contribution.

Few questions:
* Does the router have GUI?
* Does it support authentication (LDAP, Kerberos, JWT)?
* Does it automatically route REST requests (based on Query Id) to appropriate cluster (e.g can it be used to gracefully phase out cluster)?

**Comment by findepi** [comment]
@beinan we don't have our CLA on file yet. Could you please fill it?
See https://github.com/prestosql/cla for guidance.

**Comment by luohao** [comment]
> Does the router have GUI?
YES

> Does it support authentication (LDAP, Kerberos, JWT)?
NO, it redirects the query to the coordinator and auth is done in the coordinator. It does similar things like the presto-proxy, but with rule-based redirection.

> Does it automatically route REST requests (based on Query Id) to appropriate cluster (e.g can it be used to gracefully phase out cluster)?
Not based on Query Id (it doesn't generate query id), but rather based on other query contexts like `user` and `source`.

**Comment by kokosing** [comment]
>  It does similar things like the presto-proxy, but with rule-based redirection.

Why not to add `rule-based redirection` to `presto-proxy` then? How user will know when to use which?

**Comment by sopel39** [comment]
> Not based on Query Id (it doesn't generate query id), but rather based on other query contexts like user and source.

So user will always be routed to same cluster? How do you grafecully deal with cluster termination then?

**Comment by dain** [comment]
> > It does similar things like the presto-proxy, but with rule-based redirection.
> 
> Why not to add `rule-based redirection` to `presto-proxy` then? How user will know when to use which?

We had a similar system at Facebook.  The servers are complimentary.  The proxy is expensive because it proxies all requests, and requires SSL termination, so there must be a trust relationship.  The router simply inspects the query request and then routes it to a cluster that can server the query.  At FB we used this to select an interactive or batch cluster in a datacenter containing the data being queried.  We also used a proxy in front of the gateway for requests crossing security domains (e.g. corp to prod).

The answer on how users will know what to use is pretty simple.  If they want routing they will need a router, then they will use a router.  If they want to hide backend servers (and HTTP redirects) from the clients, they would use a proxy.  If they want both, they would run both, and can choose which order they are applied.

>>> Does it automatically route REST requests (based on Query Id) to appropriate cluster (e.g can it be used to gracefully phase out cluster)?
>
> > Not based on Query Id (it doesn't generate query id), but rather based on other query contexts like user and source.
> 
> So user will always be routed to same cluster? How do you gracefully deal with cluster termination then?

With the router, the client gets a redirected a cluster (coordinator), and then all future requests for that query are sent directly to that cluster.  This can be used for cluster turn-down by simply removing the cluster's coordinators from the possible redirection targets.  We used this at Facebook for cluster draining.

**Comment by luohao** [comment]
There seems to have some unrelated failures. I'll rebase and re-run the Travis tests.

**Comment by sopel39** [comment]
> With the router, the client gets a redirected a cluster (coordinator), and then all future requests for that query are sent directly to that cluster.

But that requires routing based on Query Id, which I don't think is supported by this router implementation, I'm I correct @luohao

**Comment by luohao** [comment]
> But that requires routing based on Query Id, which I don't think is supported by this router implementation, I'm I correct @luohao ?

No, the query routing is not based on query id. 

Only the first request to `/v1/statement` hits the router, and the router will find a coordinator for this query to execute based on `RequestInfo`(which is a set of attributes parsed from the request, e.g., user, source). The router sends a response with code `307` and the Presto coordinator URI so that the client will resend the request to the Presto coordinator. All subsequent requests will happen between the client and the coordinator.

**Comment by puneetjaiswal** [comment]
Couple of pointers (from what I learned from our gateway- https://github.com/lyft/presto-gateway ):

1. How does this handle routing for kill query commands ? 
BI tools like Apache-superset/mode/looker send kill query commands when user cancels the query.
`CALL system.runtime.kill_query(query_id => '20190628_193620_05456_x9ux4', message => 'Looker query cancel.')`

2. SAAS BI tools like mode/looker can't follow the redirect response (since they access internal infra via a gateway/bridge)

3. How would router be aware of transactions? (We are working on adding session stickiness based on both query and transaction id - if present.) please take a look - https://github.com/lyft/presto-gateway/issues/48

**Comment by beinan** [comment]
> @beinan we don't have our CLA on file yet. Could you please fill it?
> See https://github.com/prestosql/cla for guidance.

submitted,  thanks for the link!

**Comment by luohao** [comment]
> Couple of pointers (from what I learned from our gateway- https://github.com/lyft/presto-gateway ):
> 
> 1. How does this handle routing for kill query commands ?
>    BI tools like Apache-superset/mode/looker send kill query commands when user cancels the query.
>    `CALL system.runtime.kill_query(query_id => '20190628_193620_05456_x9ux4', message => 'Looker query cancel.')`

Good point. It currently doesn't handle kill command. Supporting it would need to have the query id map stored somewhere, such as external storage.

> 2. SAAS BI tools like mode/looker can't follow the redirect response (since they access internal infra via a gateway/bridge)

We also noticed that ODBC driver in our tableau server doesn't handle redirect. We have to set up a separate cluster for it.

> 3. How would router be aware of transactions? (We are working on adding session stickiness based on both query and transaction id - if present.) please take a look - [lyft/presto-gateway#48](https://github.com/lyft/presto-gateway/issues/48)

No, the current implementation doesn't handle transactions. We need to figure out how to support it. One idea is to have a transaction map stored externally in some K/V store so routers stay stateless and lookup the external storage for coordinator where the transaction resides.

**Comment by dain** [comment]
> > Couple of pointers (from what I learned from our gateway- https://github.com/lyft/presto-gateway ):
> > 
> > 1. How does this handle routing for kill query commands ?
> >    BI tools like Apache-superset/mode/looker send kill query commands when user cancels the query.
> >    `CALL system.runtime.kill_query(query_id => '20190628_193620_05456_x9ux4', message => 'Looker query cancel.')`
> 
> Good point. It currently doesn't handle kill command. Supporting it would need to have the query id map stored somewhere, such as external storage.

Routing the above requires the routing code to be able to parse analyze and possibly partially execute the above query (IIRC it is legal for the queryId literal to be an expression).  Instead, BI tools should be using the cancel URI sent with each request, or send a PUT http request to `/v1/query/{queryId}/killed` containing the message in the body.

> We also noticed that ODBC driver in our tableau server doesn't handle redirect. We have to set up a separate cluster for it.

I recommend switching Tableau to the JDBC driver.

**Comment by luohao** [comment]
> Routing the above requires the routing code to be able to parse analyze and possibly partially execute the above query (IIRC it is legal for the queryId literal to be an expression). Instead, BI tools should be using the cancel URI sent with each request, or send a PUT http request to `/v1/query/{queryId}/killed` containing the message in the body.
> 
> >

Yeah, if BI tool sends `/v1/query/{queryId}/killed` to kill a query, it's technically possible to route the query to the right coordinator because the router alreay tracks running queries in all Presto clusters.

Also for transaction support, we have a workaround that routes all queries in transactions(e.g., `START TRANSACTION` and subsequent queries with transaction id header) to one cluster (it works for us because we don't have a lot of transactions in Prseto). Our internal version has `QueryType` and transaction id header as selection criteria, but I didn't include `QueryType` in this PR to avoid dependency on `presto-main` (I was discussing with @martint about whether can we move the `StatementUtils` to some other modules).

**Comment by dain** [comment]
> Also for transaction support, we have a workaround that routes all queries in transactions(e.g., `START TRANSACTION` and subsequent queries with transaction id header) to one cluster (it works for us because we don't have a lot of transactions in Prseto).

In my remote coordinator branch, I have special endpoints that the dispatcher uses to list every query and transaction on all coordinators, and then use that to route kill commands and to send a query to the coordinator managing the transaction.

**Comment by tooptoop4** [comment]
are u still working on this @luohao ?

**Pull request closed without merging**
