### PR TITLE
Handle duplicate expressions in CTAS with partitioning

### PR DESCRIPTION
**Pull request by weiatwork**
## Description
There is a scenario that CTAS queries could fail when the same expression appears more than once (`'01'` in below example query) and they are used as partition columns (e.g. with Hive connector).
```
CREATE TABLE tbl
WITH (partitioned_by = ARRAY['year', 'month', 'day' ])
AS SELECT
  'somevalue' as c1,
  '2010' as year,
  '01' as month,
  '01' as day
WITH NO DATA;
```

```
Query 20230331_162800_00000_3zv84 failed: Multiple entries with same key: expr_1=expr_1 and expr_1=expr_1
```

To some extent this is similar to #8023 @martint 

## Release notes

(X) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

Fixes https://github.com/trinodb/trino/issues/17072

### CODE REVIEW

**Comment by weiatwork** [comment]
I've verified locally. Please let me know the relevant UT that should be enhanced if any.

**Comment by leetcode-1533** [comment]
Please add a unit test or integration test for this,

**Comment by findepi** [comment]
> There is a scenario that CTAS queries could fail when the same expression appears more than once (`'01'` in below example query) and they are used as partition columns (e.g. with Hive connector).
> 
> ```
> CREATE TABLE tbl
> WITH (partitioned_by = ARRAY['year', 'month', 'day' ])
> AS SELECT
>   'somevalue' as c1,
>   '2010' as year,
>   '01' as month,
>   '01' as day
> WITH NO DATA;
> ```
> 
> ```
> Query 20230331_162800_00000_3zv84 failed: Multiple entries with same key: expr_1=expr_1 and expr_1=expr_1
> ```

@weiatwork can you please file this is an issue for visibility?

**Comment by weiatwork** [comment]
@leetcode-1533 Any suggestion on a good place to add new test for it?

@findepi Issue https://github.com/trinodb/trino/issues/17072 is created

**Comment by mosabua** [comment]
@findepi and @martint could you please chime in here

**Pull request closed without merging**
