### PR TITLE
Derive non-null from symbol-to-symbol comparisons in domain translator

### PR DESCRIPTION
**Pull request by sopel39**

### CODE REVIEW

**Comment by sopel39** [comment]
This might be too simplistic without support for things like `x = y + 1`

**Comment by findepi** [comment]
Slightly related: https://github.com/prestosql/presto/pull/2415

**Comment by sopel39** [comment]
@kasiafi would you like to generalize this? We could discuss if you want

**Comment by sopel39** [comment]
> his change crosses the line between extracting what's described by the expression to inferring properties based on the semantics of values and operations. Those inferences belong in upper layers (EqualityInference or a generalization of it, PredicatePushdown, etc). Now, it's possible DomainTranslator is no longer the right abstraction for performing the actions we need, but we have to be very careful about how to evolve it given everywhere it's being used.

`PredicatePushdown` could derive `x NOT null` predicates too. However, it only makes sense in joins: https://github.com/prestosql/presto/pull/2415
For non-join filter redundant predicates like `x NOT null` would stay in plan and be evaluated for every row. That's why I think `DomainTranslator` is a right place for this deduction.

**Comment by tooptoop4** [comment]
travis-bot retest/

**Comment by mosabua** [comment]
:wave: @sopel39  - this PR has become inactive.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Pull request closed without merging**
