### PR TITLE
Refactor: use `Switch Expression` in Java 17

### LINKED ISSUE #13979: Use `Switch Expression` in Java 17
trino have used java 17.
We can use new feature in java 17 -- `Switch Expression` to improve the code

### PR DESCRIPTION
**Pull request by jackwener**
Signed-off-by: jackwener <jakevingoo@gmail.com>

## Description
use `Switch Expression` in Java 17

> Is this change a fix, improvement, new feature, refactoring, or other?

refactoring

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

general.

> How would you describe this change to a non-technical end user or system administrator?

refactor code

## Related issues, pull requests, and links

* Fixes #13979

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Refactor: use `Switch Expression` in Java 17. ({issue}`13979`)
```

### CODE REVIEW

**Comment by martint** [comment]
@cla-bot check

**Comment by jackwener** [comment]
look like checkstyle is wrong, I'll fix it.

**Comment by findepi** [comment]
@jackwener thank you for your PR

is the change manual or automated?

**Comment by jackwener** [comment]
use idea auto format

**Comment by jackwener** [comment]
Hi @findepi , PTAL

**Review by electrum — APPROVED** [review]
Apologies the delay. Please rebase and then I'll merge this

**Pull request closed without merging**
