### PR TITLE
Remove local file connector

### PR DESCRIPTION
**Pull request by wendigo**
Supersedes: https://github.com/trinodb/trino/pull/23551

I've applied fixes to make build happy.

### CODE REVIEW

**Comment by ebyhr** [comment]
@wendigo Why did you ignore https://github.com/trinodb/trino/pull/23551#issuecomment-2371942708?

**Comment by wendigo** [comment]
@ebyhr I didn't, I just doubt that anyone uses it and we can always revert a commit if needed.

**Comment by ebyjacob** [comment]
@wendigo We would need the local file connector, as we will be using this extensively. Would appreciate if this could be supported in future releases.

**Comment by hashhar** [comment]
@ebyjacob This connector doesn't read "files from local filesystem". It only reads the Trino HTTP request log.

For local files see https://github.com/trinodb/trino/pull/25006. I assume that's what you were actually looking for?

**Pull request merged**
