### PR TITLE
Fix formatting in EXPLAIN docs

### PR DESCRIPTION
**Pull request by verhovsky**

### CODE REVIEW

**Review by mosabua — APPROVED** [review]
lgtm .. trivial change. Maybe we can get that merged before the release tomorrow @martint and @colebow .. 

If you have not done so already .. could you sign and submit the CLA document please @verhovsky .. this is required for a merge.

**Comment by verhovsky** [comment]
signed.

**Comment by verhovsky** [comment]
can I re-run the CLA check for this and my other PR?

**Comment by martint** [comment]
@cla-bot check

**Pull request merged**
