### PR TITLE
Use standard Hive query runner in fault tolerant execution tests

### PR DESCRIPTION
**Pull request by losipiuk**
With this change FTE tests use Hive query runner which does not depend on Hive docker images. Hive docker images in use do not work properly on ARM64 architecture which makes it hard to diagnose tests issues on Apple M1 laptops.

### CODE REVIEW

**Comment by losipiuk** [comment]
The downside of this PR is that it makes test coverage somewhat worse. We are not testing against reals Hive metastore + S3. @arhimondr what is your take on that?

**Comment by losipiuk** [comment]
cc: @findepi

**Comment by linzebing** [comment]
I would prefer having better coverage. Isn't the correct way is to fix the docker image themselves?

**Comment by losipiuk** [comment]
> I would prefer having better coverage. Isn't the correct way is to fix the docker image themselves?

I do not believe it is possible with Hive images. We do not have Hive images compiled for ARM. Also, Hive versions we are using are running on Java8 which is not very ARM friendly (experimental support only according to what @findepi told me). There is a slim chance that we could craft a working docker image for ARM using newer java, but I have little hope for that.

**Comment by mosabua** [comment]
@losipiuk is this still in progress or should we close?

**Pull request closed without merging**
