### PR TITLE
Remove deprecated access control functions

### PR DESCRIPTION
**Pull request by ksobolew**
## Description

They were deprecated in 445 when replacement methods were added; I guess 10 versions is long enough for a transition period.

## Additional context and related issues

Related PR: #21374

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# SPI (Breaking Change)
* Removed deprecated variants of `checkCanExecuteQuery` and `checkCanSetSystemSessionProperty` that do not take `QueryId` parameter from `SystemAccessControl`. ({issue}`23244`)
```

### CODE REVIEW

**Review by hashhar — APPROVED** [review]

**Comment by ebyhr** [comment]
> (x) This is not user-visible or is docs only, and no release notes are required.

We should mention SPI changes in release notes. Could you update the PR description?

**Comment by ksobolew** [comment]
> We should mention SPI changes in release notes. Could you update the PR description?

You're right, I'll fix. On the other hand, I was expecting revapi to complain - does it ignore changes to deprecated methods?

**Comment by mosabua** [comment]
Hey @dain I am reopening this.. I think we should still do this clean up. Thoughts?

**Comment by mosabua** [comment]
If necessary.. please rebase @ksobolew

**Comment by mosabua** [comment]
Also added stale-ignore label

**Review by wendigo — APPROVED** [review]

**Comment by ksobolew** [comment]
@wendigo there's one failing test:

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 205.5 s <<< FAILURE! -- in io.trino.filesystem.alluxio.TestAlluxioFileSystem
Error:  io.trino.filesystem.alluxio.TestAlluxioFileSystem -- Time elapsed: 205.5 s <<< ERROR!
java.util.concurrent.ExecutionException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image alluxio/alluxio:2.9.5
```

It's clearly unrelated.

**Pull request merged**
