### PR TITLE
Skip calculating table_type when not needed

### PR DESCRIPTION
**Pull request by findepi**
## Description

`ConnectorMetadata.listTables` returns all relations (tables, views,
materialzied views). Thus, when reading `information_schema.table` and
`table_type` column is not needed, the `getViews` call can be skipped.
`getViews` can be expensive as it pulls view information sometimes even
converting it (e.g. in case of Hive views).

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]
Looks good except for `TestInformationSchemaConnector.testMetadataCalls` failure.

**Comment by findepi** [comment]
> Looks good except for `TestInformationSchemaConnector.testMetadataCalls` failure.

Thanks @ebyhr  for pointing this out and the fix. I think i will fix it slightly differently, not to loose test coverage for the "typical case" (assuming it's typical to select table_type column).

**Comment by ebyhr** [comment]
I don't think the modified query itself is typical though the internal path might be typical. I believe code readers won't understand why those queries contain a `coalesce` function.

**Comment by findepi** [comment]
@ebyhr updated

**Pull request merged**
