### PR TITLE
Add docs for fs caching with Hudi

### PR DESCRIPTION
**Pull request by mosabua**
## Description

Docs for incoming code PR from @codope and @yihua

## Additional context and related issues

Part of https://github.com/trinodb/trino/issues/20550

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Review by electrum — APPROVED** [review]

**Comment by ebyhr** [comment]
@mosabua This PR is already approved. Can we merge if there is no remaining task?

**Comment by mosabua** [comment]
@ebyhr .. we can not merge this since fs caching is not yet implemented for the Hudi connector.

From what I understand the plan is for @yihua to work on the upgrade to Hudi 1.0 which includes the dehadooping .. and then work on fs caching after .. and then move on to add write support. So this PR is on hold but ready to merge when implementation is done.

**Comment by ebyhr** [comment]
I don't think it happens soon. Please reopen when the implementation is done.

**Comment by mosabua** [comment]
Sure.

**Pull request closed without merging**
