### PR TITLE
Revert "Add support for OpenTelemetry in JDBC connectors"

### PR DESCRIPTION
**Pull request by hashhar**
This reverts commit 7b269fac5c9056c42f7d0ea713a05ec11a508036.

We've observed NullPointerException being thrown like:

    Error listing schemas for catalog bootcamppostgresql: java.lang.NullPointerException: Cannot invoke "java.sql.Connection.getMetaData()" because "connection" is null.

The error comes from OpenTelemetry code
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/9cf710f17c028d017ae0520d595ef72b9917e241/instrumentation/jdbc/library/src/main/java/io/opentelemetry/instrumentation/jdbc/internal/JdbcUtils.java#L102.

After a proper fix is available the reverted commit can be reintroduced.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# XXX
* xxx. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]
I think the release entry isn't required because it's not user-facing. At least, we didn't mention the JDBC connector's tracing in the past release notes like other modules.

**Comment by martint** [comment]
What’s involved in fixing the actual problem? Can we just do that instead of reverting the change?

**Comment by hashhar** [comment]
@martint right now I've been unable to find a source for why otel gets null connections.

Yuya submitted a patch to otel to fix the NPE however we need to wait for releases.

I'd prefer to reintroduce this once we have a fix instead of keeping around functionality that we know to be broken.

**Comment by martint** [comment]
@ebyhr, BTW, if this fixes a user-visible error, it should have a release note. Something like "Fix failure when xxx". It's not about whether the issue is related to tracing or not, but whether the users are visibly affected by the problem. We want to make it easier for people to be able to find out whether a given release fixes a problem they are experiencing.

**Review by wendigo — APPROVED** [review]

**Comment by electrum** [comment]
Can we simply disable this rather than reverting the entire change? It's best to eliminate code churn when possible.

**Comment by hashhar** [comment]
superseded by https://github.com/trinodb/trino/pull/19021

**Pull request closed without merging**
