### PR TITLE
Test: Enable Select pushdown on uncompressed files

### PR DESCRIPTION
**Pull request by findepi**
test for https://github.com/trinodb/trino/pull/12633 with secrets

### CODE REVIEW

**Comment by preethiratnam** [comment]
Hi @ilfrin @nineinchnick there are some tests failing on the Iceberg plugin. I'm not sure if it was caused by my changes in the Hive plugin. Can you please help debug?

**Comment by nineinchnick** [comment]
> Hi @ilfrin @nineinchnick there are some tests failing on the Iceberg plugin. I'm not sure if it was caused by my changes in the Hive plugin. Can you please help debug?

I don't know anything about these, but looks like you should rebase over latest master to include #12707

**Comment by preethiratnam** [comment]
> I don't know anything about these, but looks like you should rebase over latest master to include #12707

Hi @nineinchnick I've now rebased to latest master. Can you please re-run the tests?

**Comment by nineinchnick** [comment]
I'm not a maintainer and I don't have any permissions in this repository. @findepi can you do this? BTW I am currently working on streamlining this :-)

**Comment by findepi** [comment]
> BTW I am currently working on streamlining this :-)

Thanks you @nineinchnick 

> Can you please re-run the tests?

done

**Pull request closed without merging**
