### PR TITLE
Move tracing code from trino-main to trino-plugin-toolkit

### PR DESCRIPTION
**Pull request by oskar-szwajkowski**
## Description
Move tracing code from trino-main to trino-plugin-toolkit
This way more modules could utilize this code when dealing with capturing some tracing details in spans

## Additional context and related issues
Tracing is not specific to `trino-main`, and it could be utilized within plugins to trace some specific parts of execution. Even though `Tracer` is exposed, some other utilities like `ScopedSpan` were not.

## Release notes

(X) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by electrum — CHANGES_REQUESTED** [review]
What is the motivation here? Most of the attributes are specific to the engine and would not be needed by connectors. Also, `TracingConnectorMetadata` doesn't seem useful to reuse.

We could consider moving `ScopedSpan`, but if you look at `TracingHiveMetastore` and `TracingFileSystem`, you can see that we use a different pattern where we record the exception.

It's not a problem to have a few duplicated utility classes. That is better than creating a shared API that is the wrong shape.

**Comment by oskar-szwajkowski** [comment]
> `TracingConnectorMetadata`

This is actually my main motivation.
I want to add traces to objectstore connector in galaxy, because right now we only track outer spans, and with this change it would allow us to track 'internal' connector calls and see details about which table types are queried etc.

**Comment by electrum** [comment]
Since this is a private plugin and likely requires changes, I suggest copying the code into your plugin.

**Comment by oskar-szwajkowski** [comment]
> Since this is a private plugin and likely requires changes, I suggest copying the code into your plugin.

ye, I'll most likely do that

**Pull request closed without merging**
