### PR TITLE
Add .sdkmanrc java version

### PR DESCRIPTION
**Pull request by wendigo**
While jenv is fine, I personally find sdkman much more convenient. Adding .sdkmanrc instructs sdkman to use a specified java vendor and version to use.

### CODE REVIEW

**Comment by wendigo** [comment]
I had no idea that we already have this file here :)

**Comment by wendigo** [comment]
When sdkman is installed:
```
cd ~/trino
Stop! java 22.0.1-tem is not installed.

Run 'sdk env install' to install it.
(base) ➜  trino git:(serafin/sdkman) ✗ sdk env install

Downloading: java 22.0.1-tem

In progress...

######################################################################## 100.0%

Repackaging Java 22.0.1-tem...
Stop! java 22.0.1-tem is not installed.

Run 'sdk env install' to install it.

Done repackaging...
Cleaning up residual files...

Installing: java 22.0.1-tem
Done installing!

Do you want java 22.0.1-tem to be set as default? (Y/n):
Setting java 22.0.1-tem as default.

Using java version 22.0.1-tem in this shell.
```

**Comment by wendigo** [comment]
@findepi ptal

**Review by findepi — APPROVED** [review]
I am fine with the change. Previously some maintainers were strongly against adding new top level files in the project, based on the concern that it makes the README harder to see in the GitHub UI. So not sure you should merge this.

**Comment by wendigo** [comment]
That's a valid concern @findepi. I can live without this change. I'll add this file to .gitignore instead so I can have my own.

**Comment by findepi** [comment]
BTW for the same reason we probably should have thought twice before adding `.idea` folder and `.temurin-release` file.
Maybe we can move docs under core to reclaim some space?

**Comment by wendigo** [comment]
@findepi food for though, use git prehook to place these files on root while keeping them elsewhere

**Pull request closed without merging**
