### PR TITLE
Remove JdbcIdentity

### PR DESCRIPTION
**Pull request by kokosing**
Remove JdbcIdentity

JdbcIdentity is not much different to ConnectorIdentity.
Only groups and roles are missing.

JdbcIdentity is adding another separation layer that makes code cannot
be reused between connectors that are not based on trino-base-jdbc framework.

Notice that one can say they can also groups or used roles may
also affect user access to objects. This depend how JDBC connector is
implemented.

### CODE REVIEW

**Comment by kokosing** [comment]
This is a draft, I would like to feel your opinions first before polishing this.

**Review by ksobolew — COMMENTED** [review]
I think the rationale is sound.

This could also indeed open possibility to base some operations not just on the user name but also on groups and roles. Not sure how we could use them. On the other hand, connectors might feel required to use these properties (perhaps a silly worry).

**Comment by ksobolew** [comment]
There are also other kinds of identity classes. How far you think we can go in unifying them?

**Comment by kokosing** [comment]
> There are also other kinds of identity classes. How far you think we can go in unifying them?

I would like to do one step a time. Each might require different discussion. Also, by default, these `other kinds of identity classes` or not guilty, so I would expect that they are there for a reason. Unless someone can prove the otherwise.

**Comment by findepi** [comment]
lgtm overall

**Review by hashhar — APPROVED** [review]
LGTM for me.

This looks like premature extensibility in hindsight.

**Pull request merged**
