### PR TITLE
Add CSV_UNQUOTED_AND_UNESCAPED & CSV_HEADER_UNQUOTED_AND_UNESCAPED output format to CLI

### LINKED ISSUE #12370: [trino-cli] CSV_UNQUOTED with "(double-quote) escaped
Even though I set output-format as `CSV_UNQUOTED`, all the double-quote(") characters like for JSON is quoted. Actually they are escaped by the default escape behavior of au.com.bytecode.opencsv.CSVWriter.
```bash
$ trino-cli --server localhost:8080 --execute "SELECT 'test', CAST('abc' AS JSON);" --output-format CSV_UNQUOTED
test,""abc""
```

So I modified the source [io/trino/cli/CsvPrinter.java#L71-L71](https://github.com/trinodb/trino/blob/bcb89ab765dc77bc499e24b4ecd8cbb7e31cfe89/client/trino-cli/src/main/java/io/trino/cli/CsvPrinter.java#L71-L71) like below;
`this.writer = csvOutputFormat.isQuoted() ? new CSVWriter(writer) : new CSVWriter(writer, CSVWriter.DEFAULT_SEPARATOR, CSVWriter.NO_QUOTE_CHARACTER, CSVWriter.NO_ESCAPE_CHARACTER);`

```bash
$ trino/client/trino-cli/target/trino-cli-381-SNAPSHOT-executable.jar --server localhost:8080 --execute "SELECT 'test', CAST('abc' AS JSON);" --output-format CSV_UNQUOTED
test,"abc"
```

How about this? I think CSV_UNQUOTED option should not escape double-quote("), too.

### PR DESCRIPTION
**Pull request by EugeneChung**
## Description

- Remove "(double-quote) escape behavior for trino-cli with `--output-format CSV_UNQUOTED`
- I proposed the change at #12370 .

> Is this change a fix, improvement, new feature, refactoring, or other?

fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

client library

> How would you describe this change to a non-technical end user or system administrator?

trino-cli will not generate additional "(double-quote) for all double-quoted data when `--output-format CSV_UNQUOTED` is specified

## Related issues, pull requests, and links

* Fixes #12370

## Documentation

( ) No documentation is needed.
(X) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
(X) Release notes entries required with the following suggested text:

```markdown
# Section
* trino-cli will not generate additional "(double-quote) for all double-quoted data when `--output-format CSV_UNQUOTED` is specified ({issue}`12370`)
```

### CODE REVIEW

**Review by nineinchnick — APPROVED** [review]

**Comment by hashhar** [comment]
IIUC CSV has two terms: quoting and escaping.

Quoting refers to adding `"` around values.
Escaping refers to escaping any inline `"` or other special chars.

So `CSV_UNQUOTED` as it exists today is correct.

Maybe you should add a new output format called `CSV_RAW` (or `CSV_UNQUOTED_AND_UNESCAPED`) with this new behaviour you are proposing which will do neither quoting nor escaping. (Better names welcome)

cc: @electrum

**Comment by EugeneChung** [comment]
I'm not sure the concept of quoting and escaping are separated. 
For me, it seems escaping is one of the options for quoting.

I think some may think they are separated and others think escaping is the part of quoting.
- separated : https://javadoc.io/doc/au.com.bytecode/opencsv/latest/index.html
- the part of quoting : https://docs.python.org/3/library/csv.html#csv.QUOTE_ALL

Anyway, I totally agree changing the behavior of the existing option can break the compatibility so adding a new format seems more desirable. 
CSV_UNQUOTED_AND_UNESCAPED would be a good option, because it's aligned with au opencsv.

**Comment by EugeneChung** [comment]
I've added two options, `CSV_UNQUOTED_AND_UNESCAPED` and `CSV_HEADER_UNQUOTED_AND_UNESCAPED`. I updated TestCsvPrinter, too.

**Review by nineinchnick — APPROVED** [review]
Can you also update docs at `docs/src/main/sphinx/installation/cli.rst`?

**Comment by EugeneChung** [comment]
> Can you also update docs at `docs/src/main/sphinx/installation/cli.rst`?

I did it!

**Review by nineinchnick — APPROVED** [review]

**Review by hashhar — APPROVED** [review]
Looks good to go to me. cc: @electrum PTAL.

**Comment by mosabua** [comment]
:wave: @EugeneChung  - this PR has become inactive. We hope you are still interested in working on it. 

@electrum can you please chime in to clarify that this is a good improvement.

Please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Pull request closed without merging**
