### PR TITLE
Remove Hive legacy security

### PR DESCRIPTION
**Pull request by electrum**
## Description

Remove Hive legacy security. The new default is `allow-all`.

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# Hive connector
* The `legacy` mode for `hive.security` has been removed, and the default is now `allow-all`.
  Use `read-only` if you want to prevent write operations, or use `file` for fine-grained control.
  The legacy properties `hive.allow-drop-table`, `hive.allow-rename-table`,
    `hive.allow-add-column`, `hive.allow-drop-column`
    `hive.allow-rename-column`, `hive.allow-comment-table`,
  and `hive.allow-comment-column` must be removed. ({issue}`21013`)
```

### CODE REVIEW

**Review by dain — APPROVED** [review]

**Review by dain — APPROVED** [review]

**Comment by mosabua** [comment]
Docs change is fine .. just really depends now what you want to merge first .. this PR or https://github.com/trinodb/trino/pull/21015 

I am fine either way

**Review by mosabua — APPROVED** [review]
Docs are good and I slightly updated the release notes suggestion

**Comment by mosabua** [comment]
Also note @colebow the release notes entry needs the `{{breaking}}`

**Comment by electrum** [comment]
This only affects Hive. The other connector changes are just cleanups, so that the code is similar in all connectors.

**Pull request merged**
