### PR TITLE
Update connector documentation to have generic catalog names

### PR DESCRIPTION
**Pull request by sheajamba**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

Improvement

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Connector documentation

> How would you describe this change to a non-technical end user or system administrator?

Changes example catalog names to not match the name of the connector.

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by mosabua** [comment]
@electrum @hashhar .. this PR is to undo https://github.com/trinodb/trino/pull/9252 .. before this got merged we were attempting to ensure that the catalog names are NOT the same the as the connector names. The linked PR reestablishes this problematic setup. It causes users to misunderstand that catalogs are separate from connectors and you can have as many catalogs accessing different database as you want .. including using all using the same connector. 

With this PR we propose to come up with a standard solution that can then be used in all connector docs. Before we proceed we would like to get to an agreement on what that name should be. It could be like in the current PR where it is the same for all connector docs .. e.g. always mycatalog, test_catalog or whatever

Or it could be different for each connector as long as it is not the same as the connector name `my_sqlserver_db` or whatever for `sqlserver` and so on...

**Comment by hashhar** [comment]
A better way to show that you can have multiple catalogs for a connector is to actually show multiple catalogs instead of trying to imply it via different name.

We can say something like `Create a abc.properties and xyz.properties with this content` and then show that `SHOW CATALOGS` returns both.

**Comment by mosabua** [comment]
> A better way to show that you can have multiple catalogs for a connector is to actually show multiple catalogs instead of trying to imply it via different name.
> 
> We can say something like `Create a abc.properties and xyz.properties with this content` and then show that `SHOW CATALOGS` returns both.

Sure .. we can do that as well in a generic document about connectors and catalogs. But nevertheless .. in the individual connector docs we should NOT use the same name for catalog and connector.. so what should we do there?

**Comment by hashhar** [comment]
People don't often follow links. If they are looking to only use MySQL connector they won't ever click through to the generic page.

I'm proposing to add an example of multiple catalogs to each connector's doc instead of a generic page (which already exists https://trino.io/docs/current/overview/concepts.html#catalog)

**Review by electrum — APPROVED** [review]

**Comment by mosabua** [comment]
Just to clarify .. @electrum @sheajamba and myself synced up and discussed this .. we are going to use example.properties in all connector docs .. Shea will update this PR or send replacement and link it here

**Comment by mosabua** [comment]
@sheajamba did you want to close this and send separate replacement PRs as discussed?

**Pull request closed without merging**
