### PR TITLE
[WIP] Update to TestNG 6.14.3

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by kokosing** [comment]
FYI: https://github.com/prestosql/presto/pull/1642

**Comment by mosabua** [comment]
This PR is invalid since TestNG is no longer used at all. Closing PR.

**Comment by hashhar** [comment]
> This PR is invalid since TestNG is no longer used at all. Closing PR.

This is untrue. But agreed that it's stale.

**Comment by mosabua** [comment]
> > This PR is invalid since TestNG is no longer used at all. Closing PR.
> 
> This is untrue. But agreed that it's stale.

We just did not find the testng dependency version declaration in the top level POM at all anymore. Is that moved to airlift or somehow managed differently?

**Comment by hashhar** [comment]
See various module level poms - version gets inherited from airlift's `dependencyManagement` section.

**Pull request closed without merging**
