### PR TITLE
Add clean to mvn calls that can be retried

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

If `mvn` crashes for any reason, it might leave behind invalid artifacts, and it'll keep failing in all subsequent runs. All these commands run on an already clean environment, but adding `clean` in the first run should not add too much overhead. Note that retries were added to handle failures during dependencies download and this will keep working the same.

> Is this change a fix, improvement, new feature, refactoring, or other?
ci improvement

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
ci

> How would you describe this change to a non-technical end user or system administrator?
n/a

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by hashhar — APPROVED** [review]
Thank you.

FYI @findepi .

**Comment by findepi** [comment]
> If `mvn` crashes for any reason, it might leave behind invalid artifacts, and it'll keep failing in all subsequent runs.

can you please stitch this into commit message?

**Comment by findepi** [comment]
@nineinchnick btw is this addressing a problem that may occur, or a problem that has already manifested itself?

**Comment by nineinchnick** [comment]
@findepi amended the commit message. I've seen this happening but I can't link to a GHA run. Maven failed with:
```
Warning: ][warning][gc,alloc] pool-717-thread-2: Retried waiting for GCLocker too often allocating 625002 words
Terminating due to java.lang.OutOfMemoryError: Java heap space
```
and then retries were failing with:
```
 Error:  Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade (default) on project trino-product-tests-launcher: Error creating shaded jar: error in opening zip file /home/runner/work/trino-lts/trino-lts/testing/trino-product-tests-launcher/target/trino-product-tests-launcher-370-SNAPSHOT.jar -> [Help 1]
```

**Pull request merged**
