### PR TITLE
Add Druid pushdown docs

### PR DESCRIPTION
**Pull request by mosabua**
Can you provide the list of supported functions @Parth-Brahmbhatt ? I literally just guessed and added a start

### CODE REVIEW

**Comment by lkm** [comment]
I'm not sure the Druid connector supports any at the moment, see https://github.com/trinodb/trino/pull/4313. I will be spending a bit of time on that PR this week to see whether I can get it through.

**Comment by Parth-Brahmbhatt** [comment]
@lkm I will update my PR by EOD tomorrow, sorry for the delay.

**Comment by mosabua** [comment]
We discussed in the Trino Community Broadcast and want to ensure that docs are going live at same time as features. I will work with @Parth-Brahmbhatt to have the correct info for aggregate and other pushdowns..

**Comment by mosabua** [comment]
I am closing this PR ... in case any pushdown gets implemented or is known .. please just ping me and I will create a new PR.

**Pull request closed without merging**
