### PR TITLE
Remove unused ctor parameter in PlanOptimizers

### PR DESCRIPTION
**Pull request by brandboat**
This is a cleanup after 9777b4676720954cece4532d9996826bf3f5c608.

### CODE REVIEW

**Review by sopel39 — APPROVED** [review]

**Comment by martint** [comment]
This is a duplicate of https://github.com/trinodb/trino/pull/7842, but let me close that other one since this one includes something that was missing there.

**Comment by brandboat** [comment]
> This is a duplicate of #7842, but let me close that other one since this one includes something that was missing there.

Sorry... I didn't notice there is another duplicate PR.

**Comment by sopel39** [comment]
merged, thanks!

**Comment by martint** [comment]
> Sorry... I didn't notice there is another duplicate PR.

No worries! Thanks for working on it!

**Pull request merged**
