### PR TITLE
Add 'location' and 'external' table properties for CREATE TABLE and CREATE TABLE AS SELECT

### LINKED ISSUE #1277: Allow setting location property for managed tables too
Currently, CREATE TABLE creates an external table if we provide external_location property in the query and creates managed table otherwise.
But Hive allows creating managed tables with location provided in the DDL so we should allow this via Presto too.

This will also change SHOW CREATE TABLE behaviour to now show location even for managed tables.

We can do this:
1. Have a boolean property "external" to signify external tables
2. Rename "external_location" property to just "location" and allow it to be used in both case of external=true and external=false

c.c. @electrum I see your commits around this. Let me know if you have other ideas around this.

### PR DESCRIPTION
**Pull request by shubhamtagra**
fixes #1277 

1. New table properties 'location' and 'external' are added to hive connector
2. CREATE TABLE and CREATE TABLE AS SELECT consumes these properties to set location for table (both managed and external) and set table type as managed or external
3. 'external_location' property is deprecated but supported for backward compatibility
4. SHOW CREATE TABLE shows both of these properties

### CODE REVIEW

**Comment by stagraqubole** [comment]
There are test failures in CREATE TABLE LIKE because we are inheriting location property of the original table as well. I am working on limiting what properties of a table can be inherited in new table by adding new getTableMetadata spi

**Comment by stagraqubole** [comment]
Tests passed, this is ready for review @electrum.

Apart from the description, this has these additional changes (conforming to Hive behaviour) in Create Table Like:
* Does not copy external flag
* Does not copy location

There are changes corresponding to this in FileHiveMetastore too.

**Comment by willmo83** [comment]
@stagraqubole can you add a configuration to disable the capability to set the location property explicitly? In some environments it might not be permissible for users to write data anywhere that the Presto process has access to. This is along the same lines as https://github.com/prestosql/presto/commit/0da1b56aff516ba4ce16578951ec0c574e44f013

**Comment by ebyhr** [comment]
@stagraqubole Could you resolve conflicts?

**Comment by stagraqubole** [comment]
> @stagraqubole Could you resolve conflicts?

Yes, will be adding the config @willmo83 suggested

**Comment by stagraqubole** [comment]
@willmo83 A config to disable/enable locations in table creation paths would be enough to disallow creation of external tables all together hence we can deprecate "hive.non-managed-table-creates-enabled" (but still support for sometime) with that change. What do you think?

**Comment by willmo83** [comment]
@stagraqubole that sounds like the correct approach, since the intent is the same in both cases.

**Comment by tooptoop4** [comment]
would this fix https://github.com/prestosql/presto/issues/1089 ?

**Comment by stagraqubole** [comment]
@tooptoop4 yes it will.

**Comment by tooptoop4** [comment]
gentle ping @stagraqubole

**Comment by tooptoop4** [comment]
this PR is talking about specifying arbitrary location for managed tables

**Comment by colebow** [comment]
:wave: @shubhamtagra - this PR is inactive and doesn't seem to be under development. If you'd like to continue work on this at any point in the future, feel free to re-open.

**Pull request closed without merging**
