### PR TITLE
Run iceberg tests on CDH5 and HDP3

### PR DESCRIPTION
**Pull request by wendigo**
Fixes https://github.com/trinodb/trino/issues/7898

### CODE REVIEW

**Review by hashhar — APPROVED** [review]
LGTM % green CI builds.

**Comment by hashhar** [comment]
@wendigo please re-run ci. Tag was missing.

**Comment by wendigo** [comment]
@hashhar: change affects PTs which were executed.

**Comment by wendigo** [comment]
Ptal @hashhar

**Review by hashhar — COMMENTED** [review]
@wendigo Looks like Iceberg PTs are defined in Suite7NonGeneric which doesn't run with CDH5 or HDP3? Or am I misreading things?

My initial review was incorrect it seems.

**Review by hashhar — APPROVED** [review]

**Comment by wendigo** [comment]
You are right but this is spark-based environment. Hadoop+Iceberg tests are executed in suite-2, suite-3 and suite-5 for CDH5 and HDP3 as I've checked.

**Pull request merged**
