### PR TITLE
Add @ConfigSecuritySensitive to configuration classes

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Review by mosabua — COMMENTED** [review]
Looks good but I feel like there should be a lot more cases where we need to use this. Are you doing this all at once or batching it up over multiple PRs.

**Comment by wendigo** [comment]
@mosabua I've found these cases where @ConfigSecuritySensitive was missing. Maybe there are others that I didn't catch.

**Comment by mosabua** [comment]
> @mosabua I've found these cases where @ConfigSecuritySensitive was missing. Maybe there are others that I didn't catch.

Ok .. so these are just the additional ones that seems to have been missing. Works for me.

**Comment by wendigo** [comment]
@mosabua yes, exactly

**Review by kokosing — APPROVED** [review]

**Review by mosabua — APPROVED** [review]
Ship it

**Review by findepi — APPROVED** [review]
thank you

**Review by dain — APPROVED** [review]

**Review by electrum — APPROVED** [review]

**Pull request merged**
