### PR TITLE
Remove support for Databricks 9.1 LTS

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

9.1 LTS will reach EOL on January 24, 2025. 
We will be able to change the default compression to ZSTD in follow-up. https://github.com/trinodb/trino/pull/17426

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Comment by ebyhr** [comment]
CI hit #24559

**Review by raunaqmorarka — APPROVED** [review]

**Comment by kokosing** [comment]
I see that master is failing with:

```
Error:  io.trino.tests.product.launcher.suite.TestAllGroupsUsed.testAllTestGroupsUsedInSuites -- Time elapsed: 0.910 s <<< FAILURE!
java.lang.AssertionError: 
[All groups defined by TestGroups should be used in test suites] 
Expecting empty but was: ["delta-lake-databricks-104"]
```
is this related with this PR?

**Comment by ebyhr** [comment]
https://github.com/trinodb/trino/pull/24564

**Comment by mosabua** [comment]
Are you sure this does not need a doc update or a release notes entry @ebyhr ?

**Comment by ebyhr** [comment]
@mosabua Yes. From the user's perspective, this should have no effect.

**Comment by mosabua** [comment]
ok

**Pull request merged**
