### PR TITLE
Allow pushJoinIntoTableScan apply on merge target

### PR DESCRIPTION
**Pull request by chenjian2664**
## Description

Fix https://github.com/trinodb/trino/issues/17003

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

**Comment by Praveen2112** [comment]
Can we add some test overages to it  ?

**Comment by chenjian2664** [comment]
Thanks @Praveen2112, I am adding 👍

**Comment by chenjian2664** [comment]
@Praveen2112 Could you suggest where and how could to test for this part?
There is a test class `TestPushJoinIntoTableScan` but feel like not suitable to add test here, actually we need test is sth like "Test merge plan's right join, left scan table is a target". Any thoughts?

**Comment by mosabua** [comment]
:wave: @chenjian2664 @Praveen2112  - this PR has become inactive. If you're still interested in working on it, please let us know.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Pull request closed without merging**
