### PR TITLE
Changes to add display timezone based on user timezone

### PR DESCRIPTION
**Pull request by amerissa**
A Trino query against an iceberg table timestamp column renders the query result differently from how Spark renders the query result for the same iceberg table:

Spark-SQL:
```
set time zone local;

CREATE TABLE spark_catalog.ts_iceberg.example_timestamp_ltz (ltz TIMESTAMP) USING iceberg 
LOCATION '<a_path>/ts_iceberg.db/example_timestamp_ltz' 
TBLPROPERTIES ('current-snapshot-id' = 'none', 
                                 'format' = 'iceberg/parquet', 
                                 'format-version' = '2')

insert into ts_iceberg.example_timestamp_ltz values(timestamp '2024-03-25 12:12:12.123456 America/Toronto');


select * from ts_iceberg.example_timestamp_ltz;
2024-03-25 16:12:12.123456  <- UTC normalized and timestamp is rendered using local time zone (UTC)

set time zone 'America/Toronto';
select * from ts_iceberg.example_timestamp_ltz;
2024-03-25 12:12:12.123456  <- timestamp rendered using time zone ‘America/Toronto’
```

Trino SQL (against the same Spark generated iceberg table above):

```
set time zone local;
select * from iceberg.ts_iceberg.example_timestamp_ltz;
2024-03-25 16:12:12.123456 UTC  <- timestamp rendered with ‘UTC’ suffix which is different than Spark

set time zone 'America/Toronto';
select * from iceberg.ts_iceberg.example_timestamp_ltz;
2024-03-25 16:12:12.123456 UTC  <- set time zone‘America/Toronto’ ignored – UTC localized with UTC suffix
```

Postgres rendering behavior for a table with a timestamptz column is like Spark:

```
create table public.test_iceberg (test_column timestamptz NULL);

ez_utility_uat=> show timezone;
TimeZone
----------
 UTC
(1 row)

ez_utility_uat=> insert into public.test_iceberg_ts_wtz values(timestamptz '2024-03-25 12:12:12.123456 America/Toronto');
INSERT 0 1

ez_utility_uat=> select * from public.test_iceberg_ts_wtz;
          test_column
-------------------------------
 2024-03-25 16:12:12.123456+00  <- UTC normalized and timestamp is rendered using local time zone (UTC)
(1 row)

ez_utility_uat=> set time zone 'America/Toronto';
SET

ez_utility_uat=> select * from public.test_iceberg_ts_wtz;
          test_column
-------------------------------
 2024-03-25 12:12:12.123456-04  <- timestamp rendered using session time zone ‘America/Toronto’
(1 row) 
```

The only option available in Trino for rendering the timestamp column at the desired timezone is to employ the Trino at_timezone function. This is undesirable as it requires a code change to existing queries. Adding the ability for Trino to transparently render the Timestamp based on a set/configured Timezone similar to how Spark and Postgres behaves is preferred because it is less intrusive.

This PR introduces configurable Trino query behavior for rendering Iceberg table timestamp columns in the same manner that Spark and Postgres render timestamp with time zone data type columns. It simplifies and encourages the adoption of Iceberg format tables that have columns of type timestamp with time zone.

The enhancement ensures that an Iceberg table timestamp column value:

Is normalized to UTC time
Is rendered at query time according to a default or specified session Time Zone

### CODE REVIEW

**Comment by findepi** [comment]
Should this be a client-side thing, @martint ?

**Comment by sbrackenbury-teranet** [comment]
This PR originates from this Issue:
https://github.com/trinodb/trino/issues/21871

**Comment by martint** [comment]
> Should this be a client-side thing, @martint ?

Yes, see my comment in the issue. IMO, it should either be a CLI rendering option or an addition to the protocol to allow clients to specify that they want all timestamp with time zone converted to the client's time zone before they are transported to the client. I'm not a big fan of the latter, as it introduces an entire new layer of processing and complexity. 

The downside is that either of these options requires updates to clients and client applications. Controlling the latter it via a session property instead of a protocol option also has the downside that it only works for clients that support multi-statement interactions with the server.

**Comment by wendigo** [comment]
@martint WITH SESSION that allows for tz switch would address the last concern, correct?

**Comment by martint** [comment]
> WITH SESSION that allows for tz switch would address the last concern, correct?

Yes, but that's the smallest of the issues. It still requires introducing a processing layer to translate all values to such timezone before returning the results to the client.

**Comment by mosabua** [comment]
Given the discussion in this PR and the inactivity I think we can close this. Feel free to reopen this PR or start a new one if you will work on a more complex and suitable approach @amerissa

**Pull request closed without merging**
