### PR TITLE
Mark TestMemoryConnectorTest.testCustomMetricsScanOnly as flaky

### PR DESCRIPTION
**Pull request by raunaqmorarka**
Fixes https://github.com/trinodb/trino/issues/8691

### CODE REVIEW

**Comment by findepi** [comment]
CI https://github.com/trinodb/trino/issues/1671

**Comment by findepi** [comment]
lgtm

**Comment by findepi** [comment]
@raunaqmorarka can you please add an empty commit?

**Comment by sopel39** [comment]
@raunaqmorarka please squash commits

**Comment by sopel39** [comment]
@raunaqmorarka please squash commits

**Review by sopel39 — APPROVED** [review]

**Review by sopel39 — APPROVED** [review]

**Comment by findepi** [comment]
> please squash commits

@sopel39 empty commits disappear on rebase & merge

> Fixes #8691

we still don't know the underlying problem
we just added band aid on it, but we don't know whether it's test's problem or product's fault

please reopen or create a dedicated issue to track the supposed bug.

**Comment by sopel39** [comment]
I'm pretty sure https://github.com/trinodb/trino/issues/5172 is the cause

**Pull request merged**
