### PR TITLE
Opentelemetry tracing introduction with auto instrumentation using opentelemetry-javaagent

### PR DESCRIPTION
**Pull request by przemekak**

### CODE REVIEW

**Comment by mattstep** [comment]
I'm curious why you've chosen OpenTelemetry? The way that various providers integrate with it is to override or extend https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java by using an agent. On the other hand, OpenCensus does way more to respect classloader hierarchy and implements in the OSS project itself all the integrations with other tracing collection providers. Have you done a comparison between OpenTracing, OpenTelemetry, and OpenCensus?

**Comment by martint** [comment]
Anything that does automatic bytecode instrumentation is dangerous and brittle. It's hard to reason about potential performance effects, stack traces no longer correspond to actual code, it makes it harder to upgrade to new versions of the JVM, etc. Also, it's not clear where that instrumentation gets exposed (files, unix domain sockets, network connections, etc). That also needs to be explicit and in line with how everything in airlift works.

We've been discussing on and off supporting something like this, but it needs a more comprehensive approach that allows us to gather events throughout the whole query lifecycle (client protocol interactions, query state transitions, interactions with connectors and external services for metadata APIs, split creation, tasks, driver execution, interactions with external data source and sinks, etc).

See https://github.com/trinodb/trino/pull/2010 for previous discussions of goals for this kind of tracing.

**Comment by przemekak** [comment]
> I'm curious why you've chosen OpenTelemetry? The way that various providers integrate with it is to override or extend https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java by using an agent. On the other hand, OpenCensus does way more to respect classloader hierarchy and implements in the OSS project itself all the integrations with other tracing collection providers. Have you done a comparison between OpenTracing, OpenTelemetry, and OpenCensus?

I went with OpenTelemetry as it seems the most popular open source solution out there. And as OpenTracing and OpenCensus got merged into OpenTelemetry it seems to me to better use newer solution then something that isn't actively developed anymore.

> Anything that does automatic bytecode instrumentation is dangerous and brittle. It's hard to reason about potential performance effects, stack traces no longer correspond to actual code, it makes it harder to upgrade to new versions of the JVM, etc. Also, it's not clear where that instrumentation gets exposed (files, unix domain sockets, network connections, etc). That also needs to be explicit and in line with how everything in airlift works.
> 
> We've been discussing on and off supporting something like this, but it needs a more comprehensive approach that allows us to gather events throughout the whole query lifecycle (client protocol interactions, query state transitions, interactions with connectors and external services for metadata APIs, split creation, tasks, driver execution, interactions with external data source and sinks, etc).
> 
> See #2010 for previous discussions of goals for this kind of tracing.

I actually saw this discussion in mentioned PR, it just looked to me like reinventing the wheel when there is popular and ready to use open source solution for tracing. And there already exist open source solution for monitoring such tracing like [Jaeger](https://www.jaegertracing.io/) or [zipkin](https://zipkin.io/) which make it easy for user to collect, present, analyse such tracing events.

Also OpenTelemetry can be used in manual way to create traces with much more details, parameters etc. to look exactly like in mentioned PR, but this is not such case.  This PR just enables user to start creating traces for (quite large) number of popular [libraries](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#libraries--frameworks).

To use that user would need to specifically state so in his JVM config when starting the server, without such action there should be no difference. Example config that I used:
```
   -javaagent:/usr/lib/trino/lib/opentelemetry-javaagent-1.7.2.jar
   -Dotel.propagators=tracecontext,baggage,jaeger
   -Dotel.resource.attributes=service.name=trino
   -Dotel.traces.exporter=jaeger
   -Dotel.metrics.exporter=none
   -Dotel.exporter.jaeger.endpoint=http://jaeger-collector:14250
   -Dotel.instrumentation.methods.include=
      io.trino.execution.SqlTaskExecutionFactory[create];
      io.trino.execution.SqlTaskExecution.DriverSplitRunner[processFor];
      io.trino.execution.executor.TaskExecutor[addTask,removeTask,enqueueSplits];
      io.trino.operator.TableScanOperator[addSplit];
      io.trino.execution.SqlTask[updateTask];
```
So to enable tracing user need to set javaagent with this jar and specify what to do with traces, here I send them to some collector. User is also able to specify list of classes with methods for which he want to crate traces. Agent is highly customisable, here is a list of main [features](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/agent-features.md) .

I run my server on kubernetes and because of ready to use solutions it was super easy to start using tracing.
I could just deploy jeager agents/collectors/ui with `helm install jaeger`, deploy Trino with mentioned JVM config and observe all created traces in Jaeger UI, also send it to OpenSearch instance where I could analyse them in more details.

**Comment by mosabua** [comment]
:wave: @przemekak - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get discuss further with @martint @mattstep and others to see if this is a feasible approach to get towards merge.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by colebow** [comment]
Closing this one out due to inactivity, but please reopen if you would like to pick this back up.

**Pull request closed without merging**
