### PR TITLE
Include enabled roles in QueryContext for event listeners

### PR DESCRIPTION
**Pull request by ksobolew**
## Description

It's odd that it included the principal and groups, but not enabled roles.

## Additional context and related issues

This information is definitely useful for some event listeners.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
cc @djsstarburst @losipiuk @kokosing @erichwang

**Review by djsstarburst — APPROVED** [review]
It is good to have visibility into the enabled roles if available, so I approved.

HOWEVER, I have made a (so far unsuccessful) effort to optimize out calling `listEnabledRoles` for every query.

If you have any suggestions to debug problems like this optimization I'd like to hear them.  The PR feels a bit foolish to me - - but I couldn't think of another way to gain insight.

**Comment by ksobolew** [comment]
Huh. And here I thought that it's just list a list of names :) I should have known better, I did look at that HTTP context factory before...

**Review by wendigo — APPROVED** [review]

**Comment by ksobolew** [comment]
Green and ready to be merged

**Review by kokosing — APPROVED** [review]

**Pull request merged**
