### PR TITLE
Improve title for alter table limitation fragment

### PR DESCRIPTION
**Pull request by tlblessing**
## Description

Improve header to be more specific to its content.

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by mosabua** [comment]
We do not want to have separate section for each version of ALTER TABLE .. and we probably need to add more limitations or maybe even have some in place already. The current header is still correct as it stands.

**Comment by tlblessing** [comment]
> We do not want to have separate section for each version of ALTER TABLE .. and we probably need to add more limitations or maybe even have some in place already. The current header is still correct as it stands.

@mosabua this is just applicable to a few fragments (includes) in the repo. Not all permutations of ALTER TABLE. This edit makes it immediately clear as to the command flavor. Easier for readers to consume and quickly skim and comprehend the content. And this makes it consistent with the ALTER TABLE EXECUTE sections. cc: @jhlodin

**Comment by mosabua** [comment]
Okay .. that sounds good @tlblessing .. can you please just verify that none of the usage of the fragment are followed by some other ALTER TABLE content that would make the header wrong. Once we know that for sure I can merge.

**Review by mosabua — APPROVED** [review]
Looks good now. Thank you for confirming.

**Pull request merged**
