### PR TITLE
Update docker-images to v67

### PR DESCRIPTION
**Pull request by wendigo**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

> How would you describe this change to a non-technical end user or system administrator?

## Documentation

(x) No documentation is needed.

## Release notes

(x) No release notes entries required.

### CODE REVIEW

**Comment by hashhar** [comment]
@ebyhr Indeed looks like the Spark image update needs changes to be handled.

**Comment by ebyhr** [comment]
I'm looking the failure now. We may need a new docker image.

**Comment by ebyhr** [comment]
Delta Lake product test keeps failing
```
spark               | Exception in thread "main" java.lang.IllegalAccessError: class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x4e800f52) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x4e800f52
spark               | 	at org.apache.spark.storage.StorageUtils$.<init>(StorageUtils.scala:213)
spark               | 	at org.apache.spark.storage.StorageUtils$.<clinit>(StorageUtils.scala)
spark               | 	at org.apache.spark.storage.BlockManagerMasterEndpoint.<init>(BlockManagerMasterEndpoint.scala:110)
spark               | 	at org.apache.spark.SparkEnv$.$anonfun$create$9(SparkEnv.scala:348)
spark               | 	at org.apache.spark.SparkEnv$.registerOrLookupEndpoint$1(SparkEnv.scala:287)
spark               | 	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:336)
spark               | 	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:191)
spark               | 	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:277)
spark               | 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:460)
spark               | 	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2690)
spark               | 	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:949)
spark               | 	at scala.Option.getOrElse(Option.scala:189)
spark               | 	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:943)
spark               | 	at org.apache.spark.sql.hive.thriftserver.SparkSQLEnv$.init(SparkSQLEnv.scala:54)
spark               | 	at org.apache.spark.sql.hive.thriftserver.HiveThriftServer2$.main(HiveThriftServer2.scala:96)
spark               | 	at org.apache.spark.sql.hive.thriftserver.HiveThriftServer2.main(HiveThriftServer2.scala)
spark               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
spark               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
spark               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
spark               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
spark               | 	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
spark               | 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
spark               | 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
spark               | 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
spark               | 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
spark               | 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
spark               | 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
spark               | 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by ebyhr** [comment]
Regarding Delta Lake, I think Java 17 doesn't work in the current Spark version 3.2.1. Spark 3.3 supports 17, but the Delta Lake release is still in progress. https://github.com/delta-io/delta/releases/tag/v2.1.0rc1

**Comment by findepi** [comment]
@ebyhr why would we want want to run Spark on Java 17? What's the point?

**Comment by ebyhr** [comment]
@findepi It depends on the motivation of https://github.com/trinodb/docker-images/pull/140 (I don't know why). I think it would be better to rollback Delta Lake image's Java to 11 for now. 

cc: @wendigo

**Comment by wendigo** [comment]
I was planning to do exactly that. For both Spark and Phoenix images @ebyhr

**Comment by wendigo** [comment]
@findepi then we should revert https://github.com/trinodb/docker-images/commit/d67aab39bd61677d3d3442c85e78d6000488aa88 or explicitly switch delta/phoenix to use base centos7 image with jdk 11 installed

**Pull request closed without merging**
