### PR TITLE
Add sql server lock timeout for sqlserver tests

### PR DESCRIPTION
**Pull request by grantatspothero**
As discussed here: https://github.com/trinodb/trino/pull/10034#discussion_r755723599

Breaking this config change out into a separate PR and stress testing it

### CODE REVIEW

**Comment by grantatspothero** [comment]
I'll revert the ci commit after an approval

**Review by hashhar — COMMENTED** [review]
Should we have expected the known-flaky test to fail? Maybe we need to set an even stricter value, like 5 seconds.

The goal of this PR is just to find all "theoritical" places where we can get deadlocked under "normal" workloads. It doesn't need to use the "relaxed" 2min lock timeout.

(If we find none even with values like 5 seconds it seems like it's good enough for now, we can wait until someone reports a deadlock.)

**Comment by grantatspothero** [comment]
> Should we have expected the known-flaky test to fail? Maybe we need to set an even stricter value, like 5 seconds.
> 

No because the flaky test from the other PR deadlocks (eg: 2 transactions are each holding locks that the other transaction needs). The deadlock detector will kill one of the transactions allowing the other to complete.

This `lockTimeout` config is useful for cases where one transaction is blocked for a long time because another transaction is holding the lock it needs. The default behavior is to block forever, this config changes that behavior to instead let the transaction fail after a given period of time waiting for the lock instead of blocking forever.

**Comment by grantatspothero** [comment]
The config was useful for tests because when attempting to create deadlocks I accidentally created a transaction that was blocked (and instead of failing after a period of time it blocked forever). Just should give faster feedback on broken tests.  

I can reduce the lockTimeout to see if tests flake 👍

**Comment by grantatspothero** [comment]
One final look @hashhar , rebased/squashed commits.

**Review by hashhar — APPROVED** [review]

**Review by ebyhr — APPROVED** [review]

**Comment by ebyhr** [comment]
Merged, thanks!

**Pull request merged**
