### PR TITLE
Separate BigQuery arrow test

### PR DESCRIPTION
**Pull request by vlad-lyutenko**
## Description
Sometimes timeout occurs during BugQuery tests (https://github.com/trinodb/trino/actions/runs/3844470384/jobs/6547614598), we need to separate run for arrow tests

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

**Comment by ebyhr** [comment]
When's the last failure? The provided link is 2 weeks ago. https://github.com/trinodb/trino/actions/runs/3844470384/jobs/6547614598

**Comment by ebyhr** [comment]
/test-with-secrets sha=cc84f18b21dd06ee0a99d6ed973bf8f9f7cad0c3

**Review by ebyhr — APPROVED** [review]

**Comment by ebyhr** [comment]
CI hit #15773

**Comment by ebyhr** [comment]
/test-with-secrets sha=cc84f18b21dd06ee0a99d6ed973bf8f9f7cad0c3

**Comment by ebyhr** [comment]
`TestBigQueryCaseInsensitiveMapping` ran on both jobs. 
* `test (plugin/trino-bigquery)` https://github.com/trinodb/trino/actions/runs/3955416679/jobs/6774070849
* `test (plugin/trino-bigquery, cloud-tests-arrow)` https://github.com/trinodb/trino/actions/runs/3955416679/jobs/6774070933

**Comment by vlad-lyutenko** [comment]
> Do you know the last day of the timeout? Is this change still required? The provided link is 2 weeks ago.

To be honest don't know. But I think it's still worth to fix it, not to run 2 BaseConnectorTests in row. Or it could be some downside from such configuration? wdyt

**Comment by losipiuk** [comment]
It looks like `/test-with-secrets` does not allow testing changes in `ci.yml` (that is what I observed elswhere, cc: @mwd410). @nineinchnick is that true?

**Comment by losipiuk** [comment]
I crated mirror from `trinodb/trino`: https://github.com/trinodb/trino/pull/15790. It should run with updateded ci.yml

**Comment by nineinchnick** [comment]
Yes, the run it schedules runs the workflow from the master and only checks out the requested commit to build and test it.

**Comment by losipiuk** [comment]
mirror PR passed fine

**Review by losipiuk — APPROVED** [review]

**Comment by ebyhr** [comment]
> Or it could be some downside from such configuration?

@vlad-lyutenko One of the downside is it may hide the unexpected slow performance in the connector.

**Pull request merged**
