### PR TITLE
Upgrade to localstack 3.3.0

### PR DESCRIPTION
**Pull request by sullis**
## Description

upgrade to latest localstack (3.3.0)

## Additional context and related issues

https://hub.docker.com/r/localstack/localstack/tags

image

## Release notes

(x ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by sullis** [comment]
I signed the CLA and submitted it via email

**Review by wendigo — APPROVED** [review]

**Comment by wendigo** [comment]
@martint can you process outstanding CLAs 
?

**Comment by sullis** [comment]
Still waiting for my signed CLA to get processed.

**Comment by wendigo** [comment]
@cla-bot recheck

**Comment by wendigo** [comment]
@cla-bot[bot] recheck

**Comment by wendigo** [comment]
@cla-bot check

**Review by wendigo — APPROVED** [review]

**Pull request merged**
