### PR TITLE
Add support for OpenTelemetry in Elasticsearch

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Add support for OpenTelemetry in Elasticsearch
Screenshot 2024-02-13 at 22 16 14

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Comment by wendigo** [comment]
@ebyhr what about opensearch?

**Comment by ebyhr** [comment]
@wendigo I couldn't find a library for OpenSearch. https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/opensearch is javaagent, not library.

**Review by wendigo — APPROVED** [review]

**Comment by wendigo** [comment]
Pom is not sorted @ebyhr

**Comment by ebyhr** [comment]
It seems the library hides the actual cause in some situation ([example](https://github.com/trinodb/trino/actions/runs/7887151731/job/21523123861?pr=20680)). I don't think we can introduce as-is. We need to fix the issue in opentelemetry side.

**Pull request closed without merging**
