### PR TITLE
Add partition column to the Iceberg's File metadata table

### PR DESCRIPTION
**Pull request by osscm**
## Description

Adding partition column to the file metadata table. 
Table has to be partitioned to access the partition column.

Underlying Iceberg DataFile/ContentFile has partition data, Spark supports and provide that information.
This information is required while debugging data issues.

ref: https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/ContentFile.java#L52

## Additional context and related issues

fixes: https://github.com/trinodb/trino/issues/17148

Sample query

```
SELECT content,partition FROM "tab$files"
```

## Release notes

( ) Release notes are required, with the following suggested text:

Partition column is added to the File metadata table. 

```markdown
# Section
* Fix some things. ({issue}`17148`)
```

### CODE REVIEW

**Comment by mosabua** [comment]
Can @findepi and @alexjo2144 please have a first look?

**Comment by ebyhr** [comment]
Could you rebase on master to resolve conflicts?

**Comment by mosabua** [comment]
Could you rebase @osscm so that @ebyhr and others can review

**Comment by osscm** [comment]
Sure, Pardon for the delay, I’m away for few days, will do this weekend.
Thanks!

**Comment by osscm** [comment]
> Could you rebase on master to resolve conflicts?

@ebyhr rebased, now you can review please.

**Comment by osscm** [comment]
> > Could you rebase on master to resolve conflicts?
> 
> @ebyhr rebased, now you can review please.

can someone please help in reviewing this PR, thanks!

cc @ebyhr or @findinpath or @mosabua

**Comment by mosabua** [comment]
Could you help out here @findepi @ebyhr ?

**Comment by ebyhr** [comment]
Superseded by #24102

**Pull request closed without merging**
