### PR TITLE
Migrate Kafka test to use BaseConnectorTest

### LINKED ISSUE #7114: Migrate Kafka tests to use BaseConnectorTest
https://github.com/trinodb/trino/pull/6989 introduced new `BaseConnectorTest` test class which replaces `AbstractTestDistributedQueries` and `AbstractTestIntegrationSmokeTest`.

Scope of this ticket is to restructure Kafka test code to follow new pattern.
`TestKafkaIntegrationSmokeTest` should be renamed to `TestKafkaConnectorTest` and extend `BaseConnectorTest` instead of `AbstractTestIntegrationSmokeTest`

A PR which restructures MySQL tests is a good reference:  https://github.com/trinodb/trino/pull/7011

### PR DESCRIPTION
**Pull request by Alicewillbe**
Fixes #7114

1. renamed TestKafkaIntegrationSmokeTest to TestKafkaConnectorTest
2. extended to BaseConnectorTest instead of AbstractTestIntegrationSmokeTest

### CODE REVIEW

**Comment by Alicewillbe** [comment]
Assigned CLA was sent from ```zhaolonglong4008@gmail.com```.  Let me double check my account 😅

**Comment by losipiuk** [comment]
> Signed CLA was sent from `zhaolonglong4008@gmail.com`
> @losipiuk Not sure who should be assigned as the reviewer.

CLA database management is a manual process for now. @martint please handle that when you have a chance :)

**Comment by hashhar** [comment]
You might need to override the various `supportsXxx` methods from superclass according to which features are supported or not in Kafka connector.

Take a look at the test failures to see which ones need adjusting. (Kafka tests can be run in IDE so you can test locally as well).

**Comment by Alicewillbe** [comment]
> You might need to override the various `supportsXxx` methods from superclass according to which features are supported or not in Kafka connector.
> 
> Take a look at the test failures to see which ones need adjusting. (Kafka tests can be run in IDE so you can test locally as well).

Hello @hashhar, thanks for advising! 

Yes, I noticed that the refactored ```TestKafkaConnectorTest``` class failed ```68/145``` tests.
But not sure from #7114 instructions, am I supposed to do more than just refactoring the class and name?
If you want me to try fixing these exceptions, I'm definitely willing to do :D

All of failed tests are inherited from the indirect superclasses ```AbstractTestDistributedQueries```.
```66/68``` are errors and ```2/68``` are assertion failure caused by errors.

Here are all the distinct exception messages:
```
java.lang.RuntimeException: This connector does not support creating tables with data
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:502)
at io.trino.testing.AbstractTestDistributedQueries.testWrittenStats(AbstractTestDistributedQueries.java:1070)
...
```
```
java.lang.RuntimeException: This connector does not support creating tables with data
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:491)
at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:225)
at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:220)
at io.trino.testing.AbstractTestDistributedQueries.testSymbolAliasing(AbstractTestDistributedQueries.java:1056)
...
```
```
java.lang.RuntimeException: This connector does not support creating tables
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:491)
at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:215)
at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:210)
at io.trino.testing.AbstractTestDistributedQueries.testColumnName(AbstractTestDistributedQueries.java:1145)
at io.trino.testing.AbstractTestDistributedQueries.testColumnName(AbstractTestDistributedQueries.java:1132)
...
```
```
java.lang.RuntimeException: This connector does not support creating schemas
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:491)
at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:215)
at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:210)
...
```
```
java.lang.RuntimeException: This connector does not support creating views
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:491)
at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:215)
at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:210)
at io.trino.testing.AbstractTestDistributedQueries.testViewMetadata(AbstractTestDistributedQueries.java:881)
...
```
```
java.lang.RuntimeException: This connector does not support creating views
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:120)
at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:491)
at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:129)
at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:124)
at io.trino.testing.AbstractTestDistributedQueries.testViewCaseSensitivity(AbstractTestDistributedQueries.java:818)
...
```

**Comment by Alicewillbe** [comment]
@hashhar @losipiuk 
After a few tries at local, I don't think the failed tests can be easily solved by overriding ```supportsXXX``` to return ```false```.
For example, if I understand it correctly, ```AbstractTestDistributedQueries::testInsert``` first checks ```supportsInsert()``` and if the connector supports insert, it should pass and continue testing.
In our case, although Kafka connector supports ```insert``` behaviors technically, it still introduces ```io.trino.spi.TrinoException: This connector does not support creating tables with data``` at the line ```CREATE TABLE ...```. So there is actually dependency between ```supportInsert``` and ```supportsCreateTable```.

Maybe we need to ```@Override```  and rewrite unit tests specifically for ```TestKafkaConnectorTest```?

**Comment by losipiuk** [comment]
> @hashhar @losipiuk
> After a few tries at local, I don't think the failed tests can be easily solved by overriding `supportsXXX` to return `false`.
> For example, if I understand it correctly, `AbstractTestDistributedQueries::testInsert` first checks `supportsInsert()`. If the connector supports insert, it should pass and continue testing.
> In our case, although the Kafka connector supports `insert` behaviors technically, it still introduces `io.trino.spi.TrinoException: This connector does not support creating tables with data` at the line `555: assertUpdate("CREATE TABLE "...`
> So there is actually dependency between `AbstractTestDistributedQueries::testInsert` and `supportsCreateTable()`.
> 
> Maybe we need to `@Override` and rewrite unit tests from `AbstractTestDistributedQueries` specifically for `TestKafkaConnectorTest`?

I think our supported-feature flags set is not expressive enough.  

We just have `supports-insert` and `supports-create` and we are missing explicit `supports-create-as-select`.  We should add that and modify the `AbstractTestDistributedQueries` accordingly, so correct flag is tested depending on what test requires.
@findepi do you agree that is proper approach?
@Alicewillbe would you be fine implementing that (lets wait for @findepi ACK).

**Comment by findepi** [comment]
> We just have `supports-insert` and `supports-create` and we are missing explicit `supports-create-as-select`. We should add that and modify the `AbstractTestDistributedQueries` accordingly, so correct flag is tested depending on what test requires.

That's OK interim, but note that we generally move towards `TestingConnectorBehavior`.
Same purpose, just a bit more terse representation of the information.

**Comment by kokosing** [comment]
>  modify the AbstractTestDistributedQueries

I think at some point we should remove AbstractTestDistributedQueries and put all its tests to either engine tests or BaseConnectorTests (where we could use `TestingConnectorBehavior`.

Kafka connector is a bit complicated. In near future with Schema Registry one will be able to create a table and insert, while with file descriptors is not doable. Today, one can insert with file descriptors while insert is not supported (nor create) is supported for kafka with schema registry. So we need two `BaseConnectorTest` classes here. One for Kafka with file descriptors  and one for schema registry.

**Comment by Alicewillbe** [comment]
@losipiuk Sorry for the late reply. I don't think I know kafka enough to do the kafka specific test migration right now, based on what @findepi and @kokosing said. Feel free to close this PR and un-assign me from the issue #7114. I will keep watching and see if I'm able to fix it in near future. (I'm learning kafka on Udemy right now...)

**Comment by losipiuk** [comment]
> @losipiuk Sorry for the late reply. I don't think I know kafka enough to do the kafka specific test migration right now, based on what @findepi and @kokosing said. Feel free to close this PR and un-assign me from the issue #7114. I will keep watching and see if I'm able to fix it in near future. (I'm learning kafka on Udemy right now...)

Thanks @Alicewillbe for giving it a shot. It is my bad that I tagged it as good-first-issue while actually work is more complex here.

**Pull request closed without merging**
