### PR TITLE
Mdeady bigquery fte 3877

### PR DESCRIPTION
**Pull request by losipiuk**
## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by hashhar** [comment]
You can try `/test-with-secrets sha=<commit sha of HEAD of PR branch>`.

**Comment by losipiuk** [comment]
> You can try `/test-with-secrets sha=<commit sha of HEAD of PR branch>`.

Yeah the intention of this branch was exactly for that :)
Can this be done only on PRs created by maintainers. Or on any PRs?

**Comment by findepi** [comment]
> Can this be done only on PRs created by maintainers. Or on any PRs?

Any PRs

A maintainer can create a PR _within repo_, and then manual `/test-with-secrets` is not needed after every push.

**Pull request closed without merging**
