### PR TITLE
Remove Event listeners from main docs navigation

### PR DESCRIPTION
**Pull request by ryandoowan**
## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Review by mosabua — APPROVED** [review]
This removes the top level left hand navigation item for event listeners and just nests it in admin .. like we already do for security and others.

**Comment by mosabua** [comment]
Any concerns with merging this @electrum or @arhimondr ?

**Comment by mosabua** [comment]
Please update commit message to 

"Remove Event listeners" from main navigation

**Review by electrum — APPROVED** [review]

**Comment by mosabua** [comment]
Thanks @ryandoowan and @electrum

**Pull request merged**
