### PR TITLE
Add logos to Trino connector pages

### PR DESCRIPTION
**Pull request by Jessie212**
> Is this change a fix, improvement, new feature, refactoring, or other?

Improvement

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Documentation

> How would you describe this change to a non-technical end user or system administrator?

Add logos to Trino connector pages

## Documentation

( ) No documentation is needed.
(x) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

### CODE REVIEW

**Review by mosabua — APPROVED** [review]
Looks good and brings it all in line with Delta Lake ;-)

**Comment by Jessie212** [comment]
> Looks good and brings it all in line with Delta Lake ;-)

I agree.

**Comment by wendigo** [comment]
@Jessie212 please squash those two commits into a single one.

**Comment by mosabua** [comment]
Could you please merge @wendigo ?

**Comment by mosabua** [comment]
@hashhar @ebyhr  .. merge please?

**Comment by ebyhr** [comment]
@mosabua Let's wait confirmation from @martint

**Comment by mosabua** [comment]
@martint can you please confirm and merge.

**Pull request merged**
