### PR TITLE
Remove BaseCostBasedPlanTests and RecordingHiveMetastore

### PR DESCRIPTION
**Pull request by dain**
## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Review by martint — APPROVED** [review]
Let's file an issue to add proper tests for the join ordering optimizer and the stats interfaces for each connector.

**Comment by sopel39** [comment]
Why these need to be removed at this time before porting converge to some other mechanism? Do these block anything?

**Comment by dain** [comment]
We cleaning up usages of HDFS and metastores in tests.

**Comment by sopel39** [comment]
> We cleaning up usages of HDFS and metastores in tests.

Which cost-based planning tests collide with cleaning of HDFS usages? Please be more specific if we want to migrate test coverage to some other mechanism.

**Pull request merged**
