### PR TITLE
Add PushDownDereferencesThroughMarkDistinct rule to optimizer

### PR DESCRIPTION
**Pull request by losipiuk**
As spotted by @kasiafi  `PushDownDereferencesThroughMarkDistinct` was missing from the list of rules.
Likely an omission.

### CODE REVIEW

**Review by phd3 — APPROVED** [review]
😮 

Is there an easy-to-add test (i.e. in `TestDereferencePushDown`) if we've identified issue with a particular query? 

I'm not sure what is our general policy for e2e plan tests for optimizer rules, but that could've saved us here. Since the rule has a test, I'm fine with merging this as is.

**Review by kasiafi — APPROVED** [review]
@phd3 This was identified while inspecting code, so no ready test case. I thing it would be worthy to add one.

**Comment by mosabua** [comment]
@losipiuk @kasiafi @phd3 is this still valid. Looks like a very quick change that might already be done actually. Could you close or update and merge please?

**Comment by losipiuk** [comment]
> @losipiuk @kasiafi @phd3 is this still valid. Looks like a very quick change that might already be done actually. Could you close or update and merge please?

Oh - it was left behind :) Let me see if it is still valid

**Comment by colebow** [comment]
Does this have a tangible user impact / does it need a release note?

**Comment by losipiuk** [comment]
> Does this have a tangible user impact / does it need a release note?

It can impact performance some obscure queries for which pushdown would not happen without hte change. But it is not anything substantial, and also would be super hard to percisly describe it in RN. Let's skip it.

**Pull request merged**
