### PR TITLE
Add support for TRUNCATE statement in memory connector

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Relates to #22208

## Release notes

```markdown
# Memory
* Add support for `TRUNCATE` statement. ({issue}`22337`)
```

### CODE REVIEW

**Review by wendigo — APPROVED** [review]

**Comment by cpcloud** [comment]
This doesn't seem to work on Trino 452 from the CLI:

```
trino:default> create table t (x int);                                                                                
CREATE TABLE
trino:default> insert into t values (1), (2), (3);                                                                    
INSERT: 3 rows

Query 20240713_225914_01546_iphh3, FINISHED, 1 node
Splits: 11 total, 11 done (100.00%)
0.09 [0 rows, 0B] [0 rows/s, 0B/s]

trino:default> select count(*) from t;                                                                                
 _col0
-------
     3
(1 row)

Query 20240713_225919_01549_iphh3, FINISHED, 1 node
Splits: 13 total, 13 done (100.00%)
0.12 [3 rows, 0B] [24 rows/s, 0B/s]

trino:default> create table s as select * from t;                                                                     
CREATE TABLE: 3 rows

Query 20240713_225926_01556_iphh3, FINISHED, 1 node
Splits: 18 total, 18 done (100.00%)
0.13 [3 rows, 15B] [23 rows/s, 118B/s]

trino:default> truncate table t;                                                                                      
TRUNCATE TABLE
trino:default> select count(*) from t;
 _col0
-------
     0
(1 row)

Query 20240713_225938_01566_iphh3, FINISHED, 1 node
Splits: 6 total, 6 done (100.00%)
0.14 [0 rows, 0B] [0 rows/s, 0B/s]

trino:default> select count(*) from s;
 _col0
-------
     3
(1 row)

Query 20240713_225946_01573_iphh3, FINISHED, 1 node
Splits: 13 total, 13 done (100.00%)
0.13 [3 rows, 0B] [23 rows/s, 0B/s]

trino:default> insert into t select * from s;                                                                         
INSERT: 3 rows

Query 20240713_225952_01578_iphh3, FINISHED, 1 node
Splits: 18 total, 18 done (100.00%)
0.07 [3 rows, 15B] [41 rows/s, 208B/s]

trino:default> select count(*) from t;                                                                                
 _col0
-------
     6
(1 row)
```

**Comment by cpcloud** [comment]
This still seems to be broken.

**Comment by martint** [comment]
@cpcloud, thanks for the report. Can you file an issue so that we can track it separately?

**Comment by cpcloud** [comment]
Oops, yep! Will do early next week.

**Comment by ebyhr** [comment]
We already have the issue. #22665

**Comment by cpcloud** [comment]
> We already have the issue. #22665

Ah right, I forgot! Thanks!

**Pull request merged**
