### PR TITLE
Revert "Use a dedicated certificate for each node"

### PR DESCRIPTION
**Pull request by findepi**
Reverts trinodb/trino#7844

### CODE REVIEW

**Comment by findepi** [comment]
Thanks @hashhar for the reminder. I will know the rationale (ie whether i want that) when tests pass.

BTW This is a blind attempt to fix broken master.

**Comment by findepi** [comment]
cc @skrzypo987

**Comment by hashhar** [comment]
Broken master might also be related to https://github.com/trinodb/trino/pull/8022 fyi.

**Comment by findepi** [comment]
Doesn't come green, but i don't recognize the failure. 

```
tests               | 2021-05-28 21:37:22 INFO: FAILURE     /    io.trino.tests.product.cli.TestTrinoLdapCli.shouldFailQueryForLdapUserInChildGroup (Groups: profile_specific_tests, ldap_cli, ldap) took 1.8 seconds
tests               | 2021-05-28 21:37:22 SEVERE: Failure cause:
tests               | java.lang.AssertionError: 
tests               | Expecting any element of:
tests               |   <["Error running command: Error starting query at https://presto-master:8443/v1/statement returned an invalid response: JsonResponse{statusCode=500, statusMessage=Internal Server Error, headers={content-length=[6419], content-type=[text/plain], date=[Fri, 28 May 2021 15:52:22 GMT]}, hasValue=false} [Error: java.lang.RuntimeException: Authentication error",
tests               |     "at io.trino.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:73)",
tests               |     "at io.trino.server.security.AuthenticationFilter.filter(AuthenticationFilter.java:88)",
tests               |     "at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)",
tests               |     "at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)",
tests               |     "at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)",
tests               |     "at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)",
tests               |     "at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)",
tests               |     "at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)",
tests               |     "at org.glassfish.jersey.internal.Errors.process(Errors.java:316)",
tests               |     "at org.glassfish.jersey.internal.Errors.process(Errors.java:298)",
tests               |     "at org.glassfish.jersey.internal.Errors.process(Errors.java:268)",
tests               |     "at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)",
tests               |     "at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)",
tests               |     "at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)",
tests               |     "at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)",
tests               |     "at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)",
tests               |     "at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)",
tests               |     "at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)",
tests               |     "at io.trino.plugin.password.ldap.LdapAuthenticator.createAuthenticatedPrincipal(LdapAuthenticator.java:102)",
tests               |     "at io.trino.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:58)",
tests               |     "... 61 more",
tests               |     "Caused by: java.lang.RuntimeException: Authentication error",
tests               |     "at io.trino.plugin.password.ldap.LdapAuthenticator.authenticateWithBindDistinguishedName(LdapAuthenticator.java:157)",
tests               |     "at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168)",
tests               |     "at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)",
tests               |     "at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)",
tests               |     "at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)",
tests               |     "at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)",
tests               |     "... 67 more",
tests               |     "]"]>
tests               | to satisfy the given assertions requirements but none did:
tests               | 
tests               |   <"Error running command: Error starting query at https://presto-master:8443/v1/statement returned an invalid response: JsonResponse{statusCode=500, statusMessage=Internal Server Error, headers={content-length=[6419], content-type=[text/plain], date=[Fri, 28 May 2021 15:52:22 GMT]}, hasValue=false} [Error: java.lang.RuntimeException: Authentication error">
tests               | error: 
tests               | Expecting:
tests               |  <"Error running command: Error starting query at https://presto-master:8443/v1/statement returned an invalid response: JsonResponse{statusCode=500, statusMessage=Internal Server Error, headers={content-length=[6419], content-type=[text/plain], date=[Fri, 28 May 2021 15:52:22 GMT]}, hasValue=false} [Error: java.lang.RuntimeException: Authentication error">
tests               | to contain:
tests               |  <"User [ChildGroupUser] not a member of an authorized group"> 
```

@electrum is this something related to cert handling changes?

**Comment by hashhar** [comment]
@findepi this is the Ldap Auth change. https://github.com/trinodb/trino/pull/8022

A runtime exception is thrown instead of what's expected from the SPI.

**Comment by findepi** [comment]
I think i know too little to even identify the breaking change. I will let @trinodb/maintainers chime in.

**Pull request closed without merging**
