### PR TITLE
Extract JDBC write-related configuration to separate class

### PR DESCRIPTION
**Pull request by wendigo**
Follow-up to https://github.com/trinodb/trino/pull/8434#discussion_r712215094

### CODE REVIEW

**Review by sergey-melnychuk — APPROVED** [review]

**Comment by hashhar** [comment]
Phoenix failure is related. Phoenix has it's own module IIRC.

**Comment by kokosing** [comment]
What is the motivation?

**Comment by findepi** [comment]
> What is the motivation?

@kokosing https://github.com/trinodb/trino/pull/8434#discussion_r712215094

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
CI https://github.com/trinodb/trino/issues/5892 & sth else

**Comment by findepi** [comment]
... and https://github.com/trinodb/trino/issues/8691 cc @sopel39

**Review by hashhar — APPROVED** [review]

**Pull request merged**
