### PR TITLE
Bump redshift-jdbc42 to 2.1.0.12

### PR DESCRIPTION
**Pull request by findinpath**
## Description

Changelog

https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/CHANGELOG.md#v21011-2023-02-03

This new version of the JDBC AWS Redshift driver includes relevant bug fixes for Trino specific scenarios:

- https://github.com/aws/amazon-redshift-jdbc-driver/pull/74
- https://github.com/aws/amazon-redshift-jdbc-driver/pull/75

Thank you @ssheikin  for your contribution.

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by findinpath** [comment]
This should be merged after https://github.com/trinodb/trino/pull/15817 lands.

**Comment by mosabua** [comment]
Looks like this might be good for merge even though the linked PR for the CI update is closed.

**Review by ssheikin — APPROVED** [review]

**Comment by kokosing** [comment]
/test-with-secrets sha=1e2c88a4e9908965777020c02a7556684f3fd423

**Comment by findinpath** [comment]
CI hit #16484

**Review by ebyhr — APPROVED** [review]

**Review by hashhar — APPROVED** [review]

**Pull request merged**
