### PR TITLE
Fix syntax error in set-milestone workflow

### PR DESCRIPTION
**Pull request by hashhar**

### CODE REVIEW

**Review by nineinchnick — APPROVED** [review]

**Review by raunaqmorarka — APPROVED** [review]

**Review by ebyhr — APPROVED** [review]

**Comment by ebyhr** [comment]
Let me merge since the job keeps failing. Thanks for sending this PR.

**Comment by ebyhr** [comment]
The job is still failing on master. https://github.com/trinodb/trino/actions/runs/3500540195/jobs/5863313308
```
Error: Unhandled error: HttpError: Validation Failed: {"resource":"Milestone","code":"already_exists","field":"title"}
```

**Comment by hashhar** [comment]
I'll revert to known working state and try to test on a fork somehow.

**Comment by hashhar** [comment]
revert commit - https://github.com/trinodb/trino/pull/15118

**Pull request merged**
