### PR TITLE
Support customization of Iceberg connector name

### PR DESCRIPTION
**Pull request by jitheshtr**
## Description
IcebergConnectorFactory allows customization by accepting additional module class to be bound in its constructor. While using this facility, we would also want to customize the connector name to signify that this is not the regular "iceberg" connector. Supporting an alternate name will also allow us to have both "iceberg" and "iceberg-custom" connector plugins installed together.

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by phd3 — APPROVED** [review]

**Review by findepi — CHANGES_REQUESTED** [review]
> IcebergConnectorFactory allows customization by accepting additional module class to be bound in its constructor.

This is there primarily for test purposes, not meant as extension point to create derivative connectors.

If you want a different, not-really-an-`iceberg`-connector, please do not use `IcebergConnectorFactory` (or override getName). In either case, you're doing this at your own risk, as the project won't guarantee any source/binary compatibility for that.

**Comment by phd3** [comment]
@findepi Thanks for the feedback. My understanding was that it's generally okay to be able to add additional modules through this extension e.g. for hive connector. And then it's possible add extensions for things that are bound using optional binder e.g. `ThriftMetastoreClientFactory`. I understand we need to be cautious about it to avoid proliferation of such things. 

In this particular case, the end goal is for us is to be able to potentially use a different catalog implementation that follows the `TrinoCatalog` interface. Would there be a better way to do it than adding an additional module to bind a new catalog (assuming existing catalogs are not sufficient) - considering the major chunk of the connector is still the same?  

w.r.t. naming, I think we could have a separate factory that still makes use of InternalIcebergConnectorFactory, and have a different name. I guess we need to take the risk of it breaking with future changes - given this is not SPI.  

hive connector also allows adding a name. If that's for legacy reason, should we add a comment there saying it shouldn't be used as a precedent?

**Review by baohe-zhang — APPROVED** [review]

**Comment by findepi** [comment]
> w.r.t. naming, I think we could have a separate factory

makes sense to me

> hive connector also allows adding a name.

i think this is only to support the legacy name (`hive-hadoop2`) and the current connector name (`hive`)

**Comment by findepi** [comment]
@jitheshtr   there  was apparently a force push to the  master branch (per https://github.com/trinodb/trino/pull/15365#issuecomment-1358243396), so your PR appears as if containing some unrelated commits. You would need to rebase to remove them. However, I still think we shouldn't merge this change.

**Comment by phd3** [comment]
having a different naming isn't a hard blocker imo - we can close this.

**Comment by jitheshtr** [comment]
Closing this based on the discussion above

**Pull request closed without merging**
