### PR TITLE
Test: Handle missing StorageDescriptor in Hive Glue tables 

### PR DESCRIPTION
**Pull request by findepi**
Test https://github.com/trinodb/trino/pull/11092

### CODE REVIEW

**Comment by findepi** [comment]
cc @alexjo2144

**Comment by alexjo2144** [comment]
hdp-3 failure looks like an external failure, but it is a Glue test so it might be worth a rerun

```2022-02-18T19:56:28.8533706Z [ERROR] Tests run: 113, Failures: 1, Errors: 0, Skipped: 32, Time elapsed: 685.732 s <<< FAILURE! - in io.trino.plugin.hive.metastore.glue.TestHiveGlueMetastore
2022-02-18T19:56:28.8537420Z [ERROR] io.trino.plugin.hive.metastore.glue.TestHiveGlueMetastore.testUpdateBasicPartitionStatistics  Time elapsed: 2.784 s  <<< FAILURE!
2022-02-18T19:56:28.8538684Z io.trino.spi.TrinoException: InternalServiceException: Internal server error (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: InternalServerError; Request ID: LJ6OMJL7JQCTBMLRU5DJIHK0C3VV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)
2022-02-18T19:56:28.8540145Z 	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.propagatePartitionErrorToTrinoException(GlueHiveMetastore.java:1013)
2022-02-18T19:56:28.8541178Z 	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.lambda$addPartitions$33(GlueHiveMetastore.java:978)
2022-02-18T19:56:28.8542295Z 	at io.trino.plugin.hive.metastore.glue.GlueMetastoreApiStats.call(GlueMetastoreApiStats.java:35)
2022-02-18T19:56:28.8543197Z 	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.addPartitions(GlueHiveMetastore.java:963)
2022-02-18T19:56:28.8544260Z 	at io.trino.plugin.hive.HiveMetastoreClosure.addPartitions(HiveMetastoreClosure.java:245)
2022-02-18T19:56:28.8545322Z 	at io.trino.plugin.hive.AbstractTestHive.createDummyPartitionedTable(AbstractTestHive.java:3207)
2022-02-18T19:56:28.8546683Z 	at io.trino.plugin.hive.AbstractTestHive.testUpdateBasicPartitionStatistics(AbstractTestHive.java:3071)
2022-02-18T19:56:28.8547804Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-02-18T19:56:28.8549188Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-02-18T19:56:28.8551328Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-02-18T19:56:28.8552599Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-02-18T19:56:28.8553816Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2022-02-18T19:56:28.8554764Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2022-02-18T19:56:28.8556047Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2022-02-18T19:56:28.8557174Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2022-02-18T19:56:28.8558213Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2022-02-18T19:56:28.8559218Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2022-02-18T19:56:28.8560068Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-02-18T19:56:28.8561255Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-02-18T19:56:28.8561962Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
@alexjo2144 rerun

**Comment by findepi** [comment]
```
57 successful, 1 cancelled, and 1 failing checks
ci / hive-tests (config-empty) (pull_request) Cancelled after 60m — hive-tests (config-empty)
ci / test (:trino-hive -P test-failure-recovery) (pull_request) Failing after 27m — test (:trino-hive -P test-failure-recovery)
```

**Comment by findepi** [comment]
@alexjo2144 rerun

**Comment by findepi** [comment]
same again. @alexjo2144 please investigate the results.

**Comment by alexjo2144** [comment]
The `test-failure-recovery` module is the only thing that was failing for the last two runs, and it was also failing on `master` yesterday 

https://github.com/trinodb/trino/runs/5280866004?check_suite_focus=true

**Comment by findepi** [comment]
I was more concerned about `ci / hive-tests (config-empty) (pull_request) Cancelled after 60m`

**Pull request closed without merging**
