### PR TITLE
Test changing Hive default compression to ZSTD

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by findepi** [comment]
see also https://github.com/trinodb/trino/pull/9773

**Comment by raunaqmorarka** [comment]
Just rebasing to master to see if situation changed here

**Comment by raunaqmorarka** [comment]
Still many failures with Hive
```
2023-05-09T06:37:32.1080856Z tests               | 2023-05-09 12:22:32 SEVERE: Failure cause:
2023-05-09T06:37:32.1081886Z tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: java.io.IOException: org.apache.avro.AvroRuntimeException: Unrecognized codec: zstandard
2023-05-09T06:37:32.1083114Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2023-05-09T06:37:32.1083857Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2023-05-09T06:37:32.1084737Z tests               | 	at io.trino.tests.product.hive.TestAvroSchemaLiteral.testTrinoCreatedTable(TestAvroSchemaLiteral.java:69)
2023-05-09T06:37:32.1148009Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-05-09T06:37:32.1148661Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-05-09T06:37:32.1149345Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-05-09T06:37:32.1149905Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-05-09T06:37:32.1150457Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2023-05-09T06:37:32.1150986Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2023-05-09T06:37:32.1151458Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2023-05-09T06:37:32.1152022Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2023-05-09T06:37:32.1152573Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2023-05-09T06:37:32.1153419Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2023-05-09T06:37:32.1153970Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-05-09T06:37:32.1154547Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-05-09T06:37:32.1154991Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-09T06:37:32.1155514Z tests               | Caused by: java.sql.SQLException: java.io.IOException: org.apache.avro.AvroRuntimeException: Unrecognized codec: zstandard
2023-05-09T06:37:32.1156043Z tests               | 	at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:121)
2023-05-09T06:37:32.1156522Z tests               | 	at org.apache.hive.jdbc.Utils.verifySuccessWithInfo(Utils.java:109)
2023-05-09T06:37:32.1157031Z tests               | 	at org.apache.hive.jdbc.HiveQueryResultSet.next(HiveQueryResultSet.java:330)
2023-05-09T06:37:32.1157560Z tests               | 	at io.trino.tempto.query.QueryResult$QueryResultBuilder.addRows(QueryResult.java:250)
2023-05-09T06:37:32.1158070Z tests               | 	at io.trino.tempto.query.QueryResult.forResultSet(QueryResult.java:199)
2023-05-09T06:37:32.1158640Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:129)
2023-05-09T06:37:32.1159352Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2023-05-09T06:37:32.1159734Z tests               | 	... 15 more
2023-05-09T06:37:32.1160104Z tests               | 	Suppressed: java.lang.Exception: Query: SELECT * FROM test_avro_schema_literal_trino
2023-05-09T06:37:32.1160653Z tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2023-05-09T06:37:32.1161067Z tests               | 		... 16 more
```

**Comment by mosabua** [comment]
@electrum is this still in progress?

**Comment by raunaqmorarka** [comment]
Still fails in Apache Hive
```
2024-08-16T04:36:20.8923356Z tests               | 2024-08-16 10:21:20 SEVERE: Failure cause:
2024-08-16T04:36:20.8930374Z tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: java.io.IOException: org.apache.parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file hdfs://hadoop-master:9000/user/hive/warehouse/test_nested_fields_written_by_trino/20240816_043620_00130_nqh9r_d12e7694-1122-4884-80da-cca4bc7ce1cd
2024-08-16T04:36:20.8933071Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2024-08-16T04:36:20.8933931Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2024-08-16T04:36:20.8934920Z tests               | 	at io.trino.tests.product.hive.TestHiveStorageFormats.testNestedFields(TestHiveStorageFormats.java:615)
2024-08-16T04:36:20.8936106Z tests               | 	at io.trino.tests.product.hive.TestHiveStorageFormats.testNestedFieldsWrittenByTrino(TestHiveStorageFormats.java:558)
2024-08-16T04:36:20.8937279Z tests               | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2024-08-16T04:36:20.8938125Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-08-16T04:36:20.8938929Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2024-08-16T04:36:20.8939722Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2024-08-16T04:36:20.8940386Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2024-08-16T04:36:20.8941087Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2024-08-16T04:36:20.8942070Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2024-08-16T04:36:20.8943206Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2024-08-16T04:36:20.8944330Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-08-16T04:36:20.8945296Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-08-16T04:36:20.8946023Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:1570)
2024-08-16T04:36:20.8947924Z tests               | Caused by: java.sql.SQLException: java.io.IOException: org.apache.parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file hdfs://hadoop-master:9000/user/hive/warehouse/test_nested_fields_written_by_trino/20240816_043620_00130_nqh9r_d12e7694-1122-4884-80da-cca4bc7ce1cd
2024-08-16T04:36:20.8949654Z tests               | 	at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:121)
2024-08-16T04:36:20.8950353Z tests               | 	at org.apache.hive.jdbc.Utils.verifySuccessWithInfo(Utils.java:109)
2024-08-16T04:36:20.8951141Z tests               | 	at org.apache.hive.jdbc.HiveQueryResultSet.next(HiveQueryResultSet.java:330)
2024-08-16T04:36:20.8951975Z tests               | 	at io.trino.tempto.query.QueryResult$QueryResultBuilder.addRows(QueryResult.java:260)
2024-08-16T04:36:20.8952779Z tests               | 	at io.trino.tempto.query.QueryResult.forResultSet(QueryResult.java:209)
2024-08-16T04:36:20.8953639Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:129)
2024-08-16T04:36:20.8954523Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2024-08-16T04:36:20.8955085Z tests               | 	... 14 more
2024-08-16T04:36:20.8955655Z tests               | 	Suppressed: java.lang.Exception: Query: SELECT * FROM test_nested_fields_written_by_trino
2024-08-16T04:36:20.8956556Z tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2024-08-16T04:36:20.8957349Z tests               | 		... 15 more
```

**Pull request closed without merging**
