### PR TITLE
Update to Hadoop 3.3.5

### LINKED ISSUE #2196: HadoopIllegalArgumentException occurred in the table with HDFS erasure coding
Hi,
We use prestosql 324 but ```HadoopIllegalArgumentException``` occurred in the table with HDFS erasure coding.

Any suggestion?

DDL
```
CREATE EXTERNAL TABLE hoge.piyo (
       hh STRING,
       mmss STRING,
       log STRING  COMMENT 'json'
)
PARTITIONED BY (service STRING, yyyymmdd STRING)
STORED AS RCFILE
LOCATION
'hdfs://...'
;
```

query
```
SELECT count(*) FROM hoge.piyo WHERE ... AND yyyymmdd='20190930' LIMIT 100
```

stacktrace
```
io.prestosql.spi.PrestoException: Failed to read RC file: hdfs://.../yyyymmdd=20190930/000044_0
	at io.prestosql.plugin.hive.rcfile.RcFilePageSource.getNextPage(RcFilePageSource.java:152)
	at io.prestosql.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:244)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:286)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_324____20191204_075334_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.HadoopIllegalArgumentException: Invalid buffer, not of length 951251
	at org.apache.hadoop.io.erasurecode.rawcoder.ByteBufferDecodingState.checkOutputBuffers(ByteBufferDecodingState.java:137)
	at org.apache.hadoop.io.erasurecode.rawcoder.ByteBufferDecodingState.<init>(ByteBufferDecodingState.java:48)
	at org.apache.hadoop.io.erasurecode.rawcoder.RawErasureDecoder.decode(RawErasureDecoder.java:86)
	at org.apache.hadoop.io.erasurecode.rawcoder.RawErasureDecoder.decode(RawErasureDecoder.java:170)
	at org.apache.hadoop.hdfs.StripeReader.decodeAndFillBuffer(StripeReader.java:433)
	at org.apache.hadoop.hdfs.PositionStripeReader.decode(PositionStripeReader.java:74)
	at org.apache.hadoop.hdfs.StripeReader.readStripe(StripeReader.java:390)
	at org.apache.hadoop.hdfs.DFSStripedInputStream.fetchBlockByteRange(DFSStripedInputStream.java:507)
	at org.apache.hadoop.hdfs.DFSInputStream.pread(DFSInputStream.java:1360)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:1324)
	at org.apache.hadoop.fs.FSInputStream.readFully(FSInputStream.java:121)
	at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:111)
	at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:111)
	at io.prestosql.plugin.hive.rcfile.HdfsRcFileDataSource.readFully(HdfsRcFileDataSource.java:82)
	at io.prestosql.rcfile.RcFileReader$DataSourceSliceLoader.load(RcFileReader.java:693)
	at io.prestosql.rcfile.RcFileReader$DataSourceSliceLoader.load(RcFileReader.java:667)
	at io.airlift.slice.ChunkedSliceInput$InternalLoader.load(ChunkedSliceInput.java:383)
	at io.airlift.slice.ChunkedSliceInput.ensureAvailable(ChunkedSliceInput.java:111)
	at io.airlift.slice.ChunkedSliceInput.readBytes(ChunkedSliceInput.java:259)
	at io.airlift.slice.ChunkedSliceInput.read(ChunkedSliceInput.java:242)
	at com.google.common.io.ByteStreams.skipUpTo(ByteStreams.java:819)
	at com.google.common.io.ByteStreams.skipFully(ByteStreams.java:795)
	at io.prestosql.rcfile.RcFileReader.advance(RcFileReader.java:410)
	at io.prestosql.plugin.hive.rcfile.RcFilePageSource.getNextPage(RcFilePageSource.java:122)
	... 13 more
```

### LINKED ISSUE #6413: "HadoopIllegalArgumentException: Invalid buffer, not of length X" when querying Hive erasure coding tables
Hello! Our current Presto version is 344 but possibly it should be relevant to the latest version too.
We have Hive tables with HDFS erasure coding enabled. If some datanode with EC blocks is unavailable then executing a query throws 

```
io.prestosql.spi.PrestoException: Error reading from hdfs://path_to_the_file at position 3395
        at io.prestosql.plugin.hive.orc.HdfsOrcDataSource.readInternal(HdfsOrcDataSource.java:91)
        at io.prestosql.orc.AbstractOrcDataSource.readFully(AbstractOrcDataSource.java:108)
        at io.prestosql.orc.AbstractOrcDataSource$DiskOrcDataReader.read(AbstractOrcDataSource.java:323)
        at io.prestosql.orc.stream.AbstractDiskOrcDataReader.seekBuffer(AbstractDiskOrcDataReader.java:91)
        at io.prestosql.orc.stream.CompressedOrcChunkLoader.ensureCompressedBytesAvailable(CompressedOrcChunkLoader.java:165)
        at io.prestosql.orc.stream.CompressedOrcChunkLoader.nextChunk(CompressedOrcChunkLoader.java:115)
        at io.prestosql.orc.stream.OrcInputStream.advance(OrcInputStream.java:204)
        at io.prestosql.orc.stream.OrcInputStream.read(OrcInputStream.java:96)
        at io.prestosql.orc.stream.OrcInputStream.readFully(OrcInputStream.java:121)
        at io.prestosql.orc.stream.ByteArrayInputStream.next(ByteArrayInputStream.java:43)
        at io.prestosql.orc.reader.SliceDirectColumnReader.readBlock(SliceDirectColumnReader.java:198)
        at io.prestosql.orc.reader.SliceColumnReader.readBlock(SliceColumnReader.java:74)
        at io.prestosql.orc.OrcBlockFactory$OrcBlockLoader.load(OrcBlockFactory.java:76)
        ...
Caused by: org.apache.hadoop.HadoopIllegalArgumentException: Invalid buffer, not of length 1045181
        at org.apache.hadoop.io.erasurecode.rawcoder.ByteBufferDecodingState.checkOutputBuffers(ByteBufferDecodingState.java:137)
        at org.apache.hadoop.io.erasurecode.rawcoder.ByteBufferDecodingState.<init>(ByteBufferDecodingState.java:48)
        at org.apache.hadoop.io.erasurecode.rawcoder.RawErasureDecoder.decode(RawErasureDecoder.java:86)
        at org.apache.hadoop.io.erasurecode.rawcoder.RawErasureDecoder.decode(RawErasureDecoder.java:170)
        at org.apache.hadoop.hdfs.StripeReader.decodeAndFillBuffer(StripeReader.java:433)
        at org.apache.hadoop.hdfs.PositionStripeReader.decode(PositionStripeReader.java:74)
        at org.apache.hadoop.hdfs.StripeReader.readStripe(StripeReader.java:390)
        at org.apache.hadoop.hdfs.DFSStripedInputStream.fetchBlockByteRange(DFSStripedInputStream.java:507)
        at org.apache.hadoop.hdfs.DFSInputStream.pread(DFSInputStream.java:1360)
        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:1324)
        at org.apache.hadoop.fs.FSInputStream.readFully(FSInputStream.java:121)
        at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:111)
        at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:111)
        at io.prestosql.plugin.hive.orc.HdfsOrcDataSource.readInternal(HdfsOrcDataSource.java:76)
        ... 32 more
```

Probably the reason is [HDFS-14373](https://issues.apache.org/jira/browse/HDFS-14373). Presto Hadoop client depends on [3.2.0 Apache version](https://github.com/prestosql/presto-hadoop-apache/blob/bac6b32ff7f3a52d259976b4bb3c9021742ff424/pom.xml#L45) but the issue has been fixed only in 3.2.2.
Also i've found similar issue https://github.com/prestosql/presto/issues/2196
It seems hadoop client should be updated at least to 3.2.2

### PR DESCRIPTION
**Pull request by electrum**
Fixes #6413
Fixes #2196

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

**Comment by electrum** [comment]
/test-with-secrets sha=37a12710e7e64afb206080c565132dc811866171

**Comment by electrum** [comment]
/test-with-secrets sha=1893ffbb38dc9aada989d843a222000ed57ea5ee

**Comment by electrum** [comment]
/test-with-secrets sha=38d6202e4b2f89bc2ba83ceb4162a171236c7bb8

**Review by ebyhr — APPROVED** [review]

**Comment by awdavidson** [comment]
Is there a timeline for getting this merged and released? Very keen for this

**Comment by electrum** [comment]
Just merged. This will be in the next release. We try to release Trino weekly.

**Pull request merged**
