### PR TITLE
Allow dictionary processing for date type in parquet

### PR DESCRIPTION
**Pull request by raunaqmorarka**
## Description
Date columns are usually low cardinality

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by raunaqmorarka** [comment]
Small cpu gains in tpcds (ignore duration, it's flaky)
Screenshot 2023-07-06 at 9 37 03 PM

[Date dictionary parquet partitioned sf1k.pdf](https://github.com/trinodb/trino/files/11970169/Date.dictionary.parquet.partitioned.sf1k.pdf)

**Review by sopel39 — APPROVED** [review]
why dates are so beneficial?

**Review by lukasz-stec — APPROVED** [review]
lgtm

**Comment by raunaqmorarka** [comment]
> why dates are so beneficial?

Dates are low cardinality and they show up in a few TPC queries

**Pull request merged**
