### PR TITLE
Add rank() window operator test

### PR DESCRIPTION
**Pull request by sopel39**

### CODE REVIEW

**Review by losipiuk — APPROVED** [review]

**Comment by losipiuk** [comment]
Note the red build

**Comment by findepi** [comment]
CI https://github.com/trinodb/trino/issues/6223

**Review by erichwang — APPROVED** [review]
Seems good to me for now, NaN handling is broken, and needs to fixed.

**Comment by erichwang** [comment]
I just added a fix for the DISTINCT handling for NaN: #6472

There was a test there that probably can supersede this one.

**Comment by sopel39** [comment]
> There is a test there that might be able to supersede this one.

I think the test should be added as separate commit and then changed by https://github.com/trinodb/trino/pull/6472

**Comment by erichwang** [comment]
> I think the test should be added as separate commit and then changed by #6472

Ok i'll put it in the other PR. Just curious, what's the reasoning behind this? I think it would be added and then replaced in that case right?

**Comment by sopel39** [comment]
> Ok i'll put it in the other PR. Just curious, what's the reasoning behind this? I think it would be added and then replaced in that case right?

If the test is added as separate commit, then it's more explicit (when the test is changed in following commit) how window semantics is changed.

**Pull request merged**
