### PR TITLE
Update to Accumulo 1.10.0

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Review by dain — APPROVED** [review]

**Comment by adamjshook** [comment]
I'd suggest holding off on merging this. I'll work on removing the use of MiniAccumuloCluster in favor of Accumulo in Docker and we can test to make sure the client libraries work with older versions of Accumulo. I think it'll be okay, but I'd like to test to make sure.

**Comment by electrum** [comment]
@adamjshook should we revisit this?

**Comment by adamjshook** [comment]
> @adamjshook should we revisit this?

@electrum Yes! The Docker image used for testing is on 1.7.4, so if the tests all pass with the updated client library, I'm happy. I believe the latest 1.x Accumulo version is 1.10.1.

**Comment by mosabua** [comment]
hey @adamjshook and @electrum .. this looks inactive, but valuable. Probably just needs to be updated. Did you want to continue working on this or close the PR?

**Comment by bitsondatadev** [comment]
Pinging @electrum on slack on this. If this hasn't been addressed in a week then I would say let's close it.

**Comment by adamjshook** [comment]
I think it is important to update the client to the latest 1.x since 1.7 has been EOL for a while. I can rebase this change and open another PR to supersede this one if David doesn't have time to do so.

We should also support Accumulo 2.x, but that's a separate issue.

**Comment by bitsondatadev** [comment]
@adamjshook, would you mind rebasing and I'll work with @electrum to look at this.

**Comment by bitsondatadev** [comment]
@adamjshook, just checking in here again though I know it's the holidays :)

**Comment by bitsondatadev** [comment]
Since #15626 supersedes this, I will close this.

**Pull request closed without merging**
