### PR TITLE
Use `putIdentity` method to reduce code duplication

### PR DESCRIPTION
**Pull request by findinpath**
## Description

Refactoring with the purpose of reducing code duplication.

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]
We could update the following classes as well:
* PushAggregationThroughOuterJoin
* TestPushProjectionThroughExchange
* TestPushTopNThroughProject

**Comment by ebyhr** [comment]
@findinpath Could you confirm CI failure?

**Review by pajaks — APPROVED** [review]

**Comment by findinpath** [comment]
> @findinpath Could you confirm CI failure?

My mistake. Removed one wrong modification.

**Comment by findinpath** [comment]
CI hit https://github.com/trinodb/trino/issues/16315

**Pull request merged**
