### PR TITLE
Refactor toString method for improved StringBuilder usage and attribute concatenation

### PR DESCRIPTION
**Pull request by awesomewhy**
minor changes to improve code reading

### CODE REVIEW

**Comment by mosabua** [comment]
Did you submit a signed CLA yet @awesomewhy ?

**Comment by mosabua** [comment]
@cla-bot check

**Comment by awesomewhy** [comment]
ok, i will @mosabua

**Comment by awesomewhy** [comment]
@cla-bot check

**Comment by awesomewhy** [comment]
i submitted the signed CLA on September 4th

**Pull request closed without merging**
