### PR TITLE
Allow to disable arbitrary plugins

### PR DESCRIPTION
**Pull request by ssheikin**
which are delivered within the original trino package under `/plugins`

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
(x) Release notes are required, with the following suggested text: Allow to disable arbitrary plugins

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by martint** [comment]
What's the motivation for this?

**Comment by hashhar** [comment]
> What's the motivation for this?

One use-case can be to conditionally load a plugin. e.g. let's say I ship some PostGis compatible functions in postgres connector but don't want to enable them by default and only load them when a config toggle is enabled.

GlobalFunctionCatalog#addFunctions looks like that but I don't think it's accessible from connectors? Can you suggest alternative?

**Comment by martint** [comment]
There are two modes for loading functions, currently:
* The legacy mode, which involves loading functions provided by Plugin.getFunctions() into the global namespace. This is done unconditionally when the plugin code is loaded, and independently of any configuration
* The new mode, which involves connectors providing functions dynamically via `ConnectorMetadata.getFunctions()`. These functions are mounted under a catalog and schema and are accessible via their fully qualified name, or via the short name if the catalog/schema is in the function path (via SET PATH)

If you wanted to ship PostGIS compatible functions, you'd have to add the necessary logic inside `ConnectorMetadata.getFunctions()` for that connector and decide whether the function is available based on session or config parameters.

**Review by electrum — CHANGES_REQUESTED** [review]
The way that plugins are named and shipped is an implementation detail that can (and sometimes does) change. We shouldn't expose it to end users in this manner. Plugins don't have the concept of a name.

Given the stated goal of adding this feature to allow conditionally loading global functions, we should consider how to tackle that directly, assuming that connector-provided functions are not sufficient.

**Comment by martint** [comment]
@ssheikin, see my comment above. The use case described can be handled via connector-provided functions, so this change seems unnecessary.

**Comment by kokosing** [comment]
BTW one can disable catalog from loading with `catalog.disabled-catalogs`

**Pull request closed without merging**
