### PR TITLE
Fix getPartitionNamesByFilter for Glue metastore

### PR DESCRIPTION
**Pull request by findepi**
This supposedly fixes `TestHiveGlueMetastore`.

Alternative to https://github.com/trinodb/trino/pull/8223 
cc @sopel39 @electrum

### CODE REVIEW

**Comment by hashhar** [comment]
@findepi Please push an empty commit for all the hive tests to run.

**Review by sopel39 — APPROVED** [review]

**Review by electrum — APPROVED** [review]
Thanks, I didn't realize Glue tests were not run for PRs

**Comment by sopel39** [comment]
> Thanks, I didn't realize Glue tests were not run for PRs

Which tags we need to set now to run Glue tests? Are the available tags described somewhere?

**Comment by findepi** [comment]
> > Thanks, I didn't realize Glue tests were not run for PRs
> 
> Which tags we need to set now to run Glue tests? Are the available tags described somewhere?

you need to run not-from-a-fork, due to secrets.

**Pull request merged**
