### PR TITLE
Support varargs in ConnectorExpression

### PR DESCRIPTION
**Pull request by takezoe**
## Description
Make it possible to pushdown functions that take varargs to connectors.

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by mosabua** [comment]
Ping @martint

**Comment by wendigo** [comment]
@martint please chime in

**Comment by martint** [comment]
ConnectorExpression already supports varargs. All you need to do is construct a `Call` with the proper concrete type and arguments.

**Comment by takezoe** [comment]
Hmm... In my understanding ConnectorExpression needs to be able to round-trip and functions like `format` takes `Row` as a vararg. How can we round-trip varargs in that case?

**Pull request closed without merging**
