### PR TITLE
Respect deprecated.legacy-catalog-roles=true in SHOW ROLES

### PR DESCRIPTION
**Pull request by kokosing**
Respect deprecated.legacy-catalog-roles=true in SHOW ROLES

### CODE REVIEW

**Comment by kokosing** [comment]
Alternative version of https://github.com/trinodb/trino/pull/9491

**Review by gaurav8297 — APPROVED** [review]

**Review by ksobolew — APPROVED** [review]
I'm not entirely sure that's actually better. Hidden session properties? It's kind of like using `ThreadLocal` to pass values between functions instead of adding an explicit parameter ;) Also, this value now lives in two places instead of one. On the other hand, it *removes code* instead of adding more, which is nice. But I'm fine with it in general.

**Comment by kokosing** [comment]
> Hidden session properties?

Now it becomes a feature of product.  User is able to update that configuration using `SET SESSION legacy_catalog_roles=true`. The toggle is hidden so `SHOW SESSION` does not show it. To me that session property might be useful. Notice while hitting https://github.com/trinodb/trino/issues/9485 user could simply change the session instead of configuration and restarting the cluster.

**Comment by ksobolew** [comment]
> Now it becomes a feature of product. User is able to update that configuration using `SET SESSION legacy_catalog_roles=true`. The toggle is hidden so `SHOW SESSION` does not show it. To me that session property might be useful. Notice while hitting #9485 user could simply change the session instead of configuration and restarting the cluster.

Sure. But now the sensible thing to do is to convert as many of the properties in `FeaturesConfig` to hidden session properties. Just sayin' :)

**Review by Praveen2112 — APPROVED** [review]
But why are we making it this session property hidden ?

**Comment by kokosing** [comment]
> But why are we making it this session property hidden ?

I am not sure if it is should be public yet.

**Comment by gaurav8297** [comment]
> But why are we making it this session property hidden ?

Yeah, why not a public session property? As it is not an experimental feature

**Comment by kokosing** [comment]
> Yeah, why not a public session property? As it is not an experimental feature

It is a legacy feature. We want to remove it, so make it public will make removal harder.

**Pull request merged**
