### PR TITLE
Elastic search plugin support for  pushdown TopN and  Aggregation

### PR DESCRIPTION
**Pull request by murthy-chelankuri**
## Additional context and related issues
This PR provides the support pushing down TopN and Aggregation function to elasticsearch. 

( ) This is not user-visible or docs only and no release notes are required.
( x) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown

# Fixes
```
* #12381 
* #7026
* #4803

### CODE REVIEW

**Comment by cploonker** [comment]
Following for updates

**Comment by murthy-chelankuri** [comment]
@hashhar @kokosing , Can you please review this merge request

**Comment by mosabua** [comment]
:wave: @murthy-chelankuri @martint @bitsondatadev  - this PR has become inactive. If you're still interested in working on it, please let us know.

Also fyi .. thanks to the work of @wendigo we now also have an OpenSearch connector .. so the changes could be ported there as well. 

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by murthy-chelankuri** [comment]
@mosabua sorry for the delayed response. Yes I would like these changes merged. Please let me know about the next steps on this.

**Comment by mosabua** [comment]
Can you check out the test failures and ensure they at least do not occur on your own setup.

**Comment by murthy-chelankuri** [comment]
@mosabua I made a few changes, and now the tests are successful without any issues. However, the pipeline is failing even for the build, although both the build and tests worked well on my local machine.

**Comment by wendigo** [comment]
@murthy-chelankuri definitely not. I guess that your local setup is invalid rather then our pipelines which runs several hundred times a week.

**Comment by wendigo** [comment]
This branch is not rebased:

```
commit e1dc146f2409447318c47a0ebf1167fa4c315942
Author: Martin Traverso <mtraverso@gmail.com>
Date:   Mon Sep 25 09:21:59 2023 -0700

    Avoid exponential DFA in LIKE matcher

    When a pattern contains a % and a sequence of _ somewhere
    after it, it may produce a DFA with exponential number of states.
    In such cases, fall back to the NFA matcher.
```

it's based on commit from 6 months ago. In the meantime, elasticsearch client was updated.

**Comment by wendigo** [comment]
After rebasing I'm getting the same compilation errors as in the CI:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project trino-elasticsearch: Compilation failure: Compilation failure:
[ERROR] /Users/mateuszgajewski/Projects/src/github.com/trinodb/trino/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java:[37,57] package org.elasticsearch.search.aggregations.metrics.avg does not exist
[ERROR] /Users/mateuszgajewski/Projects/src/github.com/trinodb/trino/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java:[38,57] package org.elasticsearch.search.aggregations.metrics.max does not exist
[ERROR] /Users/mateuszgajewski/Projects/src/github.com/trinodb/trino/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java:[39,57] package org.elasticsearch.search.aggregations.metrics.min does not exist
[ERROR] /Users/mateuszgajewski/Projects/src/github.com/trinodb/trino/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java:[40,57] package org.elasticsearch.search.aggregations.metrics.sum does not exist
[ERROR] /Users/mateuszgajewski/Projects/src/github.com/trinodb/trino/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java:[41,64] package org.elasticsearch.search.aggregations.metrics.valuecount does not exist
[ERROR] /Users/mateuszgajewski/Projects/src/github.com/trinodb/trino/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/AggregateQueryPageSource.java:[33,59] package org.elasticsearch.search.aggregations.metrics.stats does not exist
[ERROR] /Users/mateuszgajewski/Projects/src/github.com/trinodb/trino/plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/AggregateQueryPageSource.java:[299,45] cannot find symbol
```

**Comment by murthy-chelankuri** [comment]
@mosabua now the tests are running without any failures can you help me to get the changes at the earliest.

**Comment by mosabua** [comment]
Can you please squash the commits and ensure the build actually passes. Currently CI is still failing.

**Comment by murthy-chelankuri** [comment]
@mosabua Thank you for the information. I have squashed the commits and the pipeline has passed all checks.

**Comment by mosabua** [comment]
Can you change the commit message to 

```
Add support for TopN and aggregation pushdown
```

@murthy-chelankuri 


I will see if @wendigo @ebyhr or others are available for review help.

**Comment by murthy-chelankuri** [comment]
> Can you change the commit message to
> 
> ```
> Add support for TopN and aggregation pushdown
> ```
> 
> @murthy-chelankuri
> 
> I will see if @wendigo @ebyhr or others are available for review help.

Changed the commit message as per your suggestion

**Comment by murthy-chelankuri** [comment]
@mosabua can you help to prioritize the code review for this PR before we lose traction?

**Comment by jbackofe** [comment]
Looking forward to this feature!

**Comment by murthy-chelankuri** [comment]
@ebyhr , @wendigo spend some time today and resolved the merge conflicts. Now every thing looks good Can we reopen the merge request. Some reason i could not reopen this MR. Shall open a new MR ?

**Comment by murthy-chelankuri** [comment]
I have resolved the merge conflicts, and now everything looks good. All the tests have passed successfully.

**Comment by murthy-chelankuri** [comment]
@bitsondatadev @colebow @mosabua is there a way can we open is merge request instead of creaing  new one ?

**Comment by murthy-chelankuri** [comment]
Reopening this MR as all the conflicts got resolved now.

**Comment by mosabua** [comment]
You should be able to reopen the PR. If not just close it and create a new one and link to this one for completeness of info

**Comment by murthy-chelankuri** [comment]
Thanks @mosabua  opened new PR (https://github.com/trinodb/trino/pull/23118) as i am not able to reopen this PR fro some reason.

**Pull request closed without merging**
