### PR TITLE
Update action-surefire-report

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

`v1.6.0` uses a more efficient XML parsing library
that should handle all test reports generated in Trino.

Bind to this version specifically because `v1` doesn't point to it yet because of some compatibility issues, see https://github.com/ScaCap/action-surefire-report/issues/140. It's safe to use for use since we're running on `ubuntu-latest` VMs.

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by nineinchnick** [comment]
Note that this PR changes an action that doesn't run in any workflow for PRs, so we don't have to wait for it to be green.

**Review by ebyhr — APPROVED** [review]

**Comment by ebyhr** [comment]
@nineinchnick Still failing on master with a new error message. Could you confirm that? 
```
Run scacap/action-surefire-report@v1.6.0
  with:
    fail_if_no_tests: false
    commit: e191cb9c998956574c4c401f734f9596[2](https://github.com/trinodb/trino/actions/runs/4382083337/jobs/7670771144#step:4:2)120f[4](https://github.com/trinodb/trino/actions/runs/4382083337/jobs/7670771144#step:4:4)92
    github_token: ***
    report_paths: **/surefire-reports/TEST-*.xml, **/failsafe-reports/TEST-*.xml
    create_check: true
    check_name: Test Report
    fail_on_test_failures: false
    skip_publishing: false
    file_name_in_stack_trace: false
Going to parse results form **/surefire-reports/TEST-*.xml
 **/failsafe-reports/TEST-*.xml
Error: internal error: Huge input lookup
```

https://github.com/trinodb/trino/actions/runs/4382083337/jobs/7670771144

**Comment by nineinchnick** [comment]
I managed to replicate this locally. The weird thing is that it fails on reports that are not the largest:
```
# du -mcs test-reports/test\ report\ test\ \(plugin_trino-iceberg\,*/plugin/trino-iceberg/target/surefire-reports/TEST-TestSuite.xml 
22	test-reports/test report test (plugin_trino-iceberg, , )/plugin/trino-iceberg/target/surefire-reports/TEST-TestSuite.xml
38	test-reports/test report test (plugin_trino-iceberg, additional-catalog-tests, )/plugin/trino-iceberg/target/surefire-reports/TEST-TestSuite.xml
2	test-reports/test report test (plugin_trino-iceberg, cloud-tests, )/plugin/trino-iceberg/target/surefire-reports/TEST-TestSuite.xml
7	test-reports/test report test (plugin_trino-iceberg, fte-tests, )/plugin/trino-iceberg/target/surefire-reports/TEST-TestSuite.xml
66	total
```

and
```
# export INPUT_REPORT_PATHS=test-reports/test\ report\ test\ \(plugin_trino-iceberg*/**/TEST-TestSuite.xml 
# node dist/index.js 
Going to parse results form test-reports/test report test (plugin_trino-iceberg*/**/TEST-TestSuite.xml
::debug::followSymbolicLinks 'false'
::debug::followSymbolicLinks 'false'
::debug::implicitDescendants 'true'
::debug::matchDirectories 'true'
::debug::omitBrokenSymbolicLinks 'true'
::debug::Search path '/src/test-reports'
::debug::Parsing file /src/test-reports/test report test (plugin_trino-iceberg, , )/plugin/trino-iceberg/target/surefire-reports/TEST-TestSuite.xml
::debug::Parsing file /src/test-reports/test report test (plugin_trino-iceberg, additional-catalog-tests, )/plugin/trino-iceberg/target/surefire-reports/TEST-TestSuite.xml
::error::internal error: Huge input lookup%0A
```

but it works when executed on the largest report:
```
# export INPUT_REPORT_PATHS=test-reports/test\ report\ test\ \(plugin_trino-iceberg\,\ additional-catalog-tests\,\ \)/plugin/trino-iceberg/target/surefire-reports/TEST-TestSuite.xml 
# node dist/index.js 
Going to parse results form test-reports/test report test (plugin_trino-iceberg
 additional-catalog-tests
 )/plugin/trino-iceberg/target/surefire-reports/TEST-TestSuite.xml
::debug::followSymbolicLinks 'false'
::debug::followSymbolicLinks 'false'
::debug::implicitDescendants 'true'
::debug::matchDirectories 'true'
::debug::omitBrokenSymbolicLinks 'true'
::debug::Search path '/src/test-reports/test report test (plugin_trino-iceberg'
::debug::Search path '/src/additional-catalog-tests'
::debug::Search path '/src/)/plugin/trino-iceberg/target/surefire-reports/TEST-TestSuite.xml'
Not publishing test result due to skip_publishing=true

::set-output name=conclusion::success
```

**Comment by nineinchnick** [comment]
The solution from https://github.com/libxmljs/libxmljs/issues/372 works. I'll create another PR for the action, and we'll have to update again when it gets merged.

**Comment by nineinchnick** [comment]
https://github.com/ScaCap/action-surefire-report/pull/144

**Pull request merged**
