### PR TITLE
Add row pattern recognition functions to list of functions

### PR DESCRIPTION
**Pull request by verhovsky**
I missed these in https://github.com/sql-formatter-org/sql-formatter/pull/297 and added them in https://github.com/sql-formatter-org/sql-formatter/pull/333 also needed this for https://github.com/codemirror/codemirror5/pull/6962

### CODE REVIEW

**Review by mosabua — APPROVED** [review]
Looks good.

**Comment by mosabua** [comment]
Could you resolve the conflict @verhovsky ?

**Comment by verhovsky** [comment]
In a week or two maybe.

**Comment by mosabua** [comment]
Ping ..

**Review by mosabua — APPROVED** [review]
Thanks for noticing and fixing!

**Comment by mosabua** [comment]
Btw .. I will add sql-formatter as an add-on tool listed on the trino.io website.

Also note that the Trino and Presto dialect are NOT the same at this stage.

**Pull request merged**
