### PR TITLE
Update azure-sdk to 1.2.28

### PR DESCRIPTION
**Pull request by anusudarsan**
## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by anusudarsan** [comment]
@wendigo can you please trigger `trino-filesystem-azure` cloud-tests to make sure https://github.com/Azure/azure-sdk-for-java/pull/41648 fixed the oauth logging noise?

**Review by wendigo — APPROVED** [review]

**Comment by wendigo** [comment]
@anusudarsan tested here: https://github.com/trinodb/trino/pull/23617

**Comment by wendigo** [comment]
@anusudarsan looks good

**Comment by anusudarsan** [comment]
@wendigo yes I confirmed too. please merge!

**Pull request merged**
