### PR TITLE
Update protobuf to 4.28.0

### PR DESCRIPTION
**Pull request by wendigo**
## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by wendigo** [comment]
I need this to update mysql jdbc driver to the latest (required protobuf 4.x but the existing code didn't work with pre 4.28.0 because of the binary backward-compatibility being broken). This should be possible due to https://github.com/protocolbuffers/protobuf/commit/6bf01c51a0b92278958f0169d330d64a08dbb4ec

**Comment by ebyhr** [comment]
> I need this to update mysql jdbc driver 

Did you figure out the root cause of https://github.com/trinodb/trino/issues/21945?

**Review by ebyhr — COMMENTED** [review]
Kafka CI failure looks related to this change.

**Comment by wendigo** [comment]
@ebyhr yeah, still not backward-compatible :/

**Pull request closed without merging**
