### PR TITLE
Bump iceberg to 0.14.1

### PR DESCRIPTION
**Pull request by findinpath**
## Description

Iceberg library upgrade to 0.14.1

## Non-technical explanation

N/A

## Release notes

(x) This is not user-visible and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by findinpath** [comment]
Waiting for the release notes of 0.14.1 before going further with the PR.

**Review by Fokko — APPROVED** [review]
LGTM

You can find the release notes over here: https://iceberg.apache.org/releases/#0141-release

**Comment by alexjo2144** [comment]
@findepi want to kick off a test with secrets?

**Comment by findepi** [comment]
Test PR with secrets: https://github.com/trinodb/trino/pull/14146
(@nineinchnick's https://github.com/trinodb/trino/pull/12817 will make these PRs easier)

**Comment by findepi** [comment]
> You can find the release notes over here: https://iceberg.apache.org/releases/#0141-release

of these, i think none are end-user facing from Trino perspective.

@alexjo2144 see this one "Core: Fix snapshot log with intermediate transaction snapshots ([#5568](https://github.com/apache/iceberg/pull/5568))"

**Comment by findinpath** [comment]
> @alexjo2144 see this one "Core: Fix snapshot log with intermediate transaction snapshots (https://github.com/apache/iceberg/pull/5568)"

Created https://github.com/trinodb/trino/issues/14165

**Pull request merged**
