### PR TITLE
Upgrade Elasticsearch client to 7.x

### PR DESCRIPTION
**Pull request by wendigo**
This removes support for Elasticsearch 6.x and Opensearch 1.x while introducing support and test coverage for 8.x.

Both http security and user authentication are enabled by default.

OpenSearch support is moved to a separate connector via https://github.com/trinodb/trino/pull/20257

Fixes https://github.com/trinodb/trino/issues/20238

### CODE REVIEW

**Comment by wendigo** [comment]
Fixes https://github.com/trinodb/trino/issues/20238

**Comment by wendigo** [comment]
@ebyhr @hashhar PTAL. This completes Elasticsearch and Opensearch plugins separation

**Review by hashhar — COMMENTED** [review]
we no longer have tests for ES without auth. Or is that no longer a supported ES configuration?

**Comment by wendigo** [comment]
@hashhar clusters are secure by default and since open ES clusters were source of many data leaks, we should also discourage plain, unauthenticated usage. it will still work thou

**Review by hashhar — APPROVED** [review]

**Comment by wendigo** [comment]
@mosabua we can follow-up with the elasticsearch docs cleanup similiar to the opensearch one

**Pull request merged**
