### PR TITLE
add collect_set() function.

### LINKED ISSUE #1756: add collect_set(col) function
Hi, in my company, there are many scenarios that require a function to return a set of objects with duplicate elements eliminated, can you add this support? Just like collect_set(col) in hive.

### PR DESCRIPTION
**Pull request by bhji123**
Fixes #1756
Returns a set of objects with duplicate elements eliminated.

### CODE REVIEW

**Comment by ebyhr** [comment]
Hi, thanks for your contribution! There's #dev channel in our [Slack](https://prestosql.io/slack.html). Please feel free to join there. 

Current implementation looks not improving the performance comparing to alternative suggested by @Praveen2112  and it was slower than existing array function in my quick test case with tpch connector. (It doesn't mean we don't need this function) Have you already tested in your environment?

**Comment by bhji123** [comment]
> function

Thank you for your suggestion. I have tested with hive connector and jdbc, it seems ok.
And I will try more tests.

**Comment by bhji123** [comment]
> Hi, thanks for your contribution! There's #dev channel in our [Slack](https://prestosql.io/slack.html). Please feel free to join there.
> 
> Current implementation may not improve the performance comparing to alternative suggested by @Praveen2112 and it was slower than existing array function in my quick test case with tpch connector. (It doesn't mean we don't need this function) Have you already tested in your environment?

Hi, Thanks a lot for your suggestion. 
I have tested with hive connector and jdbc, it seems ok, but I will try more tests.

**Comment by KevinKobi** [comment]
Is there progress with this?
@bhji123  I would also be interested in this feature

**Comment by bhji123** [comment]
> Thank you for your pull request and welcome to our community. We require contributors to sign our [Contributor License Agreement](https://github.com/prestosql/cla/raw/master/Presto%20Foundation%20Individual%20CLA.pdf), and we don't seem to have you on file. In order for us to review and merge your code, please submit the signed CLA to [cla@prestosql.io](mailto:cla@prestosql.io). For more information, see https://github.com/prestosql/cla.

I have signed CLA to [cla@prestosql.io] a few months ago, didn't you receive it?

**Comment by bhji123** [comment]
> Is there progress with this?
> @bhji123 I would also be interested in this feature

hi, I have updated this function. But it seems CLA verification always failed.

**Comment by ebyhr** [comment]
@bhji123 You are registered as `bhji123`, but the commit author is `jibaohua`. Can you fix it?

**Comment by bhji123** [comment]
> @bhji123 You are registered as `bhji123`, but the commit author is `jibaohua`. Can you fix it?

hi, I have fixed this problem, finally the CLA verification passed.
Thanks a lot.

**Comment by ebyhr** [comment]
This PR is logically conflicted. Could you rebase on upstream?

**Comment by bitsondatadev** [comment]
:wave: @bhji123  - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.
We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by bitsondatadev** [comment]
Mah bad

**Pull request closed without merging**
