### PR TITLE
Test: Propagate redshift query cancellation

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Run CI with secrets for https://github.com/trinodb/trino/pull/22774

### CODE REVIEW

**Comment by SemionPar** [comment]
Pushdown failures are unrelated to https://github.com/trinodb/trino/pull/22774 - I have also seen those while testing driver upgrade - I will take a look.

**Comment by findinpath** [comment]
@SemionPar what about the other failures? 

https://github.com/trinodb/trino/actions/runs/10209742683/job/28248262256?pr=22917

```
2024-08-01T22:38:50.335-0600	WARN	TestHangMonitor	io.trino.testing.services.junit.LogTestDurationListener	No test started or completed in 8.00m. Running tests:
	TestRedshiftConnectorTest running for 33.08m
	JUnit Jupiter running for 33.08m
	TestRedshiftConnectorTest.testDataMappingSmokeTest() running for 23.67m.
```

?

**Comment by SemionPar** [comment]
`TestRedshiftConnectorTest.testDataMappingSmokeTest()` is very slow, because it creates tables and this is slow in Redshift. It is not related to query cancellation changes.
Other failures with pushdowns are also unrelated - we could confirm that by doing similar PR from master branch.

**Comment by SemionPar** [comment]
I am tackling these other failures in https://github.com/trinodb/trino/pull/22959

**Comment by SemionPar** [comment]
https://github.com/trinodb/trino/pull/22959 has been merged and I rebased https://github.com/trinodb/trino/pull/22774 - I could not update this branch though

**Pull request closed without merging**
