### PR TITLE
Add dynamic loading functions

### PR DESCRIPTION
**Pull request by Jay-ju**
## Description

We can dynamic loading functions through this feature .
Step1:
 we need put function jar to every worker server(in future we can put it on some distribute filesystem, like hdfs, s3 etc.). 

Step2:
 we can execute some sql like that
   add jar '/tmp/udfs/functions1.jar' ,  here functions1.jar must be absolute path

Step3:
 we can drop all functions in a function jar 
   drop jar  '/tmp/udfs/functions1.jar'   or     drop jar 'functions1'

we can use  'show functions'  to show detail description on function like jar‘s name or jar's url

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by Jay-ju** [comment]
> Thank you for your pull request and welcome to our community. We could not parse the GitHub identity of the following contributors: **jukejian**. This is most likely caused by a git client misconfiguration; please make sure to:
> 
> 1. check if your git client is configured with an email to sign commits `git config --list | grep email`
> 2. If not, set it up using `git config --global user.email email@example.com`
> 3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

done

**Comment by colebow** [comment]
👋 @Jay-ju - after seeing your ping on the Trino Slack regarding getting some help with a review, I ran this PR by the maintainer team, and after a discussion, the conclusion was that they're not fans of moving forward with an approach like this. The ability to add arbitrary Java functions to Trino has some major security and reliability concerns which make it tough and problematic to support. We do understand that being able to add functions is powerful and and a highly-desired feature, but it's probably going to need to wait until it can be supported more in a more robust and security-conscious manner, which is a way out.

**Comment by Jay-ju** [comment]
> 👋 @Jay-ju - after seeing your ping on the Trino Slack regarding getting some help with a review, @bitsondatadev and I ran this PR by the maintainer team, and after a discussion, the conclusion was that they're not fans of moving forward with an approach like this. The ability to add arbitrary Java functions to Trino has some major security and reliability concerns which make it tough and problematic to support. We do understand that being able to add functions is powerful and and a highly-desired feature, but it's probably going to need to wait until it can be supported more in a more robust and security-conscious manner, which is a way out.

**Comment by Jay-ju** [comment]
> 
the reason that it's unsafe for adding udf on trino seems that functions are managed by global catalog? in other word, first we must implement separate namespace or plugin or execute environment for functions（like remote udf）?  i think this feature is not conflict with them？ here i have used plugin as function classloader isolation, remote udf can be implemented in future?

**Comment by colebow** [comment]
Yeah, remote UDF may be coming somewhere down the line (though probably after things like a batch execution mode and creating a function language). It's not that this feature conflicts with that approach, it's that as an independent thing, it has major security drawbacks.

**Comment by mosabua** [comment]
We now have support for SQL routines so I think we can close this PR.

https://trino.io/docs/current/routines.html

**Pull request closed without merging**
