### PR TITLE
Skip UNION [ALL, DISTINCT] tests on CDH5

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Review by hashhar — COMMENTED** [review]
Is there a workaround for CDH5? Does it work with legacy view translation?

If not - we should maybe consider reverting the change instead.

Please also add some context into the commit message for our future selves.

**Comment by wendigo** [comment]
@hashhar this kind of Hive view is not possible to create on CDH5 due to Hive version. There is no workaround as it's just not possible to create

**Comment by hashhar** [comment]
> @hashhar this kind of Hive view is not possible to create on CDH5 due to Hive version. There is no workaround as it's just not possible to create

Thanks for clearing it up. I understand now. Please mention that this syntax isn't supported in CDH5 in the commit message.

**Comment by hashhar** [comment]
Would the "correct" fix be to adjust the test to make use of `getHiveVersion` in the product test to decide instead of skipping on just CDH5? That way it's kind of self-documenting.

**Comment by wendigo** [comment]
@hashhar idk whether this syntax is supported by a concrete major hive version. I can test that.

**Comment by wendigo** [comment]
Or maybe I can just add exclusion to ConfigCdh5

**Comment by losipiuk** [comment]
> @hashhar idk whether this syntax is supported by a concrete major hive version. I can test that.

Issue @hashhar linked suggests it was. Having version based logic would be better IMO

**Comment by losipiuk** [comment]
But I am also fine with reverting the change and reintroduce it in proper shape.

**Comment by wendigo** [comment]
@losipiuk sure, I'll revert.

**Pull request closed without merging**
