### PR TITLE
Make stale action only run in Trino repo

### PR DESCRIPTION
**Pull request by colebow**
## Description

We're having the stale bot running in Trino forks when the pull request isn't submitted to the main Trino, which... is bad and awkward.

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

**Review by bitsondatadev — APPROVED** [review]
LGTM

**Comment by mosabua** [comment]
So weird that it does that by default .. but yes.. lets get that merged asap before we get warnings and notifications from tons of forks.

**Review by mosabua — APPROVED** [review]
Ship it asap

**Comment by mosabua** [comment]
Thank you @electrum

**Pull request merged**
