### PR TITLE
Expose AWS HTTP Client stats via JMX

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Review by findepi — APPROVED** [review]
Can this be tested, perhaps in `TestHiveFileSystemS3`?

**Comment by losipiuk** [comment]
> Can this be tested, perhaps in `TestHiveFileSystemS3`?

I tried and I failed. It could be testable easily if we had PT referencing S3. Then we could verify the metrics using query over `jmx.current.XXXXXX`.

**Comment by findepi** [comment]
In `TestHiveFileSystemS3` we don't have the server, and so we don't have the `jmx` connector, but maybe we can access the mbean server directly?

**Comment by losipiuk** [comment]
> In `TestHiveFileSystemS3` we don't have the server, and so we don't have the `jmx` connector, but maybe we can access the mbean server directly?

I spent more time on that. I can run the test. I see that stats callback are being called. But I cannot read JMX values as mbeans are not registered at all in tests. All the JMX mbean registration is happening via Guice automation which is not done by the test at all.
Even if I reworked the test to use Guice (which can be problematic) it is hard to write the test itself. I have have no control over pool state. I do not know how to predict expected pool size before and after test. With high probability we should expect same state as the HTTP connection would be created by other tests accessing S3, which are ran as part of this test class. Testing number of `active` HTTP connections is even more problematic as I would need to catch the HTTP request which is in-progress with an assertion.

I would say it is not worth it....

**Comment by findepi** [comment]
Thanks for investigating this.

**Review by pettyjamesm — APPROVED** [review]

**Comment by kokosing** [comment]
> . But I cannot read JMX values as mbeans are not registered at all in tests. All the JMX mbean registration is happening via Guice automation which is not done by the test at all.

That is typical issue when doing unit tests for JMX. Rule of thumb: it does not work. I have seen few examples of case where it worked but then such test has to be executed in separation as any other test can override mbeans or take precedence (not sure what actually happens). 

The only advised way for JMX tests are product tests.

**Pull request merged**
