### PR TITLE
Code cosmetics io.trino.plugin.hive.util.Statistics#createColumnToComputedStatisticsMap

### PR DESCRIPTION
**Pull request by findinpath**
Use java streams in the method createColumnToComputedStatisticsMap

### CODE REVIEW

**Review by hashhar — COMMENTED** [review]
The test is a very welcome addition but I'm not sure if the streams version helps with readability/understanding here.

I'll defer to others on it.

**Comment by findinpath** [comment]
@hashhar  I agree with your point regarding the readability.
The fact that the results were added one by one in  a mutable list got me started to do the refactor, but I also agree now, even though I've spent some time to make it work, that it is no relevant refactoring for readability sake.

**Review by hashhar — COMMENTED** [review]
@findinpath Can you revert the refactor but keep the test?

This looks good to merge otherwise.
@electrum @Praveen2112 PTAL if you want.

**Comment by findinpath** [comment]
@hashhar  sure. I think this is a good idea. The test is definitely  a useful addition in the context where the method `Statistics#fromComputedStatistics` does not have currently any unit tests.

**Review by hashhar — APPROVED** [review]
LGTM.

Thanks for adding a test.

**Review by sopel39 — APPROVED** [review]

**Pull request merged**
