### PR TITLE
Add example SQL routines for formatting topn results

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

Add example SQL routines for formatting topn results

## Additional context and related issues

Currently query does not complete when used as catalog routine - filed as #19997 

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by mosabua** [comment]
I rebased, did minor style edits, and pushed. Problem is that creating the routine works but the example query to use the routine does not finish for me locally. It just hangs there. I tried on 435 with a tarball local single node Trino. Any idea @nineinchnick ?

**Comment by nineinchnick** [comment]
I reported it a while ago as https://github.com/trinodb/trino/issues/19997 - we shouldn't merge this until it's resolved.

**Comment by mosabua** [comment]
> I reported it a while ago as #19997 - we shouldn't merge this until it's resolved.

Agreed.

**Comment by mosabua** [comment]
Update.. it works when using the routine as inline routine. However we should still hold this example until it work as catalog routine as well.

**Comment by nineinchnick** [comment]
The fix has just been merged but I think we should wait until the next release.

**Comment by mosabua** [comment]
Why @nineinchnick .. if we test it with a current build and it works nothing speaks against merging this PR right?

**Comment by nineinchnick** [comment]
Users will need 436 to be able to use a function like this

**Comment by mosabua** [comment]
Yes ... well.. by the time the docs go live, 436 will be live and the docs are for that version. We should never hold back docs because the version is needed that the docs are covering ..

**Review by mosabua — APPROVED** [review]
Looks good and works now. Merging.

**Pull request merged**
