### PR TITLE
clear error message when casting to raw parametric type

### PR DESCRIPTION
**Pull request by PennyAndWang**
Resolves : https://github.com/trinodb/trino/issues/7732
@martint ,  my test results are shown as below, please review.

屏幕快照 2021-06-16 14 17 57

### CODE REVIEW

**Comment by Praveen2112** [comment]
Thanks for working on this. Can you please take a look at test failures

**Comment by PennyAndWang** [comment]
> Thanks for working on this. Can you please take a look at test failures

OK，I am working on it.

**Comment by PennyAndWang** [comment]
> Thanks for working on this. Can you please take a look at test failures

@Praveen2112  all checks have passed.

**Comment by colebow** [comment]
:wave: @PennyAndWang - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by colebow** [comment]
Closing this one out due to inactivity, but please reopen if you would like to pick this back up.

**Pull request closed without merging**
