### PR TITLE
Revert "Update Iceberg from 1.3.1 to 1.4.1"

### PR DESCRIPTION
**Pull request by alexjo2144**
## Description

This reverts commits e6c145971f02e04d9ffeb8a1c88adbc3f5cc03d9, face6d8660e2dd2da5d9082c19c930bf353c259c. and  bb66918ce46913a9f4017a73c72aa08d8860f854.

Iceberg 1.4.x contains a silent correctness issue when concurrently committing writes to a table.

See: https://github.com/apache/iceberg/issues/9227

## Additional context and related issues

Fixes https://github.com/trinodb/trino/issues/20092

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
(x) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by alexjo2144** [comment]
FYI: @danielcweeks

**Review by findepi — APPROVED** [review]

**Review by electrum — CHANGES_REQUESTED** [review]
Can we disable retries instead? This is removing functionally that users may be relying on.

**Comment by ajantha-bhat** [comment]
or we can have a quick 1.4.3 release which contains that fix and bump to that version. 

cc: @nastra, @Fokko WDYT?

**Comment by findinpath** [comment]
FWIW https://github.com/apache/iceberg/pull/9230 has been merged a few hours ago.

From @danielcweeks in the context of dealing with this silent correctness issue

>  ... we will probably do a quick round for 1.4.3 release...

@danielcweeks when do you plan to do the release

**Comment by nastra** [comment]
@findinpath I'll do an 1.4.3 RC today and then the community has 3 days to vote on the release

**Comment by findepi** [comment]
> Can we disable retries instead? This is removing functionally that users may be relying on.

What functionality is being removed? You mean for Nessie writes?

Disabling retries would also remove existing functionality that users rely on.

If we can't revert, than rolling forward is the only way that doesn't remove anything.

**Comment by alexjo2144** [comment]
If we're not planning on releasing Trino in the next week or so then waiting for 1.4.3 sounds like the way forward to me. As far as this PR goes, I was considering the features I was reverting here less important than support for concurrent writes.

**Comment by electrum** [comment]
This is removing the ability to register and unregister tables. Concurrent writes have a workaround on the user side.

**Pull request closed without merging**
