### PR TITLE
Revert "Replace custom air.main.basedir property with built-in session.rootDirectory"

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

Reverts commit ff1cddbd31d70610952922b19c13bd957e33f00f from trinodb/trino#20486

It doesn't work with `mvnd`:
```
[ERROR] Failed to execute goal org.gaul:modernizer-maven-plugin:2.7.0:modernizer (modernizer) on project trino-root: Error opening violation file: ${session.rootDirectory}/.mvn/modernizer/violations.xml: ${session.rootDirectory}/.mvn/modernizer/violations.xm
l (No such file or directory) -> [Help 1]
```

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by wendigo** [comment]
cc @cstamas

**Review by wendigo — APPROVED** [review]

**Comment by wendigo** [comment]
Reported https://github.com/apache/maven-mvnd/issues/910

**Comment by hashhar** [comment]
Please add context to revert commit message.

**Comment by wendigo** [comment]
Pushed to master with amended commit message: https://github.com/trinodb/trino/commit/b81b7f264471d96b17fe1c798164884a2a5e0d1f

**Comment by findepi** [comment]
two breakages in few days (https://github.com/trinodb/trino/pull/20762)
Maybe we should test mvnd on CI :)

**Pull request closed without merging**
