### PR TITLE
Allow fetching relation names with their types (v2)

### PR DESCRIPTION
**Pull request by findepi**
This reduces number of Glue calls when reading from
`information_schema.tables` or `system.jdbc.tables`.

Like https://github.com/trinodb/trino/pull/19832 but avoids contentious rename (https://github.com/trinodb/trino/pull/19832#discussion_r1399768605).

### CODE REVIEW

**Review by losipiuk — APPROVED** [review]

**Comment by findepi** [comment]
CI https://github.com/trinodb/trino/issues/19747

**Comment by findepi** [comment]
CI https://github.com/trinodb/trino/issues/16315

**Comment by findepi** [comment]
@losipiuk thank you for your review!

I noticed there was a would-be regression for Iceberg, so I added a preparatory commit (currently first) with a test case, that later shows a regression and later improvement. @losipiuk please take another look

Now this is an improvement for `information_schema.tables` and `system.jdbc.tables` for Iceberg with Glue as well.
This is however a regression for Iceberg and Hive with HMS (instead of 2 listing calls we do 3).
I think the Glue improvement is more important from performance sensitivity perspective, and I think we should go ahead with the change.

**Comment by losipiuk** [comment]
> I think the Glue improvement is more important from performance sensitivity perspective, and I think we should go ahead with the change.

We chatted offline - and even though this is not an universal truth - it makes sense. The important point in the discussion was that HMS protocol is not suited for large deployments anyway; each call to HMS is bounded by request-timeout anyway so extra time is bounded.

**Review by losipiuk — APPROVED** [review]

**Comment by findepi** [comment]
CI https://github.com/trinodb/trino/issues/19888

**Comment by findepi** [comment]
CI https://github.com/trinodb/trino/issues/19242

**Comment by mosabua** [comment]
Do we need a release note for this .. something about performance improvement for Glue access in Iceberg, Delta Lake and Hive/

**Comment by mosabua** [comment]
I am going to assume we dont need release notes entry.

**Pull request merged**
