### PR TITLE
Upgrade maven to 3.9.0

### PR DESCRIPTION
**Pull request by wendigo**
On top of the https://github.com/trinodb/trino/pull/12661

Maven 3.9.0 release notes: https://maven.apache.org/docs/3.9.0/release-notes.html

### CODE REVIEW

**Review by nineinchnick — APPROVED** [review]

**Comment by martint** [comment]
There seems to be a known performance issue with Maven 3.9.0. We should make sure Trino is not affected: https://issues.apache.org/jira/browse/MNG-7677

**Comment by wendigo** [comment]
@martint I'm gonna check those numbers for us

**Comment by wendigo** [comment]
Before: `Total time:  04:08 min (Wall Clock)`
After: `Total time: Total time:  04:04 min (Wall Clock)`

It's comparable I'd say.

**Comment by wendigo** [comment]
Replaced by https://github.com/trinodb/trino/pull/16777

**Pull request closed without merging**
