### PR TITLE
Reduce Hive ACID/Transactional tables test repetitions on CI

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Comment by findepi** [comment]
cc @trinodb/maintainers @nineinchnick @findinpath i hope this will make the CI faster.
There are other duplications which still wait to be discovered and fixed.

**Review by nineinchnick — APPROVED** [review]

**Review by wendigo — APPROVED** [review]

**Comment by findepi** [comment]
relates to https://github.com/trinodb/trino/issues/15096

**Review by findinpath — APPROVED** [review]
LGTM

**Review by djsstarburst — APPROVED** [review]
This looked good to me.  It's always great to remove test runs that add no value.

**Pull request merged**
