### PR TITLE
Fix style in Kudu documentation

### LINKED ISSUE #11380: Fix style in Kudu documentation
Screen Shot 2022-03-09 at 9 58 36

- `-` becomes `・` : We can fix by using two hyphen  `--`
- `1(1,2)`: It looks little awkward

### PR DESCRIPTION
**Pull request by dchvn**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

Change a fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Document

> How would you describe this change to a non-technical end user or system administrator?

Fix style in Kudu documentation

## Related issues, pull requests, and links
* Fixes #11380

## Documentation

( ) No documentation is needed.
(x) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

### CODE REVIEW

**Comment by dchvn** [comment]
@ebyhr Can you take a look if you have time? Thank you.

**Review by ebyhr — APPROVED** [review]
Thanks. Let's fix only `\-` and not touch footnotes until we find better solution.

**Comment by dchvn** [comment]
Updated! Thank you @ebyhr !

**Comment by ebyhr** [comment]
@dchvn Could you squash commits into one?

**Comment by dchvn** [comment]
Updated! Thanks @ebyhr

**Comment by ebyhr** [comment]
Merged, thanks!

**Pull request merged**
