### PR TITLE
Fix build error and link in PostgreSQL docs

### PR DESCRIPTION
**Pull request by colebow**
## Description

Fix the build error in docs. Double underscore makes these anonymous, so they can share the same name. Technically also works as long as the links are the same, but let's just solve the problem twice. 😄 

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by mosabua — APPROVED** [review]

**Review by jhlodin — APPROVED** [review]
LGTM, thanks for catching

**Comment by findepi** [comment]
Looks like we merged https://github.com/trinodb/trino/pull/14240  failing the build.

**Review by findepi — APPROVED** [review]
Confirmed `docs/build` is failing locally on current master and is not failing as fast after the change. (it somehow froze though, maybe that's an docker image arch issue)

@martint please merge once the CI passes.

**Comment by martint** [comment]
Tested locally

**Pull request merged**
