### PR TITLE
Run BigQuery Arrow and FTE tests in a separated profile

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Separate profile for BigQuery FTE tests to fix timeout issue on CI. 
e.g. https://github.com/trinodb/trino/actions/runs/6882906460/job/18722457149

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Review by hashhar — APPROVED** [review]

**Comment by ebyhr** [comment]
`ci / test (plugin/trino-bigquery) (pull_request)` still takes 50 minutes... We may want to merge arrow and fte into one. 

Screenshot 2023-11-16 at 15 06 15

**Comment by hashhar** [comment]
merging those two makes sense.

Let me check if BigQueryInstanceCleaner has been leaving cruft behind, 50m seems like a lot.

**Comment by ebyhr** [comment]
@hashhar It seems we separated arrow profile for adding additional JVM options. Do we still want to merge those profile?

**Comment by hashhar** [comment]
We can as long as we have at least one profile with default JVM.

**Review by wendigo — APPROVED** [review]

**Pull request merged**
