### PR TITLE
Apply overrides from provided config when running SuiteDescribe

### PR DESCRIPTION
**Pull request by hashhar**

### CODE REVIEW

**Review by findepi — APPROVED** [review]

**Comment by hashhar** [comment]
To observe the difference try to run `ptl suite describe --suite suite-1` vs `ptl suite describe --suite suite-1 --config config-cdh5`.

Even though ConfigCdh5 excludes the group `skip_on_cdh5` it doesn't show up in the describe output because the config overrides from config-cdh5 aren't applied during SuiteDescribe.

**Comment by hashhar** [comment]
Force-pushed with better commit message.

**Review by wendigo — APPROVED** [review]
👍🏼

**Comment by hashhar** [comment]
test-other-modules failed pulling Oracle's Docker images during a test setup. Will look at adding retries.

the suite-8 failure seems concerning (but is unrelated and not present on `master`)

```
tests               | 2021-09-01 20:35:46 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveTransactionalTable.testPartitionedInsertAndRowLevelDelete [TRINO, HIVE] (Groups: hive_transactional) took 3.8 seconds
tests               | 2021-09-01 20:35:46 SEVERE: Failure cause:
tests               | java.lang.AssertionError: [onTrino] Could not find rows:
tests               | [40]
tests               | 
tests               | actual rows:
tests               | [60]
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.verifySelect(TestHiveTransactionalTable.java:1930)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.verifySelectForTrinoAndHive(TestHiveTransactionalTable.java:1920)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.lambda$testPartitionedInsertAndRowLevelDelete$17(TestHiveTransactionalTable.java:779)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.withTemporaryTable(TestHiveTransactionalTable.java:1632)
tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.testPartitionedInsertAndRowLevelDelete(TestHiveTransactionalTable.java:767)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by findepi** [comment]
@hashhar sounds very concerning. Note that this stacktrace you quoted occurred even before any invocation with Hive, only `onTrino` queries involved.

FWIW i run this
```
    @Test(groups = HIVE_TRANSACTIONAL, timeOut = TEST_TIMEOUT, invocationCount = 100, threadPoolSize = 4)
    public void testPartitionedInsertAndRowLevelDelete()
    {
        HiveOrTrino inserter = HiveOrTrino.TRINO;
        HiveOrTrino deleter = HiveOrTrino.TRINO;=
        withTemporaryTable("partitioned_row_level_delete_" + randomTableSuffix(), true, true, NONE, tableName -> {
            .....
```

locally.
Runs 0-89 succeeded and then i got a bunch of weird failures which could potentially be explained by HS2 crashing.

In any case, it did not reproduce the problem.

**Comment by hashhar** [comment]
I can't reproduce that locally either. I'll create an issue so that we don't forget and can investigate further.

Merging this.

**Pull request merged**
