### PR TITLE
added support for querying tables with upper case character names

### PR DESCRIPTION
**Pull request by dheerajkulakarni**
This PR addresses https://github.com/trinodb/trino/issues/6850

### CODE REVIEW

**Review by Praveen2112 — COMMENTED** [review]
Thanks for working on this. Can you please add test cases for this

**Review by hashhar — CHANGES_REQUESTED** [review]
The change itself looks good. But please add some tests to make sure a regression isn't introduced in the future. Take a look at `TestPostgreSqlCaseInsensitiveMapping` for inspiration.

**Comment by dheerajkulakarni** [comment]
Sure @Praveen2112 @hashhar as you suggested will try to add some test cases around this!

**Comment by dheerajkulakarni** [comment]
Hey @findepi @hashhar, not sure what just happened in here, I am not able to see my commit. Can I raise another PR?

**Comment by findepi** [comment]
> @findepi findepi merged commit 5638d2d into trinodb:master 4 hours ago

I don't think i understand what happened here.  I don't think I merged this PR, and I surely had no intention to.
My wild guess is that you reset your `master` branch in your repo to the `master` branch with from Trino main repo, but i may be wrong.

Anyway, since no code has been actually merged (0 commits), yes, please do create a new PR

**Comment by findepi** [comment]
BTW @dheerajkulakarni  are you on [our slack](https://trino.io/slack.html) already?
please join the `#dev` channel

**Pull request merged**
