### PR TITLE
Test using snappy as default in hive

### PR DESCRIPTION
**Pull request by raunaqmorarka**
## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by sopel39** [comment]
Why not use `ZSTD` as in Iceberg?

**Comment by raunaqmorarka** [comment]
> Why not use `ZSTD` as in Iceberg?

ZSTD wasn't working with Apache Hive as seen in https://github.com/trinodb/trino/pull/12361#issuecomment-1539656051

**Comment by findepi** [comment]
i hope it's not the case that some ancient hive version prevents us from using the best defaults possible in modern world.

**Comment by raunaqmorarka** [comment]
> i hope it's not the case that some ancient hive version prevents us from using the best defaults possible in modern world.

The version of Apache Hive that we test with (regardless of whether it is ancient or not) doesn't work with ZSTD.
We can either choose to ignore these specific test failures or find a different version of Hive to test against where this works.
IMO, not worth the effort since users can easily change default compression for their environment and iceberg has the better default already.

**Pull request closed without merging**
