### PR TITLE
Error Prone tweaks

### PR DESCRIPTION
**Pull request by ksobolew**

### CODE REVIEW

**Review by kokosing — APPROVED** [review]

**Comment by kokosing** [comment]
Let me know when CI passes, so I can merge it.

**Review by findepi — APPROVED** [review]

**Comment by ksobolew** [comment]
` ci / error-prone-checks (pull_request) Successful in 21m `

There was some weird thing in `ci / maven-checks (17) (pull_request)`, but that's not relevant.

**Comment by kokosing** [comment]
Please report a flaky test issue.

**Comment by kokosing** [comment]
Thanks!

**Comment by ksobolew** [comment]
> Please report a flaky test issue.

I think this was a glitch in the environment, does this qualify as a flaky test?

```
🐢 Validating trino:369-SNAPSHOT-amd64 on platform linux/amd64...
🚨 Too many retries waiting for Trino to start
Error response from daemon: No such container: 59f4b62fecaee5268410428097f0a231593223e060419324898fe438c4796750
Error response from daemon: No such container: 59f4b62fecaee5268410428097f0a231593223e060419324898fe438c4796750
Error: Process completed with exit code 1.
```

**Comment by kokosing** [comment]
Anything that randomly happens and makes the build red should be reported IMO

**Pull request merged**
