### PR TITLE
Add support for describing table function invocation

### PR DESCRIPTION
**Pull request by wendigo**
This adds support for describing PTF invocations:

```
❯ ./client/trino-cli/target/trino-cli-392-SNAPSHOT-executable.jar
trino> use postgresql.tpch;
USE
trino:tpch> DESCRIBE TABLE(system.query(query => 'SELECT NOW()'));
 Column |            Type             | Extra | Comment
--------+-----------------------------+-------+---------
 now    | timestamp(6) with time zone | NULL  | NULL
(1 row)

trino:tpch> DESCRIBE TABLE(system.query(query => 'SELECT 1 AS _col2'));
 Column |  Type   | Extra | Comment
--------+---------+-------+---------
 _col2  | integer | NULL  | NULL
(1 row)

trino:tpch> DESCRIBE TABLE(system.query(query => 'SELECT name AS t2, CAST(nationkey  AS DECIMAL(10, 2)) FROM tpch.nation'));
  Column   |     Type      | Extra | Comment
-----------+---------------+-------+---------
 t2        | varchar(25)   | NULL  | NULL
 nationkey | decimal(10,2) | NULL  | NULL
(2 rows)

trino:tpch> DESCRIBE TABLE(system.query(query => 'SELECT name FROM tpch.nation'));
 Column |    Type     | Extra | Comment
--------+-------------+-------+---------
 name   | varchar(25) | NULL  | NULL
(1 row)

trino:tpch> DESCRIBE TABLE(system.query(query => 'SELECT * FROM tpch.nation'));
  Column   |     Type     | Extra | Comment
-----------+--------------+-------+---------
 nationkey | bigint       | NULL  | NULL
 name      | varchar(25)  | NULL  | NULL
 regionkey | bigint       | NULL  | NULL
 comment   | varchar(152) | NULL  | NULL
(4 rows)
```

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

> How would you describe this change to a non-technical end user or system administrator?

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by findepi** [comment]
> trino:tpch> DESCRIBE TABLE(system.query(query => 'SELECT NOW()'));

Rather than something like this I would rather want to add ability to "describe" output of any query.
Perhaps `DESCRIBE (....)`, similar to what we did with SHOW STATS.

However, before we discuss different syntactic options, @wendigo can you please describe the problem you're trying to solve?

**Comment by wendigo** [comment]
i.e. Spark has a similiar feature for describing queries: https://spark.apache.org/docs/3.0.0-preview/sql-ref-syntax-aux-describe-query.html

**Comment by findepi** [comment]
> While working with the query PTF I found it convenient to be able to output the descriptor type in a way that the engine sees that invocation.

I think the developer use-case is already satisfied.

See https://trinodb.slack.com/archives/CP1MUNEUX/p1657120850360139 thread and @findepi 's comment there in particular

> you probable can do PREPARE https://trino.io/docs/current/sql/prepare.html + DESCRIBE https://trino.io/docs/current/sql/describe-output.html to get columns of a PTF.

**Comment by wendigo** [comment]
@findepi if this is enough then I'm closing this PR

**Comment by findepi** [comment]
discussion moved to https://github.com/trinodb/trino/issues/13473

**Pull request closed without merging**
