### PR TITLE
Pre-fetching of parquet data pages

### PR DESCRIPTION
**Pull request by samarthjain**
While working on in the iceberg-spark vectorized read path, I noticed in the profiling that significant amount of CPU time is spent on decompressing the Parquet data pages. Implementing pre-fetching helped boost the JMH measured ops/second by up to 60%. I think a similar opportunity exists in the presto parquet read path where in the next data page to be read can be prefetched eagerly using a thread pool. Parking my patch here to see if it didn't break any tests. If tests are green, I would like to figure out what benchmarks I could possibly run or build to measure the performance impact of this change.

### CODE REVIEW

**Comment by findepi** [comment]
No doubt that delegating some work to a thread to do it earlier will boost single reader performance.
You can use an otherwise underutilized core to improve throughput.
However, for a typical larger query, there should be multiple concurrent readers, so hopefully more (or all)
cores are utilized. This observation is an important assumption in the current code. For example, it is 
the justification for using blocking IO. 

If we want to remove this assumption and change the design  principles -- I am OK.
But i think we should have a more thorough plan. For example: we should not only introduce threading,
but also should think about some shared thread pools (eg decompression thread pool, or rather:
a separate IO thread pool and "CPU" thread pool). We should also change defaults for some tuning
knobs. E.g. `task.max-worker-threads` is currently set to "2 * cores" and should become "1 * cores".

**Comment by sopel39** [comment]
I will also add that one doesn't know if entire content of next page will be read. In Presto we use lazy reads. This means that at runtime we evaluate filter conditions. For example, we might read one block of a page and filter rest of the blocks because none of the rows matched filter condition

**Comment by samarthjain** [comment]
> No doubt that delegating some work to a thread to do it earlier will boost single reader performance.
> You can use an otherwise underutilized core to improve throughput.
> However, for a typical larger query, there should be multiple concurrent readers, so hopefully more (or all)
> cores are utilized. This observation is an important assumption in the current code. For example, it is
> the justification for using blocking IO.
> 
> If we want to remove this assumption and change the design principles -- I am OK.
> But i think we should have a more thorough plan. For example: we should not only introduce threading,
> but also should think about some shared thread pools (eg decompression thread pool, or rather:
> a separate IO thread pool and "CPU" thread pool). We should also change defaults for some tuning
> knobs. E.g. `task.max-worker-threads` is currently set to "2 * cores" and should become "1 * cores".

Having a dedicated thread pool for CPU bound tasks like decompression makes sense to me. But then, I am sure there are various operators that are primarily doing CPU bound work too (filter, some aggregators, etc.). Does that mean the CPU thread pool is the default pool with a dedicated thread pool for IO? 
One point I would like to make here is that decompression is generally performed within the scan operator which I would generally assume is one of the first operators in the pipeline. So while the rest of the pipeline is working on the current page, the next page will concurrently be decompressed. Whether the extra threads doing asynchronous decompression will take away CPU from the operators is debatable. Maybe longer the pipeline chain, the effect of CPU taken away by the decompressing thread  becomes less noticeable?

**Comment by samarthjain** [comment]
> I will also add that one doesn't know if entire content of next page will be read. In Presto we use lazy reads. This means that at runtime we evaluate filter conditions. For example, we might read one block of a page and filter rest of the blocks because none of the rows matched filter condition

I haven't looked at how presto parquet read path in detail. In some other read paths I have seen, it is generally decided to skip the entire row group based on row group metrics and/or dictionary metrics. 
If we do still decide to go ahead with the current pre-fetch approach, then yes, in worst case, we possibly could be wasting resources on reading an extra page per reader.

**Comment by colebow** [comment]
:wave: @samarthjain - this PR has drawbacks that don’t align with our preferred approach, so we’re not going to proceed with this implementation. If you'd like to continue the discussion on this at any point in the future, feel free to re-open and chime in.

**Pull request closed without merging**
