### PR TITLE
Rewrite LIKE patterns to string matching

### PR DESCRIPTION
**Pull request by takezoe**
Improve `LIKE` predicates performance by rewriting to UDFs which don't use a regular expression.

- Add `ENDS_WITH` and `CONTAINS` functions
- Rewrite `LIKE` predicates to `STARTS_WITH`, `ENDS_WITH` or `CONTAINS` if possible

### CODE REVIEW

**Comment by findepi** [comment]
`LIKE` has special treatment in `DomainTranslator`. 
Currently we do not have to add same treatment for `starts_with`
because `DesugarLikeRewriter` is called pretty much at the end
of the optimization process.  However, it doesn't have to be always 
so. @martint should we have similar support for `starts_with` in
`DomainTranslator`?

**Comment by takezoe** [comment]
I didn't know what `DomainTranslator` is doing. However, after reading it, I think there is no reason to not apply the same domain translation to `STARTS_WITH`. I created another pull request for that: https://github.com/prestosql/presto/pull/4669

By the way, if Presto has `CONTAINS` (or `MATCHES` function which can compare the specified part of string with another string), we will be able to rewrite more patterns of `LIKE` predicates to not use regular expressions.

**Comment by martint** [comment]
>  @martint should we have similar support for starts_with in DomainTranslator?

Yes, that makes sense (for now -- eventually we should be able to get rid of DomainTranslator or drastically reduce the scope of what it does and where it's used).

**Comment by takezoe** [comment]
Is there a possibility to adopt this kind of optimization? If this optimization has a possibility to be adopted  but adding new UDFs is not an ideal solution, I would suggest two options:

1. Optimize cases where can be rewritten to `STARTS_WITH`
2. Introduce a hidden UDF for this optimization

**Comment by ubyyj** [comment]
hi, what's the reason we haven't applied the optimzation in DesugarLikeRewriter? I think it would help a lot.

**Comment by ubyyj** [comment]
the rewrite could also happen in ExpressionInterpreter.visitLikePredicate()

**Comment by martint** [comment]
FYI, as part of https://github.com/trinodb/trino/issues/13184, we're trying to remove usage of LikePredicate within the optimizer, as well as all desugaring rules. Those will be part of the initial translation of SQL query AST -> Plan IR.

**Comment by colebow** [comment]
@martint is it safe to say we're not going with this approach and can close this PR out?

**Comment by martint** [comment]
It's possible some of the rewrites proposed here are still relevant, but they will need to be reimplemented to match the function calls for the like matching functions instead of the Like expression node, as that's going away in the planner very soon (as part of https://github.com/trinodb/trino/pull/13961)

**Comment by takezoe** [comment]
Sounds like it's better to raise a fresh pull request after #13961. I would close this pull request for now.

**Pull request closed without merging**
