### PR TITLE
Support JOIN pushdown for relational operators on varchar in PostgreSQL connector

### PR DESCRIPTION
**Pull request by takezoe**
Follow-up to https://github.com/trinodb/trino/pull/9746

### CODE REVIEW

**Comment by hashhar** [comment]
FYI @wendigo .

**Comment by hashhar** [comment]
@takezoe See also https://github.com/trinodb/trino/pull/10059 for an alternative extension point which looks more flexible to me.

**Comment by takezoe** [comment]
Oh, I see. Then, I would close this and wait for #10059.

**Comment by hashhar** [comment]
#10059 only adds the extension point. There needs to be another PR built on top of it which uses the new functionality. I believe @wendigo was working on it.

**Comment by wendigo** [comment]
I've implemented join pushdown for char types in PostgreSQL in https://github.com/trinodb/trino/pull/10059

**Pull request closed without merging**
