### PR TITLE
Fix BigQuery predicate pushdown for varchars with backslashes or newlines

### PR DESCRIPTION
**Pull request by findepi**
Fixes tests failing on master since https://github.com/trinodb/trino/pull/14125 (past 6 days)

Fixes https://github.com/trinodb/trino/issues/7900 
Follows https://github.com/trinodb/trino/pull/7869

### CODE REVIEW

**Comment by findepi** [comment]
I don't think it's readonable to test all possible BigQuery sequences, because we actually don't generate them.
We escape the string so that there are no (or -- as few as possible) sequences.

**Comment by findepi** [comment]
CI

```
Error:  io.trino.plugin.bigquery.TestBigQueryConnectorTest.testInsertUnicode  Time elapsed: 1.282 s  <<< FAILURE!
io.trino.testing.QueryFailedException: The service is currently unavailable.
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:123)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:480)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:323)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:318)
	at io.trino.testing.BaseConnectorTest.testInsertUnicode(BaseConnectorTest.java:2911)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: SQL: INSERT INTO test_insert_unicode_1fstiydkrw(test) VALUES 'aa', 'bé'
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:483)
		... 17 more
Caused by: com.google.cloud.bigquery.BigQueryException: The service is currently unavailable.
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.insertAll(HttpBigQueryRpc.java:494)
	at com.google.cloud.bigquery.BigQueryImpl.insertAll(BigQueryImpl.java:1074)
	at io.trino.plugin.bigquery.BigQueryClient.insert(BigQueryClient.java:301)
	at io.trino.plugin.bigquery.BigQueryPageSink.appendPage(BigQueryPageSink.java:65)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:257)
	at io.trino.operator.Driver.processInternal(Driver.java:416)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:736)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:515)
	at io.trino.$gen.Trino_testversion____20220922_135336_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 503 Service Unavailable
POST https://www.googleapis.com/bigquery/v2/projects/sep-bq-cicd/datasets/tpch/tables/test_insert_unicode_1fstiydkrw/insertAll?prettyPrint=false
{
  "code" : 503,
  "errors" : [ {
    "domain" : "global",
    "message" : "The service is currently unavailable.",
    "reason" : "backendError"
  } ],
  "message" : "The service is currently unavailable.",
  "status" : "UNAVAILABLE"
}
```

**Comment by hashhar** [comment]
>  don't think it's readonable to test all possible BigQuery sequences, because we actually don't generate them.
> We escape the string so that there are no (or -- as few as possible) sequences.

That's what I meant by we should be fine as long as we escape quotes and backslash properly.

**Review by hashhar — APPROVED** [review]
Thanks.

**Comment by findepi** [comment]
`pt (hdp3, suite-azure, )`

`testing/bin/ptl` failed to print the project version due to maven central communication issue

`test (plugin/trino-iceberg)`

looks like failure is related

**Comment by findepi** [comment]
(just rebased)

**Comment by findepi** [comment]
`BaseIcebergConnectorTest#testSplitPruningForFilterOnNonPartitionColumn` piggy-backs on `testDataMappingSmokeTestDataProvider` and requires values to be shorter than 16 characters, since ORC and Parquet predicates have min/max truncated in Iceberg.
I've reduce the length

cc @alexjo2144

**Review by hashhar — APPROVED** [review]

**Comment by findepi** [comment]
CI https://github.com/trinodb/trino/issues/14035

**Pull request merged**
