### PR TITLE
Update to Avro 1.10.2

### PR DESCRIPTION
**Pull request by electrum**
Depends on https://github.com/trinodb/trino-hive-apache/pull/30

### CODE REVIEW

**Comment by jirassimok** [comment]
This seems to work. The reproducible failure I had relating to outdated Avro schemas no longer fails with this change.

**Comment by hashhar** [comment]
`TestAvroSymlinkInputFormat` is failing. Looks related.

**Comment by jirassimok** [comment]
Running locally, I didn't get that error; it might be a flake.

**Comment by hashhar** [comment]
Yeah, it's a flake indeed. will keep an eye if this repeats (couldn't get it to fail locally across 10 runs).

**Review by hashhar — APPROVED** [review]

**Comment by electrum** [comment]
Seems suspicious that the failing test would be Avro related. I'll run again just to be sure.

**Comment by electrum** [comment]
Thanks @hashhar for adding the label to run the tests. I forgot about that.

**Pull request merged**
