### PR TITLE
Upgrade Clickhouse JDBC driver to 0.2.6 

### LINKED ISSUE #9300: Flaky test setup TestClickHouseConnectorTest.init
https://github.com/trinodb/trino/runs/3650369157

```
Error:  io.trino.plugin.clickhouse.TestClickHouseConnectorTest.init  Time elapsed: 32.713 s  <<< FAILURE!
java.lang.RuntimeException: Failed to insert data: ClickHouse exception, code: 1002, host: localhost, port: 49159; localhost:49159 failed to respond
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:119)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:476)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:339)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:331)
	at io.trino.testing.QueryAssertions.copyTpchTables(QueryAssertions.java:323)
	at io.trino.plugin.clickhouse.ClickHouseQueryRunner.createClickHouseQueryRunner(ClickHouseQueryRunner.java:68)
	at io.trino.plugin.clickhouse.TestClickHouseConnectorTest.createQueryRunner(TestClickHouseConnectorTest.java:50)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE IF NOT EXISTS customer AS SELECT * FROM tpch.tiny.customer
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:479)
		... 19 more
Caused by: io.trino.spi.TrinoException: Failed to insert data: ClickHouse exception, code: 1002, host: localhost, port: 49159; localhost:49159 failed to respond
	at io.trino.plugin.jdbc.JdbcPageSink.finish(JdbcPageSink.java:193)
	at io.trino.operator.TableWriterOperator.finish(TableWriterOperator.java:214)
	at io.trino.operator.Driver.processInternal(Driver.java:405)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_testversion____20210920_102607_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: localhost, port: 49159; localhost:49159 failed to respond
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:91)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:24)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:855)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:824)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:817)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:335)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:320)
	at io.trino.plugin.jdbc.JdbcPageSink.finish(JdbcPageSink.java:177)
	... 12 more
Caused by: org.apache.http.NoHttpResponseException: localhost:49159 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:849)
	... 17 more
```

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #9300

### CODE REVIEW

**Comment by hashhar** [comment]
The original failure seems solved but a new one has popped up. 🙁

**Comment by ebyhr** [comment]
Thank you for your confirmation. I'm looking into now. 
https://github.com/trinodb/trino/runs/3689119185

```bash
2021-09-23T16:12:53.2323962Z 2021-09-23T11:12:53.193-0500 SEVERE Error processing Split 20210923_161250_00645_ynqag.1.0-0 io.trino.plugin.jdbc.JdbcSplit@15ffac25 (start = 333540.32125, wall = 12 ms, cpu = 0 ms, wait = 0 ms, calls = 1): JDBC_ERROR: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: localhost, port: 49156; Port 9000 is for clickhouse-client program.
2021-09-23T16:12:53.2325622Z You must use port 8123 for HTTP.
2021-09-23T16:12:53.2325864Z 
2021-09-23T16:12:53.2327378Z io.trino.spi.TrinoException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: localhost, port: 49156; Port 9000 is for clickhouse-client program.
2021-09-23T16:12:53.2328687Z You must use port 8123 for HTTP.
2021-09-23T16:12:53.2328932Z 
2021-09-23T16:12:53.2329912Z 	at io.trino.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:299)
2021-09-23T16:12:53.2331298Z 	at io.trino.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:113)
2021-09-23T16:12:53.2332642Z 	at io.trino.plugin.jdbc.JdbcRecordSet.cursor(JdbcRecordSet.java:63)
2021-09-23T16:12:53.2333855Z 	at io.trino.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
2021-09-23T16:12:53.2336205Z 	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
2021-09-23T16:12:53.2338017Z 	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
2021-09-23T16:12:53.2339771Z 	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:267)
2021-09-23T16:12:53.2341811Z 	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:195)
2021-09-23T16:12:53.2343404Z 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
2021-09-23T16:12:53.2344706Z 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2021-09-23T16:12:53.2346009Z 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
2021-09-23T16:12:53.2347308Z 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2021-09-23T16:12:53.2348594Z 	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
2021-09-23T16:12:53.2349895Z 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2021-09-23T16:12:53.2351768Z 	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
2021-09-23T16:12:53.2353388Z 	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
2021-09-23T16:12:53.2354997Z 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2021-09-23T16:12:53.2356952Z 	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
2021-09-23T16:12:53.2358377Z 	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
2021-09-23T16:12:53.2359775Z 	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
2021-09-23T16:12:53.2361729Z 	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:151)
2021-09-23T16:12:53.2363441Z 	at io.trino.operator.Driver.processInternal(Driver.java:387)
2021-09-23T16:12:53.2364342Z 	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
2021-09-23T16:12:53.2365204Z 	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
2021-09-23T16:12:53.2366073Z 	at io.trino.operator.Driver.processFor(Driver.java:284)
2021-09-23T16:12:53.2367181Z 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
2021-09-23T16:12:53.2368843Z 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
2021-09-23T16:12:53.2370381Z 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
2021-09-23T16:12:53.2371280Z 	at io.trino.$gen.Trino_testversion____20210923_161131_1.run(Unknown Source)
2021-09-23T16:12:53.2372358Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-09-23T16:12:53.2614893Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-09-23T16:12:53.2616026Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-09-23T16:12:53.2619923Z Caused by: java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: localhost, port: 49156; Port 9000 is for clickhouse-client program.
2021-09-23T16:12:53.2621863Z You must use port 8123 for HTTP.
2021-09-23T16:12:53.2622289Z 
2021-09-23T16:12:53.2623432Z 	at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:99)
2021-09-23T16:12:53.2625168Z 	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:80)
2021-09-23T16:12:53.2626596Z 	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:55)
2021-09-23T16:12:53.2627892Z 	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:47)
2021-09-23T16:12:53.2629502Z 	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:29)
2021-09-23T16:12:53.2631543Z 	at io.trino.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:65)
2021-09-23T16:12:53.2634165Z 	at io.trino.plugin.clickhouse.ClickHouseConnectionFactory$1.<init>(ClickHouseConnectionFactory.java:44)
2021-09-23T16:12:53.2636621Z 	at io.trino.plugin.clickhouse.ClickHouseConnectionFactory.openConnection(ClickHouseConnectionFactory.java:42)
2021-09-23T16:12:53.2639784Z 	at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
2021-09-23T16:12:53.2641894Z 	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
2021-09-23T16:12:53.2644565Z 	at io.trino.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
2021-09-23T16:12:53.2646873Z 	at io.trino.plugin.jdbc.LazyConnectionFactory.lambda$openConnection$0(LazyConnectionFactory.java:45)
2021-09-23T16:12:53.2648579Z 	at io.trino.plugin.jdbc.LazyConnectionFactory$LazyConnection.getDelegate(LazyConnectionFactory.java:76)
2021-09-23T16:12:53.2650298Z 	at io.trino.plugin.jdbc.ForwardingConnection.setReadOnly(ForwardingConnection.java:124)
2021-09-23T16:12:53.2652007Z 	at io.trino.plugin.jdbc.BaseJdbcClient.getConnection(BaseJdbcClient.java:413)
2021-09-23T16:12:53.2653552Z 	at io.trino.plugin.jdbc.ForwardingJdbcClient.getConnection(ForwardingJdbcClient.java:131)
2021-09-23T16:12:53.2655600Z 	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getConnection$10(StatisticsAwareJdbcClient.java:151)
2021-09-23T16:12:53.2657143Z 	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
2021-09-23T16:12:53.2735931Z 	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getConnection(StatisticsAwareJdbcClient.java:151)
2021-09-23T16:12:53.2737793Z 	at io.trino.plugin.jdbc.CachingJdbcClient.getConnection(CachingJdbcClient.java:201)
2021-09-23T16:12:53.2739312Z 	at io.trino.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:79)
2021-09-23T16:12:53.2740789Z 	... 30 more
2021-09-23T16:12:53.2742773Z Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: localhost, port: 49156; Port 9000 is for clickhouse-client program.
2021-09-23T16:12:53.2744685Z You must use port 8123 for HTTP.
2021-09-23T16:12:53.2744930Z 
2021-09-23T16:12:53.2746326Z 	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:91)
2021-09-23T16:12:53.2748778Z 	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
2021-09-23T16:12:53.2751108Z 	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
2021-09-23T16:12:53.2753402Z 	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1046)
2021-09-23T16:12:53.2755544Z 	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:737)
2021-09-23T16:12:53.2757503Z 	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:196)
2021-09-23T16:12:53.2759903Z 	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:166)
2021-09-23T16:12:53.2761820Z 	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:161)
2021-09-23T16:12:53.2763711Z 	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:156)
2021-09-23T16:12:53.2765707Z 	at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:94)
2021-09-23T16:12:53.2766836Z 	... 50 more
2021-09-23T16:12:53.2767596Z Caused by: java.lang.Throwable: Port 9000 is for clickhouse-client program.
2021-09-23T16:12:53.2814602Z You must use port 8123 for HTTP.
2021-09-23T16:12:53.2814868Z 
2021-09-23T16:12:53.2816150Z 	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
2021-09-23T16:12:53.2817683Z 	... 58 more
```

**Comment by ebyhr** [comment]
@wgzhao Do you have any idea about the above error?

**Comment by wgzhao** [comment]
uses error port？
jdbc driver uses port 8123 instead of 9000

**Comment by ebyhr** [comment]
@wgzhao We are connecting to 8123 via port mapping in testcontainers.

**Comment by wgzhao** [comment]
>2021-09-23T16:12:53.2323962Z 2021-09-23T11:12:53.193-0500 SEVERE Error processing Split 20210923_161250_00645_ynqag.1.0-0 io.trino.plugin.jdbc.JdbcSplit@15ffac25 (start = 333540.32125, wall = 12 ms, cpu = 0 ms, wait = 0 ms, calls = 1): JDBC_ERROR: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: localhost, port: 49156; Port 9000 is for clickhouse-client program.

The above error message maybe means connect to port 9000

ONLY uprade jdbc driver to tigger the error

I'm looking into the driver's changlog

**Comment by grantatspothero** [comment]
Unrelated to the flaky tests, upgrading the clickhouse jdbc driver to 3.x causes a problem with float handling of nans/inf see here for details:
https://github.com/ClickHouse/clickhouse-jdbc/pull/770

**Pull request closed without merging**
