### PR TITLE
Cancel JDBC connector queries

### PR DESCRIPTION
**Pull request by kokosing**

### CODE REVIEW

**Comment by findepi** [comment]
> "Convert JdbcRecordCursor to JdbcPageSource"

That's not a "obviously good idea".

Pages are optimal when you pull data in columnar fashion.
They often utilize lazy blocks to avoid materializing columns that are not needed.

Cursors are optimal when you pull row-oriented data.
It's up to the engine to ask for filtering column first. 
Engine should not ask for other columns (skip decoding, and read functions) when data is being filtered out.

I can imagine that this may impact not only CPU cycles, but also IO if eg JDBC driver fetches large CLOB values lazily.

**Comment by kokosing** [comment]
> That's not a "obviously good idea".

Have you checked https://github.com/trinodb/trino/pull/7255? Yielding in record cursor is also complex.

**Comment by findepi** [comment]
> Have you checked #7255? Yielding in record cursor is also complex.

i haven't because it was closed before i saw it. Added a comment there.

**Comment by kokosing** [comment]
> Cursors are optimal when you pull row-oriented data.

It does not really matter. Engine is column-oriented so cursors are shortly transformed into pages. No magic, no laziness. 

> Engine should not ask for other columns (skip decoding, and read functions) when data is being filtered out.

It is hard for me to imagine this could be implemented for cursor. Currently data is read eagerly. If laziness is possible in egine for cursor then it surely is possible in `JdbcPageSource` too.

**Comment by findepi** [comment]
> It is hard for me to imagine this could be implemented for cursor. 

`ResultSet.getString` could pull more data then already contained in the `ResultSet`.

For example, i'd hope it's the case for PostgreSQL's TOAST storage, but i did not check.

> Currently data is read eagerly. 

indeed and you needed to remind me about this second time, thanks.
@electrum do you happen to remember whether column-level laziness of RecordCursor was considered before?

I.e. are we talking here about possible future improvement, or about an already failed idea we do not need to care about?

> If laziness is possible in egine for cursor then it surely is possible in `JdbcPageSource` too.

I don't think it would be possible, how?

**Comment by kokosing** [comment]
> I don't think it would be possible, how?

I was thinking about `RecordPageSource`, if one can optimize something there we could move that to `JdbcPageSource`. If would engine leverage the fact it reads from the cursor and optmized something then I would be not possible to port it.

**Comment by findepi** [comment]
> > I don't think it would be possible, how?
> 
> I was thinking about `RecordPageSource`, if one can optimize something there we could move that to `JdbcPageSource`. If would engine leverage the fact it reads from the cursor and optmized something then I would be not possible to port it.

Depending on the API of this thing and whether it's suitable for baking in into SPI.

For example, engine can decide which columns to read first from RC, then it can apply a filter.
We can later decide to do it in steps -- eg if we have two filters, we can read one column, then filter, then another column, then another filter.
Of course, this makes sense for selective filters only, so we would want to make this adaptive.

If we wanted to express this logic over SPI, we so that `JdbcPageSource` can remain on the connector side, we could perhaps basically reinvent the `RecordCursor` API (of course, not necessarily so).

**Comment by kokosing** [comment]
> For example, engine can decide which columns to read first from RC, then it can apply a filter.

Sure, but engine is column oriented so it needs a block of column values.

**Comment by sopel39** [comment]
> ResultSet.getString could pull more data then already contained in the ResultSet.

Do we know it's actually the case or JDBC result set fetches all columns when advancing next row?
I agree that `PageSource` does not support exactly the same flow (it could with single row pages), but I don't think we should extend record cursor API in such a way that it expect connectors to implement active loops (which is a specific solution for a specific issue).

**Comment by findepi** [comment]
> Do we know it's actually the case or JDBC result set fetches all columns when advancing next row?

i betted on PostgreSQL doing this, but i think now it doesn't do that.
Oracle driver seems like it could be doing that though.

**Comment by findepi** [comment]
> > Currently data is read eagerly.
> 
> indeed and you needed to remind me about this second time, thanks

i take this back.

It's read eagerly by `RecordPageSource` indeed, but that's not the only call site:

```
java.lang.RuntimeException: i am being called here
	at io.trino.plugin.jdbc.StandardColumnMappings.lambda$varcharReadFunction$12(StandardColumnMappings.java:294)
	at io.trino.plugin.jdbc.JdbcRecordCursor.getSlice(JdbcRecordCursor.java:193)
	at io.trino.$gen.CursorProcessor_20210314_180306_24.project_1(Unknown Source)
	at io.trino.$gen.CursorProcessor_20210314_180306_24.process(Unknown Source)
	at io.trino.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:323)
```

And indeed the `CursorProcessor` gets columns lazily.
For example for query `SELECT name FROM nation WHERE nationkey % 2 = 0;` against PostgreSQL connector, the bigint read function is called 2x more times than a varchar read function.

**Comment by sopel39** [comment]
> It's read eagerly by RecordPageSource indeed, but that's not the only call site:

There is `TableScanOperator`. It does not use `CursorProcessor`
There is `ScanFilterAndProjectOperator`. It does use `CursorProcessor`

**Comment by kokosing** [comment]
Replaced with https://github.com/trinodb/trino/pull/7306

**Pull request closed without merging**
