### PR TITLE
Allow AbstractTestQueryFramework to run with JUnit

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

A follow-up to #18765 that allows `AbstractTestQueryFramework` to run with JUnit in the Singlestore plugin, which also have tests using that base class.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by nineinchnick** [comment]
@wendigo please schedule a test run with all secrets

**Comment by wendigo** [comment]
/test-with-secrets sha=6eb7963d6796a16cd44228cdc50b9fa96fd729d3

**Comment by hashhar** [comment]
/test-with-secrets sha=6eb7963d6796a16cd44228cdc50b9fa96fd729d3

**Comment by nineinchnick** [comment]
The tests are running now: https://github.com/trinodb/trino/actions/runs/6185475592/job/16792524140

**Review by wendigo — APPROVED** [review]

**Comment by wendigo** [comment]
Singlestore has passed

**Pull request merged**
