### PR TITLE
Correct config.properties section 

### PR DESCRIPTION
**Pull request by mosabua**
## Description

The query configuration parameters are NOT required and have reasonable default set. Documenting otherwise is misleading and just makes the experience more complicated than necessary. I am also removing this in the book and have discussed this with @martint .

- Remove optional query memory footprint configuration
- Clarify one coordinator per cluster only
- Add links to properties reference and other useful sections

> Is this change a fix, improvement, new feature, refactoring, or other?

Improvement. 

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Only affects the documentation. 

> How would you describe this change to a non-technical end user or system administrator?

Simplify the minimal default configuration. 

## Related issues, pull requests, and links

n.a.

## Documentation

( ) No documentation is needed.
(✅) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(✅ ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

### CODE REVIEW

**Comment by hashhar** [comment]
The default is not reasonable - it's just 20GB. Per-node is also tuned towards extremely high concurrency at just 30% of heap.

While these are reasonable defaults for toy clusters they aren't good globally. I'd argue to instead clarify in the documentation that **ALL** configuration properties have reasonable default values and don't need tuning (i.e. won't improve performance playing with them) unless you are actually running into an issue.

**Review by hashhar — CHANGES_REQUESTED** [review]
The default is not reasonable - it's just 20GB. If it was set to unlimited then maybe. Per-node is also tuned towards extremely high concurrency at just 30% of heap.

While these are reasonable defaults for toy clusters they aren't good globally. I'd argue to instead clarify in the documentation that **ALL** configuration properties have reasonable default values and don't need tuning (i.e. won't improve performance playing with them) unless you are actually running into an issue.

**Comment by mosabua** [comment]
I am not sure I understand @hashhar .. are you ok with removing the parameter in that page or not?

And yes.. we should add some generic section that says.. use the minimal config and then refine as needed (and link to the properties doc for that).

And in a related question .. should we update the default behaviour to be more dynamic/suitable to be used without configuration need?

**Comment by hashhar** [comment]
Sorry for being unclear. I meant we should keep the documentation of the two configs. Removing the configs from the example snippets does seem good though.
And agreed with both points - use minimal config unless needed + smarter behavior from the engine.

**Comment by mosabua** [comment]
@hashhar I left the documentation for the two properties out since there is no reason for these to be treated differently than all other properties. Instead I expanded the section below that talks about more properties and linked to numerous related pages. 

I also fixed the misleading sentence about the coordinator and multiple servers.

**Review by hashhar — APPROVED** [review]
Much better. Thank you.

**Pull request merged**
