### PR TITLE
Use GroupByHash#createGroupByHash with Session argument

### PR DESCRIPTION
**Pull request by sopel39**

### CODE REVIEW

**Review by losipiuk — COMMENTED** [review]
What for? (add commit message explanation).
Do we still need another override (should it be removed or deprecated)?

**Comment by sopel39** [comment]
> What for? (add commit message explanation).

So that callers don't have to deal with `dictionary processing enabled` system session property (it's internal detail of `GroupByHash`)

> Do we still need another override (should it be removed or deprecated)?

Useful in tests

**Comment by losipiuk** [comment]
> > Do we still need another override (should it be removed or deprecated)?
> 
> It's useful in tests

If it is just that you should put a helper method in test code; instead of having an override in production code.

**Review by losipiuk — APPROVED** [review]

**Comment by sopel39** [comment]
> If it is just that you should put a helper method in test code; instead of having an override in production code.

It's also used by `GroupByHashPageIndexer` which I don't want to untangle currently.

**Pull request merged**
