### PR TITLE
Add docs for update statements to JDBC connectors

### PR DESCRIPTION
**Pull request by colebow**
## Description

RN was slightly misleading and connector docs need to mention update support. Knock those both out.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Review by mosabua — APPROVED** [review]

**Review by hashhar — COMMENTED** [review]
Not all `UPDATE` queries would work. Same limitation as `DELETE` applies.

Only `UPDATE` queries that can actually be "pushed down" are supported hence the release notes mentioned `pushdown`.

**Comment by mosabua** [comment]
> Not all `UPDATE` queries would work. Same limitation as `DELETE` applies.
> 
> Only `UPDATE` queries that can actually be "pushed down" are supported hence the release notes mentioned `pushdown`.

How can we explain that to users... how would you know if a update query can be pushed down or not.

**Comment by mosabua** [comment]
Any insights @hashhar ? Looks like the PR from @vlad-lyutenko #16445 has more info. Can @vlad-lyutenko please send a PR to update the docs more .. potentially working with @colebow or @jhlodin  .. I can help with review and merge.

**Comment by vlad-lyutenko** [comment]
Maybe I can describe more detailed about limitation:
we support only constant updates, like : `UPDATE nation SET col1 = 1 WHERE col3 = 1; `
it means that we can not use any expressions in SET section like  `UPDATE nation SET col1 = col2 + 2 WHERE col3 = 1; `

Also we cannot use AND/OR in predicates like `UPDATE nation SET col1 = 1 WHERE col3 = 1 AND col2 = 3; `

And most tricky limitation - UPDATE ALL, it means -
if we have table with 3 columns - col1 col2 col3
We cannot execute query which update all 3 columns simultaneously, like this:
`UPDATE nation SET col1 = 1, col2=2, col3=3 WHERE col3 = 1; `
But we can update 2 or 1 of them like:
`UPDATE nation SET col1 = 1, col2=2 WHERE col3 = 1; `

**Pull request merged**
