### PR TITLE
Add UpdateKind to ConnectorMetadata.beginMerge to fix incorrect operation field in Delta Lake CommitInfo

### LINKED ISSUE #15763: `CommitInfo`.`operation` is always `MERGE` for a DML operation in Delta Lake
`trino-delta-lake` fills in for `operation` always `MERGE` in the `CommitInfoEntry` when doing `UPDATE`/`DELETE`/`MERGE` operations.

https://github.com/trinodb/trino/blob/9d6764dac0c3da9296ae2a619dfab949281415c1/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java#L1629

Expected functionality would actually be to use the same name as the DML operation name in there.

Negative outcome - `DESCRIBE HISTORY table` in Databricks shows always `MERGE` which could make debugging eventually harder.

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Add UpdateKind to ConnectorMetadata.beginMerge to fix incorrect operation field in Delta Lake CommitInfo
Fixes #15763

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# SPI
* Add `UpdateKind` to `ConnectorMetadata.beginMerge` method. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by martint** [comment]
Why does Delta Lake care about whether the operation was an update/delete vs merge?

cc @electrum

**Comment by findinpath** [comment]
> Why does Delta Lake care about whether the operation was an update/delete vs merge?

https://github.com/trinodb/trino/blob/2536dc2adbbf42fb2bf13e904b5899cb4ee66241/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java#L338-L340

It's not the Delta Lake format which is actually affected - AFAIK Delta Lake Spark is not misfunctioning because of Trino showing `MERGE` for the operation in the `$history` table. See https://trino.io/docs/current/connector/delta-lake.html#history-table

It is actually the end user (in Trino or Spark while checking the history of the table) who does not know what kind of operation was performed.

**Comment by dain** [comment]
This part of DELTA is not well thoughtout, and I don't think we should add anything to support this in Trino.  A merge statement can be used to the other update kinds, so the orginal query used DELETE instead of MERGE is totally useless.

**Comment by findinpath** [comment]
> It is actually the end user (in Trino or Spark while checking the history of the table) who does not know what kind of operation was performed.

> This part of DELTA is not well thoughtout

Any idea how we can cover the functional need of the connector to showcase the type of DML operation performed?

**Comment by ebyhr** [comment]
Closing as we talked offline.

**Pull request closed without merging**
