### PR TITLE
Pinot stress test

### PR DESCRIPTION
**Pull request by xiangfu0**
## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by xiangfu0** [comment]
One round of passing 100 tests: https://github.com/trinodb/trino/actions/runs/3251833562/jobs/5339480470

**Comment by xiangfu0** [comment]
Found 1 fail out of 100: https://github.com/trinodb/trino/actions/runs/3254819255/jobs/5343505302

**Comment by xiangfu0** [comment]
100 run with 1 failing: https://github.com/trinodb/trino/actions/runs/3255193620/jobs/5344357843

**Comment by xiangfu0** [comment]
Another failed run: https://github.com/trinodb/trino/actions/runs/3257551630/jobs/5348892515
```
Error:  Tests run: 251, Failures: 1, Errors: 0, Skipped: 15, Time elapsed: 622.329 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.pinot.TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest.testAggregationPushdown  Time elapsed: 18.428 s  <<< FAILURE!
java.lang.AssertionError: 
[Rows for query [SELECT bool_col, COUNT(long_col) FROM "SELECT bool_col, long_col FROM alltypes" GROUP BY bool_col]] 
Expecting:
  <(true, 9), (false, 1)>
to contain exactly in any order:
  <[(true, 8), (false, 2)]>
elements not found:
  <(true, 8), (false, 2)>
and elements not expected:
  <(true, 9), (false, 1)>

	at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$matches$2(QueryAssertions.java:390)
	at io.trino.sql.query.QueryAssertions$QueryAssert.matches(QueryAssertions.java:377)
	at io.trino.sql.query.QueryAssertions$QueryAssert.hasCorrectResultsRegardlessOfPushdown(QueryAssertions.java:560)
	at io.trino.sql.query.QueryAssertions$QueryAssert.hasPlan(QueryAssertions.java:549)
	at io.trino.sql.query.QueryAssertions$QueryAssert.isNotFullyPushedDown(QueryAssertions.java:513)
	at io.trino.sql.query.QueryAssertions$QueryAssert.isNotFullyPushedDown(QueryAssertions.java:500)
	at io.trino.plugin.pinot.BasePinotIntegrationConnectorSmokeTest.testAggregationPushdown(BasePinotIntegrationConnectorSmokeTest.java:1877)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testAggregationPushdown:1877 [Rows for query [SELECT bool_col, COUNT(long_col) FROM "SELECT bool_col, long_col FROM alltypes" GROUP BY bool_col]] 
Expecting:
  <(true, 9), (false, 1)>
to contain exactly in any order:
  <[(true, 8), (false, 2)]>
elements not found:
  <(true, 8), (false, 2)>
and elements not expected:
  <(true, 9), (false, 1)>

[INFO] 
Error:  Tests run: 251, Failures: 1, Errors: 0, Skipped: 15
```

**Comment by xiangfu0** [comment]
Got 100 pass: https://github.com/trinodb/trino/actions/runs/3257736455/jobs/5349231796

**Comment by xiangfu0** [comment]
Another failed: https://github.com/trinodb/trino/actions/runs/3258870072/jobs/5351288748
```
Error:  Tests run: 251, Failures: 17, Errors: 0, Skipped: 15, Time elapsed: 602.591 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.pinot.TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest.testAggregatePassthroughQueriesWithExpressions  Time elapsed: 2.074 s  <<< FAILURE!
io.trino.testing.QueryFailedException: 
Query select percentile("int_col", '90') from alltypes limit 10 encountered exception code: '305' message: 'null:
1 segments [alltypes__0__0__20221016T0856Z] unavailable' with query "select percentile("int_col", '90') from alltypes limit 10"
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:481)
	at io.trino.sql.query.QueryAssertions$QueryAssert.newQueryAssert(QueryAssertions.java:299)
	at io.trino.sql.query.QueryAssertions.query(QueryAssertions.java:118)
	at io.trino.testing.AbstractTestQueryFramework.query(AbstractTestQueryFramework.java:287)
	at io.trino.testing.AbstractTestQueryFramework.query(AbstractTestQueryFramework.java:282)
	at io.trino.plugin.pinot.BasePinotIntegrationConnectorSmokeTest.testAggregatePassthroughQueriesWithExpressions(BasePinotIntegrationConnectorSmokeTest.java:2371)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: SQL: SELECT "percentile(int_col, 90.0)"  FROM "SELECT percentile(int_col, 90) FROM alltypes"
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:484)
		... 18 more
Caused by: io.trino.plugin.pinot.PinotException: Query select percentile("int_col", '90') from alltypes limit 10 encountered exception code: '305' message: 'null:
1 segments [alltypes__0__0__20221016T0856Z] unavailable' with query "select percentile("int_col", '90') from alltypes limit 10"
	at io.trino.plugin.pinot.client.PinotClient.lambda$submitBrokerQueryJson$7(PinotClient.java:563)
	at io.trino.plugin.pinot.client.PinotClient.doWithRetries(PinotClient.java:631)
	at io.trino.plugin.pinot.client.PinotClient.submitBrokerQueryJson(PinotClient.java:540)
to contain exactly in any order:
  <[(1970-01-01T00:00)]>
but could not find the following elements:
  <(1970-01-01T00:00)>

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testPassthroughQueriesWithAliases:2109->AbstractTestQueryFramework.query:282->AbstractTestQueryFramework.query:287 » QueryFailed
Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testPassthroughQueriesWithPushdowns:2163->AbstractTestQueryFramework.query:282->AbstractTestQueryFramework.query:287 » QueryFailed
Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testRealWithInfinity:1971 [Rows for query [SELECT element_at(float_array_col, 1)  FROM alltypes  WHERE bytes_col = X'']] 
Expecting:
  <>
to contain exactly in any order:
  <[(-Infinity), (-Infinity)]>
but could not find the following elements:
  <(-Infinity), (-Infinity)>

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testTimestamp:2444 [Rows for query [SELECT ts FROM alltypes ORDER BY ts LIMIT 1]] 
Expecting:
  <>
to contain exactly in any order:
  <[(1970-01-01T00:00)]>
but could not find the following elements:
  <(1970-01-01T00:00)>

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testTransformFunctions:2044->AbstractTestQueryFramework.query:282->AbstractTestQueryFramework.query:287 » QueryFailed
Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testVarbinary:2436 [Rows for query [SELECT bytes_col FROM alltypes WHERE string_col != 'array_null']] 
Expecting:
  <>
to contain exactly in any order:
  <[([]),
    ([115, 116, 114, 105, 110, 103, 95, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 49, 50, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 50, 52, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 51, 54, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 52, 56, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 54, 48, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 55, 50, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 56, 52, 48, 48]),
    ([115, 116, 114, 105, 110, 103, 95, 57, 54, 48, 48])]>
but could not find the following elements:
  <([]), ([115, 116, 114, 105, 110, 103, 95, 48]), ([115, 116, 114, 105, 110, 103, 95, 49, 50, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 50, 52, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 51, 54, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 52, 56, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 54, 48, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 55, 50, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 56, 52, 48, 48]), ([115, 116, 114, 105, 110, 103, 95, 57, 54, 48, 48])>

Error:    TestPinotWithoutAuthenticationIntegrationLatestVersionConnectorSmokeTest>BasePinotIntegrationConnectorSmokeTest.testVarbinaryFilters:1926 [Rows for query [SELECT string_col  FROM alltypes  WHERE bytes_col = X'']] 
Expecting:
  <>
to contain exactly in any order:
  <[(null), (array_null)]>
but could not find the following elements:
  <(null), (array_null)>

[INFO] 
Error:  Tests run: 251, Failures: 17, Errors: 0, Skipped: 15
[INFO] 
Warning:  Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/runner/work/trino/trino/plugin/trino-pinot/target/surefire-reports/2022-10-16T08-53-24_166-jvmRun1.dumpstream
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:08 min
[INFO] Finished at: 2022-10-16T09:03:28Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project trino-pinot: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/trino/trino/plugin/trino-pinot/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: Process completed with exit code 1.
```

**Comment by xiangfu0** [comment]
Failed: https://github.com/trinodb/trino/actions/runs/3258870072/jobs/5351288748

**Comment by ebyhr** [comment]
Closing as this is an old PR for stress testing.

**Pull request closed without merging**
