### PR TITLE
Update provisio-maven-plugin to 1.0.20

### PR DESCRIPTION
**Pull request by kokosing**
Update provisio-maven-plugin to 1.0.20

### CODE REVIEW

**Review by electrum — APPROVED** [review]

**Comment by hashhar** [comment]
Seems to have hit a case where we don't have all dependencies downloaded but we're running maven with `--offline`. cc: @nineinchnick

**Review by hashhar — APPROVED** [review]
LGTM % confirming CI indeed works

**Comment by nineinchnick** [comment]
I think we should remove the `--offline` flag and allow Maven to download missing dependencies when necessary.

I see there are multiple versions of `plexus-java` being downloaded, and the tools we use to download dependencies might not properly handle that. Before we'll be able to track down the root cause and fix it, we should not be blocked. cc @findepi because you insisted on adding it.

**Comment by kokosing** [comment]
Retry does not help.

**Comment by kokosing** [comment]
@nineinchnick I have rebased and the issue is still there. Is this related to this PR or is it that highly flaky?

**Comment by nineinchnick** [comment]
This PR introduces a new version of a dependency that doesn't get downloaded by the commands we execute in [download-maven-dependencies.sh](https://github.com/trinodb/trino/blob/master/.github/bin/download-maven-dependencies.sh). You either have to add it as an exception there (download it explicitly) or remove `--offline` in these places:
* https://github.com/trinodb/trino/blob/master/.github/workflows/ci.yml#L21
* https://github.com/trinodb/trino/blob/master/.github/actions/compile-commit/action.yml#L35

**Comment by kokosing** [comment]
> You either have to add it as an exception there (download it explicitly)

How?

**Comment by nineinchnick** [comment]
> > You either have to add it as an exception there (download it explicitly)
> 
> How?

```bash
./mvnw dependency:get -Dartifact=org.codehaus.plexus:plexus-java:1.1.1:jar -Dtransitive=false
```

**Comment by kokosing** [comment]
>  remove --offline in these places:

I have tried with the other option and so far no luck. I am now more inclined to remove the `--offline` switch. Possibly I need to create a separate PR. First I wanted to get your opinion about it: @nineinchnick  and @findepi ?

**Comment by nineinchnick** [comment]
I saw you tried explicitly downloading provisio, not that transitive dependency the ci is complaining about, as I was suggesting. I'm ok with removing --offline but let's wait for @findepi.

**Comment by findepi** [comment]
@nineinchnick i don't understand yet what we're blocked on. If I understand how `--offline` works, it provides us with determinism. Before we go offline, we use retries. Once we go offline, we don't need retries. Removing `--offline` brings us back to less predictibility.

What are we gaining? Why is this new provisio version special?

**Comment by nineinchnick** [comment]
> @nineinchnick i don't understand yet what we're blocked on. If I understand how `--offline` works, it provides us with determinism. Before we go offline, we use retries. Once we go offline, we don't need retries. Removing `--offline` brings us back to less predictibility.
> 
> What are we gaining? Why is this new provisio version special?

We can't figure out how to download all required dependencies. I have the same problem in #12929 now.

**Comment by nineinchnick** [comment]
@kokosing can you try adding it explicitly in the configuration for the `go-offline-maven-plugin`?

```patch
diff --git a/pom.xml b/pom.xml
index 5887dfdc09..922d798cf8 100644
--- a/pom.xml
+++ b/pom.xml
@@ -2148,6 +2148,12 @@
                                 <version>${dep.drift.version}</version>
                                 <repositoryType>PLUGIN</repositoryType>
                             </DynamicDependency>
+                            <DynamicDependency>
+                                <groupId>ca.vanzyl.provisio.maven.plugins</groupId>
+                                <artifactId>provisio-maven-plugin</artifactId>
+                                <version>1.0.20</version>
+                                <repositoryType>PLUGIN</repositoryType>
+                            </DynamicDependency>
                             <DynamicDependency>
                                 <groupId>com.google.errorprone</groupId>
                                 <artifactId>error_prone_core</artifactId>
```

**Comment by findepi** [comment]
@nineinchnick how did we come up with this list https://github.com/trinodb/trino/blob/a400eaf3df018dc73e57c73e8eaa3203e73e1241/pom.xml#L2132-L2226 ?
why can't we refresh it now?

**Comment by nineinchnick** [comment]
This caused a new error when downloading dependencies:
```
2023-03-11T07:19:27.4286197Z [INFO] --- go-offline-maven-plugin:1.2.8:resolve-dependencies (default-cli) @ trino-root ---
2023-03-11T07:19:33.4363449Z [ERROR] Error resolving plugin io.takari.maven.plugins:takari-lifecycle-plugin
2023-03-11T07:19:33.4364197Z [ERROR] version can neither be null, empty nor blank
```

I wonder if this is caused by how `provisio` calls `takari-lifecycle-plugin` and if this can be fixed by again adding it explicitly to `dynamicDependencies`.

**Review by wendigo — APPROVED** [review]

**Pull request merged**
