### PR TITLE
Update DEVELOPMENT.md

### PR DESCRIPTION
**Pull request by hantmac**
Fix development docs

### CODE REVIEW

**Review by wendigo — APPROVED** [review]

**Comment by hantmac** [comment]
@wendigo Hi bro, I have send the signed cla file, would you like to help me to check it ?

**Comment by wendigo** [comment]
@martint do you plan to process CLAs this week?

**Comment by hantmac** [comment]
@martint Hi bro, I have send the signed CLA file, would you like to help me to check it ?

**Comment by wendigo** [comment]
@cla-bot recheck

**Comment by ebyhr** [comment]
@cla-bot check

**Pull request merged**
