### PR TITLE
Upgrade BigQuery client libraries

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Comment by hashhar** [comment]
Any notable bug-fixes or changes?

**Comment by wendigo** [comment]
@hashhar a lot of changes around bigquery storage read/write API: https://github.com/googleapis/java-bigquerystorage/blob/main/CHANGELOG.md

**Comment by hashhar** [comment]
https://github.com/googleapis/java-bigquerystorage/pull/1521#issue-1127465850 seems like the big one.

**Comment by wendigo** [comment]
I've tested it locally and only a single test failed (due to lack of the permissions):
Screenshot 2022-02-09 at 12 33 09

**Pull request merged**
