### PR TITLE
Abolish taking over Presto JDBC driver

### PR DESCRIPTION
**Pull request by takezoe**
Although Trino JDBC driver is not compatible with Presto's now, it takes over Presto JDBC URL and even driver implementations. Since it's really confusing for users who want to connect to both Trino and Presto in a single application, Trino JDBC driver shouldn't take over Presto JDBC driver.

### CODE REVIEW

**Review by electrum — APPROVED** [review]
Thanks! This is something we've been meaning to do.

**Comment by electrum** [comment]
Product tests are failing due to using the old driver class name. Looks like that was fixed in https://github.com/trinodb/tempto/pull/73 but we need to release it and update.

**Comment by electrum** [comment]
Created https://github.com/trinodb/trino/pull/8062 to update Tempto

**Comment by findepi** [comment]
> Looks like that was fixed in [trinodb/tempto#73](https://github.com/trinodb/tempto/pull/73) 

i don't think the driver class name is hard-coded in tempto.
it seemed to me the PR was changing examples and README only (and `KafkaTableManager`, but this seems not to hardcode class names either)

**Comment by electrum** [comment]
@findepi you're right, this is actually in the Trino source code

@takezoe please update the driver class name in https://github.com/trinodb/trino/blob/86079ee7cb0f27e7fae4fa2915fa45d370ffbedd/testing/trino-product-tests/src/main/resources/tempto-configuration.yaml#L33

**Comment by takezoe** [comment]
Oh, I overlooked it. Updated the driver name in the tempo configuration.

**Comment by electrum** [comment]
Thanks!

**Pull request merged**
