### PR TITLE
Update confluent to 7.4.1

### PR DESCRIPTION
**Pull request by wendigo**
Extracted from https://github.com/trinodb/trino/pull/18623

### CODE REVIEW

**Comment by wendigo** [comment]
PTAL @hashhar @kokosing

**Review by kokosing — APPROVED** [review]

**Comment by kokosing** [comment]
@elonazoulay any comments?

**Comment by wendigo** [comment]
@elonazoulay gentle ping :)

**Comment by wendigo** [comment]
@elonazoulay ptal :)

**Pull request merged**
