### PR TITLE
Get iceberg splits asynchronously

### LINKED ISSUE #17631: Make IcebergSplitSource generate splits asynchronously
The current `IcebergSplitSource::getNextBatch` is synchronous by returning a completed future. I wonder if there're specific reasons why it's implemented this way and whether we can make it asynchronous.

Some background: we made our iceberg use a blocking queue when planning files (in order to reduce memory consumption). Then if multiple-stage query run concurrently in trino, it can run into some kind of dead lock, because the stage scheduler can be blocked at `IcebergSplitSource::getNextBatch` while the thread pool used in planning files is occupied by other stages.

### PR DESCRIPTION
**Pull request by lirui-apache**
## Description

Get iceberg splits in a separate thread.

## Additional context and related issues

Fixes #17631

### CODE REVIEW

**Comment by alexjo2144** [comment]
Do we have any benchmarks on if this improves planning time?

**Comment by lirui-apache** [comment]
Hey @alexjo2144 , the purpose of the PR is not to improve planning time, but to avoid potential issue when planning with a blocking queue to reduce memory pressure. I put some background [here](https://github.com/trinodb/trino/issues/17631).
As to performance, we've been using the proposed patch internally for about a year, and we haven't found any noticeable impact on planning time according the to `getSplitDistribution` metrics.

**Comment by mosabua** [comment]
@cla-bot check

**Comment by mosabua** [comment]
@lirui-apache can you please submit a CLA?

@hashhar and @alexjo2144 can you help on reviewing this PR?

**Comment by lirui-apache** [comment]
Hi @mosabua , I have submitted my CLA and rebased the PR

**Comment by mosabua** [comment]
@cla-bot check

**Comment by mosabua** [comment]
Looks like the CLA has to be processed yet. In the meantime I assigned reviewers and hope they can help out soon.

**Comment by mosabua** [comment]
@cla-bot check

**Comment by mosabua** [comment]
@alexjo2144 @electrum do we want to reopen and continue on this approach?

**Pull request closed without merging**
