### PR TITLE
Add catalog.skip-load-error config param for silent catalog file loading

### PR DESCRIPTION
**Pull request by olegsavin**
## Description
Add catalog.skip-load-error config param for silent catalog file loading with default file-based StaticCatalogStore.

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
(x) Documentation issue #11330 is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
(x) Release notes entries required with the following suggested text:

```markdown
# General
* Add boolean catalog.skip-load-error configuration parameter for silent catalog file loading.
```

### CODE REVIEW

**Comment by findepi** [comment]
What's the use case?

**Comment by olegsavin** [comment]
> What's the use case?

@findepi appreciate you taking a look, the use case is existing multi-user cluster, adding a misconfigured catalog, causes entire cluster to go down, this way we can configure it to be best-effort and limit impact of catalog config error to just that one catalog.

**Comment by findepi** [comment]
Thanks for explaining the use case. I am not aware of people asking for this specifically, and obviously we don't want to add features that will have very small user base. We'd rather spend complexity budget elsewhere.

@olegsavin Do you know how often this would be useful?

**Comment by olegsavin** [comment]
It would be useful in any production multi-user scenario. Otherwise that's too easy to disrupt running workloads for long time (putting server restart aside). The change is simple, minimal, bkwd-compatible, it doesn't eat up much of complexity budget imo.
Ideally we'd love to have dynamic catalogs registration feature (#2110 and #2445) which would logically do the same - one bad request to add catalog would not bring down whole cluster for all users. But given explained complexity for updates/deletes of catalogs, this small change a stop gap for at least one scenario.

**Comment by olegsavin** [comment]
@findepi so does above sounds convincing? Or complexity budget is that tight even for such change :)

**Comment by olegsavin** [comment]
Hi @electrum can you take a look please - what do you say?

**Comment by bitsondatadev** [comment]
:wave: @olegsavin - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by colebow** [comment]
Closing this one out due to inactivity, but please reopen if you would like to pick this back up.

**Pull request closed without merging**
