### PR TITLE
Upgrade depedencies

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Comment by ebyhr** [comment]
Could you confirm SingleStore CI failure? 
```
Error:  Failures: 
Error:    TestSingleStoreConnectorTest>BaseConnectorTest.testAddColumn:2275->AbstractTestQueryFramework.assertQuery:348 Execution of 'actual' query 20240117_203121_00714_em7m3 failed: SELECT * FROM test_add_column_fnlcuoyzuk
Error:  Errors: 
Error:    TestSingleStoreConnectorTest.testAddNotNullColumn:276->AbstractTestQueryFramework.query:328->AbstractTestQueryFramework.query:333 » QueryFailed Data type LONGBLOB (not binary) cannot be decoded as Blob
Error:    TestSingleStoreConnectorTest>BaseConnectorTest.testAddNotNullColumnToEmptyTable:2355->AbstractTestQueryFramework.query:328->AbstractTestQueryFramework.query:333 » QueryFailed Data type LONGBLOB (not binary) cannot be decoded as Blob
Error:    TestSingleStoreConnectorTest>BaseConnectorTest.testVarcharCastToDateInPredicate:605->AbstractTestQueryFramework.query:328->AbstractTestQueryFramework.query:333 » QueryFailed Data type LONGBLOB (not binary) cannot be decoded as Blob
Error:    TestSingleStoreTypeMapping.testSingleStoreCreatedParameterizedVarchar:563 » QueryFailed Data type TINYBLOB (not binary) cannot be decoded as Blob
Error:    TestSingleStoreTypeMapping.testSingleStoreCreatedParameterizedVarcharUnicode:581 » QueryFailed Data type TINYBLOB (not binary) cannot be decoded as Blob
Error:    TestSingleStoreTypeMapping.testTrinoCreatedParameterizedVarchar:549 » QueryFailed Data type BLOB (not binary) cannot be decoded as Blob
```

**Comment by wendigo** [comment]
@ebyhr ptal

**Comment by wendigo** [comment]
@ebyhr ping

**Comment by wendigo** [comment]
Rebased

**Review by hashhar — COMMENTED** [review]
re: " Update singlestore-jdbc-client to 1.2.1 ".

~It seems~ https://github.com/trinodb/trino/blob/469cc1ff4e7a425c0c07b91b768aec16eb934d7b/plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClientModule.java#L56-L57 ~is redundant now. The driver has changed behaviour in https://github.com/memsql/S2-JDBC-Connector/commit/db0115a958f962b932ae6e76fe3406728efddc7a.~

Nevermind, our config applies to tinyints, not bits being treated as booleans.

**Review by hashhar — APPROVED** [review]

**Pull request merged**
