### PR TITLE
Pin openpolicyagent/opa version as 0.70.0

### LINKED ISSUE #24559: Flaky OPA tests
TestOpaAccessControlDataFilteringSystem and TestOpaAccessControlSystem are recently very flaky:
https://github.com/trinodb/trino/actions/runs/12445332216/job/34746537598

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Version 1.0.0~ doesn't pass CI. 

Fixes #24559

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Review by raunaqmorarka — APPROVED** [review]
Is it a problem in the usage or a bug in the OPA project ?
Can we report the bug there if its not a known bug ?

**Comment by ebyhr** [comment]
I would leave it to @vagaerg.

**Comment by vagaerg** [comment]
> I would leave it to @vagaerg.

Thank you very much @ebyhr for proactively opening the PR, hadn't noticed the tests were flaky. I will take a look today and revert back

**Comment by anderseknert** [comment]
Happy to help support you with the 1.0 upgrade should you need that! Provided that all policies are 1.0 compatible, it should hopefully be rather straightforward. If you need to support both pre-1.0 policies and 1.0+ policies from the same application, that's totally doable, but requires some additional planning / work.

**Pull request merged**
