### PR TITLE
Fix LDAP Authenticator validation issues with ActiveDirectory service

### LINKED ISSUE #12321: LDAP Password Authenticator doesn't work with ActiveDirectory
This PR - https://github.com/trinodb/trino/pull/11909 - breaks our LDAP Password Authenticator when it tries to connect with an ActiveDirectory server with the following error

```
2022-05-10T09:21:11.178Z        DEBUG   http-worker-123 io.trino.plugin.password.ldap.LdapAuthenticator Authentication failed for user [ajay.trivedi], Missing 'equals'
javax.naming.directory.InvalidSearchFilterException: Missing 'equals'; remaining name 'user.name@example.com'
        at java.naming/com.sun.jndi.ldap.Filter.encodeSimpleFilter(Filter.java:330)
        at java.naming/com.sun.jndi.ldap.Filter.encodeFilter(Filter.java:171)
        at java.naming/com.sun.jndi.ldap.Filter.encodeFilterString(Filter.java:74)
        at java.naming/com.sun.jndi.ldap.LdapClient.search(LdapClient.java:547)
        at java.naming/com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:2014)
        at java.naming/com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1873)
        at java.naming/com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1798)
        at java.naming/com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:392)
        at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:358)
        at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:341)
        at java.naming/javax.naming.directory.InitialDirContext.search(InitialDirContext.java:267)
        at io.trino.plugin.base.ldap.JdkLdapClient$CloseableContext.search(JdkLdapClient.java:171)
        at io.trino.plugin.base.ldap.JdkLdapClient.searchContext(JdkLdapClient.java:103)
        at io.trino.plugin.base.ldap.JdkLdapClient.executeLdapQuery(JdkLdapClient.java:92)
        at io.trino.plugin.password.ldap.LdapAuthenticatorClient.validatePassword(LdapAuthenticatorClient.java:41)
        at io.trino.plugin.password.ldap.LdapAuthenticator.authenticateWithUserBind(LdapAuthenticator.java:135)
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4956)
        at com.google.common.cache.ForwardingLoadingCache.getUnchecked(ForwardingLoadingCache.java:51)
        at io.trino.plugin.password.ldap.LdapAuthenticator.createAuthenticatedPrincipal(LdapAuthenticator.java:106)
        at io.trino.server.ui.PasswordManagerFormAuthenticator.isValidCredential(PasswordManagerFormAuthenticator.java:83)
        at io.trino.server.ui.FormWebUiAuthenticationFilter.checkLoginCredentials(FormWebUiAuthenticationFilter.java:231)
        at com.starburstdata.presto.server.security.webui.FormWebUiAuthenticator.lambda$login$1(FormWebUiAuthenticator.java:71)
        at java.base/java.util.Optional.flatMap(Optional.java:294)
```

### PR DESCRIPTION
**Pull request by Praveen2112**
## Description

In regards with testing - There isn't any dockerized setup for ActiveDirectory (which uses UPN aka Unique Principal Name for login purpose) .. But have tested locally and it works as expected. 

> Is this change a fix, improvement, new feature, refactoring, or other?

Fixes #12321. 

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

This is specific to LDAP password authenticator. 

> How would you describe this change to a non-technical end user or system administrator?

This PR fixes LDAP Authenticator validation issues with ActiveDirectory

## Related issues, pull requests, and links
https://github.com/trinodb/trino/pull/11909

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
(x) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by findepi** [comment]
What does this change do?

**Comment by Praveen2112** [comment]
cc: @ajaytrivedi67. Can you please confirm from your side that this patch works for you.

**Comment by Praveen2112** [comment]
@findepi Have revisited the rationale

**Review by kokosing — APPROVED** [review]

**Review by s2lomon — APPROVED** [review]
lgtm

**Pull request merged**
