### PR TITLE
Convert more documentation to markdown source

### PR DESCRIPTION
**Pull request by mosabua**
## Description

* Admin section
* Client section
* Installation section

Verified that the produced HTML is identical or just has wrapping and style changes that do NOT affect the output at all. 

Also improved layout of some tables first to make conversion a bit easier, but left in separate commit.

## Additional context and related issues

Prior PRs that migrated other docs:

#17732 
#17742

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Review by hashhar — COMMENTED** [review]
At the end of this wouldn't we be left with both rst and markdown? AFAIK not everything that rst allows you to express can be expressed in markdown without dropping down to plain HTML.

In other words, it'll be helpful if you can state the goals of this change.

**Comment by mosabua** [comment]
@hashhar .. the Myst Parser supported all features from rst and more. It will be a complete port. I am just taking it in steps since I have to find the right extensions and so on. I will also update the readme in the docs folder with info soon. 

Just for reference : 

https://myst-parser.readthedocs.io/en/latest/index.html

**Comment by hashhar** [comment]
Ah, so we're switching parsers as well. Thanks for the context - that was the missing piece for me.

**Comment by mosabua** [comment]
We were already using both in parallel ever since we switched the release notes to be markdown based @hashhar . Now we are just completing the move and going with it for everything. Also note that the result is not vanilla markdown .. it has a bunch of more features and syntax usage. And I am adding extensions for things as needed.

**Review by raunaqmorarka — APPROVED** [review]

**Comment by mosabua** [comment]
Thank you @raunaqmorarka

**Pull request merged**
