### PR TITLE
Add catalog and schema to `SHOW FUNCTIONS` results

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Add `Catalog` and `Schema` fields to `SHOW FUNCTIONS` results.
https://github.com/trinodb/trino/pull/16107#discussion_r1106096831

## Release notes

```markdown
# General
* Add catalog and schema to `SHOW FUNCTIONS` results. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by hashhar — APPROVED** [review]

**Comment by hashhar** [comment]
CI failures are related. LGTM otherwise.

**Comment by mosabua** [comment]
Fyi @Jessie212 .. when this gets merged we should aborb the relevant doc updates into your PR. I will try to review that asap.

**Comment by electrum** [comment]
I asked @dain to take a look at this. I seem to remember that we don't want to expose `system.builtin` to end users, which is why we didn't add this originally.

**Review by dain — CHANGES_REQUESTED** [review]
Ya, I don't think we should expose the `system.builtin` schema for these funtions.  I expect we will reorganize the functions into buckets for sql standard functions, Trino extensions, and user provided global (legacy) UDFs, so hiding the current name makes this future reorganization easier.

**Comment by electrum** [comment]
We could make the catalog and schema fields empty for the built in functions.

The way we designed UDFs with default catalog and schema, most users won’t care or need to care about the fully qualified name. Maybe we should keep the existing behavior and add a keyword to show the qualified name?

**Pull request closed without merging**
