### PR TITLE
Make timeline readable

### PR DESCRIPTION
**Pull request by wendigo**
Before:

Screenshot 2024-07-25 at 15 27 21

After:

Screenshot 2024-07-25 at 15 26 53

### CODE REVIEW

**Review by krvikash — APPROVED** [review]

**Review by mosabua — APPROVED** [review]
Love the brighter colors.

**Comment by mosabua** [comment]
I assume you are running with rebasing and merging soonish @wendigo  .. also @aliloney what do you think about the colors?

**Comment by wendigo** [comment]
@mosabua Yes, I'll rebase in one week. I'm hiking in Yosemite atm :)

**Comment by mosabua** [comment]
We still want to get this in. Added stale-ignore

**Comment by wendigo** [comment]
@mosabua I'm going to rebase it now.

**Pull request closed without merging**
