### PR TITLE
Require JDK 11 to use CLI and JDBC driver

### PR DESCRIPTION
**Pull request by wendigo**
Release notes: Require JDK 11 to use client library, CLI and JDBC driver.

### CODE REVIEW

**Comment by martint** [comment]
We should update to JDK21 directly, IMO. Updating to 11 and then to 21 will cause additional burden for users.

**Comment by wendigo** [comment]
@martint I think that this is too early as a lot of tools will not run on 21 (like dbeaver). Update to 11 is necessary because next jline3 will require 11.

**Comment by mosabua** [comment]
Agreed that 21 is too new. 17 might be okay as it has been around for quite a while but sticking with 11 is the safe step and follows what we have done in the past.

**Comment by sajjoseph** [comment]
@wendigo  - is this still needed if we are upgrading the JDK to 11 ?

https://github.com/trinodb/trino/blob/2b939ee00b03be9de28937d3ee4bd74c2be3e1b1/client/trino-client/src/main/java/io/trino/client/JsonCodec.java#L59

**Comment by wendigo** [comment]
@sajjoseph yeah, I think so

**Comment by wendigo** [comment]
This will be obsolete with Jackson 3.0

**Comment by martint** [comment]
For the JDBC driver, yes. For the CLI, no, as that is an independent application -- all the users needs to do is install an updated JVM (or we could start shipping it with the CLI)

**Comment by wendigo** [comment]
So we could: switch JDBC to 11, CLI to 17 (as for now), client to 11 (as it's shared between CLI and JDBC), is this correct @martint ?

**Comment by wendigo** [comment]
@martint urgency? No, but I'd like to do some cleanup in the meantime while waiting for Temurin builds

**Comment by wendigo** [comment]
@martint let me know your thoughts

**Comment by electrum** [comment]
If the reason to update is for the CLI, then we don't need to update the JDBC driver. We can leave that at JDK 8 for the widest compatibility. Updating to JDK doesn't seem to help much from a dependency standpoint.

**Pull request closed without merging**
