### PR TITLE
Test: Add support for fetching Redshift query results using Redshift unload command

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Run CI with secrets: https://github.com/trinodb/trino/pull/24117

### CODE REVIEW

**Comment by mayankvadariya** [comment]
@ebyhr please help me pull latest commit from https://github.com/trinodb/trino/pull/24117

**Comment by ebyhr** [comment]
Updated.

**Comment by ebyhr** [comment]
Updated.

**Comment by mayankvadariya** [comment]
@ebyhr can you please pull the latest changes from parent PR?

**Comment by mayankvadariya** [comment]
https://github.com/trinodb/trino/actions/runs/12343063858/job/34443666325?pr=24359#step:19:179 test passes locally with these commits. 🤔

**Comment by ebyhr** [comment]
Updated.

**Comment by mayankvadariya** [comment]
https://github.com/trinodb/trino/actions/runs/12401862084/job/34622195723?pr=24359#step:19:181 failed again.

**Comment by mayankvadariya** [comment]
@ebyhr please update the PR with the latest commits from source PR.

**Comment by ebyhr** [comment]
Updated.

**Comment by mayankvadariya** [comment]
Finally redshift tests are passing https://github.com/trinodb/trino/actions/runs/12462869117/job/34784444202?pr=24359 with https://github.com/trinodb/trino/pull/24117/commits/b93a8f0e86bf6c71466c3a22787522640b3d1c66 commit. TY @raunaqmorarka for helping me put the right fix.

**Comment by mayankvadariya** [comment]
@ebyhr please update the PR with the latest commits from source PR.

**Comment by mayankvadariya** [comment]
It seems unload tests are passing but Redshift job is timing out. @ebyhr can you please rerun redshift job?
https://github.com/trinodb/trino/actions/runs/12521687438/job/34929074733?pr=24359#step:19:453



```
[INFO] Tests run: 33, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 826.6 s -- in io.trino.plugin.redshift.TestRedshiftUnload
[INFO] Tests run: 41, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 622.9 s -- in io.trino.plugin.redshift.TestRedshiftUnloadTypeMapping
```

**Comment by mayankvadariya** [comment]
@hashhar @Praveen2112 @wendigo can you please help me rerun failing jobs including Redshift one? 
https://github.com/trinodb/trino/actions/runs/12521687438/job/34929074733?pr=24359

**Comment by wendigo** [comment]
@mayankvadariya I did and it failed again

**Comment by mayankvadariya** [comment]
Thank you @wendigo. Let's wait for the third run to finish https://github.com/trinodb/trino/actions/runs/12521687438/job/34987834854?pr=24359
If it fails again with the timeout then, can you please push a temporary commit with increased timeout in ci.yml?

**Comment by wendigo** [comment]
@mayankvadariya the failure was due to a deadlock, not a timeout so I guess it won't help

**Comment by mayankvadariya** [comment]
Closing as source PR https://github.com/trinodb/trino/pull/24117 has been merged.

**Pull request closed without merging**
