### PR TITLE
Test: Add Delta Lake connector

### PR DESCRIPTION
**Pull request by findepi**
Test https://github.com/trinodb/trino/pull/10897

### CODE REVIEW

**Comment by findepi** [comment]
cc @jirassimok @alexjo2144 @nineinchnick

**Comment by findepi** [comment]
@alexjo2144 @jirassimok please check the secrets-related CI stuff

**Comment by jirassimok** [comment]
I got the secret names wrong, oops. My latest push to the original PR should fix it.

**Comment by findepi** [comment]
Updated for https://github.com/trinodb/trino/pull/10897#discussion_r815699466
cc @jirassimok @nineinchnick

**Comment by ebyhr** [comment]
I rebased on #10897 based on @jirassimok request.

**Comment by findepi** [comment]
Updated with the current state of the PR

**Comment by findepi** [comment]
CI https://github.com/trinodb/trino/issues/11196, something else, and something legitimate.

**Pull request closed without merging**
