### PR TITLE
Fix wrong row values in column channel in tpcds queries q05, q14, q49, q76, q80

### PR DESCRIPTION
**Pull request by przemekak**

### CODE REVIEW

**Review by losipiuk — APPROVED** [review]
How did problem manifest?

**Comment by losipiuk** [comment]
Probably better commit name would be:
`Fix column alias in TPC-DS queries q05, q14, q49, q76, q80`

**Comment by przemekak** [comment]
@losipiuk 
Result would contain name of the used catalog and schema instead of just the name of collection:
e.g.:
...
tpcds.sf10.store,71637,0.0000,1,83
tpcds.sf10.store,53513,0.0000,1,94
tpcds.sf10.store,55395,0.6327,3,2
tpcds.sf10.store,5537,0.6495,4,1
...
So we would have different results for such queries if we use different connector/schema.
And column name was stable, actual values in columns `channel` are different.

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
> `Fix column alias in TPC-DS queries q05, q14, q49, q76, q80`

note that it's not _alias_ what changed.

**Comment by losipiuk** [comment]
> > `Fix column alias in TPC-DS queries q05, q14, q49, q76, q80`
> 
> note that it's not _alias_ what changed.

Yeah - right - my bad.

**Pull request merged**
