### PR TITLE
Fix error-prone violation in trino-server-rpm

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Review by nineinchnick — APPROVED** [review]

**Review by losipiuk — APPROVED** [review]

**Comment by wendigo** [comment]
This is new: 
```
#  SIGSEGV (0xb) at pc=0x00007f14fa61fcd1, pid=2495, tid=2628
#
# JRE version: OpenJDK Runtime Environment Temurin-22+36 (22.0+36) (build 22+36)
# Java VM: OpenJDK 64-Bit Server VM Temurin-22+36 (22+36, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x81fcd1][thread 2610 also had an error]
  G1ParScanThreadState::trim_queue_to_threshold(unsigned int)+0x3861
```

https://github.com/adoptium/adoptium-support/issues/959

**Comment by findepi** [comment]
> # JRE version: OpenJDK Runtime Environment Temurin-22+36 (22.0+36) (build 22+36)

is this related to https://github.com/trinodb/trino/pull/21161?

**Comment by wendigo** [comment]
@findepi rather to the reduced memory than to a jdk 22

**Comment by findepi** [comment]
might be, agreed! but did we reduce memory for maven main process or for tests (https://github.com/trinodb/trino/pull/21256)?
BTW it says SIGSEGV rather than "out of memory".

**Comment by wendigo** [comment]
@findepi the linked bug manifests itself during high-memory pressure scenarios hence the assumption. Let's monitor this

**Comment by findepi** [comment]
not sure which part of the linked bug (https://github.com/adoptium/adoptium-support/issues/959) apply to our case. it says Java 21 but it also says it's resolved for some time

**Pull request merged**
