### PR TITLE
Iceberg: remove useless todo list for residual expression

### PR DESCRIPTION
**Pull request by caneGuy**
Since 'applyFilter' has been implemented for Iceberg Connector, so the todo list is useless now

### CODE REVIEW

**Comment by findepi** [comment]
What is a residual expression?

**Comment by caneGuy** [comment]
> What is a residual expression?

IIUC it was row filter for 'FileScanTask' in iceberg @findepi

**Review by electrum — APPROVED** [review]
These TODO are indeed outdated as we handle this now with `unenforcedPredicate` which is used in `IcebergPageSourceProvider` and `applyFilter()`.

**Comment by caneGuy** [comment]
> These TODO are indeed outdated as we handle this now with `unenforcedPredicate` which is used in `IcebergPageSourceProvider` and `applyFilter()`.

Thanks @electrum i have submit a cla file to cla@trino.io. But i still can not cla-check workload, could you help me figure out what i missed?

**Comment by electrum** [comment]
@caneGuy apologies for the delay on processing the CLA. @martint will follow up shortly

**Comment by caneGuy** [comment]
> @caneGuy apologies for the delay on processing the CLA. @martint will follow up shortly

Thanks @electrum @martint

**Comment by caneGuy** [comment]
@electrum @martint could help review this? thanks

**Comment by caneGuy** [comment]
cc @findepi could you help review this?thanks

**Comment by findepi** [comment]
@cla-bot check

**Comment by findepi** [comment]
Merging per  https://github.com/trinodb/trino/pull/8718#pullrequestreview-720697067

**Comment by findepi** [comment]
Merged, thanks!

**Comment by caneGuy** [comment]
Thanks @findepi

**Pull request merged**
