### PR TITLE
Update docker-images to v56

### PR DESCRIPTION
**Pull request by wendigo**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

> How would you describe this change to a non-technical end user or system administrator?

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by wendigo** [comment]
Only failure is:

```
.spi.TrinoException: Failed to commit to table default.test_insert_concurrent_1t3m941y6gr2
presto-master       | 	at io.trino.plugin.iceberg.catalog.hms.HiveMetastoreTableOperations.commitToExistingTable(HiveMetastoreTableOperations.java:102)
presto-master       | 	at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.commit(AbstractIcebergTableOperations.java:145)
presto-master       | 	at org.apache.iceberg.BaseTransaction.lambda$commitSimpleTransaction$5(BaseTransaction.java:363)
presto-master       | 	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404)
presto-master       | 	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214)
presto-master       | 	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198)
presto-master       | 	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190)
presto-master       | 	at org.apache.iceberg.BaseTransaction.commitSimpleTransaction(BaseTransaction.java:348)
presto-master       | 	at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:238)
presto-master       | 	at io.trino.plugin.iceberg.IcebergMetadata.finishInsert(IcebergMetadata.java:584)
presto-master       | 	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:518)
presto-master       | 	at io.trino.metadata.MetadataManager.finishInsert(MetadataManager.java:891)
presto-master       | 	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$3(LocalExecutionPlanner.java:3952)
presto-master       | 	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:318)
presto-master       | 	at io.trino.operator.Driver.processInternal(Driver.java:388)
presto-master       | 	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
presto-master       | 	at io.trino.operator.Driver.tryWithLock(Driver.java:693)
presto-master       | 	at io.trino.operator.Driver.processFor(Driver.java:285)
presto-master       | 	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
presto-master       | 	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
presto-master       | 	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
presto-master       | 	at io.trino.$gen.Trino_9c60bbe____20220405_165751_2.run(Unknown Source)
presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
presto-master       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
presto-master       | 	at java.base/java.lang.Thread.run(Thread.java:829)
presto-master       | Caused by: org.apache.iceberg.exceptions.CommitFailedException: Metadata location [hdfs://hadoop-master:9000/user/hive/warehouse/test_insert_concurrent_1t3m941y6gr2/metadata/00000-eb4b42c0-431d-44a1-b196-7bcf1347478c.metadata.json] is not same as table metadata location [hdfs://hadoop-master:9000/user/hive/warehouse/test_insert_concurrent_1t3m941y6gr2/metadata/00001-83d8c537-a772-4d46-92c0-1cb224ff9004.metadata.json] for default.test_insert_concurrent_1t3m941y6gr2
```

**Comment by Praveen2112** [comment]
Is this failure flaky or ?

**Comment by wendigo** [comment]
@Praveen2112 seems so

**Comment by wendigo** [comment]
@findepi thanks for rerunning. It seems that this failure can be related to https://github.com/trinodb/docker-images/commit/55408599bba009943d5b4e74136bd10094410237

**Comment by wendigo** [comment]
I guess that I'll just wait for https://github.com/trinodb/trino/pull/11642

**Comment by findepi** [comment]
> I guess that I'll just wait for #11642

what's the  relation between the two?

cc @alexjo2144

**Comment by wendigo** [comment]
@findepi seems like there is/was some relation. @alexjo2144 pulled v55 in his PR, so this should be fine right now.

**Review by hashhar — APPROVED** [review]

**Comment by wendigo** [comment]
That's interesting failure:

```
Error:  io.trino.orc.TestSliceDictionaryColumnWriter.testDirectConversion  Time elapsed: 1.301 s  <<< FAILURE!
io.airlift.slice.InvalidCodePointException: Invalid code point 0x1CEAAE
	at io.airlift.slice.SliceUtf8.lengthOfCodePoint(SliceUtf8.java:926)
	at io.airlift.slice.SliceUtf8.codePointToUtf8(SliceUtf8.java:1053)
	at io.trino.orc.metadata.statistics.StringStatisticsBuilder$StringCompactor.truncateMax(StringStatisticsBuilder.java:240)
	at io.trino.orc.metadata.statistics.StringStatisticsBuilder.computeStringMinMax(StringStatisticsBuilder.java:191)
	at io.trino.orc.metadata.statistics.StringStatisticsBuilder.buildStringStatistics(StringStatisticsBuilder.java:135)
	at io.trino.orc.metadata.statistics.StringStatisticsBuilder.buildColumnStatistics(StringStatisticsBuilder.java:147)
	at io.trino.orc.writer.SliceDictionaryColumnWriter.finishRowGroup(SliceDictionaryColumnWriter.java:312)
	at io.trino.orc.TestSliceDictionaryColumnWriter.testDirectConversion(TestSliceDictionaryColumnWriter.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/issues/11847

**Pull request merged**
