### PR TITLE
Use JDK 17 based image for Server IT

### PR DESCRIPTION
**Pull request by Praveen2112**
## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by nineinchnick — APPROVED** [review]

**Review by hashhar — APPROVED** [review]
All other usages of the image are pinned to a version so not failing yet but will start failing on next docker-images update.

**Comment by nineinchnick** [comment]
The failures in tests are caused by treating an empty impacted modules list as a signal to run all tests. The list is empty because the rpm module is excluded when running `mvn validate`.

@Praveen2112 can you also add these changes?
```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index f02c356b6d5..fc074784184 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -408,7 +408,7 @@ jobs:
       - name: Maven validate
         run: |
           export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
-          $RETRY $MAVEN validate ${MAVEN_FAST_INSTALL} ${MAVEN_GIB} -Dgib.logImpactedTo=gib-impacted.log -P disable-check-spi-dependencies -pl '!:trino-docs,!:trino-server,!:trino-server-rpm'
+          $RETRY $MAVEN validate ${MAVEN_FAST_INSTALL} ${MAVEN_GIB} -Dgib.logImpactedTo=gib-impacted.log -P disable-check-spi-dependencies -pl '!:trino-docs'
       - name: Set matrix
         id: set-matrix
         run: |
@@ -658,7 +658,7 @@ jobs:
       - name: Map impacted plugins to features
         run: |
           export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
-          $MAVEN validate ${MAVEN_FAST_INSTALL} ${MAVEN_GIB} -Dgib.logImpactedTo=gib-impacted.log -pl '!:trino-docs,!:trino-server-rpm'
+          $MAVEN validate ${MAVEN_FAST_INSTALL} ${MAVEN_GIB} -Dgib.logImpactedTo=gib-impacted.log -pl '!:trino-docs'
           # GIB doesn't run on master, so make sure the file always exist
           touch gib-impacted.log
           testing/trino-plugin-reader/target/trino-plugin-reader-*-executable.jar -i gib-impacted.log -p core/trino-server/target/trino-server-*-hardlinks/plugin > impacted-features.log
```

**Comment by nineinchnick** [comment]
It can be a separate commit, before the one you have right now. It should be merged.

**Comment by nineinchnick** [comment]
I was considering doing this in a separate PR but I'd have to duplicate your change in the rpm module anyway.

**Comment by Praveen2112** [comment]
@nineinchnick Applied it.

**Comment by Praveen2112** [comment]
@nineinchnick I think we can handle them in a different PR.

**Comment by nineinchnick** [comment]
I added a fix for the tests/exclusion issue in https://github.com/trinodb/trino/pull/12854 and tested it in https://github.com/nineinchnick/trino/pull/14

**Comment by Praveen2112** [comment]
@nineinchnick Should we worry about the test failures here ?

**Comment by Praveen2112** [comment]
Maven checks were successful.

**Comment by findepi** [comment]
> Use JDK 17 based image for Server IT

What changed? I guess Java 17 was used even before the change, just with a different image, otherwise the container wouldn't start at all, would it?

**Pull request merged**
