### PR TITLE
Support sort merge join

### PR DESCRIPTION
**Pull request by sleep1661**
## Description

Supporting sort merge join, a more stable join implementation for equi joins between large tables, would be better suited for the stability requirements of joins in batch processing ETL scenarios.

Explanation of the Implementation Process:
1. Define a new `PlanNode` - `SortMergeJoinNode`. Compared to `JoinNode`, `SortMergeJoinNode` adds `needSortLeft` and `needSortRight` properties to indicate whether the left and right sub-PlanNodes need to be sorted to achieve sort elimination optimization.
2. Add the optimization rule `TransformHashJoinToSortMergeJoin`, which can convert `JoinNode` to `SortMergeJoinNode` under certain conditions.
3. Add the optimization rule `EliminateSortOptimizer`, which can eliminate sort in certain scenarios where multiple tables trigger sort merge join, by changing the `needSortLeft` and `needSortRight` properties of `SortMergeJoinNode`.
4. The worker node uses the `LocalExecutionPlanner::Visitor::visitSortMergeJoin` method to parse the `SortMergeJoinNode` in the plan fragment and convert it into an operator pipeline of two left and right side `SortMergeJoinOperators`.
5. The worker node will decide whether to sort the left and right child nodes based on the `needSortLeft` and needSortRight properties of the `SortMergeJoinNode`. For those that require sorting, a preceding `OrderByOperator` will be added to each child node to ensure the correct sorting order.
6. The `SortMergeJoinProbeOperator` selects different join scanners based on the join type and currently supports four join types - inner join, left join, right join, and full join.

## Additional context and related issues

issue:  https://github.com/trinodb/trino/issues/17422

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
(x) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by linzebing** [comment]
@sleep1661 : also, didn't look into the details of implementation, but I would assume spilling would be needed to use SMJ effectively?

**Comment by sleep1661** [comment]
> 

There are two situations where partitioned hash join may fail due to insufficient memory:
1. The worker memory is relatively small, and at the same time, the fault-tolerant-execution-partition-count parameter configured for the cluster is also small. If the join process encounters a relatively large build table, it is likely to fail due to insufficient memory. Of course, this situation can be improved by adjusting the `fault-tolerant-execution-partition-count`. For many ETL tasks in production, it is not possible to finely evaluate and optimize the `fault-tolerant-execution-partition-count` for each one.
2. As you mentioned, in the case of data skew, if the worker memory cannot accommodate a certain partition with data skew, it can only fail.

Partitioned hash join can work normally in most cases, but there is a higher probability of failure in the above situations. In production, ETL batch job require more stable joins, and may tolerate slower performance. According to our actual performance test results, the performance of SMJ degraded by about 10% for partitioned hash join.

**Comment by sleep1661** [comment]
> @sleep1661 : also, didn't look into the details of implementation, but I would assume spilling would be needed to use SMJ effectively?

Yes, SMJ requires spilling capability, and there are two situations that may trigger spilling to disk:
1. When the sorting process does not have enough memory to hold the entire partition data. (`OrderByOperator`)
2. When the build side of the merge join has a large number of records for a join key that cannot be loaded into memory. (`SpillableMatchedPages`)

**Comment by arhimondr** [comment]
I may not be able to get to this any time soon. @trinodb/maintainers Does anyone want to run a first pass?

**Comment by nikita-sheremet-java-developer** [comment]
@arhimondr, @hackeryang, @linzebing

I also appologies if I'm bothering you, but are there any plans to release this in a feature?

@sleep1661 are you planning to rebase this on last version?

To say the truth ability to use worker with small RAM for large tables is a killer feature. Especially for situation wtih small clusters. My team considering switching from Spark to Trino even in ETL processes but joining 1Tb table fails with `Insufficient Resources` error. SMJ makes Trino a eal replacement for Spark in ETL. Of cource we can spin up a cluster with more memory but this will significant costs.

About spilling - as far as I know there are plans for removing it. Any thoughts about SMJ works with/without spilling?

I am not Trino developer but if you need some help I will try to do something.

Again please accept my apologies if I'm bothering you. 

Waiting for your opinions. A lot of thanks in advance!

**Comment by nikita-sheremet-java-developer** [comment]
Does anybody consider to release this feature with enbaling/disabling flag and/or mark this feature as experimental? In this case we will get feature released and ability to swith back to default implementation when/if something goes wrong.

**Pull request closed without merging**
