### PR TITLE
Test: Adapt Delta product tests for execution on top of Databricks backed by AWS Glue

### PR DESCRIPTION
**Pull request by findepi**
Test https://github.com/trinodb/trino/pull/12896 with secrets

cc @findinpath @alexjo2144 @ebyhr

### CODE REVIEW

**Comment by findepi** [comment]
Updated to current state of https://github.com/trinodb/trino/pull/12896

**Comment by findepi** [comment]
Updated to current state of https://github.com/trinodb/trino/pull/12896

**Comment by ebyhr** [comment]
@findinpath Updated to the latest status.

**Comment by findepi** [comment]
Updated to current state of https://github.com/trinodb/trino/pull/12896

**Comment by ebyhr** [comment]
Updated to current state of #12896

**Pull request closed without merging**
