### PR TITLE
Test: Add register_table procedure support for iceberg table

### PR DESCRIPTION
**Pull request by ebyhr**
Run tests with secret #14375

### CODE REVIEW

**Comment by krvikash** [comment]
Hi @ebyhr, Can we rebase again with the latest change in https://github.com/trinodb/trino/pull/14375?

**Comment by ebyhr** [comment]
Updated.

**Comment by krvikash** [comment]
> Updated.

Thanks, @ebyhr. Can you rebase again with the latest change?

**Comment by ebyhr** [comment]
Sure, updated.

**Pull request closed without merging**
