### PR TITLE
Fix updating PR comments from tests with secrets workflow

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

Don't use `always()` in step condition with additional predicates, because it ignores other predicates.

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by nineinchnick** [comment]
Example failed run: https://github.com/trinodb/trino/actions/runs/5482967673/jobs/9988837361

**Review by wendigo — APPROVED** [review]

**Comment by nineinchnick** [comment]
@wendigo can you merge this?

**Comment by wendigo** [comment]
@nineinchnick I'm not sure whether it fixes things

**Comment by nineinchnick** [comment]
The workflow is broken so we can't break it more :-)

**Comment by wendigo** [comment]
Let's see whether it helps

**Pull request merged**
