### PR TITLE
Introduce RankingBuilder and streaming way to calculate rank

### PR DESCRIPTION
**Pull request by qqibrow**
Fixes: https://github.com/prestosql/presto/issues/1073

Still work in progress, needs further refactoring before review.

### CODE REVIEW

**Comment by findepi** [comment]
@KathrynMO we don't have your CLA on file yet. Could you please sign the CLA? Follow the instructions at https://github.com/prestosql/cla.

**Comment by findepi** [comment]
@cla-bot check

**Comment by sopel39** [comment]
@qqibrow would you continue work on this?

**Comment by qqibrow** [comment]
sorry. I am not actively working on this anymore.

**Comment by sopel39** [comment]
> sorry. I am not actively working on this anymore.

Are you OK if we pick it up?

**Comment by qqibrow** [comment]
@sopel39 sure. Ping me if you I can help in any other ways. thanks!

**Comment by colebow** [comment]
@sopel39  - if you'd like to pick up work on this at any point in the future, it'd probably be best to open another PR, so it's best to close this out.

**Pull request closed without merging**
