### PR TITLE
Add Deploy on Kubernetes Doc (on Plural)

### PR DESCRIPTION
**Pull request by avaidyanatha**
## Main Changes

- Added a guide on how to deploy Trino on a Kubernetes cluster in one's own cloud with Plural.
- This is a docs-only change.

## Why is this valuable?

A user-friendly, open-source way to deploy Trino on self-hosted Kubernetes is valuable as a happy path for individuals that want a simplified DevOps experience within their organization.

## Full Description

[Plural](https://www.plural.sh/) is a platform that offers a path to easily self-hosting Trino on Kubernetes. I've added a document on how one can spin up a Trino instance on Kubernetes in their own cloud with the CLI.

It offers a lot of post deployment features to monitor deployments, authentication with OIDC, and is a good learning tool for becoming more familiar with Kubernetes as a whole. Additionally, all the configuration (K8s YAML, Helm, Terraform) is fully ejectable, so you can eject from the Plural platform if needed.

## Testing Notes

I built the docs locally and ran the docsite locally to validate all changes!

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by findepi** [comment]
Thank you for your contribution!

What's specific about Trino that makes you think this Plural guide should be hosted here and not at https://plural.sh/ ?

**Comment by avaidyanatha** [comment]
> Thank you for your contribution!
> 
> What's specific about Trino that makes you think this Plural guide should be hosted here and not at https://plural.sh/ ?

Plural is more of an implementation detail at the end of the day, but the guide goes over specifically getting Trino up and running on a self-hosted Kubernetes instance.

As an aside, I also talked to @brianzhan and I think he ran this by the docs team!

**Comment by findepi** [comment]
> Plural is more of an implementation detail at the end of the day,

In the interest of full disclosure, you could also mention that the main reason you're doing this PR is because you work for Plural :) 

> but the guide goes over specifically getting Trino up and running on a self-hosted Kubernetes instance.

@nineinchnick what is the simplest way to deploy Trino on a self-hosted Kubernetes instance?
Does plural come pre-installed with a self-hosted Kubernetes instance? If no, Is Trino installation convoluted enough that we would want users to use additional dependencies?

**Comment by nineinchnick** [comment]
> > Plural is more of an implementation detail at the end of the day,
> 
> In the interest of full disclosure, you could also mention that the main reason you're doing this PR is because you work for Plural :)
> 
> > but the guide goes over specifically getting Trino up and running on a self-hosted Kubernetes instance.
> 
> @nineinchnick what is the simplest way to deploy Trino on a self-hosted Kubernetes instance? Does plural come pre-installed with a self-hosted Kubernetes instance? If no, Is Trino installation convoluted enough that we would want users to use additional dependencies?

Right now, the preferred way of deploying Trino on Kubernetes is to use the Helm chart: https://github.com/trinodb/charts. We do want to add this to docs, but without mentioning any specific Kubernetes distribution.

**Comment by mosabua** [comment]
Agreed @nineinchnick  .. we are in the process of adding a page about K8s and the Helm chart .. after that is done we can add another one that expands on that content and focusses on using Plural

**Comment by mosabua** [comment]
@avaidyanatha this PR has been left without any updates from your end. Since you submitted the PR we added proper Docker and Kubernetes documentation. We can still think about adding some plural documentation, but it might be best to have that on your site and we just link to it from our documentation as an alternative. 

I am also happy meet and chat about details.

**Comment by avaidyanatha** [comment]
@mosabua The branch was pretty bricked a while ago to merge conflicts 😅 Yeah, if we could meet to go over this that would be great - I'll check in on the Trino Slack.

**Pull request closed without merging**
