### PR TITLE
Add alias support in Having predicate

### PR DESCRIPTION
**Pull request by DoubleDue**
Solve issue https://github.com/trinodb/trino/issues/8582#issue-946713398 Alias not support in Having predicate #8582

image-20210717124201855

### CODE REVIEW

**Review by findepi — CHANGES_REQUESTED** [review]
This behavior was correct and per SQL specification.

Note that while it looks like a benign departure from a spec -- some queries that didn't work will now work --  it would actually change semantics of certain queries that used to work previously.

cc @martint @kasiafi

**Comment by kasiafi** [comment]
Logically, the `HAVING` clause is applied before the `SELECT` clause. Its purpose is to filter out groups of the source table, and not to filter the `SELECT` results. It shouldn't "see" the aliases assigned to the output columns.
The proposed change might affect the semantics of certain queries -- particularly when an output column alias "overrides" a source column.

Consider this example:
```
trino> WITH t(a, total) AS (
    ->                      VALUES
    ->                             (1, 100),
    ->                             (2, 200),
    ->                             (3, 300)
    ->                     )
    -> SELECT count(a) total
    -> FROM t
    -> GROUP BY total
    -> HAVING total > 50;
```

current result:
```
 total
-------
     1
     1
     1
(3 rows)
```

After the change, the result would probably be:
```
 total
-------
     0
     0
     0
(3 rows)
```

**Comment by DoubleDue** [comment]
@kasiafi Although this is a rare case, it does exist. I fixed this in my latest commit.

**Comment by martint** [comment]
The SQL specification is very clear about how column references in the HAVING clause are resolved:

>  3) Each column reference directly contained in the `<search condition>` shall be one of the following:
>  a) An unambiguous reference to a column that is functionally dependent on G.
>  b) An outer reference.
> 4) Each column reference contained in a `<query expression>` in the `<search condition>` that references a column of T shall be one of the following:
>  a) An unambiguous reference to a column that is functionally dependent on G.
>  b) Contained in an aggregated argument of a `<set function specification>`.

In particular, the following query would not behave as expected with the proposed change if there's a column named `total` in table `u`:

```
SELECT * 
FROM u
WHERE EXISTS (
    SELECT count(*) AS total
    FROM t
    HAVING total > 5
)
```

**Comment by DoubleDue** [comment]
@martint Thank you for your comments, i test your sql in my second commit version and found it has the same result as before, I wonder if there's anything I haven't thought about yet.

**Comment by kasiafi** [comment]
> i test your sql in my second commit version and found it has the same result as before

I'm pretty sure the results should differ for:
```
trino> WITH u(total) AS (VALUES -100), t AS (VALUES 1, 2, 3, 4, 5, 6)
    -> SELECT *
    -> FROM u
    -> WHERE EXISTS (
    ->     SELECT count(*) AS total
    ->     FROM t
    ->     HAVING total > 5
    -> );
```

**Pull request closed without merging**
