### PR TITLE
Fix decode of URI path

### PR DESCRIPTION
**Pull request by guyco33**
Fixes https://github.com/trinodb/trino/issues/17621

## Release notes

( x) Release notes are required, with the following suggested text:

```markdown
# Hive connector
* Fix query failure for paths containing special characters. ({issue}`17621`)
```

### CODE REVIEW

**Comment by mosabua** [comment]
Fyi @martint  .. please check if this is really a release blocker and potentially halt any release

**Comment by findepi** [comment]
please add test cases in BaseTestTrinoS3FileSystemObjectStorage

**Comment by guyco33** [comment]
> please add test cases in BaseTestTrinoS3FileSystemObjectStorage

I will add this test although the issue occurs while getting string from URI object without decoding it

**Comment by mosabua** [comment]
Any chance you can look at this soon @electrum .. ideally we would like to merge and cut a new release again on Wednesday.

**Comment by guyco33** [comment]
`testRecursiveDirectoriesWithSpecialCharacters` can easily demonstrate the issue when `hive.recursive-directories=true` 
Successfully creating the partitioned table and failing to select it after.

**Review by electrum — APPROVED** [review]

**Pull request merged**
