### PR TITLE
Fix GroupedInOut estimatedSizeOf method definition

### PR DESCRIPTION
**Pull request by wendigo**
It didn't account for memory retained in `value` and `valueIdNull` fields.

Now the generated class looks like this:

```
public final class GroupedInOut_20240405_170804_120 implements InOut, GroupedAccumulatorState, InternalDataAccessor {
    private int groupId;
    private final LongBigArray value = new LongBigArray();
    private final BooleanBigArray valueIdNull = new BooleanBigArray(true);
    private static final long INSTANCE_SIZE = (long)SizeOf.instanceSize(GroupedInOut_20240405_170804_120.class);

    public long getEstimatedSize() {
        long size = INSTANCE_SIZE;
        size += this.value.sizeOf();
        size += this.valueIdNull.sizeOf();
        return size;
    }
```

All credit goes to @lukasz-stec

### CODE REVIEW

**Comment by wendigo** [comment]
I've checked other classes and they seem to have correct `getEstimatedSize` methods

**Review by lukasz-stec — APPROVED** [review]
lgtm but I would love to see a test to validate it works.

**Comment by wendigo** [comment]
@lukasz-stec I've added a simple test. Let me know your thoughts

**Review by dain — APPROVED** [review]
One comment.  Also, can you squash the commits?

**Comment by wendigo** [comment]
@dain sure, comment applied & squashed

**Comment by colebow** [comment]
Does this need a release note? cc @wendigo

**Comment by wendigo** [comment]
Yes @colebow. It fixes a situation when worker can ran out of memory when processing queries with GROUP BY clauses

**Comment by hashhar** [comment]
```
# General
* Fix possible worker crashes when running aggregation queries due to out-of-memory error.
```

**Comment by wendigo** [comment]
@hashhar perfection :)

**Pull request merged**
