### PR TITLE
Clean up exclusions on alluxio dep

### PR DESCRIPTION
**Pull request by mosabua**
## Description

As discussed on slack with @electrum and @wendigo 

https://trinodb.slack.com/archives/CP1MUNEUX/p1706892319598769

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Comment by mosabua** [comment]
Waiting to see how the build goes

**Comment by wendigo** [comment]
@mosabua build will be fine, these dependencies will be just a part of the final artifact and we don't want that

**Comment by mosabua** [comment]
I guessed as much but will wait for build and appproval anyway  .. I think Iceberg is just about to go in

**Review by wendigo — APPROVED** [review]

**Comment by wendigo** [comment]
I've checked locally dependency:tree and it looks good.

**Pull request merged**
