### PR TITLE
Add bing_tile_quadkey() to list.rst

### PR DESCRIPTION
**Pull request by Damans227**
**What this PR does / why we need it:**
Add documentation for `bing_tile_quadkey()` in trino/docs/src/main/sphinx/functions/list.rst

**Which issue(s) this PR fixes:**
Document bing_tile_quadkey function #7653

**Special notes for your reviewer:**
Please share feedback

### CODE REVIEW

**Review by hashhar — APPROVED** [review]
Thank you.

Can you also add other missing links like `format_datetime`?
You can search for "- ``"  to find such occurrences in `list.rst`.

**Comment by Damans227** [comment]
> Thank you.
> 
> Can you also add other missing links like `format_datetime`?
> You can search for `` - `` `` to find such occurrences in `list.rst`.

Sure, I have added all the missing links. Please review. Thanks!

**Review by hashhar — APPROVED** [review]
Thanks @Damans227, LGTM. @mosabua PTAL.

The links whose targets don't exist yet show up as in the image which is fine I think and it'll help make sure they automatically get linked once someone documents them.
image

**Comment by findepi** [comment]
> The links whose targets don't exist yet show up as in the image which is fine I think and it'll help make sure they automatically get linked once someone documents them.

I like this from list.rst perspective.
OTOH, i would like invalid references to be reported during docs build (as any invalid link).
If we run into a case of a historical document like release notes that talks about a function
that has been removed (extremely rare, but possible), we can perhaps replace the link with 
a preformatted text.

@hashhar would such a check be possible? (opt: would it be possible to exclude list.rst from it?)

**Comment by mosabua** [comment]
I have added all the function names in the past so we can document them. You can only add func references to the ones where documentation exists. Otherwise the build fails (and it should). Update the PR to this and it should be good. We are trying to get better coverage with all functions having docs .. list.rst is basically our reference to tell what is still missing based on the missing `func` and I created separate github issues for them all and we continue to do that. 

We should NOT use func for any function that is not yet documented.

**Comment by Damans227** [comment]
> I have added all the function names in the past so we can document them. You can only add func references to the ones where documentation exists. Otherwise the build fails (and it should). Update the PR to this and it should be good. We are trying to get better coverage with all functions having docs .. list.rst is basically our reference to tell what is still missing based on the missing `func` and I created separate github issues for them all and we continue to do that.
> 
> We should NOT use func for any function that is not yet documented, the rendering is already different.

Thank you for the clarification. I have updated the PR accordingly. Please review.

**Review by mosabua — APPROVED** [review]
Sorry for the misunderstanding. This is good to go .. and you can send more PRs for all the other missing links and documentation for the other functions ;-)

**Review by hashhar — APPROVED** [review]
Thanks @Damans227 for the PR.

Thanks @mosabua for clearing up why some links are intentionally missing.

**Pull request merged**
