### PR TITLE
Verify table name existence in EXPLAIN result

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Verify table name existence in EXPLAIN result

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

**Review by martint — CHANGES_REQUESTED** [review]
TableHandles are not (and should not be) required to have a toString() that includes the table name, so this is putting a constraint on them that doesn't exist today. If we want to ensure the table table name in the plan output, we need to change the plan IR itself to include it.

**Comment by ebyhr** [comment]
This was a request from @findepi. Closing as I have the same concern.

**Comment by findepi** [comment]
> TableHandles are not (and should not be) required to have a toString() that includes the table name, so this is putting a constraint on them that doesn't exist today.

This PR does not introduce any new requirements on table handles. This is **not** a SPI change.

All it does it encodes (in a form of a test) the design assumptions for the plugins we ship with Trino. All plugins shipped with Trino intentionally implement toString in their TableHandles and intentionally return table name in that toString (some departures from that rule are being fixed in this PR)

 > change the plan IR itself to include it, or derive it from the plan IR when printing the output of EXPLAIN.

i am fine with such a change, but that would actually be hard to do. The intermediate relations represented by TableHandle  something do not have any usable SchemaTableName.  This can be the case for example after aggregation or join pushdown. Requiring a connector to give a name to things that do not have a name, leads to made-up names such as `_generated._generated_query`. Printing them in EXPLAIN wouldn't be useful. Also, TableHandle.toString (as currently included in EXPLAIN output) **may** contain more useful information beyond table name (like applied predicates, etc.). We do not need to include toString in EXPLAIN output, but it would be a failure, if we didn't give connectors a way to include information beyond just the name.

**Comment by findepi** [comment]
Having said that... @ebyhr would you consider reopening the PR?

**Comment by ebyhr** [comment]
Reopened https://github.com/trinodb/trino/pull/18626

**Pull request closed without merging**
