### PR TITLE
Modify alluxio version to stable 2.9.5

### PR DESCRIPTION
**Pull request by jja725**
## Description
2.9.4 is a more stable version and we would keep backporting changes from 3xx to 2.9.x line. With 2.9.4 we would have the same code of local cache manager as 3xx and compatibility with the stable Alluxio Filesystem interface. That's why we chose to have 2.9.4 here

## Additional context and related issues
https://github.com/trinodb/trino/pull/21603/files#r1628261795

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
(x) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by wendigo — CHANGES_REQUESTED** [review]
Claim that 2.9.4 is "more stable" lacks evidence. Is there any issue that 2.9.4 solves?

**Comment by jja725** [comment]
> Claim that 2.9.4 is "more stable" lacks evidence. Is there any issue that 2.9.4 solves?
Hi thanks for raising the concern, 2.9.x is the stable branch that we have been tested in customer env for a long time. While 3xx is still a beta version that have breaking compatibility changes so that's why we want to avoid bring it into Trino in early stage. Regarding the local cache manager Trino is using right now, 2.9.4 & 312 should have the exactly same code.

**Comment by wendigo** [comment]
There are related failures.

**Review by mosabua — COMMENTED** [review]
If this version is truly more stable and works I am fine with the downgrade but it needs to pass CI and we need evidence from people using it in practice that this works. For example @jkylling or @raunaqmorarka might be able to test it a bit better.

Also why do we need all these additional exclusions .. it the upstream dependency declaration a lot more messed up than in 312?

**Comment by Pluies** [comment]
fwiw we at Dune used to run 2.9.3 here, with extra fixes to work around issues that got fixed in alluxio master later. We're (literally just now) moving to Trino 448's official caching code relying on alluxio 312, so we won't have experience running 2.9.4 in prod.

**Comment by Pluies** [comment]
That said I agree with the comments above; if the 2.x.x is the stable branch then I don't see any issue using it. Hopefully we should have enough coverage in CI to ensure that once everything is green, the caching code is fine 👍

**Comment by wendigo** [comment]
Thanks @jja725

**Comment by jja725** [comment]
@wendigo thanks for the quick merge!

**Pull request merged**
