### PR TITLE
Update GitHub action versions

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

The new artifacts upload action claims to be almost 100% faster. This should free up the CI queue a bit.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by hashhar** [comment]
add pr description to commit title. also clarify which specific update helps with upload speed either in commit message or extracting a commit.

**Comment by nineinchnick** [comment]
@hashhar done! I compared uploads of PT artifacts - this is the biggest one, whole Trino tarball:
* this branch, 41s - https://github.com/trinodb/trino/actions/runs/7248052559/job/19743225221?pr=20156
* master, 4m - https://github.com/trinodb/trino/actions/runs/7247045505/job/19740172322

**Review by wendigo — APPROVED** [review]

**Comment by wendigo** [comment]
Failures related

**Comment by nineinchnick** [comment]
Doesn't look like it's stable enough yet, in two our of two runs there was a request timeout in one of the PT jobs.

**Pull request closed without merging**
