### PR TITLE
Continue to use old valid config if new one fails validation

### PR DESCRIPTION
**Pull request by ssanthanam185**
Currently if the Resource Group DB is updated with an incorrect entry, for example sub-groups are added a queue with SCHEDULED fair algorithm & one of the subgroups is missing a weight, then all subsequent submitted queries fail with error 

```
io.prestosql.spi.PrestoException: Selectors cannot be fetched from database
	at io.prestosql.plugin.resourcegroups.db.DbResourceGroupConfigurationManager.match(DbResourceGroupConfigurationManager.java:161)
	at io.prestosql.execution.resourcegroups.InternalResourceGroupManager.selectGroup(InternalResourceGroupManager.java:120)
	at io.prestosql.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:183)
	at io.prestosql.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:148)
	at io.prestosql.$gen.Presto_338_1____20200908_111254_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	CONFIGURATION_UNAVAILABLE (65560)
```

This PR addresses the following : 
If the DB Resource group is updated with a buggy config, the auto-refresh doesnt load the new faulty config & continues to use the old valid configs. The metric presto.plugin.resourcegroups.db:name=DbResourceGroupConfigurationManager.RefreshFailures will be updated to indicate the latest update failed. 

In case of a cold-start; i.e if the very first time the DB is loaded & and the config is faulty then the behavior will default to failing all subsequent submitted queries

### CODE REVIEW

**Comment by ssanthanam185** [comment]
The failing test passes locally & doesnt seem related to the changes in this PR.

**Comment by ssanthanam185** [comment]
Signed CLA was sent on Nov 23rd.

**Review by phd3 — COMMENTED** [review]
The current model is to fail queries *after* a valid configuration has not been loaded for the amount specified in `resource-groups.max-refresh-interval`. Does setting this value to a high acceptable number solve the issue for you? 

I think as an admin, you'd eventually want to fix such an issue in a reasonable amount of time.

**Comment by ssanthanam185** [comment]
@phd3 Agreed, that eventually as an admin you would want to fix the config , the problem however is with the customer impact due to query failures. All of our clusters use the same DB & we encountered an issue where a bad change brought all clusters to a grinding halt with 100% query failures. 

Currently the assumption is that admins will monitor presto.plugin.resourcegroups.db:name=DbResourceGroupConfigurationManager.RefreshFailures and react by fixing / reverting the incorrect entry in the DB.  Since admin doesnt have an easy way to rollback to last valid config , this seems like a safer approach.  This proposed change avoids loading a config that failed validations.  

The negative side effect of setting a large value for maxRefreshInterval is that , in case admin wants to quickly patch /revert. It would take maxRefreshInterval time to recover and bring the clusters back to a healthy state.

**Comment by phd3** [comment]
> The negative side effect of setting a large value for maxRefreshInterval is that , in case admin wants to quickly patch /revert. It would take maxRefreshInterval time to recover and bring the clusters back to a healthy state.

@ssanthanam185  Can you provide an example here? From the [code](https://github.com/prestosql/presto/blob/master/presto-resource-group-managers/src/main/java/io/prestosql/plugin/resourcegroups/db/DbResourceGroupConfigurationManager.java#L140), it looks like as soon as the config is valid, the next refresh happening at the next second will load the latest correct config. So why would it take `maxRefreshInterval` to recover?

**Comment by ssanthanam185** [comment]
@phd3 Apologize, you are aright. The Load/refresh does happen every second : https://github.com/prestosql/presto/blob/8d2ce0e0f403816aed0baaf0656e51f52f8e6287/presto-resource-group-managers/src/main/java/io/prestosql/plugin/resourcegroups/db/DbResourceGroupConfigurationManager.java#L136 . Was under the impression the client controlled config of maxRefresh was for setting how often we want changes to get picked up. 

However, I am wondering if  a malconfig(perhaps just to a sub group deep down in the hierarchy) should globally fail all client queries. It is certainly possible that an admin is unable to rollback within the configured maxRefreshInterval.

Ideal situation would be if DB is updated only after validation passes so that the user is aware of the problem immediately.

**Comment by phd3** [comment]
@ssanthanam185 Thanks for the context. I see your point that once all the queries start failing, fixing the config becomes the only way to resolve the situation. (even a restart won't help)

`resource-groups.max-refresh-interval` is the "tolerance" that we want to allow in such cases. Setting it to an arbitrarily high value (say 365 days) would mean that we can afford such a long delay in fixing the root cause.

Another option is: Instead of relying on setting a high value, we can introduce a new boolean config `resource-groups.db.allow-stale-config`, which ignores `resource-groups.max-refresh-interval`, so `lastRefresh` is never set to 0 after a successful startup. We can set this new config to be false by default.

However, I like the current design which puts an upper bound on what Presto's willing to tolerate while depending on such an external component for one of its core components (i.e. resource management). Would be great to know others' thoughts on this. @electrum ?

**Comment by JamesRTaylor** [comment]
This code change isn't needed for the reason mentioned by @phd3, so I'll go ahead and close this PR.

**Pull request closed without merging**
