### PR TITLE
Add optional location parameter

### PR DESCRIPTION
**Pull request by JulianGoede**
Addresses #5137

Add optional location parameter to Hive procedure `create_empty_partition`.
If no location is provided trino will default to previous behaviour.

Note that I couldn't detect any existing (unit-)tests for this class nor for any other HiveProcedure.
Therefore, I integratively tested against my local hive-metastore instance using the trino-dev server `io.trino.server.DevelopmentServer`.

### CODE REVIEW

**Comment by ebyhr** [comment]
> I couldn't detect any existing (unit-)tests 

@JulianGoede The test exists in `TestHiveConnectorTest`. Please fix the class.

**Comment by findepi** [comment]
What are the security implications of calling this with a location?

**Comment by findepi** [comment]
> however currently there is also no mechanism that prevents a managed table to use the register procedure to create a partition from another location.

correct and that's also why the register procedure is disabled by default

**Comment by findepi** [comment]
that would be safe, but maybe @kokosing has an idea whether we can handle this better?

**Comment by colebow** [comment]
:wave: @JulianGoede - this PR is inactive and doesn't seem to be under development. If you'd like to continue work on this at any point in the future, feel free to re-open.

**Comment by colebow** [comment]
Closing this one out due to inactivity, but please reopen if you would like to pick this back up.

**Pull request closed without merging**
