### PR TITLE
Always use G1GC for product tests

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Comment by wendigo** [comment]
@findepi do you recall why we've used other GC settings for some of the product test environments?

**Comment by findepi** [comment]
> why we've used other GC settings for some of the product test environments?

yes, to reduce memory footprint.

production deployments start with 64GB main memory, and product tests run in a very constraint environment.
Most of them should take less than 4 GB (for all services), and G1 isn't good for such cases.

**Comment by wendigo** [comment]
@findepi since then github workers doubled the memory. It seems that this change builds fine so I'd propose to merge it and observe the stability of the CI and revert if it degrades. WDYT?

**Comment by wendigo** [comment]
@findepi https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

**Comment by findepi** [comment]
i don't see a point in such a change, nor i want to use more when running locally.

**Comment by wendigo** [comment]
@findepi consistency

**Comment by mosabua** [comment]
I agree with the idea that we should use consistent JVM setting across docs, tests, and everything else. Or alternatively if different JVM settings in terms of GC are appropriate we should also expose this fact to users in the docs .. and then test both. In the interest of keeping it simple.. I vote for one setting...

**Comment by findepi** [comment]
> I agree with the idea that we should use consistent JVM setting across docs, tests,

What is the minimal heap size recommended for running Trino?

**Comment by mosabua** [comment]
> > I agree with the idea that we should use consistent JVM setting across docs, tests,
> 
> What is the minimal heap size recommended for running Trino?

I dont think we have such a recommendation as a generic advice.

**Comment by findepi** [comment]
> > What is the minimal heap size recommended for running Trino?
> 
> I dont think we have such a recommendation as a generic advice.

https://trino.io/docs/current/installation/deployment.html

_Large memory allocation beyond 32GB is recommended for production clusters._

**Comment by findepi** [comment]
Agreed! 
but then if we differentiate between "production clusters" and "minimal heap size that it potentially workable for a minimal deployment for simple use cases" then the only rationale given for this PR (https://github.com/trinodb/trino/pull/21311#issuecomment-2071444762) is no longer valid.

**Comment by mosabua** [comment]
Well... even in that case we ideally use the same GC though. Anyway .. this PR is dead so no worries.

**Comment by mosabua** [comment]
In an ideal world we know what GC works best for specific workloads and machine sizes and assemble all that and expose the info to our users. I am not aware we have such knowledge anywhere or even if we tested these things. They also change across Java versions (since GC improvements are always a focus). 

For now .. we only recommend one type of setting to our users in the docs and the idea of this PR is to use and hence validate that setting for all scenarios.

**Comment by martint** [comment]
G1 can function with small heaps too. It’s the default GC in the JVM nowadays.

**Comment by wendigo** [comment]
@martint do you see value in that PR?

**Comment by martint** [comment]
Yes, I think it's a good thing to be consistent across the board with respect to what GC algorithm we use.

**Review by martint — APPROVED** [review]

**Comment by findepi** [comment]
Does switching over to G1 increase OS memory consumption for product tests?

**Comment by wendigo** [comment]
@findepi if you are concerned about local memory usage we can put some constraint on memory used by Trino docker containers.

**Comment by findepi** [comment]
The settings that this PR removed were for that purpose. 
But surely there are better settings that could be used instead, more direct.

**Pull request merged**
