### PR TITLE
Add xml-related functions for parsing XML data using XPath expressions

### PR DESCRIPTION
**Pull request by wgzhao**
These functions are migrated from [Hive UDF XPath functions](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+XPathUDF)

### CODE REVIEW

**Comment by ebyhr** [comment]
It looks duplicate of #9219.  
cc: @sajjoseph

**Comment by wgzhao** [comment]
Yes, I noticed that PR, but no progress recently, and the same time, I need the xpath-related parsing functions for my work, and we have developed  and deployed to the production environment in the last few days. I hope these functions will be in the official code soon

**Comment by ebyhr** [comment]
Could you talk with @sajjoseph how you collaborate with the existing PR?

**Comment by wgzhao** [comment]
I will try

**Review by tooptoop4 — APPROVED** [review]

**Comment by bitsondatadev** [comment]
:wave: @wgzhao - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that. It looks like you reached out to @sajjoseph on #9219 and there was no response. If you want to continue working on this, let me know and we can close out the older PR. Thank you for your patience here.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by colebow** [comment]
Closing this one out due to inactivity, but please reopen if you would like to pick this back up.

**Pull request closed without merging**
