### PR TITLE
Update okhttp version

### PR DESCRIPTION
**Pull request by MiguelWeezardo**

### CODE REVIEW

**Review by findepi — DISMISSED** [review]
@kokosing @lukasz-walkiewicz can you please take a look too?

**Comment by martint** [comment]
What's the motivation? Bug fixes? Performance? Please add a note to the commit message.

**Comment by kokosing** [comment]
Please see: https://github.com/trinodb/trino/issues/6172

**Comment by kokosing** [comment]
See also: https://github.com/trinodb/trino/pull/6151

**Comment by kokosing** [comment]
> What's the motivation? Bug fixes? Performance? Please add a note to the commit message.

I am aware of dependencies conflicts with the current version. Notice that `3.9.0` is dated 2017-09-03.

**Comment by MiguelWeezardo** [comment]
@lukasz-walkiewicz, should I close this PR and wait for #6151 to get merged? #6151 updates `okhttp` all the way to `1.14.9`, but it seems to be stuck as a draft.

**Comment by kokosing** [comment]
Please close. Would you like to help with https://github.com/trinodb/trino/pull/6151? I guess it needs to be rebased and possibly we still need to regenerate few certificates.

**Comment by MiguelWeezardo** [comment]
> Please close. Would you like to help with #6151? I guess it needs to be rebased and possibly we still need to regenerate few certificates.

Sure, I'll take a look at it.

**Pull request closed without merging**
