### PR TITLE
Throw exception instead of returning it

### PR DESCRIPTION
**Pull request by skrzypo987**
## Description

See commit message

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by Praveen2112 — APPROVED** [review]

**Review by kokosing — COMMENTED** [review]
Is it possible to test it?

**Comment by skrzypo987** [comment]
> Is it possible to test it?

Not much to test here. We can't test every single throw statement. And there is no chance someone will revert it and the bug will reemerge

**Comment by kokosing** [comment]
I was thinking about having negative test case with incorrect transaction log to see that it fails as expected.

**Comment by skrzypo987** [comment]
> I was thinking about having negative test case with incorrect transaction log to see that it fails as expected.

I am no t saying that the test is difficult to make. I am saying that we shouldn't test these kind of things.
We do not write tests for typos after correcting them. And this is exactly that

**Comment by kokosing** [comment]
This is not a typo. It is logic change and it looks like a correctness issue. As I understand returning `Exception` from `deserializeColumnValue` will end up with some cryptic error.

The negative test with invalid/unsupported transaction log seems reasonable.

**Comment by skrzypo987** [comment]
> This is not a typo. It is logic change and it looks like a correctness issue. As I understand returning `Exception` from `deserializeColumnValue` will end up with some cryptic error.

correct
> The negative test with invalid/unsupported transaction log seems reasonable.

In order to be consistent we'd need to test every return throw statement in a method returning Object.
Tests are a code, a code that adds to the maintainability cost.

Consider seeing that code for the first time in a fresh PR. No one would even consider writing a test for it.

**Comment by kokosing** [comment]
> In order to be consistent we'd need to test every return throw statement in a method returning Object.
Tests are a code, a code that adds to the maintainability cost.

I think there is a middle ground. I think we should provide tests for cases that may happen for users. The question is if it is the case? Maybe it is a fix in a "dead-code".

> Consider seeing that code for the first time in a fresh PR. No one would even consider writing a test for it.

I can see it could happen both ways. I understand that fresh code could be lacking such negative tests, while when code gets matured it is resilient for more and more corner cases.

Anyway, your change is a good step forward. So please let us know if you are willing to provide such negative tests. I am not blocking merge here. Just sharing my thoughts here.

**Comment by skrzypo987** [comment]
You are right that the path that may cause an error is not covered by any test, which is wrong. But this PR is not about it, so I'd like to skip testing.
I don't have cycles for that anyway.

**Comment by kokosing** [comment]
ACK

**Review by kokosing — APPROVED** [review]

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
cc @alexjo2144 @findinpath @jirassimok

**Review by jirassimok — APPROVED** [review]
I'm impressed that this went so long without being detected.

As for tests, we probably _should_ have more tests for the transaction log parser (at least making sure we have some other tests that use the different deserializations present here), but that would be more complicated than necessary to fix this bug.

**Review by alexjo2144 — APPROVED** [review]

**Pull request merged**
