### PR TITLE
Fix invisible prompt color on dark terminal background 

### LINKED ISSUE #6190: Improve CLI color scheme on dark terminal background
For me, on a dark themed terminal, presto prompt is invisible. 

Pic:
Screenshot 2020-12-03 at 12 36 05

Screenshot 2020-12-03 at 12 36 22

### PR DESCRIPTION
**Pull request by Ravenlol119**
## Description
This Pull Request modified the `InputReader`  class, it fixes #6190.  

Before:  Gray Prompt , it has Low Visibility on Dark Backgrounds, or maybe invisible on some dark themes.
eda5b365eac88fa3676bd14b4338a86

Now: Bright Cyan Prompt, Improved Visibility, it can be seen clearly on both dark theme and bright theme.
893d03707f2552cbcd3388cd880d82f

## Release notes
The prompt is now displayed in bright cyan, making it more readable on dark backgrounds.

### CODE REVIEW

**Comment by ebyhr** [comment]
Could you add the screenshot before&after this change to the PR description?

**Comment by Ravenlol119** [comment]
Before:  Gray Prompt , it has Low Visibility on Dark Backgrounds, or maybe invisible on some dark theme.
eda5b365eac88fa3676bd14b4338a86

Now: Bright Cyan Prompt, Improved Visibility, it can be seen clearly on both dark theme or bright theme.
893d03707f2552cbcd3388cd880d82f

**Comment by ebyhr** [comment]
Thanks for attaching the screenshot! 

I can see the prompt though the PR title is "invisible". I feel there is no need to make it stands out because it is just a prompt which is not so important. I would leave the review to @wendigo who create the issue #6190.

**Comment by Ravenlol119** [comment]
@cla-bot check

**Comment by mosabua** [comment]
@wendigo @electrum @ebyhr - do we want to reopen and progress with this PR?

**Pull request closed without merging**
