### PR TITLE
Add OpenSearch test for Elasticsearch connector test

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Add OpenSearch test for Elasticsearch connector test

## Documentation

(x) No documentation is needed.

## Release notes

(x) No release notes entries required.

### CODE REVIEW

**Review by hashhar — COMMENTED** [review]
Thanks, is OpenSearch based on 7.x ES or 6.x ES?

Asking because of https://github.com/trinodb/trino/pull/11263

**Comment by ebyhr** [comment]
@hashhar It's based on 7.x.

**Comment by martint** [comment]
If OpenSearch is not guaranteed to be compatible with ElasticSearch, we may need to create a dedicated plugin for it (or be prepared to do so in the future)

**Comment by ebyhr** [comment]
I suppose it's not guaranteed. That is why I didn't update the requirement in the connector's documentation. Let's continue in #11377

**Pull request closed without merging**
