### PR TITLE
Revert non-shaded jdbc driver

### PR DESCRIPTION
**Pull request by mosabua**
## Description

As agreed with @electrum and @wendigo 

fyi @gaeljw 

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
(x) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
## JDBC

* Remove publishing a JDBC driver JAR without bundled, third-party
  dependencies. ({issue}`23452`)
```

### CODE REVIEW

**Review by wendigo — APPROVED** [review]

**Comment by mosabua** [comment]
Somehow jdbc compatibility tests failed. I pushed again since it seems to have been a build time out.

**Comment by mosabua** [comment]
JBC now passes. Other failures were unrelated. Merging

**Comment by ebyhr** [comment]
@mosabua Could you explain the reason in the PR description?

**Comment by mosabua** [comment]
> @mosabua Could you explain the reason in the PR description?

Done .. i hope that makes enough sense.

**Comment by mosabua** [comment]
Follow up PR #23458

**Pull request merged**
