### PR TITLE
Test failure message when executing `register_table` procedure in Iceberg REST and JDBC catalogs

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Test failure message when executing `register_table` procedure in Iceberg REST and JDBC catalogs

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

**Review by krvikash — APPROVED** [review]
LGTM

**Review by findepi — APPROVED** [review]
Please let @alexjo2144 review as well

**Review by alexjo2144 — APPROVED** [review]
Can you create a follow-up issue to fix the error the Iceberg code is throwing?

**Comment by ebyhr** [comment]
Filed "Add support for register_table and unregister_table procedures in Iceberg REST and JDBC catalogs" https://github.com/trinodb/trino/issues/15853

**Pull request merged**
