### PR TITLE
Cleanup CI jobs for modules

### PR DESCRIPTION
**Pull request by electrum**
- simplify ORC and Parquet
- combine Elasticsearch jobs
- split out unrelated connectors
- split out longer modules into separate job

### CODE REVIEW

**Review by hashhar — CHANGES_REQUESTED** [review]
Will increase CI wall time.

Each job pays a constant overhead of compilation + some preparation which we were able to amortize by combining short modules and save up on CI minutes.

**Comment by electrum** [comment]
The increase in usage is minimal. Connectors have about 90 seconds overhead. The goal is to keep things simple and reduce wall time for long running jobs. If you're working on something that's at the end of one of these combined modules, you have wait much longer to see if it succeeds or fails.

**Comment by electrum** [comment]
Resource usage and wall time are actually separate goals. Given our concurrency limit, we actually need to break up the larger jobs in order better utilize our concurrency and decrease wall time. We also need to decrease overall usage, but there are better ways to do that, such as test avoidance.

**Comment by hashhar** [comment]
> we actually need to break up the larger jobs in order better utilize our concurrency and decrease wall time

Agreed. There is an idea to split the monolithic numbered product test suites into more targeted ones (e.g. suite-postgresql, suite-sqlserver etc.) so that we can run them selectively as well.

> test avoidance

https://github.com/trinodb/trino/pull/10323

**Review by hashhar — APPROVED** [review]

**Pull request merged**
