### PR TITLE
Let `GlueIcebergUtil.getTableInput` populate the table type property

### PR DESCRIPTION
**Pull request by krvikash**
## Description
Fixes https://github.com/trinodb/trino/issues/14967

Let `GlueIcebergUtil.getTableInput` populate the table type property

## Non-technical explanation
NA

## Release notes

(X) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by alexjo2144 — APPROVED** [review]
Thanks!

**Review by ebyhr — APPROVED** [review]

**Comment by ebyhr** [comment]
Sent #14979 with in the repository just in case.

**Comment by ebyhr** [comment]
CI hit #12521

**Comment by ebyhr** [comment]
Merged, thanks!

**Pull request merged**
