### PR TITLE
Simple event listener exposing data via HTTP

### PR DESCRIPTION
**Pull request by losipiuk**
## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
(x) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by findepi — APPROVED** [review]

**Review by hashhar — DISMISSED** [review]
this is not a listener. How does one get the query id in the first place to query the listener?

**Comment by losipiuk** [comment]
> I can see how this can work but don't see much utility in this over the other mechanisms. Specially since this adds a non-trivial amount of work on the coordinator (query events are large and serialization is costly).

Direct usecase here is to integrate query-completion-events in benchto which we use for performance testing of Trino.

**Comment by hashhar** [comment]
Thanks for the context, that's helpful and makes sense.

**Comment by mosabua** [comment]
Where are the docs for this and how does it compare to 

https://trino.io/docs/current/admin/event-listeners-http.html

Something is messed up here

**Comment by losipiuk** [comment]
> Seems like its not really a event listener that it sends the events somewhere .. more like it just makes them available .. we need to document that somehow

Yeah - it listens internally on event and exposes data over http. We may document it.

**Comment by mosabua** [comment]
hm .. we added it in the release notes @martint and @colebow but I am not sure this really is an event listener in our sense in the docs .. I am also not sure if there is a user facing scenario that warrants documenting this feature, but there might well be. I am inclined to add some minimal docs and leave the release notes entry as is. 

wdyt @losipiuk @martint @colebow @hashhar

**Comment by oneonestar** [comment]
Haven't tried this yet, but I saw no authentication for these endpoints.
I don't think this is user facing without auth.

**Comment by hashhar** [comment]
This is meant to be used with benchto only - not user facing.  See https://github.com/trinodb/benchto/pull/73

**Comment by mosabua** [comment]
> This is meant to be used with benchto only - not user facing. See [trinodb/benchto#73](https://github.com/trinodb/benchto/pull/73)

So it should be removed from the release notes then.. since its an internal implementation detail. Right?

**Comment by mosabua** [comment]
https://github.com/trinodb/trino/pull/22262

**Pull request merged**
