### PR TITLE
Capture return types for JDBC expression rewrites

### PR DESCRIPTION
**Pull request by yittg**
## Description

Capture return types for JDBC expression rewrites, then we can use it in the rewritten expression.

@findepi WDYT?

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

**Comment by yittg** [comment]
@findepi thanks for your advice. Totally agree with you. And thanks for all of your work for keeping the code clean and highly extendable. Feel free to close this issue to avoid misuse as much as possible if tricky usages can be easily involved.

A potential case is `$cast(value: class_set1): class_set2`, where `class_set1` and `class_set2` is my carefully selected types?

**Comment by findepi** [comment]
> A potential case is `$cast(value: class_set1): class_set2`, where `class_set1` and `class_set2` is my carefully selected types?

how would the rewrite rules look like if we didn't have the feature being added in this PR?

**Comment by yittg** [comment]
> how would the rewrite rules look like if we didn't have the feature being added in this PR?

it will be multiple rules like `$cast(value: class_set1): type` where type is a single type.

**Comment by yittg** [comment]
They can be cast to varchar, bigint, double, decimal(n, m)

**Comment by yittg** [comment]
@findepi 
Looks like this is not an essential feature for now.
I'm closing this issue. We can reopen and continue it if some other scenarios require it.

Thanks for your advice.

**Pull request closed without merging**
