### PR TITLE
Generate job annotations without GHA REST API

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

The separate annotate workflow was added to work around permission issues in forked repositories. This is not needed when not using the GHA REST API.

Adding annotations via the API was not working correctly anyway, since it added a check for a commit, but one commit can have multiple runs associated with it, and the check sometimes did not show up in the main run.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by nineinchnick** [comment]
This is a draft, because https://github.com/trinodb/github-actions/pull/34 and https://github.com/starburstdata/action-testng-report/pull/8/ are not merged yet.

**Comment by nineinchnick** [comment]
Tested in https://github.com/nineinchnick/trino/actions/runs/10884950374?pr=18

The annotations now show up in the run summary view even before the run finishes, which is very nice, since we have so many long running jobs.

**Review by wendigo — APPROVED** [review]

**Comment by nineinchnick** [comment]
There's a potentially flaky test failure in sqlserver and we can already see this working as expected:
image

**Comment by wendigo** [comment]
@nineinchnick nice

**Comment by wendigo** [comment]
@nineinchnick can we upgrade the node versions to reduce the warnings?

**Review by wendigo — APPROVED** [review]

**Pull request merged**
