### PR TITLE
Support predicate expression pushdown with like for ClickHouse

### PR DESCRIPTION
**Pull request by chenjian2664**
## Description

Fix https://github.com/trinodb/trino/issues/16396

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# ClickHouse
* Support predicate pushdown with like in ClickHouse. ({issue}`16396`)
```

### CODE REVIEW

**Review by ebyhr — COMMENTED** [review]
Is this change really safe from a correctness perspective? We've disabled predicate pushdown on `FixedString` & `String` types. #7100

**Comment by chenjian2664** [comment]
> Is this change really safe from a correctness perspective? We've disabled predicate pushdown on `FixedString` & `String` types. #7100

Thanks for pointing out, I would like to try support the pushdowns on text types on ClickHouse.

**Comment by ebyhr** [comment]
> I would like to try support the pushdowns on text types on ClickHouse.

Please coordinate with @tangjiangling

**Comment by style1002** [comment]
> I would like to try support the pushdowns on text types on ClickHouse.

Excuse me, Do you have support the pushdowns of equal function text types on ClickHouse demo.

**Comment by zeropool** [comment]
any progress? hope for it

**Pull request closed without merging**
