### PR TITLE
[WIP] Implement exchange encryption

### PR DESCRIPTION
**Pull request by linzebing**
Publish for early review.

### What changes were proposed in this pull request?
This PR adds encryption support for exchanges.

### Why are the changes needed?
As we work on failure recovery support in Trino (https://github.com/trinodb/trino/issues/9101), we will implement exchange spooling (to a distributed storage system like S3, or a distributed buffering service). Encrypting exchanges on a per-query basis enhances security of materialized user data, and prevents exchange data leaks between different users.

As this PR doesn't have code dependency on the WIP task-retry PR (https://github.com/trinodb/trino/pull/9818), publish it for early review.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing tests. After https://github.com/trinodb/trino/pull/9818 gets merged, exchange encryption will be enabled for all fault tolerant (aka failure recovery) tests.

### CODE REVIEW

**Comment by findepi** [comment]
@linzebing do i read this correctly this adds encryption on the wire?
shouldn't we use TLS for that instead?

or will TLS in internal communication be switched off for this?

> we will implement exchange spooling (to a distributed storage system like S3, or a distributed buffering service)

that makes sense, and then we will need to encrypt things.

cc @losipiuk

**Comment by losipiuk** [comment]
> @linzebing do i read this correctly this adds encryption on the wire? shouldn't we use TLS for that instead?
> 
> or will TLS in internal communication be switched off for this?
> 
> > we will implement exchange spooling (to a distributed storage system like S3, or a distributed buffering service)
> 
> that makes sense, and then we will need to encrypt things.
> 
> cc @losipiuk

I did not read the PR yet but IIUC what we want (at least what is most important) is to have data encrypted on disk, with per-query key assignment. So there is little chance that one query would read data from some other unrelated query. Encrypting data in flight is not crucial I believe - but also does not do much harm I think.

**Comment by findepi** [comment]
> So there is little chance that one query would read data from some other unrelated query. 

i agree with that goal

> Encrypting data in flight is not crucial I believe - but also does not do much harm I think.

Encrypting on flight is already the case if you use TLS for internal communication. Which should be on anyway for a really secure setup, where you would want to encrypted spooled data. 
I am not sure therefore about "no much harm" expectation. Will be transiting encrypted data over an already encrypted channel? isn't that redundant?

**Comment by losipiuk** [comment]
> > Encrypting data in flight is not crucial I believe - but also does not do much harm I think.
> 
> Encrypting on flight is already the case if you use TLS for internal communication. Which should be on anyway for a really secure setup, where you would want to encrypted spooled data. I am not sure therefore about "no much harm" expectation. Will be transiting encrypted data over an already encrypted channel? isn't that redundant?

Somewhat. Yet the goal of TLS and the changes this PR brings are somewhat different.

TLS uses shared key (cluster wide), and its goal is to secure Trino cluster from external processes, which are sharing the same network infrastructure.
Here we have a per-query key to guard against Trino reading data of one query in another query processing, which is crucial in multi-tenant deployments.
So even having per-query encryption within TLS brings some extra security.

**Comment by linzebing** [comment]
@findepi : @losipiuk explained it really well. This feature is mainly to prevent data leaks in a multi-tenant environment as we may use a single bucket for storing materialized exchange per region. It's mainly for batch queries, I don't think we need to enable this for interactive clusters.

**Comment by martint** [comment]
> So even having per-query encryption within TLS brings some extra security.

There's an extra cost of doing so.

Since the goal is to encrypt data that's sent to the spooling system, that should be taken care of by the spooling component. For worker to worker communication we already have TLS, as @findepi described above. 

If we decide we want per-query encryption wire encryption, that's a different topic. At this point, I'm not convinced it's necessary.

**Comment by linzebing** [comment]
> There's an extra cost of doing so.

For interactive queries, we disable exchange encryption; for batch queries, compared to encryption by the spooling component, there is no extra cost as AES encryption doesn't increase data size.

But I agree this can also be done by the spooling component, which may be a better idea from the code organization perspective. I will close this one for now.

**Pull request closed without merging**
