### PR TITLE
Don't enable the gib profile when building server for product tests

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

Don't enable the gib profile when building the server for product tests, because gib is disabled anyway.

> Is this change a fix, improvement, new feature, refactoring, or other?
improvement

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
ci

> How would you describe this change to a non-technical end user or system administrator?
n/a

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by hashhar** [comment]
The justification in PR description copied into the commit message would be helpful.

**Comment by nineinchnick** [comment]
> The justification in PR description copied into the commit message would be helpful.
> 
> Just making sure - this change is purely a refactor. i.e. this commit doesn't "disable GIB in PT" - it was already like that. You just changed the mechanism of how it's achieved.
> 
> (Asking to make sure I didn't miss anything)

Yes, exactly. Generally, it wasn't causing issues, but @wendigo noticed that the build was slightly off when working on the shading hacks for Phoenix5 for JDK 17. 

Not enabling GIB at all is also less confusing than enabling it and disabling :-)

**Review by hashhar — APPROVED** [review]

**Comment by nineinchnick** [comment]
@hashhar I reworded the commit message.

**Comment by nineinchnick** [comment]
@hashhar @findepi this is ready to go

**Comment by findepi** [comment]
Does this require any changes after https://github.com/trinodb/trino/pull/13285 merged?

**Comment by nineinchnick** [comment]
> Does this require any changes after #13285 merged?

They're complimentary, but I had to resolve conflicts.

**Pull request merged**
