### PR TITLE
Add test for MongoDB ObjectId

### PR DESCRIPTION
**Pull request by rvazquezglez**

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]
Thanks for adding tests. Please fix commit message as `Add test for MongoDB ObjectId`
https://github.com/trinodb/trino/blob/master/DEVELOPMENT.md#format-git-commit-messages

**Comment by rvazquezglez** [comment]
@ebyhr, I updated commit message. Thank you.

**Comment by ebyhr** [comment]
Merged, thanks!

**Comment by findepi** [comment]
note: there is also some existing test coverage for `ObjectId` function in `io.trino.plugin.mongodb.TestMongoIntegrationSmokeTest#testObjectIds`.

**Pull request merged**
