### PR TITLE
Cleanup POMs

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Comment by wendigo** [comment]
Fixes https://github.com/trinodb/trino/issues/5718

**Review by losipiuk — APPROVED** [review]

**Comment by losipiuk** [comment]
> Fixes #5718

AFAIU it is already fixed. This is just a cleanup.

**Comment by wendigo** [comment]
@losipiuk correct, I've linked it so it can be closed :)

**Review by kokosing — COMMENTED** [review]
Nice thanks!

@lukasz-walkiewicz FYI

**Pull request merged**
