### PR TITLE
introduced test for Elasticsearch 8, which is always secure. fix #20238

### LINKED ISSUE #20238: Connector test for Elasticsearch 8
I took `TestElasticsearch7ConnectorTest` and changed image to `elasticsearch:8.11.3`.
Container has started fine, but test failed in the beginning due to mandatory security in ES8
```
2023-12-28 23:09:51 {"@timestamp":"2023-12-28T20:09:51.409Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.23.0.2:9200, remoteAddress=/172.23.0.1:60894}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[36bee15933d0][transport_worker][T#3]","log.logger":"org.elasticsearch.http.netty4.Netty4HttpServerTransport","elasticsearch.cluster.uuid":"BDkbhquWQ8WOW-NzMpAWqQ","elasticsearch.node.id":"T_vqo2_mSHucmRulnnruww","elasticsearch.node.name":"36bee15933d0","elasticsearch.cluster.name":"docker-cluster"}
2023-12-28 23:10:00 {"@timestamp":"2023-12-28T20:10:00.643Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.23.0.2:9200, remoteAddress=/172.23.0.1:55792}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[36bee15933d0][transport_worker][T#4]","log.logger":"org.elasticsearch.http.netty4.Netty4HttpServerTransport","elasticsearch.cluster.uuid":"BDkbhquWQ8WOW-NzMpAWqQ","elasticsearch.node.id":"T_vqo2_mSHucmRulnnruww","elasticsearch.node.name":"36bee15933d0","elasticsearch.cluster.name":"docker-cluster"}
```
So, test should be tweaked for secure communication.

### PR DESCRIPTION
**Pull request by mkhludnev**
## Description

so far it reproduces two problems with Elasticsearch 8 (#20238) : 
obvious one
```
 Caused by: org.elasticsearch.client.ResponseException: method [POST], host [https://localhost:56693], URI [/_bulk?refresh=true&timeout=1m], status line [HTTP/1
.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_excep
tion","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}

        at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:484)
        at io.trino.plugin.elasticsearch.ElasticsearchLoader$ElasticsearchLoadingSession.addResults(ElasticsearchLoader.java:112)

        at io.trino.plugin.elasticsearch.ElasticsearchQueryRunner.loadTpchTopic(ElasticsearchQueryRunner.java:170)
```

```
 io.trino.plugin.elasticsearch.client.ElasticsearchClient        Error refreshing nodes
io.trino.spi.TrinoException: Connection is closed
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.doRequest(ElasticsearchClient.java:732)
..
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.refreshNodes(ElasticsearchClient.java:173)
        at io.trino.plugin.elasticsearch.client.ElasticsearchClient.initialize(ElasticsearchClient.java:155)
```
In this moment elasticsearch logs an error about non-https request and drops the conn.  

It boils down to configuring ES plugin in Trino nodes via properties, it needs to pass login,pass,https schema, and some certificate. The question is which of security configuration is the most suitable for prod setup Trino->ES. 
Is there another https plugin where I can sneak peek the approach?   

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. (#20238 )
```

### CODE REVIEW

**Comment by mkhludnev** [comment]
Old Elasticsearch client v6 always sends `type` property in `_bulk` index requests. 
It doesn't work with 8th Elasticsearch due to ""reason":"Action/metadata line [1] contains an unknown parameter [_type]"
What's worth to do: upgrade ES client to 8 dropping backward compatibility or introduce new plugin `trino-elasticsearch8`? wdyt?

**Comment by wendigo** [comment]
We should drop elssticsearchb6 support. It has reached EOL already

**Comment by wendigo** [comment]
Does the client v7 works for both 7.x and 8.x?

**Comment by mkhludnev** [comment]
@wendigo 
turns out 

> The High Level Client version 7.16 and higher can communicate with Elasticsearch version 8.x after enabling API compatibility mode. 

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-compatibility.html

**Comment by wendigo** [comment]
Let's update client to 7.16 with compatibility mode on and drop tests for 6.x while adding coverage for 8.x

**Comment by wendigo** [comment]
https://github.com/trinodb/trino/pull/20248 this should do the trick

**Comment by mkhludnev** [comment]
closing in favor of #20248

**Pull request closed without merging**
