### PR TITLE
Ignore Hive system schema when listing views/materialized views

### PR DESCRIPTION
**Pull request by findinpath**
## Description

On the Iceberg connector when trying to see the tables from within information_schema schema while working with AWS Glue metastore:

```
SHOW TABLES FROM s3.information_schema;
```

The following exception occurs:

```
"io.trino.plugin.iceberg.catalog.glue.TrinoGlueCatalog.listMaterializedViews(TrinoGlueCatalog.java:782)"
"io.trino.plugin.iceberg.IcebergMetadata.listMaterializedViews(IcebergMetadata.java:2477)"
"io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listMaterializedViews(ClassLoaderSafeConnectorMetadata.java:961)"
"io.trino.plugin.objectstore.ObjectStoreMetadata.listMaterializedViews(ObjectStoreMetadata.java:317)"
"io.trino.metadata.MetadataManager.listMaterializedViews(MetadataManager.java:1296)"
"io.trino.metadata.MetadataListing.listMaterializedViews(MetadataListing.java:131)"
"io.trino.connector.informationschema.InformationSchemaPageSource.addTablesRecords(InformationSchemaPageSource.java:275)"
"io.trino.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:215)"
"io.trino.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:179)"
```

Solution
Same as on the `TrinoHiveCatalog` make use of an utility method to ignore Hive system schemas while listing the views/materialized views:

https://github.com/trinodb/trino/blob/49e4c06aff0889f84f69158aa5cf4b185da840e8/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java#L464

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by ebyhr** [comment]
/test-with-secrets sha=3af71387dd3c0699ed56490e6a4529a1b495e4dc

**Review by ebyhr — APPROVED** [review]

**Comment by findinpath** [comment]
Unrelated failure on `ci / test (plugin/trino-accumulo)`

```
Error: write EPROTO 139828813293504:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677:
 ```

**Comment by losipiuk** [comment]
@findinpath are those failures related to a change: https://github.com/trinodb/trino/actions/runs/4140970565

**Review by losipiuk — COMMENTED** [review]
LGTM, but test-with-secrets failed. PTAL.

**Pull request merged**
