### PR TITLE
Support the full schema evolution for COW table

### PR DESCRIPTION
**Pull request by albericgenius**
## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by pettyjamesm** [comment]
cc: @jackye1995

**Comment by mosabua** [comment]
I think a lot of work was done on schema evolution recently by @findinpath. 

Could @albericgenius @jackye1995 and @pettyjamesm discuss next steps and pull in however else needed?

**Comment by findinpath** [comment]
> I think a lot of work was done on schema evolution recently by @findinpath.

@mosabua  This is probably a confusion. I haven't done anything relevant lately on the Hudi connector.

**Comment by mosabua** [comment]
Maybe @codope can provide guidance here as it relates to his work on Hudi updates and upcoming changes for Trino Hudi connector.

**Comment by mosabua** [comment]
maybe @yihua can chime in if this is worth rebasing or waiting until the upcoming Hudi release and the related planned Trino connector PRs.

**Comment by mosabua** [comment]
I am leaving this close since I think the incoming changes from @yihua might affect this anyway.

**Pull request closed without merging**
