### PR TITLE
Migrate tests to JUnit

### PR DESCRIPTION
**Pull request by martint**
## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Comment by martint** [comment]
/test-with-secrets sha=8842d422100bdd16765d2bf41fb37ecdb0cfa626

**Comment by martint** [comment]
/test-with-secrets sha=d54bcdb3d7b8f1bcacf72d38ebf705efbe6d73fb

**Comment by martint** [comment]
/test-with-secrets sha=72c7b3e72c3327f714f06ab0070e281bdf696d9f

**Comment by martint** [comment]
/test-with-secrets sha=72c7b3e72c3327f714f06ab0070e281bdf696d9f

**Review by dain — APPROVED** [review]

**Pull request merged**
