### PR TITLE
Reduce memory consumption in BigintPagesHash

### PR DESCRIPTION
**Pull request by skrzypo987**
Fixes https://github.com/trinodb/trino/issues/13380, but unfortunately there is a big performance regression.
This is a quick fix since this is a release blocker. Some more robust solution which will keep the performance gain will follow.

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

> How would you describe this change to a non-technical end user or system administrator?

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by arhimondr** [comment]
@skrzypo987 With this fix included does this behaves better or worse than the implementation before https://github.com/trinodb/trino/pull/13178? Does it make sense to simply revert https://github.com/trinodb/trino/pull/13178/commits/ba2df7c2b8ec184f2ce571611b99e0035cfc160a before a better solution is found? 

Also a meta question. Should we include peak task memory and cumulative memory metrics in our efficiency testing process? (cc: @sopel39 )

**Comment by skrzypo987** [comment]
> With this fix included does this behaves better or worse than the implementation before #13178?

This behaves a bit better than before but most of the gain is diminished. So if merging this is problematic, we can do a proper revert and start again from there..

**Comment by skrzypo987** [comment]
Our benchmarks take peak memory consumption into account. There was no regression at the time of merging. However, now when I benchmarked this PR, it showed an improvement in peak memory. So I might have just missed something before and ignore the memory regression.

**Comment by sopel39** [comment]
> This behaves a bit better than before but most of the gain is diminished. So if merging this is problematic, we can do a proper revert and start again from there..

I think we should keep values array, but limit it for small build sides.

I will revert original PR for now

**Pull request closed without merging**
