### PR TITLE
Enable hive.recursive-directories by default

### LINKED ISSUE #6485: Hive data created with UNION ALL is not visible to Trino
When data is inserted into a (non-ORC) Hive table using `UNION ALL`, it is not visible to Trino

```
hive> CREATE TABLE test (col INTEGER);
hive> INSERT INTO test SELECT 1 UNION ALL SELECT 2;
hive> SELECT col FROM test;
1
2
```

```
presto> SELECT col FROM test;
(0 rows)
```

Other data is still visible:
```
hive> INSERT INTO test VALUES (3);
hive> SELECT col FROM test;
3
1
2
```
```
presto> SELECT col FROM test;
3
```

This occurs for all storage formats besides ORC (I tested textfile, Sequence File, Avro, Parquet, RCText, and RCBinary.

The issue occurs whether the table is created from Trino or Hive, and it also occurs for `CREATE TABLE AS` with `UNION ALL`.

### PR DESCRIPTION
**Pull request by ebyhr**
As conclusion after reading several articles about Hive MR x Tez, I think we can change our default value now. 

Fixes #6485

### CODE REVIEW

**Comment by findepi** [comment]
> Fixes #6485

@ebyhr Would it make sense to add a test for that?



cc @willmostly

**Comment by sopel39** [comment]
This will (by default) prevent symlink optimization (https://github.com/trinodb/trino/commit/7e019cc70a8c3fd404ffdbfeeab67c95687ec74f) from working. It would be great to improve symlink optimization before we flip the toggle

**Comment by ebyhr** [comment]
@sopel39 Thanks for sharing the information. Let me add WIP label considering the symlink optimization.

**Comment by jitheshtr** [comment]
Hi, just chiming in and mentioning that there is a related PR https://github.com/trinodb/trino/pull/5703 which will enable recursive directories at per table level (it started with providing a session property for `recursive_directories`, and the latest decision is to support the feature as a table property based on comments from @electrum)

**Comment by sopel39** [comment]
@jitheshtr would enabling recursive directories by default make #5703 obsolete in practice?

**Comment by jitheshtr** [comment]
@sopel39 There would still be cases like we have where someone would need to override the default cluster level setting for a table.
#5703 could be used to override the behavior of default cluster level setting on a per table basis by setting to `true` or `false` or no-property-at-table-level implying use of value from global config.

**Pull request closed without merging**
