### PR TITLE
Hive: Batch the retrieval of the partition information in `sync_partition_metadata`

### PR DESCRIPTION
**Pull request by findinpath**
## Description

Avoid over-stressing the metastore service with a huge call to retrieve all the partitions of the table.

Fixes https://github.com/trinodb/trino/issues/22756

Follow-up of https://github.com/trinodb/trino/pull/22484

## Additional context and related issues

Inspiration

https://github.com/trinodb/trino/blob/eda8fdfef81e83bb81c09f3c99d76c75a70e6558/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java#L325-L331

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by nineinchnick** [comment]
How do we know this is the root cause, and not for example calling `getCanonicalPartitionName()` for every partition?

**Comment by findinpath** [comment]
> How do we know this is the root cause, and not for example calling `getCanonicalPartitionName()` for every partition?

The regression report from @guyco33  https://github.com/trinodb/trino/issues/22756 states that the metastore timeout occurs while trying to retrieve a great deal of partitions.

While retrieving the splits we do retrieve as well the partitions in batches (although probably for the main reason that we don't know how many files they contain):

https://github.com/trinodb/trino/blob/eda8fdfef81e83bb81c09f3c99d76c75a70e6558/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java#L325-L331


`getCanonicalPartitionName()` is a cheap in-memory method - it shouldn't be relevant for the issue reported.

**Comment by findinpath** [comment]
> What about the suggestion to only do this when `case_sensitive` is false?

This can be done in a follow-up.

**Comment by findinpath** [comment]
> I mean, how do you know that batching will help - have you run any benchmarks? I wonder if fetching partitions with locations is much more expensive than fetching names only.

We do fetch the names of the partitions and then we fetch the whole partition information in order to retrieve the location of the partition. It is obviously more expensive.

> how do you know that batching will help - have you run any benchmarks?

Retrieving  1M+ partitions leads to over-stress the metastore. 
I'm inclined to think that batching definitely helps. I don't know how to calibrate the exact number of partitions to retrieve per batch.

**Comment by guyco33** [comment]
The batching indeed help - no metastore timeout and sync took much longer (as expected).
To minimize the affect on the current usages, I think we can skip the `getPartitionsByNames` for ADD mode  when `case_sensitive=true`  (the default) as it was before  https://github.com/trinodb/trino/pull/22484

**Comment by ebyhr** [comment]
Superseded by #22821

**Pull request closed without merging**
