### PR TITLE
Shutdown yield executor

### PR DESCRIPTION
**Pull request by jklamer**
## Description
Shuts down the yield executor in the SqlTaskManager during the pre destroy workflow.

## Additional context and related issues

Found an executor that is not being shutdown who threads were found during a stack dump on a hung worker. 

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by charlesjmorgan** [comment]
Would you need to `shutdown` `taskManagementExecutor` too?

**Comment by jklamer** [comment]
@charlesjmorgan Don't think so because that is provided to this class. I believe it's the responsibility of the provider to do the shutdown.

**Review by electrum — APPROVED** [review]

**Review by electrum — APPROVED** [review]

**Comment by colebow** [comment]
@electrum @jklamer do we want a release note for this? Seems like it may make long-running workers perform better.

**Comment by losipiuk** [comment]
> @electrum @jklamer do we want a release note for this? Seems like it may make long-running workers perform better.

If sth I would say:
```
FIx bug when JVM running Trino worker may not finish after worker shutdown was initiated.
```

But I am not sure it is worth mentioning. Aparently it was not happening often (bug was there forever I think).

**Comment by findepi** [comment]
@jklamer did you consider switching `driverYieldExecutor` to use daemon threads?

**Comment by jklamer** [comment]
@findepi  I did not. I didn't know enough about these threads to know if that would be appropriate. I figured forgetting to add the shutdown was a more likely mistake than using the wrong type of threads for the use case but idk.

**Comment by findepi** [comment]
> I figured forgetting to add the shutdown was a more likely mistak

correct, this was missing



> using the wrong type of threads for the use case but idk.

i don't think using non-daemon threads was intentional here.

**Comment by jklamer** [comment]
yeah, I'd be okay to switch to daemons here. Especially if that makes more sense

**Comment by erichwang** [comment]
@jklamer we should do both. Even with daemon threads, it's good practice to shut everything down properly.

**Pull request merged**
