### PR TITLE
Update zookeeper version to 3.8.0

### PR DESCRIPTION
**Pull request by kobihikri**
## Description

This PR is for the sake of updating the apache zookeeper client library version being used by trino to the latest available, for the sake of enjoying bug fixes and efficiency improvements

> Is this change a fix, improvement, new feature, refactoring, or other?
This is an improvement for the sake of receiving bug fixes and performance improvements

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
No

> How would you describe this change to a non-technical end user or system administrator?
Apache Zookeeper is being use by the kafka-plugin, as well as by other plugins. The updated library is being used to communicate with Apacghe Zookeeper, and as such - it is due to receive periodic updates.

## Related issues, pull requests, and links

https://github.com/trinodb/trino/discussions/12765
https://github.com/trinodb/trino/issues/12826
https://github.com/trinodb/trino/issues/12826

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by ebyhr** [comment]
Is it ready for review? Please change to non-draft PR if so.

**Review by hashhar — APPROVED** [review]
LGTM % commit message.

Please reword as `Update zookeeper version to 3.8.0` (force pushing is ok).

**Review by hashhar — COMMENTED** [review]
Kafka 3.2 itself (and hence kafka-clients etc.) is using Zookeeper 3.6.3.

I'd like this PR to wait until we've merged https://github.com/trinodb/trino/pull/12863 to make sure CI tells us the truth.

**Comment by ebyhr** [comment]
Closing as https://github.com/trinodb/trino/commit/f96528757114e08e1d83ca18e52b79424c45a827

**Pull request closed without merging**
