### PR TITLE
[Alternative] Support drop corrupted iceberg table

### PR DESCRIPTION
**Pull request by krvikash**
## Description
Alternative to https://github.com/trinodb/trino/pull/15065. This PR makes use of exception thrown by `metadata.getRedirectionAwareTableHandle` and Ignore Exception when metadata is not found and force table drop.

**NOT FOR REVIEW**

## Additional context and related issues
NA

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by findepi** [comment]
(rebased to resolve conflicts after a force push to master (https://github.com/trinodb/trino/pull/15365#issuecomment-1358243396), no other changes)

**Comment by findepi** [comment]
> ## Description
> ## Additional context and related issues
> ## Release notes
> ( ) This is not user-visible or docs only and no release notes are required. ( ) Release notes are required, please propose a release note for me. ( ) Release notes are required, with the following suggested text:
> 
> ```gfm
> # Section
> * Fix some things. ({issue}`issuenumber`)
> ```

If you're not filling the PR template, please remove it from the PR description so that it's obvious to the reader there there isn't any information to look for.

**Comment by findepi** [comment]
Instead of empty template, can you replace the PR description with something like "Alternative to https://github.com/trinodb/trino/pull/15065. This PR differs in this-particular-way"

**Comment by krvikash** [comment]
Closing. As this PR was just to verify alternative implementation.

**Pull request closed without merging**
