### PR TITLE
Fix incorrect results with empty projections in BigQuery

### LINKED ISSUE #14981: BigQuery connector can return incorrect results for empty projections on tables written using streaming API
- Use Trino to create a new table in BigQuery as `CREATE TABLE bigquery.tpch.orders AS SELECT * FROM tpch.tiny.orders`.
- Do a count query as `SELECT count(1) FROM bigquery.tpch.orders`. The result is 0 instead of expected 15000.
- Add a predicate to the query `SELECT count(1) FROM bigquery.tpch.orders WHERE comment != 'something that is always true'`. The expected result is received.

The issue happens because writes done using [BigQuery `insertall` API](https://cloud.google.com/bigquery/docs/streaming-data-into-bigquery) do not reflect changes in `TableInfo` until the streaming buffer is flushed on BigQuery side which happens periodically without any direct control of user/application.

The connector uses the `TableInfo` when adding empty projections at https://github.com/trinodb/trino/blob/f9654eb470756696cbaac93ff579956b3e35964b/plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java#L160-L165 so it can observe a stale number of rows leading to correctness issues.

Some possible fixes might include:

- Change writes to use Storage Write API and see if they are strongly consistent - note that this would only solve issue for writes done via Trino. Other applications can still write using `insertAll` causing the issue.
- Add an artificial always true filter in `applyProjection` - that way the code-path which uses `TableInfo` would not be needed. This would incur some additional cost though.
- Change `createEmptyProjection` to run a COUNT query always - would make split generation very slow and costly

### PR DESCRIPTION
**Pull request by hashhar**
## Description

When the BigQuery connector noticed an empty projection or a query which can be answered without adding any projections then it uses the TableInfo in case of tables (not views or other table types) to find the row count and generate pages instead of actually querying BigQuery.

The row count as shown in TableInfo for tables written using the insertAll/streaming API is incorrect until the streaming buffer is flushed and there's no mechanism to trigger an on-demand flush which can lead to incorrect results.

To fix this we now execute a COUNT(*) query (similar to what was already done for views) when we want to generate pages for empty projections.

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# BigQuery
* Fix possible incorrect results for certain queries like `COUNT(*)` when the table has
  recently been written to in BigQuery. ({issue}`14981`)
```

Fixes #14981

### CODE REVIEW

**Comment by hashhar** [comment]
/test-with-secrets sha=ade3f1fcbf016f681e2c0688ecdef90ee28b2ae8

**Comment by hashhar** [comment]
/test-with-secrets sha=5477034f8dd72655c7a2e356964b33cb34c60596

**Comment by hashhar** [comment]
/test-with-secrets sha=8e39a8bba8db4fdf57538d69e98882a0e803ac3b

**Comment by hashhar** [comment]
/test-with-secrets sha=8e39a8bba8db4fdf57538d69e98882a0e803ac3b

**Review by ebyhr — APPROVED** [review]

**Comment by vlad-lyutenko** [comment]
Am I understand correctly, that this problem is totally on BigQuery side.
Because TableInfo we are getting from BigQuery client, and this flush didn't happen in time on their side?

**Comment by hashhar** [comment]
@vlad-lyutenko Correct. For the streaming API the TableInfo can be outdated.

**Review by vlad-lyutenko — APPROVED** [review]

**Pull request merged**
