### PR TITLE
Support allow/deny list of schemas from hive metastore

### PR DESCRIPTION
**Pull request by tooptoop4**
Change hive connector to exclude/include certain hive schemas (ie 2 configs like allowlist/denylist).  background is one hive metastore is being pointed to by 2 presto catalogs, one catalog is referencing public s3 buckets, the other catalog is referencing private s3 buckets. 

hive.information_schema.columns takes more than 10 minutes to query on both catalogs when only one schema should be visible to the public s3 catalog. I don't want to create a 2nd hive metastore. Also no point showing all tables in both catalogs when due to diff s3 auth per catalog (IAM role vs anonymous) a table can only be successfully queried from one catalog

### CODE REVIEW

**Comment by findepi** [comment]
Why not use access control for the same effect?

**Comment by tooptoop4** [comment]
how can file access control json specify allow all schemas **except** schemaX on catalog1?

**Comment by kokosing** [comment]
> how can file access control json specify allow all schemas except schemaX on catalog1?

Adding support for this to file based access control would make more sense as that could be used to other connectors as well.

**Comment by tooptoop4** [comment]
but for a large hive metastore listing every table/column then checking access control would take longer than excluding whole schemas upfront at metastore level

**Comment by kokosing** [comment]
> but for a large hive metastore listing every table/column then checking access control would take longer than excluding whole schemas upfront at metastore level

I sounds like a valid concern.

**Comment by findepi** [comment]
I think the access control should be applied early enough for this not to be a concern. Is it not the case today?
Do we list all tables from all schemas at once in hive metadata?

**Comment by tooptoop4** [comment]
the problem is compounded by lack of https://github.com/prestosql/presto/issues/6276. A query like select * from hive.information_schema.columns will list every table individually (taking over 10 minutes), Alation runs queries like this (in order to catalog everything)

**Comment by findepi** [comment]
IMO it would be nice to have https://github.com/prestosql/presto/issues/6276. If this is especially important to Alation, maybe they would be interested in some engineering effort for that.

This, however, does not seem to answer my question whether `SystemAccessControl` could come as a help here.
From different point of view -- if, during `hive.information_schema.columns`, we hit tables in schema not accessible to user, a potential exception could reveal some information about such tables.
Perhaps, the code here
https://github.com/prestosql/presto/blob/14fe27abce3326a5068867ea366e21372981cbfa/presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java#L600
could be amended to take SAC into account.

@kokosing wdyt?

**Comment by findepi** [comment]
( potentially related: https://github.com/trinodb/trino/issues/4796 )

**Comment by kokosing** [comment]
> I think the access control should be applied early enough for this not to be a concern. Is it not the case today?

This is something not supported today. SAC can check the access or filter entities. Here you would like to get a predicate that you could pushdown to HMS.

> Perhaps, the code here
https://github.com/prestosql/presto/blob/14fe27abce3326a5068867ea366e21372981cbfa/presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java#L600
could be amended to take SAC into account.

It is tracked by https://github.com/trinodb/trino/issues/4865, if I am not wrong.

>  if, during hive.information_schema.columns, we hit tables in schema not accessible to user, a potential exception could reveal some information about such tables.

We use https://github.com/trinodb/trino/blob/83f6809df4af0422c972c9f2719ce16c2bd356a1/presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaPageSource.java#L251 for this. It considers access control, but on results from HMS.

> IMO it would be nice to have #6276

I think we should first focus #6276. This seems as a root cause of the issue.

**Comment by kokosing** [comment]
> A query like select * from hive.information_schema.columns will list every table individually (taking over 10 minutes), 

Is it possible to ask HMS with single call to get all columns for all tables? Notice that is the hive connector is implemented. See: https://github.com/trinodb/trino/blob/83f6809df4af0422c972c9f2719ce16c2bd356a1/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java#L725. Maybe there is a space for improvement.

**Comment by findepi** [comment]
> This is something not supported today. SAC can check the access or filter entities. Here you would like to get a predicate that you could pushdown to HMS.

That would be one option, but i did not -- and would not -- go as far.

> Is it possible to ask HMS with single call to get all columns for all tables? 

I do not think there is, and that's why there probably is no desire to "push SAC into HMS".

**Comment by bitsondatadev** [comment]
:wave: @tooptoop4 - this PR is inactive and doesn't seem to be under development. If you'd like to continue work on this at any point in the future, feel free to re-open.

**Pull request closed without merging**
