### PR TITLE
Reorder schema string entry in Delta Lake

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Reorder schema string entry in Delta Lake to improve readability when checking diff between Trino and Delta. 

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

**Review by krvikash — APPROVED** [review]
LGTM. Can we have a test with the schema generated with older order?

**Comment by ebyhr** [comment]
> Can we have a test with the schema generated with older order?

The existing tests (e.g. `TestDeltaLakeSchemaSupport#testSerializeSchemaAsJson`) is enough in my opinion.

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
> when checking diff between Trino and Delta.

do we want to test this on file level?

**Review by findinpath — APPROVED** [review]

**Comment by ebyhr** [comment]
> do we want to test this on file level?

Probably, yes. Let me revisit it when I have the time.

**Pull request merged**
