### PR TITLE
Do not fail on close() if test Kudu server is not initialized

### PR DESCRIPTION
**Pull request by losipiuk**
no release notes/docs

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]

**Review by findepi — APPROVED** [review]
Note: I'm fine with the change, but i am also fine with afterclass failing if beforeclass failed.
Perhaps it helps read the logs?

**Comment by hashhar** [comment]
Is Kudu server not being initialized when after-class is called an expected situation? Are we masking some existing issue?

**Comment by losipiuk** [comment]
> Is Kudu server not being initialized when after-class is called an expected situation? Are we masking some existing issue?

With `alwaysRun` it is always called. Even if `@BeforeClass` method which is supposed to set the `kuduServer` fails before actually doing so.
It is not masking anything I think. We still get failure reports from intialization.

**Comment by losipiuk** [comment]
> Note: I'm fine with the change, but i am also fine with afterclass failing if beforeclass failed.
> Perhaps it helps read the logs?

AfterClass failure does not provide any useful information. It just adds noise into the logs. The actual failure is in tests initialization.

**Pull request merged**
