### PR TITLE
[WIP] Arbitrary table properties

### LINKED ISSUE #955: Add support for Hive auto.purge property
Hive has a boolean table property `auto.purge` which we should expose as a Presto table property in the Hive connector.

See https://issues.apache.org/jira/browse/HIVE-9118

### PR DESCRIPTION
**Pull request by dain**
Add support for arbitrary table properties in Hive connector.
```
trino:tpch> create table example (id bigint) with (extra_property_food = 'taco');
CREATE TABLE
trino:tpch> show create table example;
           Create Table           
----------------------------------
 CREATE TABLE hive.tpch.example ( 
    id bigint                     
 )                                
 WITH (                           
    extra_property_food = 'taco', 
    format = 'ORC'                
 )                                
(1 row)
```

This PR will need:
* review of SPI changes
* review of naming convention in Hive
* better error handling in Hive changes
* maybe better prevention of aliasing known Hive properties
* a review of unmanaged Hive properties for security issues
* a flag to diisable extra properties
* tests
* documentation

Resolves #955
Alternative to #9475

### CODE REVIEW

**Comment by dain** [comment]
After further thought, I'm not sure we need to implement Hive extra properties this way.  The alternative implementation #9475 used a single map to contain all of the properties.  The concern I had was that was how we would update a map like that.  You would have to read the map, modify it and post it back, but that could result in losing or restoring properties changed during the update.  What I didn't realize is we have no commands in Trino to modify a table property.  We could use the simpler map style properties in #9475, and then when we add the syntax for setting a table property,  we make it:
```
ALTER TABLE table_name SET  PROPERTY property_name[.field_name]*
```
I think this might be a better approach.

cc @martint and @electrum

**Comment by findepi** [comment]
> `    extra_property_food = 'taco', `

this is not the way to go. BTW we already discussed the syntax and decided to go with catch-all map in Hive connector only.

this new approach has two problems

- requires name mangling for property names that are not valid Trino property names; without mangling, hive dotted convention cannot be used
- leaves user with the impression that _anything_ works, and _every_ property is supported by Trino. Sub-ideal UX, but also more questions to answer ("i set this property, why did Trino do this")

**Comment by mosabua** [comment]
👋 @dain and @findepi  .. from the discussion in this PR I conclude that we can close this. Correct?

**Comment by lmove** [comment]
Hi! Our tool [BreakBot](https://github.com/alien-tools/breakbot) found that this pull request introduces **2 breaking changes** and they appear to impact **4 of your clients**. You can find the full BreakBot report in our fork repository: [report for PR#9523](https://github.com/breakbot-playground/trino/pull/4/checks).

We hope this information is valuable to you, and apologize otherwise. If you're willing to help, we would kindly ask for your help to fill in a [5-minutes survey](https://survey.breakbot.net/index.php/418865/newtest/Y?ID=trinodb-trino-9523) about the report. Your feedback will help us improve the tool and provide a better experience for users in the future!

**Pull request closed without merging**
