### PR TITLE
Modify module exports mode to production in webpack.config.js 

### PR DESCRIPTION
**Pull request by krvikash**
## Description
The generated webapp Javascript files has `eval()` function. Executing JavaScript from a string is an enormous security risk. It is far too easy for a bad actor to run arbitrary code when you use `eval()`.

Please see: [never_use_eval!](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!)

With `mode: "development"` and no mention of `devtool` in webpack config, the `devtool` defaults to `eval` and generates the javascript files with `eval()` function.

Modifying mode from `"development"` to `"production"` generates the JavaScript files without `eval()` function.

This change requires to use `webpack-cli` instead `webpack-command`, as `webpack-command` is deprecated (https://github.com/webpack-contrib/webpack-command).

## Additional context and related issues

This example demonstrates various types of source-maps: https://github.com/webpack/webpack/tree/main/examples/source-map

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Review by wendigo — APPROVED** [review]

**Comment by wendigo** [comment]
it's still using eval

**Comment by wendigo** [comment]
Can we switch `mode` to `production` ?

**Comment by krvikash** [comment]
Thanks for the review @wendigo,

> it's still using eval

I could not find eval() in the generated file. Could you point me to file?

> Can we switch mode to production ?

After switching to production mode, I was getting below error. Same as mentioned here.

```
buntu@ip-172-31-46-231:~/starburst/github/trino$ yarn --cwd core/trino-main/src/main/resources/webapp/src install
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > babel-loader@7.1.5" has incorrect peer dependency "webpack@2 || 3 || 4".
warning " > webpack-command@0.5.1" has incorrect peer dependency "webpack@^4.4.0".
warning "webpack-command > @webpack-contrib/config-loader@1.2.1" has incorrect peer dependency "webpack@^4.3.0".
warning "webpack-command > @webpack-contrib/schema-utils@1.0.0-beta.0" has incorrect peer dependency "webpack@^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
$ webpack --config webpack.config.js
⬡ webpack: Starting Build
⬡ webpack: Build Finished
/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack-command/lib/reporters/parse.js:80
      const row = [module.size, module.id.toString(), modulePath, status(module)];
                                          ^

TypeError: Cannot read property 'toString' of null
    at Object.modules (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack-command/lib/reporters/parse.js:80:43)
    at Object.files (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack-command/lib/reporters/parse.js:27:36)
    at StylishReporter.render (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack-command/lib/reporters/StylishReporter.js:91:39)
    at /home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack-command/lib/compiler.js:27:29
    at finalCallback (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack/lib/Compiler.js:441:32)
    at /home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack/lib/Compiler.js:505:17
    at /home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.storeBuildDependencies (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack/lib/Cache.js:122:37)
error Command failed with exit code 1.

```
https://stackoverflow.com/questions/68626172/on-building-babel-loader-outputs-a-module-object-with-id-null-webpack-command suggests to use `webpack-cli` instead `webpack-command` because `webpack-command` is deprecated (https://github.com/webpack-contrib/webpack-command). After using `webpack-cli`, The scripts are getting generated without `eval()` function and with license text file.

**Comment by krvikash** [comment]
Thanks for the review @wendigo,

> it's still using eval

I could not find eval() in the generated file. Could you point me to file?

> Can we switch mode to production ?

After switching to production mode, I was getting below error. Same as mentioned here.

```
$ yarn --cwd core/trino-main/src/main/resources/webapp/src install
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > babel-loader@7.1.5" has incorrect peer dependency "webpack@2 || 3 || 4".
warning " > webpack-command@0.5.1" has incorrect peer dependency "webpack@^4.4.0".
warning "webpack-command > @webpack-contrib/config-loader@1.2.1" has incorrect peer dependency "webpack@^4.3.0".
warning "webpack-command > @webpack-contrib/schema-utils@1.0.0-beta.0" has incorrect peer dependency "webpack@^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
$ webpack --config webpack.config.js
⬡ webpack: Starting Build
⬡ webpack: Build Finished
/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack-command/lib/reporters/parse.js:80
      const row = [module.size, module.id.toString(), modulePath, status(module)];
                                          ^

TypeError: Cannot read property 'toString' of null
    at Object.modules (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack-command/lib/reporters/parse.js:80:43)
    at Object.files (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack-command/lib/reporters/parse.js:27:36)
    at StylishReporter.render (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack-command/lib/reporters/StylishReporter.js:91:39)
    at /home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack-command/lib/compiler.js:27:29
    at finalCallback (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack/lib/Compiler.js:441:32)
    at /home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack/lib/Compiler.js:505:17
    at /home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.storeBuildDependencies (/home/ubuntu/starburst/github/trino/core/trino-main/src/main/resources/webapp/src/node_modules/webpack/lib/Cache.js:122:37)
error Command failed with exit code 1.

```
https://stackoverflow.com/questions/68626172/on-building-babel-loader-outputs-a-module-object-with-id-null-webpack-command suggests to use `webpack-cli` instead `webpack-command` because `webpack-command` is deprecated (https://github.com/webpack-contrib/webpack-command). After using `webpack-cli`, The scripts are getting generated without `eval()` function and with license text file.

**Review by wendigo — APPROVED** [review]

**Comment by wendigo** [comment]
LGTM. I've checked that PR locally. Seems to work

**Pull request merged**
