### PR TITLE
Remove Flaky annotation on tests expected to work

### PR DESCRIPTION
**Pull request by phd3**
#4864 seems like a duplicate of #5201.

### CODE REVIEW

**Comment by hashhar** [comment]
You can stress-test this like https://github.com/trinodb/trino/pull/7593/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR26-R28 to make sure it's not Flaky anymore.

**Review by findepi — APPROVED** [review]
Assuming this is just a left over after a244d3d6f58453b79a3958c2baecec677626352c, it may not need stress testing.

@hashhar wdyt?

**Comment by hashhar** [comment]
The beginning of the stack-trace look different between #4864 and #5201 so I'm not 100% sure the cause is same but it could be the same.

**Comment by phd3** [comment]
#4864 shows an additional warning given by iceberg finalizer code that contains the stacktrace to indicate the codepath that creates streams that weren't explicitly closed. I've also seen the same while debugging #5201, but somehow not added on the issue. I think it should be safe to get this in, since #8504 was stress-tested.

**Comment by findepi** [comment]
@hashhar thumbed up, so merging.

**Pull request merged**
