### PR TITLE
Support table redirections from Hive to Hudi

### PR DESCRIPTION
**Pull request by tooptoop4**
Allow users to run queries referencing a single hive catalog to access both normal hive tables and hudi tables with new optimised+dedicated connector (provided an admin has configured hive.hudi-catalog-name to point to a hudi catalog)

### CODE REVIEW

**Review by ebyhr — COMMENTED** [review]
Thanks. Please use rebase (not merge) and add some tests.

**Comment by findepi** [comment]
cc @codope

**Comment by codope** [comment]
@tooptoop4 This would be a useful enhancement! Please rebase. It seems due to wrong merge there are some duplicate classes.

**Comment by tooptoop4** [comment]
@codope can u take over?

**Comment by codope** [comment]
@tooptoop4 Thanks for taking it up. This would be a very useful feature. Created an issue to track it https://github.com/trinodb/trino/issues/14750

Can you please rebase properly so that only relevant code changes are shown in the PR?

**Comment by zhangbutao** [comment]
Any update? This seems like a useful feature.

**Comment by tooptoop4** [comment]
superseded by https://github.com/trinodb/trino/pull/15551

**Pull request closed without merging**
