### PR TITLE
Remove support for deprecated 'memsql' connector name

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Took almost 1 year since it became deprecated. 

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# SingleStore
* Remove support for deprecated `memsql` connector name. ({issue}`16180`)
```

### CODE REVIEW

**Comment by ebyhr** [comment]
`web-ui-checks` hit #16179

**Review by hashhar — APPROVED** [review]

**Review by Praveen2112 — APPROVED** [review]
Should we update the `singlestore` docs title to `SingleStore connector` instead of `SingleStore (MemSQL) connector` ? We could re-name the docs file as it is `memsql.rst`

**Comment by ebyhr** [comment]
I avoided updating the docs intentionally because we can't redirect the page for now. Relates to #15467

**Comment by Praveen2112** [comment]
How about the page title ?

**Pull request merged**
