### PR TITLE
Elasticsearch passthrough query support split to multiple tasks

### PR DESCRIPTION
**Pull request by whuGuo**
## Release notes

Release notes are required, with the following suggested text:

```markdown
# Section
* the query from trino to elasticsearch is always only one task，and all split are concentrated in this task. after fix, The query time is reduced by one order of magnitude. 

({issue}`15171`)

```

### CODE REVIEW

**Comment by whuGuo** [comment]
I found that there is still a problem with the merge of split data. Please give me some time to modify it

**Comment by whuGuo** [comment]
> Thank you for your pull request and welcome to the Trino community. We require contributors to sign our [Contributor License Agreement](https://github.com/trinodb/cla/raw/master/Trino%20Foundation%20Individual%20CLA.pdf), and we don't seem to have you on file. Continue to work with us on the review and improvements in this PR, and submit the signed CLA to [cla@trino.io](mailto:cla@trino.io). Photos, scans, or digitally-signed PDF files are all suitable. Processing may take a few days. The CLA needs to be on file before we merge your changes. For more information, see https://github.com/trinodb/cla

I has sent my cla to cla@trino.io just now

**Comment by whuGuo** [comment]
> Thank you for your pull request and welcome to the Trino community. We require contributors to sign our [Contributor License Agreement](https://github.com/trinodb/cla/raw/master/Trino%20Foundation%20Individual%20CLA.pdf), and we don't seem to have you on file. Continue to work with us on the review and improvements in this PR, and submit the signed CLA to [cla@trino.io](mailto:cla@trino.io). Photos, scans, or digitally-signed PDF files are all suitable. Processing may take a few days. The CLA needs to be on file before we merge your changes. For more information, see https://github.com/trinodb/cla

i have sent CLA to cla@trino.io

**Comment by mosabua** [comment]
@cla-bot check

**Comment by mosabua** [comment]
:wave: @whuGuo  - this PR has become inactive. We hope you are still interested in working on it. Please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

Maybe @wendigo and @martint can help. Also note that we have a separate OpenSearch connector now

**Comment by whuGuo** [comment]
> 👋 @whuGuo - this PR has become inactive. We hope you are still interested in working on it. Please let us know, and we can try to get reviewers to help with that.
> 
> We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.
> 
> Maybe @wendigo and @martint can help. Also note that we have a separate OpenSearch connector now

Thanks, I'm still interested. please tell me what else i need to do

**Comment by mosabua** [comment]
Closing this PR due to inactivity. Anyone interested please feel free to pick it back up and continue work on it here or in a new PR.

**Pull request closed without merging**
