### PR TITLE
add example of function murmur3 and update the link to it in list.rst

### PR DESCRIPTION
**Pull request by gaojun2048**
see #7664

### CODE REVIEW

**Review by mosabua — APPROVED** [review]
Thank you! Nice work.

**Review by m57lyra — APPROVED** [review]
LGTM, except please rebase this. The project requires that you have only one commit per PR, and I see that there are 2. To rebase, run the following commands in your gaojun2048:new_murmur3_doc branch:

git rebase -i HEAD~2
git rebase --continue
git push --force gaojun2048 gaojun2048:new_murmur3_doc

**Comment by gaojun2048** [comment]
> LGTM, except please rebase this. The project requires that you have only one commit per PR, and I see that there are 2. To rebase, run the following commands in your gaojun2048:new_murmur3_doc branch:
> 
> git rebase -i HEAD~2
> git rebase --continue
> git push --force gaojun2048 gaojun2048:new_murmur3_doc

Ok, done.

**Review by hashhar — APPROVED** [review]

**Comment by hashhar** [comment]
Thanks for improving the docs @gaojun2048

**Comment by mosabua** [comment]
Thank you very much @gaojun2048 .. great work and persistence. Next one will be easier now that you learned a lot on how things work!

**Pull request merged**
