### PR TITLE
Update airbase to 139

### PR DESCRIPTION
**Pull request by wendigo**
This brings following improvements:

* Replace checkstyle illegal imports with `RestrictImports` enforcer rules
* Checkstyle updates:
  - Require throws keyword to be on a new line.
* Dependency updates:
  - JUnit 5.9.3 (from 5.9.2)
  - Kotlin 1.8.21 (from 1.8.20)
  - Opentelemetry 1.26.0 (from 1.25.0)
  - Opentelemetry Instrumentation 1.25.1 (from 1.24.0)
  - Logback 1.4.7 (from 1.4.6)
  - Checkstyle 10.11.0 (from 10.9.3)
  - Guice 6.0.0 (from 5.1.0)
* Plugin updates:
  - Surefire 3.1.0 (from 3.0.0)
  - maven-clean-plugin 3.2.0 (from 3.0.0)
  - maven-install-plugin 3.1.1 (from 2.5.2)
  - maven-enforcer-plugin 3.3.0 (from 3.2.1)
  - maven-resources-plugin 3.3.1 (from 3.2.0)
  - maven-assembly-plugin 3.5.0 (from 3.3.0)
  - maven-javadoc-plugin 3.5.0 (from 3.2.0)
  - maven-jar-plugin 3.3.0 (from 3.2.0)
  - migrate to git-commit-id-maven-plugin 5.0.0 (from git-commit-id-plugin 4.0.5)
  - maven-source-plugin 3.2.1 (from 3.2.0)
  - license-maven-plugin 4.2 (from 3.0)
  - jacoco-maven-plugin 0.8.10 (from 0.8.9)
  - maven-checkstyle-plugin 3.2.2 (from 3.2.1)
  - maven-site-plugin 3.12.1 (from 3.2)
  - maven-scm-plugin 2.0.0 (from 1.8.1)

The first commit is a preparatory one to fix checkstyle violations due to a new rule.

### CODE REVIEW

**Review by findepi — APPROVED** [review]

**Comment by wendigo** [comment]
@findepi @hashhar can you restart failing tests?

**Comment by electrum** [comment]
This is a permanent error:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.0:test (default-test) on project trino-parser: The following artifacts could not be resolved: org.junit.platform:junit-platform-launcher:jar:1.9.3 (absent): Cannot access central (https://repo.maven.apache.org/maven2) in offline mode and the artifact org.junit.platform:junit-platform-launcher:jar:1.9.3 has not been downloaded from it before. -> [Help 1]
```

I think we need to update the version(s) in the configuration for `go-offline-maven-plugin` in the root POM.

**Comment by findepi** [comment]
> * Guice 6.0.0 (from 5.1.0)


"Released May 12th, 2023." https://github.com/google/guice/wiki/Guice600

How confident are we about this version upgrade?

cc @losipiuk @trinodb/maintainers

**Comment by wendigo** [comment]
@findepi I've tested both rc1 and rc2 before the 6.0.0 release. I'm pretty confident in that version

**Comment by wendigo** [comment]
@findepi CI. What's your concern? Despite the major version bump it's not some major version but small increment with a bunch of bugfixes. There were two versions released - 6.0 and 7.0 (7.0 being jakarta based).

**Comment by losipiuk** [comment]
Guice changelog 5.1.0 -> 6.0.0 is minimalistic - this upgrade is probably fine. Not that I feel like super necessary. (I guess you want to migrate annotations to `jakarta` namespace @wendigo right?)

**Comment by wendigo** [comment]
@losipiuk nope. Newer ASM with support for JDK19+ class formats

**Comment by wendigo** [comment]
@losipiuk jakarta comes next ;)

**Review by losipiuk — APPROVED** [review]

**Pull request merged**
