### PR TITLE
Added ability to recursively delete table data in Iceberg

### PR DESCRIPTION
**Pull request by sshkvar**
Iceberg removes table metadata only from metastore, but not removes table data and metadata from storage. This PR adding ability to also recursively removes table data and metadata from storage. Added new configuration property which is responsible for enabling/disabling recursive delete of table data on drop.

### CODE REVIEW

**Comment by sshkvar** [comment]
As we discussed in https://github.com/prestosql/presto/issues/5616 I have created this PR which is adding ability to recursively delete table data on table drop action

**Comment by findepi** [comment]
@sshkvar can you please squash commits and rebase?

**Comment by findepi** [comment]
cc @losipiuk @alexjo2144 @phd3

**Comment by findepi** [comment]
> Iceberg removes table metadata only from metastore, but not removes table data and metadata from storage.

In Iceberg (ie within https://github.com/apache/iceberg) this seems to be dependent on the Catalog implementation.


> This PR adding ability to also recursively removes table data and metadata from storage.

I do think Trino does that now, doesn't it?

**Comment by mosabua** [comment]
I think we can close this as this functionality is already implemented from all I know. Can someone like @findepi @findinpath @waraposn or @Praveen2112 confirm.

**Comment by findinpath** [comment]
Closing the PR because the functionality has been already implemented in https://github.com/trinodb/trino/pull/11062

**Pull request closed without merging**
