### PR TITLE
Label experimental mode as advanced

### PR DESCRIPTION
**Pull request by Jessie212**

### CODE REVIEW

**Review by mosabua — COMMENTED** [review]
Looks good. Now @electrum and @martint can discuss if the relabelling is okay given the status of the upstream Coral project that powers this feature and decide to merge or not.

**Comment by martint** [comment]
It's not "advanced". It's the supported and default way, but it's described as experimental due to it still having some rough edges. We could consider dropping "experimental" at this point, but we need a label other than "advanced".

**Comment by findepi** [comment]
it's still "experimental" from the feature completeness perspective.
"experimental" is the project convention for how we call features that do not guarantee stability or correctness. would we like to change the convention?

**Comment by Jessie212** [comment]
@martint @findepi @mosabua We're keeping it "Experimental", then, as in the previous PR?: 

https://github.com/trinodb/trino/pull/8728/files

**Comment by findepi** [comment]
@Jessie212  @mosabua @hashhar  was there any discussion related to https://github.com/trinodb/trino/pull/8728#discussion_r681221206  / https://github.com/trinodb/trino/pull/8728#pullrequestreview-721877593 that happened offline?

**Comment by mosabua** [comment]
The previous PR was broken up into just the content changes so we can merge that and get it updated. Now this PR is available for the maintainers to decide if they are comfortable with the rename to Advanced (seemingly not and I concur with that). 

The original request for the rename is from @claudiusli and he can now figure out a new suggestion.

**Pull request closed without merging**
