### PR TITLE
Fix jaccard_index

### PR DESCRIPTION
**Pull request by wendigo**
Jacaard index is defined as:

Jaccard-formula

Fixes https://github.com/trinodb/trino/issues/21331

### CODE REVIEW

**Comment by wendigo** [comment]
```
SELECT jaccard_index(make_set_digest(value), make_set_digest(value1)) FROM (VALUES ('abc', 'def'),('ee', 'abc')) T(value,value1);
       _col0
--------------------
 0.3333333333333333
(1 row)
```

**Comment by wendigo** [comment]
```
SELECT jaccard_index(make_set_digest(value), make_set_digest(value1)) FROM (VALUES (1,4),(2,5),(3,6),(4,7),(5,8)) T(value,value1);
 _col0
-------
  0.25
(1 row)
```

**Comment by martint** [comment]
Have you looked closely at how MinHash relates to Jaccard Index? Based on a quick skim, I'm not sure the implementation for non-exact sets is correct either. From my understanding, the probability of collision is an estimate of the Jaccard index. So, we'd need to calculate that probability. I don't think that's what the current algorithm is doing.

Take a look at:
* https://aksakalli.github.io/2016/03/01/jaccard-similarity-with-minhash.html
* https://www.cs.rice.edu/~as143/COMP480_580_Spring19/scribe/S12.pdf

**Comment by wendigo** [comment]
@martint Briefly. That's why I only corrected an index for exact sets

**Comment by Akanksha-kedia** [comment]
Error:  Failures: 
Error:    TestSetDigest.testSmallLargeIntersections:171 expected [true] but found [false]
Error:    TestSetDigest.testUnevenIntersectionCardinality:53->testIntersectionCardinality:88 Expected intersection cardinality 1612 +/- 10%, got 1201, for set of size 6457 expected [true] but found [false], 
@wendigo i had these failures while doing similar changes, could u cross check if these are passing for u as well.

https://github.com/trinodb/trino/pull/19051/files#diff-c4145123e75cc1db2127597a0631b8a4a8b30d4ff5a704c5d525671afa301091 and also Can you add a test in io.trino.sql.query.TestSetDigestFunctions?

**Comment by wendigo** [comment]
These are passing

**Comment by wendigo** [comment]
@martint probability of a hash collision is an estimate of the sets intersection, right? And that's what current code is doing for non-exact sets.

**Comment by wendigo** [comment]
@martint PTAL

**Comment by Akanksha-kedia** [comment]
@ wendigo  any specific reason why we closed this?

**Pull request closed without merging**
