### PR TITLE
Document assume canonical hive partition key

### LINKED ISSUE #6437: Document assume canonical hive partition key
When the partition key of the partition table is an integer type, no data can be found and an exception is thrown like follow：
`PrestoException：Table ‘aa.bb' was dropped by another transaction`
But in fact the table exists, and the partition also exists.
By reading the code, it is found that there is a parameter in the configuration of thrift metastore.
In order to remove this obstacle for future users, we hereby use documents to record.

### PR DESCRIPTION
**Pull request by allendang001**
When the partition key of the partition table is an integer type, no data can be found and an exception is thrown like follow：
PrestoException：Table ‘aa.bb' was dropped by another transaction
But in fact the table exists, and the partition also exists.
By reading the code, it is found that there is a parameter in the configuration of thrift metastore.
In order to remove this obstacle for future users, we hereby use documents to record.

Fixes #6437

### CODE REVIEW

**Comment by electrum** [comment]
Thanks for improving the documentation. I'd like to understand more about the problem you ran into, since the default value of `false` prevents the error. You would have to change it to `true` to see the error.

We can improve the description for the property:

> Assume that partition keys for non-string types are represented in their canonical form in the metastore. Without this assumption, filters on such columns cannot be pushed into the metastore. However, if the assumption is violated, the query may incorrectly skip data that should be present or fail entirely. Thus, you should only set this value to `true` if you are certain that your partition keys are always stored in canonical .
>
> As background, the Hive metastore uses strings for partition keys for all data types, but does not enforce a canonical representation of values. For example, a partition column of type `int` can have the value `42`, but be stored as `'0042'` in the metstore. If a query has a filter on value `42`, then the Hive connector will ask the metastore for partitions matching the string `'42'`, which will fail to match the actual partition value of `'0042'`.

**Comment by allendang001** [comment]
> Thanks for improving the documentation. I'd like to understand more about the problem you ran into, since the default value of `false` prevents the error. You would have to change it to `true` to see the error.

The actual problem is that we use presto to analyze a hive table whose partition key type is integer, with 'hive.metastore.thrift.assume-canonical-partition-keys'  default false. Presto reported that the partitions did not exist, but in fact, we can use the "show partitions" statement to view the partition and change this parameter to true, the data of this partition can be queried normally.

**Comment by findepi** [comment]
@allendang001 this sounds like a bug. Can you please file an issue with steps to reproduce?

**Comment by allendang001** [comment]
> @allendang001 this sounds like a bug. Can you please file an issue with steps to reproduce?

here https://github.com/trinodb/trino/issues/6598

**Comment by bitsondatadev** [comment]
:wave: @allendang001 - this PR is inactive and doesn't seem to be under development, and it might already be superceded by #6599. If you'd like to continue work on this at any point in the future, feel free to re-open.

**Pull request closed without merging**
