### PR TITLE
Ensure statistics predicate only for base column in delta connector

### PR DESCRIPTION
**Pull request by krvikash**
Follow up of https://github.com/trinodb/trino/pull/17085#discussion_r1189871261

### CODE REVIEW

**Comment by ebyhr** [comment]
> Create statistics predicate only for base column in delta connector

We didn't create statistics predicate for complex types even without this change because `DeltaLakeMetadata#canUseInPredicate` returns false for such types. Is my understanding wrong? The current commit title is a little confusing for me. It would be nice to describe the motivation in the commit body.

**Review by findinpath — APPROVED** [review]

**Comment by findinpath** [comment]
Undoing my approval to wait until the comment https://github.com/trinodb/trino/pull/17449#issuecomment-1545620485 gets clarified.

**Comment by krvikash** [comment]
Thanks, @ebyhr | @findinpath  for the review. I have updated the commit message and put the description in the commit body.

**Review by ebyhr — APPROVED** [review]

**Comment by colebow** [comment]
Does this need release notes? cc @ebyhr

**Comment by krvikash** [comment]
No, It does not require release notes. As we didn't create statistics predicate for complex types.

**Pull request merged**
