### PR TITLE
Make column masks insensitive to relation field order

### PR DESCRIPTION
**Pull request by atanasenko**
## Description
Changes the way column masks are applied from an incremental buildup of nested ProjectNode instances to a single projection for all fields. It's only when there are multiple masks for the same field will it nest multiple projections.
This allows masks to reference original fields without interfering with each other as much as possible.

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by martint** [comment]
How does it relate to https://github.com/trinodb/trino/pull/14420 ?

Also, see my comments in that discussion about multiple masks for the same column: https://github.com/trinodb/trino/pull/14420#issuecomment-1265775880

**Comment by atanasenko** [comment]
> How does it relate to #14420 ?

Oh, haven't seen this one. The code in this one is a combination of both, it attempts to create as few projections as possible, but retains support for multiple masks per field. It does that by combining all second masks into a second projection, third ones into third etc.

**Comment by findepi** [comment]
@atanasenko   there  was a force push to the  master branch (per https://github.com/trinodb/trino/pull/15365#issuecomment-1358243396), so your PR appears as if containing some unrelated commits.
Can you please rebase to remove them?

**Comment by atanasenko** [comment]
Closing in favor of #14420

**Pull request closed without merging**
