### PR TITLE
ClickHouse connector support split by clickhouse partition and shard info

### LINKED ISSUE #10430: ClickHouse connector support split by clickhouse partition and shard info
As pulling data(table scan) is almost the heaviest operation in clickhouse connector, make it run in parallel(with multiple split) can shorten a lot the whole query time.

This MR make trino splits by clickhouse partition info and shard info.
Partition info can extract from clickhouse system table `system.parts`, shard info can extract from clickhouse system table `system.clusters`.
The simplest split case is deal each clickhouse partition as a trino split, and filter data with `_partition_id='{partition_id}'` condition on clickhouse.
For distribute table in clickhouse, much more trino splits can be get by split pulling data into request on each shard.
With shard has multiple replications filter data request can made as load balance on those replications.

Finaly, we can control split count by `max-splits-per-shard` config item, which means max trino splits per clickhouse shard(ignore replication node), with value 0 can disable spit, with default value 10 can make about 10x faster. A bigger value can make a heavy loading on clickhouse, so recommend the value no more than 40(clickhouse `max_concurrent_queries` default value is 100).
In our testing, trino query with clickhouse connector can be about 10x faster with a single clickhouse node.

### PR DESCRIPTION
**Pull request by hoffermei**
Fixes #10430

### CODE REVIEW

**Comment by ebyhr** [comment]
@cla-bot check

**Review by ebyhr — COMMENTED** [review]
Could you add tests?

**Comment by mosabua** [comment]
:wave: @hoffermei  - this PR has become inactive. Could you add some tests as requested by @ebyhr ?

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by colebow** [comment]
Closing this one out due to inactivity, but please reopen if you would like to pick this back up.

**Pull request closed without merging**
