### PR TITLE
Enable oracle aggregation pushdown

### LINKED ISSUE #5208: Aggregation pushdown in Oracle connector
Follow-up to https://github.com/prestosql/presto/pull/3881

Relates to: https://github.com/prestosql/presto/issues/4138

### PR DESCRIPTION
**Pull request by jles01**
Changes related to make aggregation calculated by oracle.

Fixes #5208

### CODE REVIEW

**Comment by tooptoop4** [comment]
@jles01 no ImplementAvgBigint.java  change? like https://github.com/prestosql/presto/pull/5563/files has

**Comment by jles01** [comment]
> @jles01 no ImplementAvgBigint.java change? like https://github.com/prestosql/presto/pull/5563/files has

I added the corresponding change, in addition I added fetch size as a parameter. For huge tables(100billions+) increasing it from default 1000 to 100000 is huge performance improvement.

**Comment by ebyhr** [comment]
>  I added fetch size as a parameter. For huge tables(100billions+) increasing it from default 1000 to 100000 is huge performance improvement.

@jles01 fetchSize is ongoing in #3775. I would recommend avoiding to mixup two enhancement in a PR.

**Comment by jles01** [comment]
> > I added fetch size as a parameter. For huge tables(100billions+) increasing it from default 1000 to 100000 is huge performance improvement.
> 
> @jles01 fetchSize is ongoing in #3775. I would recommend avoiding to mixup two enhancement in a PR.

ohhh did not saw that, will revert

**Comment by ebyhr** [comment]
@jles01 Could you rebase on upstream to resolve conflicts? We changed directory structure and Java package. This wiki describes migration steps. https://github.com/trinodb/trino/wiki/Developer-Migration

**Comment by martint** [comment]
@cla-bot check

**Pull request closed without merging**
