### PR TITLE
Test with GCS v2

### PR DESCRIPTION
**Pull request by ebyhr**

### CODE REVIEW

**Comment by findepi** [comment]
updated per https://github.com/trinodb/trino/pull/12800#issuecomment-1211993336

**Comment by findepi** [comment]
updated per https://github.com/trinodb/trino/pull/12800#issuecomment-1212208794 cc @alexjo2144

**Comment by ebyhr** [comment]
One of the stress tests was cancelled after 60 min https://github.com/trinodb/trino/runs/7794387508

**Comment by ebyhr** [comment]
updated per https://github.com/trinodb/trino/pull/12800#issuecomment-1213364846 cc @alexjo2144

**Comment by ebyhr** [comment]
Updated per https://github.com/trinodb/trino/pull/12800#issuecomment-1219749367 cc: @alexjo2144

**Pull request closed without merging**
