### PR TITLE
Test with GCS

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Comment by findepi** [comment]
updated to current state of https://github.com/trinodb/trino/pull/12800 cc @alexjo2144

**Comment by findepi** [comment]
updated to current state of https://github.com/trinodb/trino/pull/12800 cc @alexjo2144

**Comment by ebyhr** [comment]
`trino-delta-lake -P cloud-tests` failed 😞
```
Error:  java.lang.OutOfMemoryError: Java heap space
Error:  Terminating due to java.lang.OutOfMemoryError: Java heap space
```

**Comment by alexjo2144** [comment]
I'm really at a loss what to do about the OOM

**Comment by findinpath** [comment]
Does the issue happen always?

Would it be worth trying with `<air.test.jvmsize>4g</air.test.jvmsize>` for the `cloud-tests` profile?

How does the memory consumption look like when executing the tests locally?

**Comment by ebyhr** [comment]
Updated to current state of #12800

**Comment by findepi** [comment]
replaced by https://github.com/trinodb/trino/pull/13592

**Pull request closed without merging**
