### PR TITLE
Prevent Hive from returning table handles for Hudi tables

### PR DESCRIPTION
**Pull request by homar**
## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
/test-with-secrets sha=3fbb7a66c17124359eb5bb392ac84066372a445f

**Comment by homar** [comment]
@findepi I guess we can merge, cant we ?

**Comment by colebow** [comment]
Does this need release notes? cc @findepi

**Comment by findepi** [comment]
@colebow nope

**Comment by findepi** [comment]
i don't think trino-hive connector can be used to read Hudi tables. For instance, I believe it lacks necessary libraries on its classpath

**Comment by codope** [comment]
@findepi Hudi tables are queryable using the Hive connector provided users have the hudi presto/trino bundle under the hive plugin directory. This is done through the [custom input format](https://github.com/trinodb/trino/blob/60c0042d8ce6ba8b59a804a4906fbd9b0314bb44/plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java#L525-L543) integration. This change has been there even before Trino was forked off Presto. 
This patch will be a breaking change for those who use the Hive connector to query Hudi tables. Is it possible to revert this change?

**Comment by vinothchandar** [comment]
Landing this without us having the necessary migration path to hudi-connector, will cause pain & break production queries for users out there. @bvaradar this is going to break production at Robinhood. 

We are still waiting on/working through PR reviews there to get hudi-connector on parity.

**Comment by vinothchandar** [comment]
cc @electrum Can we please be notified about such breaking changes in the future, so we can be part of the conversation.

**Comment by vburenin** [comment]
@homar Trino-hudi connector is not efficient enough and can't trim the search scope using metadata or metastore efficiently resulting in basically a full table scan. We have been using hive-connector for a long time to read hudi tables and it just works for us. I had to undo this change on our side to get things back to normal.

**Pull request merged**
