### PR TITLE
Remove unnecessary socketchannelcocketfactory

### PR DESCRIPTION
**Pull request by PennyAndWang**
@electrum , according to what you said in this PR :https://github.com/prestosql/presto/pull/5915 ,  I remove the unnecessary SocketChannelSocketFactory ,please review ,thx!

### CODE REVIEW

**Comment by findepi** [comment]
@PennyAndWang please rebase the PR on current master, so that there is no "Merge .." commit in https://github.com/prestosql/presto/pull/6002/commits

**Comment by PennyAndWang** [comment]
> @PennyAndWang please rebase the PR on current master, so that there is no "Merge .." commit in https://github.com/prestosql/presto/pull/6002/commits

**Comment by PennyAndWang** [comment]
@findepi  Done !

> @PennyAndWang please rebase the PR on current master, so that there is no "Merge .." commit in https://github.com/prestosql/presto/pull/6002/commits

**Comment by PennyAndWang** [comment]
@electrum could you please help  me review  ？ thx～～～

**Comment by PennyAndWang** [comment]
@findepi  Hi, this PR has been opened for 4 months, I don’t know whether  you could review this PR for me  or not . THX

**Comment by findepi** [comment]
@PennyAndWang i asked @electrum  for the review (https://github.com/trinodb/trino/pull/6002#event-4010476344), because he knows this area of code much better.

I don't know much about why have `SocketChannelSocketFactory` in the first place, but it seems @electrum already said it's ok to remove it in https://github.com/trinodb/trino/pull/5915#issuecomment-726238592
So i think I can proceed with this.

But... i am sorry, but could you please rebase the PR?

**Comment by PennyAndWang** [comment]
> @findepi Done !
> 
> > @PennyAndWang please rebase the PR on current master, so that there is no "Merge .." commit in https://github.com/prestosql/presto/pull/6002/commits

@findepi ,Hi, sorry to bother you again. I have rebased this PR,   I need to continue rebase  ？ or   I understand something wrong ？   or  What am I missing?

**Comment by findepi** [comment]
Merged as eeed38bbdcddf1b4e71e88c8281f7cf318ded11b.

**Pull request closed without merging**
