### PR TITLE
Retry S3InputStream operations by reconnecting the underlying stream

### PR DESCRIPTION
**Pull request by alexjo2144**
## Description

In situations like a connection being open for too long without reading any data the underlying InputStream can be closed. This attempts to reconnect the InputStream before failing the read.

This has been observed when reading Iceberg manifests after the 1.6.1 release, the Avro file reader can be held open during `planFiles` calls if the read records haven't been consumed yet.

## Additional context and related issues

https://github.com/apache/iceberg/pull/10691

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Review by losipiuk — APPROVED** [review]
seems fine. 

Testable?

**Comment by alexjo2144** [comment]
I haven't been able to reproduce it locally on Minio or real s3 unfortunately

**Comment by losipiuk** [comment]
Worth merging I think. As we see some spurious errors which may be fixed with this one.

**Review by wendigo — APPROVED** [review]

**Comment by alexjo2144** [comment]
Just circling back, this does seem to have fixed my Avro connection reset problem 👍

**Pull request merged**
