### PR TITLE
Ban io.opentelemetry:opentelemetry-semconv

### PR DESCRIPTION
**Pull request by wendigo**
It is replaced with io.opentelemetry.semconv:opentelemetry-semconv package

Fixes https://github.com/trinodb/trino/issues/23187

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by nineinchnick** [comment]
Do you know of any reference from OTEL about the change of the group ID? Like a release note, issue, or some other messaging?

**Comment by wendigo** [comment]
@nineinchnick https://github.com/open-telemetry/opentelemetry-java/pull/5786 this one?

**Comment by wendigo** [comment]
and this one (linked in the previous PR): https://github.com/open-telemetry/opentelemetry-java/issues/5463

**Review by losipiuk — APPROVED** [review]

**Comment by wendigo** [comment]
Closing in favour of provisio fix

**Pull request closed without merging**
