### PR TITLE
Move benchmark macros to queries module

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

In #14468 benchmark queries were moved to a separate module. Benchto is looking for macro files in the same directory from which it loads query files, so the macro file needs to be moved too.

## Non-technical explanation

n/a

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Review by przemekak — APPROVED** [review]

**Comment by findepi** [comment]
> Benchto is looking for macro files in the same directory from which it loads query files, so the macro file needs to be moved too.

Isn't that it all loads in a single directory on the classpath?
Do we build an uber jar for benchto?

**Comment by nineinchnick** [comment]
> > Benchto is looking for macro files in the same directory from which it loads query files, so the macro file needs to be moved too.
> 
> Isn't that it all loads in a single directory on the classpath? Do we build an uber jar for benchto?

I don't know. I didn't manage to run the jar built in the `trino-benchto-benchmarks` project and I'm running the benchto driver jar directly, like this:
```
java -jar $HOME/.m2/repository/io/trino/benchto/benchto-driver/0.21-SNAPSHOT/benchto-driver-0.21-SNAPSHOT-exec.jar \
  --sql $HOME/src/trino/testing/trino-benchmark-queries/src/main/resources/sql \
  --benchmarks $HOME/src/trino/testing/trino-benchto-benchmarks/src/main/resources/benchmarks \
  --activeBenchmarks=presto/tpch \
  --frequencyCheckEnabled false
```

How do you run these benchmarks?

**Comment by findepi** [comment]
Can you check whether `benchto-driver-0.21-SNAPSHOT-exec.jar` is a flat uber jar, or jar with jars?

for the latter, we would be fine when loading things from classpath always, not "from a classpath-turned-into-a-folder".

> How do you run these benchmarks?

i did not. I assumed things are on the classpath and classpath didn't change.

**Review by findepi — APPROVED** [review]

**Review by MiguelWeezardo — APPROVED** [review]
There should be an NOP [achievement](https://miguelweezardo.github.io/trino-git-achievements/reports/git/) for a PR with 0 lines added and removed

**Comment by nineinchnick** [comment]
> Can you check whether `benchto-driver-0.21-SNAPSHOT-exec.jar` is a flat uber jar, or jar with jars?
> 
> for the latter, we would be fine when loading things from classpath always, not "from a classpath-turned-into-a-folder".

I think it's a bit confusing that `trino-benchto-benchmarks` produces a (uber) JAR at all, because it doesn't work:
```
% java -jar ./testing/trino-benchto-benchmarks/target/trino-benchto-benchmarks-402-SNAPSHOT-executable.jar --help
java.lang.ClassNotFoundException: io.trino.benchto.driver.DriverApp
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Unfortunately, I don't know how to fix this.

`benchto-driver-0.21-SNAPSHOT-exec.jar` is a fat jar built in [a different project](https://github.com/trinodb/benchto) so it has all its dependencies but doesn't contain any benchmark yaml or SQL files.

**Comment by MiguelWeezardo** [comment]
Spring Boot 1.4 changed the way Spring Boot apps are packaged, and no longer exposes application classes/resources in the root of the JAR file. Instead, it provides a thin layer with a custom classloader which loads everything from `benchto-driver-0.21-SNAPSHOT-exec.jar/BOOT-INF`. Perhaps a runtime dependency on `benchto-driver-0.21-SNAPSHOT.jar` would help, I'll take a look.

**Pull request merged**
