### PR TITLE
Update Airbase to 135

### PR DESCRIPTION
**Pull request by ksobolew**
## Description

Pulls in some newer dependencies and other updates.

## Additional context and related issues

Most motivating for me is better pinning of Jackson modules.

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by findepi** [comment]
the build is failing

**Comment by ksobolew** [comment]
```
Terminating due to java.lang.OutOfMemoryError: Java heap space
```

Hmmmm

**Comment by ksobolew** [comment]
> the build is failing

That's an OOM in `maven-checks` on Java 20. @wendigo do you know if that happens often?

**Comment by wendigo** [comment]
@ksobolew this is the first time

**Comment by ksobolew** [comment]
Well, it's all green now; the OOM in Java 20 is not a permanent issue, but worth keeping an eye on.

**Comment by electrum** [comment]
See https://github.com/trinodb/trino/pull/16950/commits/ad6f68b97d2cc8415812a5c2f0e933f0cbb84bfe

**Comment by ksobolew** [comment]
There's a better version in #16950, closing (unless we can make it a spin-off of that PR to merge this one change faster)

**Pull request closed without merging**
