### PR TITLE
Fix code comment in Druid and base JDBC client

### PR DESCRIPTION
**Pull request by polaris6**
企业微信截图_4f8f9c9d-f3ce-4dd0-8080-ffaaf0eb5fb3

企业微信截图_08458a36-5c5a-4a79-bb65-cb074d610d2b

### CODE REVIEW

**Review by hashhar — COMMENTED** [review]
I don't think these comments are javadoc since they are useful only for the people changing the class itself - not for people using the class. i.e. it's implementation detail.

**Comment by hashhar** [comment]
Maybe we can convert to normal multi-line code comment instead.

**Comment by polaris6** [comment]
> Maybe we can convert to normal multi-line code comment instead.

hi @hashhar, thank you for your suggestion. These comments contain @link, if you use a multi-line code comment, the @link will not take effect, this makes @link a little weird here.

**Review by ebyhr — APPROVED** [review]
Please capitalize the commit title and remove commit body:
```
Fix code comment in Druid and base JDBC client
```

https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#format-git-commit-messages

**Comment by polaris6** [comment]
hi @ebyhr, thank you for your suggestion, I resubmitted it.

**Pull request merged**
