### PR TITLE
Upgrade okhttp to the newest 3.x.x version

### PR DESCRIPTION
**Pull request by lukasz-walkiewicz**

### CODE REVIEW

**Comment by electrum** [comment]
For the "regenerate" commit, can you include the command used in the commit description?

**Comment by electrum** [comment]
There is a TODO in `io.prestosql.client.JsonResponse` that we should remove along with this upgrade.

**Comment by electrum** [comment]
Looks like there is still a cert problem
```
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname presto-master.docker.cluster not verified:
    certificate: sha256/09BoHSctXTMDa3/0UPsWZ0mxEvEgtX9nZkkZTZj30y8=
    DN: CN=*.docker.cluster
    subjectAltNames: []

**Comment by lukasz-walkiewicz** [comment]
> Looks like there is still a cert problem
> 
> ```
> Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname presto-master.docker.cluster not verified:
>     certificate: sha256/09BoHSctXTMDa3/0UPsWZ0mxEvEgtX9nZkkZTZj30y8=
>     DN: CN=*.docker.cluster
>     subjectAltNames: []
> ```

I regenerated the certificate in `docker.cluster.jks` and it fixed most of these errors.
The remaining ones are caused by different certificates which have the same problem.

**Comment by kokosing** [comment]
@lukasz-walkiewicz Are we going to close it after: https://github.com/trinodb/trino/pull/6540?

**Comment by electrum** [comment]
Updating our development certificates to comply with modern standards by using alt names is good and should go in regardless of if we continue supporting legacy certs.

**Comment by kokosing** [comment]
Still needed?

**Pull request closed without merging**
