### PR TITLE
Enable Dependabot for GitHub Actions

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

Dependabot will automatically open pull requests to update GitHub Actions. The main benefit of this is knowing that new versions are available, especially if third-party GitHub Actions are pinned to specific versions. Running it weekly should give enough time to review updates, and also react swiftly to potential security updates.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by findepi** [comment]
i'd like to have dependabot for normal dependencies even more than for actions.
That's because we don't ship action code, but we do ship the dependencies. Currently the whole burden is carried by @wendigo , but that feels unfair.

**Comment by nineinchnick** [comment]
I agree we should be using Dependabot instead of checking updates manually, but we need to configure it with access to secrets, so only an admin can do this.

**Review by wendigo — APPROVED** [review]

**Comment by findepi** [comment]
> I agree we should be using Dependabot instead of checking updates manually, but we need to configure it with access to secrets, so only an admin can do this.

@martint asked me this question -- Does dependabot understand the relationship between trino and airbase?

@nineinchnick do you maybe know?

**Comment by nineinchnick** [comment]
> Does dependabot understand the relationship between trino and airbase?

You mean does it understand parent projects, or the usage of proeprties? Would it be better to discuss this on Slack? It's out of the scope of this PR.

**Comment by nineinchnick** [comment]
I've been using it in all my third-party Trino plugin repositories, check out this PR as an example: https://github.com/nineinchnick/trino-git/pull/192

**Comment by wendigo** [comment]
@mosabua it's scheduled weekly so shouldn't bring too much noise

**Comment by mosabua** [comment]
> @mosabua it's scheduled weekly so shouldn't bring too much noise

Lets hope so .. we can always tweak it as well. We might want to decide how we want to deal with the commit messages .. always squash and merge with rewording?

**Comment by wendigo** [comment]
@mosabua let's merge it and see the quality of PR and we can always revert

**Comment by mosabua** [comment]
Also note.. a bunch of this discussion is more about actual dependencies vs just the versions of the github actions .. but I am supportive of both..

**Review by mosabua — APPROVED** [review]
Agreed with @wendigo .. ship it.

**Pull request merged**
