### PR TITLE
Remove unused class FallbackToFullNodePartitionMemoryEstimator.

### PR DESCRIPTION
**Pull request by reswqa**
## Description

Remove unused class `FallbackToFullNodePartitionMemoryEstimator`.

## Additional context and related issues
#16845 

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Review by losipiuk — APPROVED** [review]
Thx. Will merge as soon as CLA gets processed.
One nit: can you drop dot from commit message summary :)

**Comment by reswqa** [comment]
Rebased master to re-trigger CI workflow.

 I'm a bit curious if we have a command to re-run CI without requiring a new push?

**Comment by reswqa** [comment]
It seems that the CI failure caused by an OOM query in `trino-ignite` not related to this change.

**Comment by losipiuk** [comment]
Merged, thanks

**Comment by losipiuk** [comment]
> Rebased on master to re-trigger CI workflow.
> 
> I'm a bit curious if we have a command to re-run CI without requiring a new push?

Not really - if you are not maintainer I think

**Comment by losipiuk** [comment]
Btw: I noticed dot is still there :) But no worries.

**Comment by reswqa** [comment]
> Btw: I noticed dot is still there

Ah, I accidentally neglected when pushing commit. 😞 

Thanks @losipiuk again!

**Pull request merged**
