### PR TITLE
Enable TRUNCATE TABLE for Hive Connector

### PR DESCRIPTION
**Pull request by sergey-melnychuk**
This PR enables TRUNCATE TABLE for Hive Connector.

See also:
https://github.com/trinodb/trino/issues/8921
https://github.com/trinodb/trino/pull/8932
https://github.com/trinodb/trino/issues/5035

### CODE REVIEW

**Comment by sergey-melnychuk** [comment]
Verified on local env, but only on very simple non-partitioned table.
For "Cannot truncate non-managed table" the workaround did the trick: https://stackoverflow.com/a/53257666

**Comment by hashhar** [comment]
TRUNCATE that simply executes DELETE doesn't feel correct. TRUNCATE has different semantics in JDBC data-sources.

e.g. for a Hive ACID / Iceberg table TRUNCATE would actually write a new snapshot with some delete delta. IMO Hive/Iceberg connectors shouldn't map `TRUNCATE tbl` to `DELETE FROM tbl WHERE 1=1`

**Review by findepi — CHANGES_REQUESTED** [review]
Please add tests

- with unpartitioned and partitioned tables
- with unpartitioned and partitioned transactional tables

**Comment by findepi** [comment]
> FWIW in Hive TRUNCATE deletes files from the filesystem (and HMS) while the current implementation you have won't do that

I agree this would be expected

> e.g. for a Hive ACID / Iceberg table TRUNCATE would actually write a new snapshot with some delete delta. 

The two goals seem at odds. 

If TRUNCATE is _not_ to break concurrent readers of a transactional table, it needs to behave exactly as `DELETE` does: write delete delta files.

If we want to purge existing files unconditionally -- which would be a pretty weird operation for a transactional Hive or Iceberg table -- we would break concurrent readers (and so "I" in ACID). For Iceberg this could be new snapshot + removal of all existing data files. For Hive, this would be equivalent to major compaction which lost all data: new base dir needs to be registered, and all the previous bases and deltas would need to be removed.

**Pull request closed without merging**
