### PR TITLE
Data skipping for Hudi connector

### PR DESCRIPTION
**Pull request by codope**
## Description

Use Hudi column stats to skip data and improve query latency.
Stacked on top of #16034 

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# Section
* Support for data skipping with column statistics in Hudi connector.
```

### CODE REVIEW

**Comment by tooptoop4** [comment]
any benchmark?

**Comment by dertodestod** [comment]
First of all a big thanks from me for the work on the connector and on hudi in general 👍. Is there a rough ETA on when this will be merged and be available in trino? Thanks again.

**Comment by mosabua** [comment]
@codope do you plan to rebase and update this PR soon?

**Comment by songpcmusic** [comment]
Is there any plan to support the use case where an operation such as `element_at(map_column, 'key') =|>|< 'value'` is required?

(Note: The =|>|< symbol is not a standard operator in most query languages, so for an accurate translation, it would be helpful to provide additional context or clarification on what the intended operation is.)

**Comment by codope** [comment]
> Is there any plan to support the use case where an operation such as `element_at(map_column, 'key') =|>|< 'value'` is required?
> 
> (Note: The =|>|< symbol is not a standard operator in most query languages, so for an accurate translation, it would be helpful to provide additional context or clarification on what the intended operation is.)

The current PR does not support that. In Hudi 1.0, we are adding [functinal indexes](https://github.com/apache/hudi/blob/master/rfc/rfc-63/rfc-63.md) which can support skipping data based on function/expression on column(s).

**Comment by mosabua** [comment]
👋 @codope .. I assume you are continuing this work at some stage and will leave the PR open.

**Comment by codope** [comment]
I am closing this PR. Once we upgrade the Hudi version in Trino (with the updated Hadoop-independent abstraction), we'll revive or create a new PR for data skipping.

**Pull request closed without merging**
