### PR TITLE
Remove legacy parse-decimal-literals-as-double option

### PR DESCRIPTION
**Pull request by martint**
The behavior was deprecated 6 years ago. The flag was there to ease during the transition, but it's time to get rid of it. It adds unnecessary complexity to the codebase.

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# General
* Remove support for legacy `parse-decimal-literals-as-double` config option. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by hashhar — DISMISSED** [review]
Add to `@DefunctConfig`.

BTW this was not declared as `@LegacyConfig` so any person who's using this most likely doesn't know it's deprecated.

We should mark as `@LegacyConfig` for a few releases and then make it defunct IMO.

cc: @kokosing

**Comment by martint** [comment]
That's not what `@LegacyConfig` does. Its purpose is to allow renaming config options while continuing to support the previous ones for some time. There's no mechanism to deprecate config options such that it will tell users that the config option is no longer supported and will be removed in the future.

**Comment by hashhar** [comment]
`@LegacyConfig` generates a warning about renamed configs. But yeah I can see that people won't read warnings either.

**Comment by martint** [comment]
> generates a warning about renamed configs

Exactly. In this case, we're not renaming it, we removing it altogether. I will add it to `@DefunctConfig`, though, so that anyone that's using it (hopefully, no one, since the feature it guards was deprecated 6 years ago and it's not even documented).

> The other option is:

Not sure that buys us much. The legacy feature *will* be removed, even if we delay it by a few releases. At that point, they'll have to bite the bullet anyway and adjust their usage. Alternatively, anyone running into an issue because they are relying on it has the option to not upgrade until they fix their usage to not need that feature.

**Review by electrum — APPROVED** [review]

**Comment by CEikermann** [comment]
@martint we have used this session property in order to make this query running
```SELECT REDUCE(ARRAY[1.0,2.0,3.0], 0.0, (s, x) -> s + x, s -> s) as col1;```

Without this session property, the query is failing:
```
Query 20240304_091217_00001_ddv4u failed: SignatureBinder.iterativeSolve does not converge after 4 iterations.
```

What is the recommend way to make this query working again without this session property?

Original solution from: https://github.com/prestodb/presto/issues/14066

**Comment by CEikermann** [comment]
Solution have been found

```
SELECT REDUCE(CAST(ARRAY[1.0,2.0,3.0] AS ARRAY(double)), 0.0, (s, x) -> s + x, s -> s) as col1
```

works as intended

**Pull request merged**
