### PR TITLE
support trino iceberg by hadoop catalog

### PR DESCRIPTION
**Pull request by lucasaytt**

### CODE REVIEW

**Comment by findepi** [comment]
Does this relate to https://github.com/trinodb/trino/pull/6977?

cc @losipiuk @alexjo2144 @phd3

**Comment by losipiuk** [comment]
> Does this relate to #6977?
> 
> cc @losipiuk @alexjo2144 @phd3

Yeah it looks it relates very much. #6977 seems to solve same problem but I find abstractions there much cleaner. @lucasaytt would #6977 work for you?

**Comment by lucasaytt** [comment]
6977 is not work for 356+

**Comment by findepi** [comment]
> 6977 is not work for 356+


@jackye1995's #6977 is still being worked on.

**Review by ebyhr — COMMENTED** [review]
Could you consider introducing `TrinoHadoopCatalog` that extends `AbstractTrinoCatalog` likes #11701 so that we can avoid redundant `useMetastore()` conditions? Also, please add some tests including product test.

**Comment by colebow** [comment]
:wave: @lucasaytt - this PR is inactive and doesn't seem to be under development. If you'd like to continue work on this at any point in the future, feel free to re-open.

**Pull request closed without merging**
