### PR TITLE
Deduplicate join output under union with aggregation

### PR DESCRIPTION
**Pull request by gaurav8297**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

improvement

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

core query engine

> How would you describe this change to a non-technical end user or system administrator?

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by raunaqmorarka — APPROVED** [review]

**Comment by raunaqmorarka** [comment]
@gaurav8297 can you take care of test failures here ?

**Comment by gaurav8297** [comment]
> @gaurav8297 can you take care of test failures here ?

Sure

**Comment by raunaqmorarka** [comment]
@gaurav8297 can you also post tpcds results for q75 partitioned and unpartitioned ?

**Comment by gaurav8297** [comment]
[union_dedup_benchmark.pdf](https://github.com/trinodb/trino/files/8537100/union_dedup_benchmark.pdf)

**Review by raunaqmorarka — APPROVED** [review]

**Comment by gaurav8297** [comment]
@sopel39 PTAL

**Review by sopel39 — APPROVED** [review]

**Pull request merged**
