### PR TITLE
Add support for FreeBSD

### PR DESCRIPTION
**Pull request by martenlindblad**

### CODE REVIEW

**Comment by electrum** [comment]
Does the Hive connector work? It uses native libraries for Hadoop and automatically extracts the right one for the current OS and architecture, but it doesn’t have the library built for FreeBSD.

**Comment by martenlindblad** [comment]
> Does the Hive connector work? It uses native libraries for Hadoop and automatically extracts the right one for the current OS and architecture, but it doesn’t have the library built for FreeBSD.

I'll do a check for that as well. I would assume no, since there are no native hadoop libraries for FreeBSD (we roll our own release) but there are none for MacOS either. Do you create the native MacOS libraries in your own hadoop module?

**Comment by electrum** [comment]
The native libraries are here (including macOS): https://github.com/trinodb/trino-hadoop-apache/tree/master/src/main/resources/nativelib

We can build one and include it. Is there a public CI service that we could add to test that project on FreeBSD?

**Comment by martenlindblad** [comment]
> The native libraries are here (including macOS): https://github.com/trinodb/trino-hadoop-apache/tree/master/src/main/resources/nativelib
> 
> We can build one and include it. Is there a public CI service that we could add to test that project on FreeBSD?

Yes: https://cirrus-ci.org/guide/FreeBSD/
I got it working with an old version of your hadoop (2.7 i think?) project but failed due to some protobuf weirdness during native compilation on Hadoop 3.2.

FreeBSD 12.2 and up provides a Hadoop installation for 2.7 from pkg: `pkg install hadoop2`.

**Comment by martenlindblad** [comment]
> The native libraries are here (including macOS): https://github.com/trinodb/trino-hadoop-apache/tree/master/src/main/resources/nativelib
> 
> We can build one and include it. Is there a public CI service that we could add to test that project on FreeBSD?

I've managed to package trino-hadoop-apache using native FreeBSD libs for Hadoop 3.2.0. Shall I make a PR on that branch with those libs?

**Comment by bitsondatadev** [comment]
:wave: @martenlindblad - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by bitsondatadev** [comment]
Gonna close this one out due to inactivity, please reopen if you would like to continue doing work here.

**Pull request closed without merging**
