### PR TITLE
Add reference to to_base64url function in list.rst

### PR DESCRIPTION
**Pull request by SivaTharun**
- Pull request related to #7693

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]
Thanks for fixing this. Could you fix the commit title as below and remove commit body?
`Add reference to to_base64url function in list.rst`

https://github.com/trinodb/trino/blob/master/DEVELOPMENT.md#format-git-commit-messages

**Comment by SivaTharun** [comment]
@ebyhr i have update the title and commit body as per your comment.

**Comment by ebyhr** [comment]
@SivaTharun Could you confirm https://github.com/trinodb/trino/pull/7860/commits? It should be one commit in this page.

**Comment by SivaTharun** [comment]
@ebyhr This PR has only change in list.rst file, The second that you are seeing is the changes from `trinodb:master` upstream branch, i had to pull from upstream, to keep the PR in sync with `trinodb:master`.

**Comment by ebyhr** [comment]
@SivaTharun Yes I know, but please don't use merge commit. You can use rebase instead.

**Comment by electrum** [comment]
Thanks!

**Pull request merged**
