### PR TITLE
Revert "Supports authentication using multiple ldap.user-bind-pattern value"

### PR DESCRIPTION
**Pull request by hashhar**
This reverts the following commits:
45f8cb4b7e0938ff6e723ac63a808214d0c3ba7a
8ca9a95531e504406a2303866143331a8c7c83c6
22ebcf7e610c93985a1eb77d4e0135e203f7d461
74a8b968c07ad185e7bd6f55457d1d487f8287ac
78293628ed5fbccc00f54fe2ca997f16e9d9b5cd

The change was implemented incorrectly and breaks tests but was not
caught because some tests were not run on the pull-request.

### CODE REVIEW

**Comment by hashhar** [comment]
Was prepared via `git revert -n 45f8cb4b7e^..78293628ed`.

**Review by electrum — APPROVED** [review]

**Comment by hashhar** [comment]
Please wait for CI run to finish before merge - there might be other commits since the first failure which are also broken.

**Comment by findepi** [comment]
> The change was implemented incorrectly [...]

if you know any detail, please include that as well

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
@hashhar this looks the same as https://github.com/trinodb/trino/pull/8127 (% squashing, thanks)

i hit some PT failure there still. just fyi

**Comment by hashhar** [comment]
I've amended to add more details to the commit message - no other changes.

**Comment by hashhar** [comment]
All tests passed. 🎉 
Merged to master.

**Comment by kokosing** [comment]
Thank you!

**Comment by findepi** [comment]
@hashhar awesome, thanks!

**Pull request merged**
