### PR TITLE
Convert some static final variables to uppercase

### PR DESCRIPTION
**Pull request by polaris6**
## Description
I saw that some static final variables should be set to uppercase, but they weren't, so I updated them to uppercase.

## Documentation
(x) No documentation is needed.

## Release notes
(x) No release notes entries required.

### CODE REVIEW

**Comment by polaris6** [comment]
There is a failing check, but it's not caused by this PR and can be ignored.

**Comment by polaris6** [comment]
Hi @ebyhr @hashhar, do you think this update is needed? I will turn it off if not needed.

**Comment by hashhar** [comment]
I don't think we follow the convention of having static variables be uppercase.

cc: @findepi

**Comment by findepi** [comment]
@hashhar constants should be UPPER_CASE and they should be static final as well.
For a `static final` field that is not a constant (eg AtomicLong) i think i prefer camelCase. The codebase isn't consistent about this.

cc @trinodb/maintainers

**Comment by arhimondr** [comment]
I find this explanation helpful: https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

> Constants are static final fields whose contents are deeply immutable and whose methods have no detectable side effects. Examples include primitives, strings, immutable value classes, and anything set to null. If any of the instance's observable state can change, it is not a constant. Merely intending to never mutate the object is not enough. Examples:

```
// Constants
static final int NUMBER = 5;
static final ImmutableList<String> NAMES = ImmutableList.of("Ed", "Ann");
static final Map<String, Integer> AGES = ImmutableMap.of("Ed", 35, "Ann", 32);
static final Joiner COMMA_JOINER = Joiner.on(','); // because Joiner is immutable
static final SomeMutableType[] EMPTY_ARRAY = {};

// Not constants
static String nonFinal = "non-final";
final String nonStatic = "non-static";
static final Set<String> mutableCollection = new HashSet<String>();
static final ImmutableSet<SomeMutableType> mutableElements = ImmutableSet.of(mutable);
static final ImmutableMap<String, SomeMutableType> mutableValues =
    ImmutableMap.of("Ed", mutableInstance, "Ann", mutableInstance2);
static final Logger logger = Logger.getLogger(MyClass.getName());
static final String[] nonEmptyArray = {"these", "can", "change"};
```

**Comment by hashhar** [comment]
Thanks, very helpful link and it puts words to what I guess we instinctively try to follow. Maybe we should link to that from our DEVELOPER.md and fix the discrepancies as we encounter them rather than a big bang cleanup?

**Comment by martint** [comment]
It's not that cut-and-dry. There are cases where something is meant to be treated as immutable but it's just not possible due to limitations of the implementation. There are other cases where an object is immutable but has side-effects (e.g., outputs to a file/stream/etc), or cases where the object is mutable but has no observable side effects (e.g., it may manage an internal cache, or have a structure that gets re-organized / re-optimized based on access).

Personally, I've opted for naming all static finals with upper case. It makes it clear what the intent is (it's a "global") and lets me spot at a glance whether there might be gotchas from accessing or using them in a certain way (e.g., if I see a "mutating" method call on such an instance, it's immediately obvious there might be an issue).

I find some of the example above unsatisfactory. For instance, would this be upper or lower case?

```java
static final Set<String> SOME_COLLECTION = makeSet();
static final SqlParser PARSER = new SqlParser();
static final File CONFIG_FILE = new File("xxx");
static final ThreadMXBean THREAD_MX_BEAN = ManagementFactory.getThreadMXBean();
```

**Pull request closed without merging**
