### PR TITLE
Add AccessControl io.trino.spi.ptf.ConnectorTableFunction#analyze

### PR DESCRIPTION
**Pull request by homar**
## Description
Adds access control capabilities to PTF on table and column levels.

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# Section
* Adds access control to PTF ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by findepi — APPROVED** [review]

**Comment by homar** [comment]
Just rebasing

**Comment by homar** [comment]
CI failure is not related: https://github.com/trinodb/trino/issues/17295

**Comment by homar** [comment]
just a rebase to fix ci failure

**Comment by findepi** [comment]
> just a rebase to fix ci failure

pushing empty commit (typically titled `empty`) is sufficient to retrigger the CI

**Pull request merged**
