### PR TITLE
Update to Jakarta servlet and JAX-RS dependencies

### PR DESCRIPTION
**Pull request by wendigo**
Dependency updates:

* https://github.com/trinodb/tempto/pull/115
* https://github.com/airlift/airbase/pull/361
* https://github.com/airlift/airlift/pull/1067
* https://github.com/airlift/discovery/pull/50
* https://github.com/airlift/drift/pull/122

### CODE REVIEW

**Review by electrum — APPROVED** [review]

**Comment by wendigo** [comment]
I've applied error-prone fixes (coming from https://github.com/trinodb/trino/pull/17740) @electrum

**Review by dain — APPROVED** [review]

**Comment by wendigo** [comment]
@hashhar can you run this PR with secrets?

**Comment by kokosing** [comment]
/test-with-secrets sha=d2a3bbb62bc7e19a35693109912bd7e979877d6e

**Comment by kokosing** [comment]
/test-with-secrets sha=501f1e0926aad64a88534ca5e1f060060b4fe93f

**Comment by wendigo** [comment]
Failures are preexisting

**Pull request merged**
