### PR TITLE
Move dependencies to provided scope for HDFS

### PR DESCRIPTION
**Pull request by wendigo**
I recall that we had a check that was verifying that listed provided deps are only in provided scope but I can't find it.

### CODE REVIEW

**Comment by wendigo** [comment]
`trino-hdfs` incorrectly added `provided` dependencies to the plugins that were using it.

**Review by findepi — APPROVED** [review]

**Review by electrum — CHANGES_REQUESTED** [review]
This change isn't correct. Provided scope is only a concern for the final artifact, as it makes an assumption about how that artifact will be used. `trino-hdfs` is a library and can be used in any context.

**Review by electrum — APPROVED** [review]
Nevermind, I understand how. HDFS is a plugin that we bundle into a ZIP file, so it does need to declare what dependencies will be provided.

**Comment by wendigo** [comment]
@electrum yes, that's the case. Thanks for approving this.

**Pull request merged**
