### PR TITLE
Support registering catalog dynamically with RESTful API

### PR DESCRIPTION
**Pull request by JiamingMai**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

This is a new feature.

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

It's a change to catalog related API. 

> How would you describe this change to a non-technical end user or system administrator?

This feature allows to register or update catalog by HTTP RESTful API. 

## Documentation

( *) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( *) No release notes entries required.
( ) Release notes entries required with the following suggested text:

### CODE REVIEW

**Comment by losipiuk** [comment]
cc: @dain

**Comment by Perledition** [comment]
Hi there, is there any update on this? Any Idea why the last test is failing?

**Comment by osscm** [comment]
are we planning to support removing catalog dynamically as well?

**Comment by Perledition** [comment]
> are we planning to support removing catalog dynamically as well?

Yes, this is included in this PR as well.

However, @JiamingMai I forked it, tried it out and had a few unanswered questions:

1. it looks like the REST api only works for the coordinator. The changes are not passed to the workers as far as I can see. As a result, the query processing can only happen on the coordinator (node-scheduler.include-coordinator=true). I can see that in your changes the announcer is also present, but don't really understand yet what it does exactly. Am I missing something here? Were you able to successfully push the changes to the workers? If so, how?

2. (less important) Currently the changes are made in memory, which I think would be okay for now. However, it would be really nice if Coordinator and Worker would share a remote FileSystem, so that changes to properties would only happen in one place.

Translated with www.DeepL.com/Translator (free version)

**Comment by JiamingMai** [comment]
> cc: @dain Hi there, is there any update on this? Any Idea why the last test is failing? It would be great if this dynamic catalog update could be added.

Good idea. Update and remove catalog should be added.

**Comment by JiamingMai** [comment]
>

**Comment by JiamingMai** [comment]
> > are we planning to support removing catalog dynamically as well?
> 
> Yes, this is included in this PR as well.
> 
> However, @JiamingMai I forked it, tried it out and had a few unanswered questions:
> 
> 1. it looks like the REST api only works for the coordinator. The changes are not passed to the workers as far as I can see. As a result, the query processing can only happen on the coordinator (`node-scheduler.include-coordinator=true`). I can see that in your changes the announcer is also present, but don't really understand yet what it does exactly. Am I missing something here? Were you able to successfully push the changes to the workers? If so, how?
> 2. (less important) Currently the changes are made in memory, which I think would be okay for now. However, it would be really nice if Coordinator and Worker would share a remote FileSystem, so that changes to properties would only happen in one place.

For the first question, I think there may be some bugs, I am going to reproduce the problem and fix it.

**Comment by BOFA1ex** [comment]
@JiamingMai 
Is that support register/delete catalog persistently? like dump as etc/catalog/xxx.properties. 
When trino restart, it will recover prev and lose all records about load/unload catalog.
And it's necessary to notified the other coordinators to dump sync.

**Comment by bitsondatadev** [comment]
:wave: @JiamingMai - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by Perledition** [comment]
> wave @JiamingMai - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.
> 
> We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

As far as I can see, only the `mysql check was failing. However, the logs are expired. I would offer my help to test and review, since a good amount of people request this feature. It would be nice, if such an API would finally be part of the official main branch.

**Comment by Perledition** [comment]
> wave @JiamingMai - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.
> 
> We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

There was an (official?) feature branch for this topic which tries to bring all requirements together: #12709 . This includes also this part of an API:  #13931 . It passes all checks but was not merged for some reason. Maybe @dain knows more?

Anyway. If #12709 is still progressing. I would suggest to close this Branch. @dain is there any plan for availability of the API? Also please let us know how we can support.

**Comment by BOFA1ex** [comment]
It seems only work on `node-scheduler.include-coordinator=true`.
if not notify other workers to load/unload the catalog, and then it will occur `No available node to query` error.

**Comment by colebow** [comment]
Closing this one out due to inactivity, but please reopen if you would like to pick this back up.

**Pull request closed without merging**
