### PR TITLE
Ensure that catalogs are loaded before reading

### PR DESCRIPTION
**Pull request by wendigo**
I don't understand how it supposed to work with this lock configuration tbh.

Fixes https://github.com/trinodb/trino/issues/20326

### CODE REVIEW

**Comment by jklamer** [comment]
Ah dang are we still experiencing this issue? Got a link? Im not sure this would solve it, but there is a way to block, tasks from being updated until all catalogs are loaded.

**Review by jklamer — CHANGES_REQUESTED** [review]
Yeah the read and writes are setup to allow concurrent loading, and synchronized pruning behind the write lock. I have another strategy that might work if we are still seeing this loading issue.

**Comment by wendigo** [comment]
@jklamer yep, still happens. How do you synchronize catalog read when the load can still be ongoing?

**Comment by jklamer** [comment]
The read is supposed to strictly speaking happen after the catalogs are loaded. This is supposed to be in this order because the loading happens before any task information is handed to task execution drivers for execution. 

If task updates happen in parallel for some reason, then the first thread falls on the sword of loading the catalogs, and the second one starts the work out of order. My understanding is that this should never happen due to mechanisms in HttpRemoteTask but I could be mistaken // or something else is going on. The solution is to have a flag set after the catalogs are loaded that blocks task from following through with the update before all catalogs are loaded.

**Comment by wendigo** [comment]
All raptors passed. Failures are due to artifacts upload conflict. 

@jklamer @findepi I prefer slow but working solution rather than fast and broken. Let's fix it and then optimize while testing for stability

**Comment by wendigo** [comment]
it seems to work fine for 20 raptor runs - 100% success rate.
I'll compare it with your change @jklamer

**Comment by wendigo** [comment]
@findepi thoughts?

**Comment by wendigo** [comment]
Here's a @jklamer change with 20 raptor builds: https://github.com/trinodb/trino/pull/21261

**Pull request closed without merging**
