### PR TITLE
updating hive.rst

### LINKED ISSUE #7572: Hive example for drop_stats needs quoting on arguments
The examples in [this section](https://trino.io/docs/current/connector/hive.html#updating-table-and-partition-statistics) be updated:

```sql
CALL system.drop_stats('schema_name', 'table_name')
```

```sql
CALL system.drop_stats(
    schema_name => 'schema',
    table_name => 'table',
    partition_values => ARRAY[ARRAY['p2_value1', 'p2_value2']])
```

### PR DESCRIPTION
**Pull request by yashhd**
inserting quotes and additional text
**Closes #7572**

### CODE REVIEW

**Comment by yashhd** [comment]
@findepi Hi Piotr, thank you for approving the PR. Can someone merge it? I have emailed the signed Contributor License Agreement form.

**Comment by findepi** [comment]
@yashhd i am sure you did. Unfortunately the CLA process involves humans, so let's wait for it to complete.
I will merge once CLA is approved.
cc @martint

**Comment by mosabua** [comment]
CLA is filed - can you merge @findepi ?

**Review by mosabua — APPROVED** [review]
Looks good.

**Comment by findepi** [comment]
@cla-bot check

**Comment by findepi** [comment]
@yashhd thanks for your patience!

@mosabua thanks for reminding about this one!

**Pull request merged**
