### PR TITLE
InfluxDB Connector

### PR DESCRIPTION
**Pull request by BigStupideer**
Resubmit a pull request for #15549 and #16293, because it fall behind too much from master.

### CODE REVIEW

**Comment by ebyhr** [comment]
> Resubmit a pull request for #15549 and #16293, because it fall behind too much from master.

Could you send a PR from a new branch instead of `master`? We will lose the past context if you close and resend PR again and again.

**Comment by BigStupideer** [comment]
Okay，so I close this PR and resending a new with a new branch now ?

**Comment by Praveen2112** [comment]
It would be nice if we could rework on this PR itself - https://github.com/trinodb/trino/pull/15549

**Comment by BigStupideer** [comment]
> It would be nice if we could rework on this PR itself - #15549

okay,got it.

**Pull request closed without merging**
