### PR TITLE
pushdown support for TopN and Aggregation for elastic search plugin

### PR DESCRIPTION
**Pull request by murthy-chelankuri**
## Description
This PR provides the support pushing down TopN and Aggregation function to elasticsearch. 

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
(x ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Fixes
```
* #12381 
* #7026
* #4803

### CODE REVIEW

**Comment by ebyhr** [comment]
Hi, thanks for your contribution. Did you confirm existing PR (https://github.com/trinodb/trino/pull/12074 & https://github.com/trinodb/trino/pull/7131)? Could you clarify the difference from them?

**Comment by murthy-chelankuri** [comment]
@ebyhr I adopted some of the code from those existing PRs. As I notice that those are not compatible with the latest version of the trino. And those changes are outdated with the latest version. We put effort to make the TOPN and aggregate pushdown work with the latest code. Thought of contributing the same.

**Comment by murthy-chelankuri** [comment]
I have sent cla singed documents last week I did not hear any thing so far. Am I missing any thing to follow to proceed on this ?

**Comment by bitsondatadev** [comment]
@cla-bot check

**Comment by bitsondatadev** [comment]
@murthy-chelankuri, does this PR supersede #7131 as in it provides the same scope for aggregation pushdown? I am hoping to close that one as I haven't had time to work on it.

**Comment by murthy-chelankuri** [comment]
@findepi @hashhar @martint @bitsondatadev  can you review the changes once when ever you get time?

**Comment by ebyhr** [comment]
You could rebase on master instead of opening a new PR.

**Pull request closed without merging**
