### PR TITLE
[Test] Support Glue catalog in Iceberg connector

### PR DESCRIPTION
**Pull request by findepi**
Test https://github.com/trinodb/trino/pull/10845 with all the secrets.

### CODE REVIEW

**Comment by findepi** [comment]
cc @alexjo2144

**Comment by alexjo2144** [comment]
Thanks! Taking a look at the failures.

**Comment by findepi** [comment]
@alexjo2144 updated.

**Comment by findepi** [comment]
Updated to current state of https://github.com/trinodb/trino/pull/10845 .

**Comment by findepi** [comment]
Updated to current state of #10845 .

**Comment by findepi** [comment]
Updated to current state of #10845 .

**Comment by findepi** [comment]
Updated to current state of #10845 .

**Comment by findepi** [comment]
Updated to current state of #10845 .

**Pull request closed without merging**
