### PR TITLE
Cleanup JVM configuration files after moving to JDK 17

### PR DESCRIPTION
**Pull request by wendigo**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

Cleanup

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Configuration

> How would you describe this change to a non-technical end user or system administrator?

Removal of no longer necessary configuration flags

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by wendigo** [comment]
Follow-up to https://github.com/trinodb/trino/pull/13014

**Comment by electrum** [comment]
First two commits look good, but we don't want to revert the heap size change. The image now correctly utilizes whatever amount of memory is provided to the container.

**Comment by wendigo** [comment]
@electrum I've dropped last commit. cc @findepi

**Review by electrum — APPROVED** [review]

**Comment by electrum** [comment]
Thanks!

**Pull request merged**
