### PR TITLE
add docs for jdbc extra credentials, fixing #1910

### LINKED ISSUE #1910: Document use of extra credentials in JDBC connectors
release notes:
```
* Add support for using a client-provided username and password. The credential
  names can be configured using the ``user-credential-name`` and ``password-credential-name``
  configuration properties. (:issue:`482`)
```

we should have proper documentation for this

related to https://github.com/prestosql/presto/issues/1911

### PR DESCRIPTION
**Pull request by jerryleooo**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

This is an improvement on docs.

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

No, only adding docs

> How would you describe this change to a non-technical end user or system administrator?

N/A

## Related issues, pull requests, and links

* Fixes #1910 

## Documentation

( ) No documentation is needed.
(*) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
(*) Release notes entries required with the following suggested text:

```markdown
# Section
* Adding docs for JDBC connector extra credentials ({issue}`1910`)
```

### CODE REVIEW

**Review by mosabua — CHANGES_REQUESTED** [review]
We should not add the CLI and JDBC related docs into the connector docs .. instead we should document the extra credential usage in the CLI page and the JDBC driver page and then link there. 

There is an ongoing PR that needs to be merged asap so that you can proceed with this as a next step.

**Comment by jerryleooo** [comment]
@mosabua thanks for the review, I have made changes accordingly

**Review by mosabua — CHANGES_REQUESTED** [review]
A couple of general things to update please

* leave secret usage to be the first solution mentioned
* wrap extra credential fragment text at 80 char
* explain what you mean by "key" in those context, and where the credentials are looked up from, maybe this whole thing is worth a separate page we link to in the authentication docs, from the current explanation I do not know how to use this
* provide separate section in CLI docs about extra credential usage 
* provide separate section in JDBC docs 
* link to those sections in the connectors

**Comment by bitsondatadev** [comment]
:wave: @jerryleooo - this PR is inactive and doesn't seem to be under development, and it might already be implemented. If you'd like to continue work on this at any point in the future, feel free to re-open.

**Comment by hashhar** [comment]
This is addressed by https://github.com/trinodb/trino/pull/14454.

**Pull request closed without merging**
