### PR TITLE
Batch dependency updates

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Comment by losipiuk** [comment]
@martint please comment on tzdb change. I do not know if we can do anything about it. But if that may be problematic to users then we should at least do some communication.

**Comment by wendigo** [comment]
More on TZ changes: https://lists.iana.org/hyperkitty/list/tz-announce@iana.org/thread/IZ7AO6WRE3W3TWBL5IR6PMQUL433BQIE/

**Comment by Praveen2112** [comment]
Should we update our connector tests to match with these special timezone representation and like 
> Asia/Choibalsan is now an alias for Asia/Ulaanbaatar

> Historical transitions for Mexico have been updated based on
     official Mexican decrees

**Comment by wendigo** [comment]
@Praveen2112 we don't, they are already there (check zone-index.properties)

**Comment by wendigo** [comment]
joda-time update requires updated tzdata in JVM which is not possible due to https://bugs.openjdk.org/browse/JDK-8339645

**Review by losipiuk — APPROVED** [review]

**Comment by Praveen2112** [comment]
@wendigo Thanks for the pointers - the `zone-index.properties` is on the Trino side for processing - I was a bit confused by this line 

> The affected timestamps occur during
     the years 1921-1927, 1931, 1945, 1949-1970, and 1981-1997.

Does it mean the datasources which happens to store the data during the time period in a Mexcian timezone would translate them differently.

**Comment by wendigo** [comment]
@Praveen2112 yes, basically the "JVM gap" disappeared for that timezone and 1970-01-01 date which renders some of the tests unusable.

**Comment by Praveen2112** [comment]
Okay - But can we capture them as additional test cases, maybe as a follow-up

**Pull request merged**
