### PR TITLE
Add event log processor

### PR DESCRIPTION
**Pull request by tinkerrrr**
Add an event log processor which can

- write query info to file system(hdfs or local) when query completed
- represent query details on the ui pages even though the query was pruned or over due, it means the important information can be saved.

[refer](https://github.com/prestodb/presto/issues/12185)

### CODE REVIEW

**Comment by Praveen2112** [comment]
@tinkerrrr Thanks for raising this PR...Instead of doing the changes in presto-main, can we have a pluggable event listener which writes these event to HDFS ?

**Comment by tinkerrrr** [comment]
> @tinkerrrr Thanks for raising this PR...Instead of doing the changes in presto-main, can we have a pluggable event listener which writes these event to HDFS ?

An event listener could only handle with QueryCompletedEvent, which doesn't contain detail information of a query, adding another kind of Event may cause other changes in presto-main, even cause cycle dependency. In addition, reading event log from HDFS happens in presto-main, so I put the changes here

**Comment by electrum** [comment]
Since this is basically the storage for the UI, we should define another type of plugin service for it. We don’t want to depend on Hadoop / HDFS in presto-main.

One complication is compatibility. We often change the UI and internal structures between Presto versions. Is this storage supposed to be persistent across versions?

**Comment by tinkerrrr** [comment]
> Since this is basically the storage for the UI, we should define another type of plugin service for it. We don’t want to depend on Hadoop / HDFS in presto-main.
> 
> One complication is compatibility. We often change the UI and internal structures between Presto versions. Is this storage supposed to be persistent across versions?

Thanks for your good advice, the current implementation isn't elegant enough, I'll try to make it better. About the compatibility, if the new structures only add or delete nullable fields, it should be compatible between Presto versions, if not, should it be ok to tolerate the incompatibility?

**Comment by tinkerrrr** [comment]
ping @electrum @Praveen2112

**Pull request closed without merging**
