### PR TITLE
Add LDAP group-provider

### PR DESCRIPTION
**Pull request by woowahan-jaehoon**
This is for LDAP group-provider.

Some logics are duplicated so I separated to LdapCommon class.

I think that reviewing each commit is more comportable even though squashing after review.

### CODE REVIEW

**Comment by hashhar** [comment]
See also existing PR under review - https://github.com/trinodb/trino/pull/10116

**Comment by woowahan-jaehoon** [comment]
> See also existing PR under review - #10116

In my case, user object don't have `memberof` attributes. So #10116 cannot help my case.

**Comment by ebyhr** [comment]
@cla-bot check

**Comment by mosabua** [comment]
👋 @woowahan-jaehoon  - this PR has become inactive. If you're still interested in working on it, please let us know.

Maybe @hashhar @kokosing and @ebyhr can chime in on how to best proceed with this PR and the related PR #10116 

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by woowahan-jaehoon** [comment]
Hi @mosabua. Thank you for message.

OK. I'll close this PR.

If I need about this issue. I'll create new PR.

(cc: @iamhongri)

**Pull request closed without merging**
