### PR TITLE
Add telemetry to event listeners

### PR DESCRIPTION
**Pull request by wendigo**
## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```
Kafka, MySQL, HTTP event listeners

Add support for OpenTelemetry tracing
```

```markdown
## Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by marton-bod — APPROVED** [review]
LGTM, thanks for this enhancement

**Review by losipiuk — APPROVED** [review]

**Comment by mosabua** [comment]
Not OpenLineage? You gonna send a follow up PR maybe @marton-bod ?

**Comment by wendigo** [comment]
@mosabua I don't know if it's possible to trace openlineage :)

**Comment by wendigo** [comment]
@mosabua https://github.com/OpenLineage/OpenLineage/discussions/1542

**Pull request merged**
