### PR TITLE
Use correct configuration property for orc bloom filter

### PR DESCRIPTION
**Pull request by Praveen2112**
Fixes https://github.com/trinodb/trino/issues/9792

### CODE REVIEW

**Review by ksobolew — APPROVED** [review]
Honestly, that's kind of embarrassing... Difficulty in writing tests for this is only a partial excuse :(

**Comment by Praveen2112** [comment]
The thing is that hive/orc doesn't provide a easier way to expose whether bloom filter is written or not. I'll take a stab at it again to check if it is possible or not.

**Comment by raunaqmorarka** [comment]
Is it possible to write a queryrunner test where the predicate can result in no data getting read only due to bloom filter (something similar to assertRowGroupPruning in TestParquetPageSkipping).

**Comment by Praveen2112** [comment]
@raunaqmorarka Thanks for the pointers. Last time when I checked with the query runner, the query stats where misleading (maybe I could have a different API). Now I'm able to test if the bloom filter is created or not. Thanks a bunch !!

@ksobolew I have added integration tests for it.

**Review by skrzypo987 — APPROVED** [review]
Do I understand correctly that this never worked?

**Comment by Praveen2112** [comment]
> Do I understand correctly that this never worked?

Yes.

**Review by sopel39 — APPROVED** [review]

**Comment by findepi** [comment]
> > Do I understand correctly that this never worked?
> 
> Yes.

@Praveen2112 let's consider fixing release notes for 339

**Comment by Praveen2112** [comment]
@findepi Updated release notes.

**Review by kokosing — APPROVED** [review]

**Pull request merged**
