### PR TITLE
Allow filesystem caching on coordinator unconditionally

### PR DESCRIPTION
**Pull request by raunaqmorarka**
## Description
Earlier this was used to work around bugs which were encountered when filesystem caching was enabled on coordinator, it's not used for that anymore. 
Removing this avoids confusion about caching not working on hive connector in a single node setup

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# Hive
* Allow file system caching on coordinator. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by findinpath — APPROVED** [review]

**Comment by osscm** [comment]
@raunaqmorarka not related to this work.
I was thinking about one question, where user might want to configure cache with differently at coordinator vs worker.
we have this config available, I believe will 
https://trino.io/docs/current/object-storage/file-system-cache.html#configuration

**Comment by raunaqmorarka** [comment]
> @raunaqmorarka not related to this PR.
> 
> I was thinking about one question, that user might want to configure cache with differently at coordinator vs worker. we have this config available, will be applicable to coordinator and worker both.
> 
> https://trino.io/docs/current/object-storage/file-system-cache.html#configuration
> 
> Any thoughts?

Could you elaborate what this difference in configuring caching on the coordinator vs worker would be and why ?

**Comment by findepi** [comment]
> Earlier this was used to work around bugs which were encountered when filesystem caching was enabled on coordinator, it's not used for that anymore.

do you maybe remember what these were?

**Comment by raunaqmorarka** [comment]
> > Earlier this was used to work around bugs which were encountered when filesystem caching was enabled on coordinator, it's not used for that anymore.
> 
> do you maybe remember what these were?

I forget which one exactly, but there were issues initially when we tried to enabled caching on coordinator in delta and iceberg 
https://github.com/trinodb/trino/pull/20803/commits/91b22ca9361ae946ba0ca1193d9cc0c2c4282445
https://github.com/trinodb/trino/pull/20696
There was also some ongoing discussion about what is safe to cache in delta lake metadata.
So we ended up enabling it coordinator in delta and iceberg in follow-ups as these were resolved and this mechanism was useful in doing that in steps. Now we no longer need it, and it causes some confusion to new users when filesystem caching doesn't work in single node setups in hive.

**Comment by findepi** [comment]
> [91b22ca](https://github.com/trinodb/trino/commit/91b22ca9361ae946ba0ca1193d9cc0c2c4282445)
> #20696

these do not look coordinator-related

**Review by findepi — APPROVED** [review]

**Comment by raunaqmorarka** [comment]
> > [91b22ca](https://github.com/trinodb/trino/commit/91b22ca9361ae946ba0ca1193d9cc0c2c4282445)
> > #20696
> 
> these do not look coordinator-related

I think the relation with coordinator was that only coordinator would load metadata files and that metadata would be non-orc/parquet formats which use streaming read APIs and the bugs were in those implementations.

**Review by wendigo — APPROVED** [review]

**Pull request merged**
