### PR TITLE
Test: Improve Iceberg Glue table caching

### PR DESCRIPTION
**Pull request by ebyhr**
Run tests with secret #13875

### CODE REVIEW

**Comment by ebyhr** [comment]
Updated to the current status of #13875

**Comment by ebyhr** [comment]
Updated to the current status of https://github.com/trinodb/trino/pull/13875

**Comment by findepi** [comment]
Updated to the current state of https://github.com/trinodb/trino/pull/13875

**Comment by findepi** [comment]
Updated to the current state of https://github.com/trinodb/trino/pull/13875

**Comment by findepi** [comment]
Updated to the current state of https://github.com/trinodb/trino/pull/13875

**Pull request closed without merging**
