### PR TITLE
Include curl in Docker image for health check

### PR DESCRIPTION
**Pull request by electrum**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

fix

## Documentation

(x) No documentation is needed.

## Release notes

(x) No release notes entries required.

### CODE REVIEW

**Review by hashhar — COMMENTED** [review]
How did we catch this?

Can we test this in `core/docker/container-test.sh` by also verifing what reports as health of the container?

**Comment by nineinchnick** [comment]
Image build logs say:
```
curl is already the newest version (7.81.0-1ubuntu1.3).
The following additional packages will be installed:
  libmpdec3 libpython3-stdlib libpython3.10-minimal libpython3.10-stdlib
  libreadline8 libsqlite3-0 media-types python3-minimal python3.10
  python3.10-minimal readline-common
```
for all three architectures. I'm not sure why this is needed.

**Comment by hashhar** [comment]
Cannot reproduce the issue so I removed release blocker label.

```
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS                    PORTS                    NAMES
5714103363d8   trinodb/trino:392   "/usr/lib/trino/bin/…"   58 seconds ago   Up 56 seconds (healthy)   0.0.0.0:8080->8080/tcp   trino
```

**Comment by electrum** [comment]
I don't know how to test the health check, so I'll leave that to someone else.

**Comment by nineinchnick** [comment]
> I don't know how to test the health check, so I'll leave that to someone else.

It's covered in container-test.sh

**Pull request closed without merging**
