### PR TITLE
Add support of JDBC store for the dynamic catalog feature

### PR DESCRIPTION
**Pull request by cdrappier**
## Description
Based on the new dynamic catalog, compatible with file and memory. I've try to add a compatibility with a jdbc database for store them.
The main feature of dynamic catalog come from this Issue : https://github.com/trinodb/trino/issues/12709#issuecomment-1290290147

## Additional context and related issues
Goal is to avoid the need of a persistant volume with a persistent dynamic catalog.

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```
# DynamicCatalog
* Add support for storing the dynamic catalog through a jdbc connector
```

### CODE REVIEW

**Comment by cdrappier** [comment]
Due to problem of duplicate classes I've had some exclusion inside other plugin.
I'm not sure it's the right way to deal with that problem

**Comment by mosabua** [comment]
@dain can you look and chime in to see if this approach is in line with the planned features?

**Comment by bitsondatadev** [comment]
@trinodb/devrel could one of you find someone to give this PR a look while @dain is out? Just to verify best practices are being followed.

**Comment by nizarhejazi** [comment]
Any update on this PR?

**Comment by cdrappier** [comment]
On my side, we are actively using it in production right now, will be happy to go further on it.

**Comment by chengh-ch** [comment]
> On my side, we are actively using it in production right now, will be happy to go further on it.

Hi, thanks for your work. 
But have you encountered the situation like these issues while using dynamic catalogs?
https://github.com/trinodb/trino/issues/18040
https://github.com/trinodb/trino/issues/18053

**Comment by mosabua** [comment]
Can you rebase this PR @cdrappier 

@dain you mentioned that this feature might be a good add ... can you help with providing guidance with the PR?

**Comment by mosabua** [comment]
@cdrappier could you potentially rebase so we can verify it against CI and then we can try to get reviewers involved again to get this to merge.

**Comment by mosabua** [comment]
I am reopening because I think @dain mentioned that he would like to have a look.

**Comment by jerryleooo** [comment]
@cdrappier is it possible to sync the catalogs periodically? as there might be more than 1 clusters, the catalog created on one cluster might also be used on another cluster.

**Comment by mosabua** [comment]
@jerryleooo there is no multi-cluster support in Trino as such at this stage. Therefore this feature should also not take this idea into account.

**Comment by mosabua** [comment]
Fyi @dprophet .. you could use this as a base to expand and improve and work with @dain and @cdrappier

**Pull request closed without merging**
