### PR TITLE
Expose AWS Glue metastore stats via JMX

### PR DESCRIPTION
**Pull request by findinpath**
## Description

Expose the Glue Hive Metastore stats over JMX.
Even though the Glue stats were previously collected, due to a regression issue, they weren't exposed by JMX.

The stats are exposed in JMX under the following object names:

- hive: "trino.plugin.hive.metastore.glue:type=GlueHiveMetastore,name=hive"
- iceberg: "io.trino.plugin.hive.metastore.glue:type=GlueMetastoreStats,name=iceberg"
- delta: "io.trino.plugin.hive.metastore.glue:type=GlueHiveMetastore,name=delta"

> Is this change a fix, improvement, new feature, refactoring, or other?

Fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Hive connector

> How would you describe this change to a non-technical end user or system administrator?

Expose the Glue Hive Metastore stats over JMX.
In Trino, the users could issue a statement like the following to retrieve the AWS Glue stats in the connectors backed by AWS Glue.

For Hive:

```
select * from jmx.current."trino.plugin.hive.metastore.glue:name=hive,type=gluehivemetastore";
```

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Hive, Iceberg, Delta Lake
* Expose AWS Glue metastore stats via JMX
```

### CODE REVIEW

**Review by losipiuk — APPROVED** [review]

**Comment by losipiuk** [comment]
nit: `Expose AWS Glue metastore stats on JMX` -> `Expose AWS Glue metastore stats via JMX`

**Review by ebyhr — APPROVED** [review]

**Comment by raunaqmorarka** [comment]
Can we add a test ?

**Comment by findinpath** [comment]
@raunaqmorarka  Due to the fact that Trino does not currently have a a product test environment specific for Glue (see https://github.com/trinodb/trino/issues/5426) for Hive / Iceberg, I can create a product test only for Delta Lake.

Integration Tests depend on the `TestingTrinoServer` configured with `TestingJmxModule` which does not catch the beans registered in the connectors (which depend on `MBeanServerModule` and subsequently on `ManagementFactory.getPlatformMBeanServer()`). This is why, the MBeans registered in the integration tests are not visible through `getQueryRunner()).getCoordinator().getMbeanServer()`.

**Comment by ebyhr** [comment]
Merged, thanks!

**Pull request merged**
