### PR TITLE
Run testTimestampInsertCompatibility only in OSS Delta

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Follow-up of https://github.com/trinodb/trino/pull/20420. 
Running the test with OSS Delta Lake seems sufficient. 

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Comment by findepi** [comment]
didn't https://github.com/trinodb/trino/pull/20420 show that results may be DBR version dependent?

**Review by findepi — APPROVED** [review]
but see previous comment/q

**Comment by mosabua** [comment]
I think this should be reopened and probably merged @ebyhr and @findepi

**Comment by ebyhr** [comment]
> didn't https://github.com/trinodb/trino/pull/20420 show that results may be DBR version dependent?

The expected result should be same regardless of Databricks version. There's no benefit to catch Databricks bug in this case.

**Pull request merged**
