### PR TITLE
Show metadata from available catalogs

### PR DESCRIPTION
**Pull request by tooptoop4**
Fixes https://github.com/prestosql/presto/issues/1173

### CODE REVIEW

**Comment by electrum** [comment]
I don't think ignoring errors is the right solution. If you ask for metadata about a catalog and that catalog throws an error, simply ignoring the error would be returning the wrong answer.

**Comment by tooptoop4** [comment]
@electrum the background is presto can have many catalogs. If the sqlserver database is down, then sqlserver catalog cannot be retrieved. But why should the hive catalog or mysql catalog not get shown at all if mysql/hive systems are up? This is about showing catalogs for the systems that are actually available rather than making it an all or nothing. This fix is critical for allowing presto to connect to many different sources/catalogs. Imagine having 10 catalogs but an outage to 1 catalog effectively means NO metadata can be retrieved from any of the other 9 catalogs! As you know JDBC clients often run a blocking query to retrieve this metadata (system.jdbc.tables) before allowing users to run queries on 'real tables'

**Comment by electrum** [comment]
I consider it a bug in the application to ask for metadata from all catalogs at once, rather than a specific catalog the user is interested in.

A core philosophy for Presto is that it always returns correct answers. If we get a query for metadata for all catalogs, we have to answer correctly or fail. Returning an incorrect answer is not an option.

It’s possible we could make this configurable, but we’d need to carefully consider the implications.

**Comment by tooptoop4** [comment]
even ```select * from system.jdbc.tables where table_cat = 'hive'``` will give error when just sqlserver catalog has outage

**Comment by electrum** [comment]
That’s a bug we need to fix. It sounds like we’re not filtering properly, which is also a performance problem.

**Comment by findepi** [comment]
> even `select * from system.jdbc.tables where table_cat = 'hive'` will give error when just sqlserver catalog has outage

@tooptoop4 can you file a separate issue for this?

**Comment by colebow** [comment]
:wave: @tooptoop4 - this PR has drawbacks that don’t align with our preferred approach, so we’re not going to proceed with this implementation. If you'd like to continue the discussion on this at any point in the future, feel free to re-open and chime in.

**Pull request closed without merging**
