### PR TITLE
Support HUDI create table

### LINKED ISSUE #14845: Support hudi create table
According to the [task](https://issues.apache.org/jira/browse/HUDI-5116), support the HUDI create table.

### PR DESCRIPTION
**Pull request by albericgenius**
## Description
Fix #14845
Implement the HUDI create table and implement unit test

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`14845`)
```

### CODE REVIEW

**Comment by albericgenius** [comment]
@codope I added create table test cases, and fixed the failed test cases already. 
Currently the failing CI task is not relative to my code.
Relay on your expertise to review the code, and give me suggestion.

Thanks
Alberic

**Comment by albericgenius** [comment]
> We should add some product tests in this PR after merging #14936. We should verify:
> 
> * Spark can read tables created by Trino
> * Spark can insert into tables created by Trino, and vice versa

May I can added the product tests in the other PR, there are already 35 files changed.

**Comment by ebyhr** [comment]
I strongly recommend adding product tests to this PR. Otherwise, the new tables might be not readable by Spark.

**Comment by albericgenius** [comment]
> #14936
got you, I saw your comments on #14936, after it merged, I will create the test case as your mentioned:
```
Create a table in Hudi and drop the table in Trino
```

**Comment by ebyhr** [comment]
@albericgenius Could you rebase on upstream and add product tests?

**Comment by albericgenius** [comment]
> @albericgenius Could you rebase on upstream and add product tests?
Yes, I will work on this.

**Comment by albericgenius** [comment]
depend on [the docker image PR](https://github.com/trinodb/docker-images/pull/156)

**Comment by ebyhr** [comment]
> The product test depend on https://github.com/trinodb/docker-images/pull/156

@albericgenius Could you explain why a new image is required?

**Comment by albericgenius** [comment]
> > The product test depend on [trinodb/docker-images#156](https://github.com/trinodb/docker-images/pull/156)
> 
> @albericgenius Could you explain why a new image is required?
+ Thanks for help.
+ The HoodieTableVersion FIVE is not existed in Hudi 0.11.1, so the updated product test will be failed.
+ After this [PR](https://github.com/trinodb/docker-images/pull/157) merged(there is still dependence issue in 73), I will sent out the new revision.

**Comment by HiIamJeff** [comment]
Hi there, 
Thanks for all your work regarding the Hudi connector! I am considering using the Hudi connector in my project but DDL/DML functionalities are essential to it. I wonder if there is any plan to merge this PR and release the update?

**Comment by mosabua** [comment]
:wave: @albericgenius  - this PR has become inactive. We hope you are still interested in working on it. Please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

also cc @codope @brandyml

**Comment by mosabua** [comment]
I am closing this pool request in the hope that you @albericgenius will still take it up again but maybe instead of re-basing choose to create a new PR.

**Pull request closed without merging**
