### PR TITLE
Clarify syntax for role grants

### PR DESCRIPTION
**Pull request by Jessie212**
## Description

Clarify syntax for role grants. The current syntax has misled multiple readers to think that this is valid.

```
GRANT ROLE test TO jessie212;
```

We assume that readers think that the lowercase `role` is a typo.

I worked with @mosabua and confirmed in the antlr spec that this is wrong and the syntax is

```
GRANT test TO jessie212;
```

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by mosabua** [comment]
Also note that this mimics the syntax example for CREATE ROLE

```
CREATE ROLE role_name
[ WITH ADMIN ( user | USER user | ROLE role | CURRENT_USER | CURRENT_ROLE ) ]
[ IN catalog ]
```

**Comment by mosabua** [comment]
Can you chime in here @martint and @dain ?

Its kinda weird that we have grant and grant roles as separate statements with similar syntax .. but I guess the SQL spec says so..

**Comment by Jessie212** [comment]
> Also note that this mimics the syntax example for CREATE ROLE
> 
> ```
> CREATE ROLE role_name
> [ WITH ADMIN ( user | USER user | ROLE role | CURRENT_USER | CURRENT_ROLE ) ]
> [ IN catalog ]
> ```

There's a See also section way at the bottom that links to the CREATE ROLES , DROP ROLES, SET ROLES, and REVOKE ROLES docs.

**Comment by mosabua** [comment]
Also .. maybe we should change the title of this page to 

```
GRANT roles
```

or even 

```
GRANT role
```

**Comment by mosabua** [comment]
Also .. maybe the GRANT and GRANT ROLES pages should be collapsed into one page??

**Comment by Jessie212** [comment]
> ```
> GRANT role
> ```
> 
> 
>     
>   
> 
> And to adjust for consistency change the GRANT page to
> 
> ```
> GRANT privilege
> ```
> 
> 
>     
>   
> 
> as title.

Should we condense the statements? For instance, all CREATE statements go on the CREATE page. Do the same for DROP, GRANT, ALTER etc...

**Comment by mosabua** [comment]
> > ```
> > GRANT role
> > ```
> > 
> > 
> > And to adjust for consistency change the GRANT page to
> > ```
> > GRANT privilege
> > ```
> > 
> > 
> > as title.
> 
> Should we condense the statements? For instance, all CREATE statements go on the CREATE page. Do the same for DROP, GRANT, ALTER etc...

No ... the objects are very important .. so the statements are all a verb and a object typically .. CREATE TABLE .. and so on. GRANT is kinda the exception.

**Comment by Jessie212** [comment]
> No ... the objects are very important .. so the statements are all a verb and a object typically .. CREATE TABLE .. and so on. GRANT is kinda the exception.

Okay. I will move and rename the GRANT files in the follow-up PR.

What about this comment: https://github.com/trinodb/trino/pull/19340#issuecomment-1756357931

**Comment by mosabua** [comment]
Lets wait and see until we get some feedback/input from @martint and @electrum  .. probably next week

**Review by mosabua — APPROVED** [review]
Looks good now. Follow approach discussed and approved by @electrum . Thank you @Jessie212

**Pull request merged**
