### PR TITLE
Add support for bucketing on decimal type

### PR DESCRIPTION
**Pull request by Praveen2112**

### CODE REVIEW

**Review by aczajkowski — APPROVED** [review]
LGTM

**Comment by findepi** [comment]
@Praveen2112 let's decide whether we want this in first, or continue with https://github.com/trinodb/trino/pull/8986?

i don't want to review both concurrency, as this could result in some review omissions around code post-merge.

**Comment by losipiuk** [comment]
@Praveen2112 still draft?

**Comment by Praveen2112** [comment]
@losipiuk , @findepi It is ready for another round of review.

**Comment by mosabua** [comment]
:wave: @Praveen2112  - this PR has become inactive.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by colebow** [comment]
Closing this one out due to inactivity, but please reopen if you would like to pick this back up.

**Pull request closed without merging**
