### PR TITLE
Test: Add Delta synchronizer for GCS

### PR DESCRIPTION
**Pull request by ebyhr**
Run tests with secret #12523

### CODE REVIEW

**Comment by ebyhr** [comment]
Updated to the current status of #12523

**Comment by ebyhr** [comment]
Updated to the current status of https://github.com/trinodb/trino/pull/12523

**Comment by findepi** [comment]
Updated to the current status of https://github.com/trinodb/trino/pull/12523

**Comment by findepi** [comment]
Updated to the current state of https://github.com/trinodb/trino/pull/12523

**Comment by findepi** [comment]
Updated to the current state of https://github.com/trinodb/trino/pull/12523

**Comment by findinpath** [comment]
@findepi  / @ebyhr please issue a new build. I'd like to verify whether the Delta GCS tests do normally take ~ 36m+ or there was an exceptional situation.
Details in https://github.com/trinodb/trino/pull/12523#issuecomment-1256861951

**Comment by ebyhr** [comment]
Pushed an empty commit.

**Comment by ebyhr** [comment]
Updated.

**Comment by findepi** [comment]
Updated to the current state of https://github.com/trinodb/trino/pull/12523

**Comment by findepi** [comment]
Updated to the current state of https://github.com/trinodb/trino/pull/12523

**Comment by findepi** [comment]
Updated to the current state of https://github.com/trinodb/trino/pull/12523

**Pull request closed without merging**
