### PR TITLE
Fix incorrect results when FTE and bulk INSERT is enabled in SQL Server 

### LINKED ISSUE #14856: Trino loading table with all nulls if bulk copy setting enabled for sql server connector
In Trino Version 401, For sql server connector if the below bulk copy setting is enabled. Trino populating table with all null data.
Issue not noticed earlier to version 380.

```
sqlserver.bulk-copy-for-write.enabled=true
sqlserver.bulk-copy-for-write.lock-destination-table=true
```

Eg DDL to re-create issue:
```
CREATE TABLE feeds.dbo.table1_stg (
   "run date" varchar(25),
   "enabled in ad" boolean,
   "enrolled in maas 360" varchar(25),
   "correct device" varchar(25),
   "valid ad username" boolean,
   "operating system updated" varchar(25),
   "device operating system" varchar(25),
   "latest operating system" varchar(25),
   "password expired" boolean,
   "device id" varchar(255),
   device varchar(50),
   carrier varchar(50),
   "device name" varchar(255),
   username varchar(50),
   "email address" varchar(255),
   "manager email address" varchar(255),
   model varchar(50),
   imei varchar(50),
   "maas 360 installed date" varchar(50),
   "maas 360 last reported date" varchar(50),
   "hire date" varchar(50),
   "rehire date" varchar(50),
   "phone number" varchar(50),
   policy varchar(100),
   "policy version" varchar(50),
   "browsing policy" varchar(50),
   "first name" varchar(50),
   "last name" varchar(50),
   state varchar(2),
   city varchar(255),
   "employee id" varchar(50),
   "position level" varchar(50),
   title varchar(255),
   "normalized title" varchar(50),
   region varchar(255),
   "kma description" varchar(50),
   company varchar(255),
   "password last set" varchar(50),
   "security patch level" varchar(50),
   "latest security patch level" varchar(50),
   "security patch level current" varchar(50),
   "rml email address" varchar(255),
   "user on loa" varchar(10),
   "device in knox" varchar(10),
   "number of enrollments" varchar(10),
   load_datetime timestamp(7)
)
WITH (
   data_compression = 'PAGE'
)
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #14856

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by ebyhr** [comment]
Looking CI failures.

**Review by losipiuk — COMMENTED** [review]
LGTM. Does new test cover that?

**Comment by ebyhr** [comment]
Yes, the new assertion failed without this change.

**Comment by ebyhr** [comment]
@losipiuk I pushed small change. Could you take another look?

**Review by losipiuk — APPROVED** [review]
Thx

**Pull request merged**
