### PR TITLE
Make functionNullability property consistent in ResolvedFunction

### PR DESCRIPTION
**Pull request by weiatwork**
The mismatch of "nullability" and "functionNullability" could cause failure of JSON deserialization for ResolvedFunction.

The symptom is query that involves function usages fails with error message like:
`java.lang.IllegalArgumentException: Invalid JSON bytes for [simple type, class io.trino.metadata.ResolvedFunction]`

Root cause is #10183, and specifically https://github.com/trinodb/trino/commit/2c1ebd61f2a017563ba27a2e7a19e51e66ae472d

The problem is exposed starting from https://github.com/trinodb/trino/pull/11217

Repro steps:
1. Create a file-based access control policy for a table with row filter or column mask that uses a function `"filter": "name LIKE 'A%'"`
2. Run a query against the table

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?
fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
core query engine

> How would you describe this change to a non-technical end user or system administrator?
n/a

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by findepi — APPROVED** [review]
The change makes sense. Seems `ResolvedFunction` wants to be serializable but we don't exercise that code in any way.
@weiatwork did you try to expose the problem with a regression test?

**Comment by weiatwork** [comment]
Thanks for taking a look. I just happened to realize my query started failing with functions in AC policies. I couldn't reproduce with pure query using functions though.

**Comment by findepi** [comment]
Could you please try to repro the problem with a test in `TestFileBasedSystemAccessControl`?

**Comment by weiatwork** [comment]
There seems to be already test case that covers this (using functions). But I'm guessing it is not easily reproducible if not in an end-to-end manner.
https://github.com/trinodb/trino/blob/master/lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java#L1350

**Comment by findepi** [comment]
@weiatwork a test can be as end-to-end as needed to exercise given portion of the code.
it seems to me that we rely on `ResolvedFunction` being json-serializable, but it didn't work, which points at a gap in our testing.

**Comment by weiatwork** [comment]
Good point. I agree this should have been covered the UT. @wendigo Do you have any idea how we can get this tested out? Thanks.

**Comment by weiatwork** [comment]
@dain @wendigo In case you missed the update

**Comment by wendigo** [comment]
@findepi, @weiatwork  since we already have `TestResolvedFunction` class I'd add a unit test there to assert on a correct round-trip:

```
@Test
    public void testRoundTrip()
    {
        ResolvedFunction resolvedFunction = createResolvedFunction("top", 3);
        ResolvedFunctionDecoder decoder = new ResolvedFunctionDecoder(TestResolvedFunction::varcharTypeLoader);

        QualifiedName serializedFunction = ResolvedFunctionDecoder.serialize(resolvedFunction);
        assertThat(decoder.deserialize(serializedFunction)).isEqualTo(resolvedFunction);
    }
```

then as @findepi said we need to add a test in `TestFileBasedSystemAccessControl` which uses a row filter function that you've mentioned. See for reference: `core/trino-main/src/test/resources/catalog_read_only.json` which is used in `testCatalogOperationsReadOnly()` test method

**Comment by wendigo** [comment]
@weiatwork @findepi there is already a round-trip test in `TestResolvedFunction`

**Comment by weiatwork** [comment]
@wendigo Thanks for the pointer. It's interesting that when I run TestResolvedFunction locally without my fix, this test does fail, and with my fix it doesn't. Why doesn't CI have the problem? Is this test ever run by CI?

**Comment by wendigo** [comment]
@weiatwork actually for me this tests passed locally, without your change

**Comment by weiatwork** [comment]
I just rebased my code to latest, and yes I also got the test succeed even without my change. That's strange. Anyway, I think the fix is still needed for sanity reason. But looks like this PR is marked as "merged" (possibly due to my rebasing of my master branch). @findepi Can you help with this PR?

**Comment by findepi** [comment]
@weiatwork  Can you please open a new PR?

**Comment by weiatwork** [comment]
@findepi https://github.com/trinodb/trino/pull/13777 has been created for the same. Sorry for the inconvenience

**Comment by findepi** [comment]
> when I run TestResolvedFunction locally without my fix, this test does fail

it doesn't fail for me

**Pull request merged**
