### PR TITLE
Add project icon for IntelliJ

### PR DESCRIPTION
**Pull request by wendigo**
This adds a project icon for IntelliJ which is nicely rendered in the project selection window:

Screenshot 2023-07-07 at 19 33 24

### CODE REVIEW

**Comment by mosabua** [comment]
File looks good to me. I am just not sure if this is a problem with existing .idea folder on developer workstations and also if we have a policy for or against checking in IDE config files.

**Comment by mosabua** [comment]
Discussed on slack and approved by @dain and @electrum

**Review by mosabua — APPROVED** [review]
Lgtm ..

**Comment by colebow** [comment]
This is awesome.

**Comment by findepi** [comment]
This looks like a Dead Bunny in JetBrains Toolbox. To me, this looks a bit like from a scary movie.

image

**Pull request merged**
