### PR TITLE
Update snakeyaml to 2.1

### PR DESCRIPTION
**Pull request by wendigo**
No release notes needed.

### CODE REVIEW

**Comment by wendigo** [comment]
PTAL @kokosing

**Comment by hashhar** [comment]
some context to updates is useful, helps when looking back to see why it was updated. Otherwise it involves guesswork.

**Comment by wendigo** [comment]
According to changes file @hashhar:

```
<action dev="asomov" type="fix" issue="1075">
    Heavy Allocation in Emitter.analyzeScalar(String) due to Regex Overhead
    (thanks to Carter Kozak)
</action>
<action dev="asomov" type="fix" issue="1064">
    Use identity in toString() for sequences to avoid OutOfMemoryError
    (thanks to 郭逸帆)
</action>
<action dev="asomov" type="fix" issue="1061">
    https://github.com/FasterXML/jackson-dataformats-text/issues/406
    https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56902
    %YAML 1.9224775801
    (thanks to Tatu Saloranta)
</action>
<action dev="asomov" type="fix" issue="1065">
    Document size limit should be applied to single document not the whole input stream
    (thanks to Petr Gladkikh)
</action>
<action dev="asomov" type="fix" issue="576">
    Detect invalid Unicode code point (thanks to Tatu Saloranta)
</action>
<action dev="maslovalex" type="remove">
    Remove Trusted*Inspector classes from main sources tree
</action>
```

**Comment by wendigo** [comment]
PTAL @hashhar

**Review by losipiuk — APPROVED** [review]

**Pull request merged**
