### PR TITLE
Call semanticException method as a format method in several places

### PR DESCRIPTION
**Pull request by ksobolew**
## Description

The `semanticException` factory method is a format method - it takes a format string and format arguments - so it shoule be called as one. A future PR will enforce that using Error Prone, this PR collects fixes for the less trivial cases that need to be converted.

## Non-technical explanation

Better code quality.

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by kokosing — APPROVED** [review]

**Comment by ksobolew** [comment]
Kudu tests timed out

**Comment by kokosing** [comment]
@ksobolew Please report the flakiness of kudu as github issue.

**Comment by ksobolew** [comment]
It's actually this one: #14487

**Comment by kokosing** [comment]
The release is now in progress. I will merge once the release is complete. Please ping me if I forget.

**Comment by ksobolew** [comment]
Ping :)

**Comment by kokosing** [comment]
No release notes.

**Comment by kokosing** [comment]
@ksobolew Thanks!

**Pull request merged**
