### PR TITLE
Throw TrinoException when creating Iceberg table that already exists

### PR DESCRIPTION
**Pull request by pajaks**
## Description

In case table already exists throw TrinoException with clear error type.

## Additional context and related issues

Example stack trace:
```  "type": "org.apache.iceberg.exceptions.AlreadyExistsException",
  "message": "Requirement failed: table already exists: xxxxxx in warehouse xxxxxxxx",
  "suppressed": [],
  "stack": [
    "org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:115)",
    "org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:102)",
    "org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:201)",
    "org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:313)",
    "org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:252)",
    "org.apache.iceberg.rest.HTTPClient.post(HTTPClient.java:358)",
    "org.apache.iceberg.rest.RESTClient.post(RESTClient.java:112)",
    "org.apache.iceberg.rest.RESTTableOperations.commit(RESTTableOperations.java:152)",
    "org.apache.iceberg.BaseTransaction.commitCreateTransaction(BaseTransaction.java:327)",
    "org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:306)",
    "io.trino.plugin.iceberg.IcebergMetadata.finishInsert(IcebergMetadata.java:1195)",
    "io.trino.plugin.iceberg.IcebergMetadata.finishCreateTable(IcebergMetadata.java:1054)",
```

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by ebyhr** [comment]
> Throw TrinoException when creating table that already exists

The PR and commit title look generic. I would recommend including "Iceberg".

**Comment by ebyhr** [comment]
The existing table should be denied by the engine. Was this a concurrent issue?

**Comment by pajaks** [comment]
> The existing table should be denied by the engine. Was this a concurrent issue?

Yes it looks like it may happen when someting changes concurrently.

**Review by losipiuk — APPROVED** [review]

**Review by ebyhr — APPROVED** [review]

**Review by anusudarsan — APPROVED** [review]
do we have tests for such scenarios?

**Comment by pajaks** [comment]
> do we have tests for such scenarios?

I haven't found any test for it.

**Comment by losipiuk** [comment]
> > do we have tests for such scenarios?
> 
> I haven't found any test for it.

I think you should read Anu's question as "consider adding test for that" :)

**Pull request merged**
