### PR TITLE
Revert "Add column add/drop/rename events"

### PR DESCRIPTION
**Pull request by findepi**
Reverts trinodb/trino#15225

The current implementation has the following problems

- does not work for Hive connector with `hive.security=system` (https://github.com/trinodb/trino/pull/15225#discussion_r1093300534)
- notifications are propagated even if transaction doesn't end up committing the DDL changes (https://github.com/trinodb/trino/pull/15225#discussion_r1094648449)
- notification propagation may disrupt transaction finish even if changes already applied in the external system (https://github.com/trinodb/trino/issues/12535#issuecomment-1417684880), for any connector that's using SYSTEM security (Iceberg, Delta with system security, or any JDBC connector)

The revert is only temporary, the functionality will be reintroduced soon.

Fixes https://github.com/trinodb/trino/issues/12535

### CODE REVIEW

**Comment by findepi** [comment]
Of course, we can also fix the functionality, instead of revert, if a fix exists.
Generally I would prefer the master branch to be always release-ready, and reverting the revert is trivial, so we lose nothing with this PR.

cc @trinodb/maintainers

**Comment by findepi** [comment]
CI failed with an Ubuntu update problem, going to be fixed by https://github.com/trinodb/trino/pull/15840
(cc @MiguelWeezardo that's why it would be nice to have an issue, https://github.com/trinodb/trino/pull/15840#issuecomment-1419011344)

**Comment by findepi** [comment]
(updated commit message, no other changes)

**Comment by findepi** [comment]
CI https://github.com/trinodb/trino/issues/15992

**Review by djsstarburst — APPROVED** [review]
Sorry that this caused trouble.

**Comment by findepi** [comment]
> Sorry that this caused trouble.

No worries @djsstarburst and thank you for your review!

**Review by electrum — CHANGES_REQUESTED** [review]
It seems like we can fix this trivially by doing the `getTableMetadata()` before the column operation. It should be guarded by the security management check, so that we don't fetch it unnecessarily.

So add column would look like
```java
@Override
public void addColumn(Session session, TableHandle tableHandle, ColumnMetadata column)
{
    CatalogHandle catalogHandle = tableHandle.getCatalogHandle();
    CatalogMetadata catalogMetadata = getCatalogMetadataForWrite(session, catalogHandle);
    ConnectorMetadata metadata = catalogMetadata.getMetadata(session);

    SchemaTableName tableName = null;
    if (catalogMetadata.getSecurityManagement() != CONNECTOR) {
        tableName = getTableMetadata(session, tableHandle).getTable();
    }

    metadata.addColumn(session.toConnectorSession(catalogHandle), tableHandle.getConnectorHandle(), column);

    if (catalogMetadata.getSecurityManagement() != CONNECTOR) {
        CatalogSchemaTableName sourceTableName = new CatalogSchemaTableName(catalogHandle.getCatalogName(), tableName);
        systemSecurityMetadata.columnCreated(session, sourceTableName, column.getName());
    }
}

**Comment by findepi** [comment]
> It seems like we can fix this trivially by doing the `getTableMetadata()` before the column operation.

That solves some, but not all, problems outlined above.

Anyway, looking forward in seeing this in a PR.

**Comment by findepi** [comment]
Marked this as a `correctness` because this fixes a correctness issue https://github.com/trinodb/trino/issues/12535.
Marked this as a `RELEASE-BLOCKER` because the correctness issue is a regression introduced in the last release (406; https://github.com/trinodb/trino/issues/12535#issuecomment-1418992171)

Talking with @electrum @djsstarburst offline about this PR.

**Review by electrum — APPROVED** [review]
I didn’t realize this is correctness issue in an existing connector, when not using this feature. We should revert.

**Comment by findepi** [comment]
Thank you @electrum for your review!

**Comment by findepi** [comment]
CI https://github.com/trinodb/trino/issues/14637

**Pull request merged**
