### PR TITLE
Allow for overriding GlueColumnStatisticsProvider

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by losipiuk** [comment]
CI: raptor issue fixed on master by https://github.com/trinodb/trino/pull/7040

**Review by hashhar — APPROVED** [review]
Looks good to me.

Are there any tests which are verifying the module setup?

**Comment by losipiuk** [comment]
> Looks good to me.
> 
> Are there any tests which are verifying the module setup?

there is `TestHiveHadoop2Plugin`

**Comment by losipiuk** [comment]
I send out another PR not from fork so Glue tests are run here: https://github.com/trinodb/trino/pull/7053

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
> Due to some GHA weirdness this PR and the other one are sharing checks.

results are tied to commit hash i believe, but @wendigo will know better

**Pull request merged**
