### PR TITLE
Use ZSTD compression by default for PARQUET in Hive connector

### PR DESCRIPTION
**Pull request by losipiuk**
## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by findepi — APPROVED** [review]

**Comment by wrborigin** [comment]
Just a note - this change should be well documented. Amazon Redshift Spectrum (Redshift way of reading data from S3) can read Parquet files, but not zstd compressed ones.

So this change might break some (admittedly pretty rare) setups where someone is writing Parquet via Trino and reading it using Redshift.

**Review by hashhar — COMMENTED** [review]
How does this play with each partition or file having different compression method? (AFAIK it's possible to have that).

(I don't know if we already have tests covering reads from a table with a mix of compression formats or file formats).

**Comment by findepi** [comment]
> How does this play with each partition or file having different compression method? (AFAIK it's possible to have that).

@hashhar  It's possible and it's not a problem


> Just a note - this change should be well documented. Amazon Redshift Spectrum (Redshift way of reading data from S3) can read Parquet files, but not zstd compressed ones.

@wrborigin thank you for pointing this out. We should make sure the change of the default compression is mentioned in the release notes.

**Comment by mosabua** [comment]
Is this still in progress @losipiuk ?

**Pull request closed without merging**
