### PR TITLE
Add docs for Athena Partition Projection

### PR DESCRIPTION
**Pull request by aczajkowski**
## Description

Adds documentation to Athena Partition Projection feature.

## Related issues, pull requests, and links

- [x] #10767
- [ ] #13218

## Documentation

 - [ ] No documentation is needed.
 - [x] Sufficient documentation is included in this PR.
 - [ ] Documentation PR is available with #prnumber.
 - [ ] Documentation issue #issue is filed, and can be handled later.

## Release notes

 - [x] No release notes entries required.
 - [ ] Release notes entries required with the following suggested text:

### CODE REVIEW

**Comment by aczajkowski** [comment]
CC: @k-haley1 Please follow up on this.

**Comment by mosabua** [comment]
@colebow can we make sure this gets in asap

**Comment by colebow** [comment]
I'm going to put up a similar PR today so we can iterate quickly and try to get this merged before release tomorrow.

**Comment by aczajkowski** [comment]
> I'm going to put up a similar PR today so we can iterate quickly and try to get this merged before release tomorrow.

@colebow  You can take over this one. Let me know if I can help anyhow.

**Comment by mosabua** [comment]
Replaced by https://github.com/trinodb/trino/pull/13238

**Pull request closed without merging**
