### PR TITLE
Check procedure argument for NULL in RollbackToSnapshotProcedure

### PR DESCRIPTION
**Pull request by krvikash**
## Description
Fixes https://github.com/trinodb/trino/issues/15399

Check procedure argument for NULL in RollbackToSnapshotProcedure to prevent NPE

## Release notes

(X) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by findinpath** [comment]
Could you pls add also a test in `io.trino.tests.product.iceberg.TestIcebergProcedureCalls#testRollbackToSnapshot` for the fix you just submitted?

**Review by ebyhr — APPROVED** [review]
> (X) Release notes are required, with the following suggested text:

There's no need to mention in release notes in my opinion. It's just for improving the error message.

**Comment by ebyhr** [comment]
@krvikash Could you confirm other procedures as well? Follow-up PR is fine.

**Review by findinpath — APPROVED** [review]

**Comment by krvikash** [comment]
@ebyhr, FYI https://github.com/trinodb/trino/pull/15508

**Pull request merged**
