### PR TITLE
Remove deprecated SPI elements

### PR DESCRIPTION
**Pull request by skrzypo987**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

> How would you describe this change to a non-technical end user or system administrator?

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

() No release notes entries required.
(x) Release notes entries required with the following suggested text:

```markdown
# SPI
* Removed deprecated SPI methods and classes related to the grouped execution feature. ({issue}`13125`)
```

### CODE REVIEW

**Comment by sopel39** [comment]
Failed due https://github.com/trinodb/trino/issues/12931

**Review by raunaqmorarka — APPROVED** [review]

**Review by sopel39 — APPROVED** [review]
I would also like other maintainers to look at it

**Comment by skrzypo987** [comment]
> > (x) No release notes entries required.
> 
> It would be better to mention in a release note in my opinion.

It is really a questions to maintainers. I don't really know whether we should do that for the removal of deprecated features.

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
@skrzypo987 the build is red

**Comment by skrzypo987** [comment]
CI seems to be hitting https://github.com/trinodb/trino/issues/12931

**Pull request merged**
