### PR TITLE
Improve performance of Iceberg optimize

### PR DESCRIPTION
**Pull request by zhengxingmao**
## Description
Improve performance of alter table execute optimize,only files smaller than the specified file size are merged.

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( *) Release notes are required, with the following suggested text:

```markdown
# Section
* Improve performance of alter table execute optimize
```

### CODE REVIEW

**Review by alexjo2144 — CHANGES_REQUESTED** [review]
This is not correct. `task.getFileSizeInBytes()` is the file size after merging the files, so if a bunch of small files are merged into a file bigger than the threshold this will cause a correctness issue with dropped data.

**Comment by alexjo2144** [comment]
This is the check which ensure that large files are not scanned during `optimize` https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java#L211

**Comment by homar** [comment]
> This is the check which ensure that large files are not scanned during `optimize` https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java#L211

lol guess who added it :D

**Comment by zhengxingmao** [comment]
> This is the check which ensures that large files are not scanned during `optimize` https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java#L211

Yeah,you're right.I closed this pr.

**Pull request closed without merging**
