### PR TITLE
Support public S3 bucket access

### PR DESCRIPTION
**Pull request by tooptoop4**
Fixes https://github.com/prestosql/presto/issues/6127

### CODE REVIEW

**Comment by mosabua** [comment]
:wave: @tooptoop4  - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.

Also @ebyhr does this functionality already exist now?

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by metadaddy** [comment]
@mosuba Funnily enough, I landed here today trying to figure out how to make Trino read data from a public Backblaze B2 bucket (via its S3-compatible API). I've done a fair bit of work with S3, so, if @tooptoop4 isn't interested, I'd be happy to adopt this PR and move it forward.

**Comment by metadaddy** [comment]
@mosabua Funnily enough, I landed here today trying to figure out how to make Trino read data from a public Backblaze B2 bucket (via its S3-compatible API). I've done a fair bit of work with S3, so, if @tooptoop4 isn't interested, I'd be happy to adopt this PR and move it forward.

**Comment by mosabua** [comment]
That sounds good. Let's wait and see how @ebyhr and @tooptoop4 chime in and then you can potentially run with this.

**Comment by tooptoop4** [comment]
@metadaddy pls take over

**Comment by tooptoop4** [comment]
ouch

**Comment by mosabua** [comment]
@ebyhr did you close this PR because the feature is already available or because @metadaddy is going to create a replacment?

**Comment by metadaddy** [comment]
@mosabua From inspecting the code in the master branch, I can confidently say that this feature is not already available.

**Comment by mosabua** [comment]
@ebyhr how did you want to proceed here?

**Comment by metadaddy** [comment]
BTW - I've rebased @tooptoop4's changes into the current master, and I'm currently testing them. I'll submit a new PR in the next week or so.

**Pull request closed without merging**
