### PR TITLE
Rename confusing property MAX_WRITER_TASK_COUNT

### PR DESCRIPTION
**Pull request by gaurav8297**
Fixes https://github.com/trinodb/trino/issues/20075

## Description
https://github.com/trinodb/trino/issues/20075

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by sopel39 — APPROVED** [review]
The doc needs update too. @mosabua  @findepi or @losipiuk could you also take a look?

**Comment by sopel39** [comment]
Fixes https://github.com/trinodb/trino/issues/20075

**Comment by findepi** [comment]
So we end up with

`max_number_of_writer_tasks`
`task_max_writer_count`

is it not still confusing?
(obviously, confusion is a subjective thing)

**Comment by findepi** [comment]
See also https://github.com/trinodb/trino/issues/20075#issuecomment-1862616374

**Review by mosabua — COMMENTED** [review]
I am in different about changing the name. On the one hand this is a bit more readable now, on the other its also inconsistent with all other naming so that makes it harder. 

If we want to merge this we at least also need to make sure the properties and session properties (if there are any) are consistent with each other (apart from _) and that the docs are updated. 

Not sure the minimal gains are worth it, and lean towards agreeing with @findepi and leaving this all alone. If anything we could update the docs more and link the properties to each other mentioned that they should not be confused.

**Comment by mosabua** [comment]
👋  @gaurav8297 .. I think we will leave the properties as they are.  Did you want to send a PR to improve the documentation instead? 

Are you okay with closing this PR @findepi and @losipiuk ?

**Pull request closed without merging**
