### PR TITLE
Properly initialize Iceberg REST catalog Configuration

### PR DESCRIPTION
**Pull request by alexjo2144**
## Description

Without these configurationInitializers catalog properties are not properly sent to the file system implementation. 

## Additional context and related issues

https://github.com/trinodb/trino/pull/13294

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
(x) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Review by electrum — CHANGES_REQUESTED** [review]
Why do we need to give it Hadoop properties? The `setConf()` calls are removed entirely here: https://github.com/trinodb/trino/pull/16454

**Comment by alexjo2144** [comment]
We either need to set it or change the FileIO implementation that's being used. Because we delegate to the core Iceberg library for the `RESTTableOperations, the FileIO that gives us back right now is a `HadoopFileIO` which needs the Configuration.

In the other TrinoCatalog implementations we use `ForwardingFileIO` but that's not plumbed in here yet.

**Comment by electrum** [comment]
We should fix it to use `ForwardingFileIO`.

**Comment by alexjo2144** [comment]
@electrum how would you feel about merging this fix for now and getting ForwardingFileIO into here and JDBC after? The rest catalog is completely broken as is.

**Comment by danielcweeks** [comment]
@alexjo2144 You can set the Catalog FileIO via the [RESTSessionCatalog initialization here](https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java#L78)

```java
properties.put(CatalogProperties.FILE_IO_IMPL, ForwardingFileIO.class.getName())
```

**Comment by alexjo2144** [comment]
Thanks Dan, I saw that but the ForwardingFileIO takes a `TrinoFileSystem` argument in the constructor and I couldn't figure out how to get that in there.

**Comment by alexjo2144** [comment]
I see, we can use ForwardingFileIO today if we implement `HadoopConfigurable`

**Comment by electrum** [comment]
@dain and I had a call with @rdblue and @danielcweeks this morning. Ryan is going to propose an API change Iceberg 1.2.0 for the catalogs that lets us provide a `FileIO` for a given configuration.

**Comment by electrum** [comment]
We'll be able to fix this with Iceberg 1.2.0 thanks to https://github.com/apache/iceberg/pull/7064

**Comment by alexjo2144** [comment]
Thanks David, if you'd rather wait for that fix in 1.2.0 I'll go ahead and close this

**Pull request closed without merging**
