### PR TITLE
Load Iceberg splits on a background thread using AsyncQueue

### PR DESCRIPTION
**Pull request by lzeiming**
## Description

Getting splits from iceberg do not return until reaching the batch size or the end. This could block the scheduler. 
This PR makes the load process in the background as Hive connector

> Is this change a fix, improvement, new feature, refactoring, or other?

improvement

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Iceberg connector

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
(x) Release notes entries required with the following suggested text:

```markdown
# Iceberg
* Load splits in the background
```

### CODE REVIEW

**Comment by hashhar** [comment]
cc: @alexjo2144

**Comment by alexjo2144** [comment]
I had a set of changes like this initially when I added Dynamic Filter support to Iceberg but @electrum and I decided it was not needed. That conversation is in a PR here: https://github.com/trinodb/trino/pull/9193#issuecomment-934481262

My understanding is that the main reason async split loading is useful in Hive is because there is a I/O block per partition while we wait for the FileSystem to list the files in the partition directory. Here in Iceberg, however, we're loading split information from a single source, reducing the gains from parallel loading.

**Comment by alexjo2144** [comment]
> The split size and number are the same, but Hive takes 1 to 2 seconds, Iceberg takes 3 to 4 seconds. I did not expect the latency increase so much.

 What was it after these changes?

**Comment by lzeiming** [comment]
> > The split size and number are the same, but Hive takes 1 to 2 seconds, Iceberg takes 3 to 4 seconds. I did not expect the latency increase so much.
> 
> What was it after these changes?
In average, Hive connector takes 1.9 seconds, Iceberg connector takes 3.4 seconds before change.
After the change Iceberg connector takes 3.1 seconds

**Comment by bitsondatadev** [comment]
:wave: @lzeiming - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Pull request closed without merging**
