### PR TITLE
Remove language codes from external URLs

### PR DESCRIPTION
**Pull request by blvckcoffee**
## Description

* Removes language codes from external URLs in multiple files to better accommodate a global audience

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by mosabua — APPROVED** [review]
Nice cleanup. Thanks.

**Review by electrum — APPROVED** [review]
Please resolve the merge conflict

**Comment by ebyhr** [comment]
There's another conflict. Could you rebase on master again?

**Review by ebyhr — APPROVED** [review]

**Comment by mosabua** [comment]
@ebyhr can you please merge?

**Pull request merged**
